### ISSUE TITLE
rhub builder down ?

### ISSUE THREAD

**Issue by kforner** [r-hub/rhub#100]
Hi,

It seems like rhub is not working fine ? 

My packages seem to hang forever. 
I tried to to revalidate my email, but I never received the token (I checked my spams). 
And this was working yesterday.

There is no link on the website to report problems, this could be useful.

Best,

**Comment by gaborcsardi** [comment]
Thanks! Going now, but has some backlog, so please wait until you get notifications.

**Comment by kforner** [comment]
Thanks !
