### ISSUE TITLE
Show installation failures

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rhub#101]
I tried `rhub::check(platform = "solaris-x86-patched")` for RMariaDB, this currently results in an installation failure. I can't seem to access `00install.out` from neither the returned object nor on the web: https://builder.r-hub.io/status/RMariaDB_1.0-3.tar.gz-1c92fbaf38884cf49b1e5bae4261294e. What am I missing?

**Comment by krlmlr** [comment]
Oh, the resulting e-mail does contain a link to the artifacts, and there I find my `00install.out`. Is there a better way to access it?

**Comment by krlmlr** [comment]
The error can also be seen at the bottom of the "Installing package dependencies" section on the web: https://builder.r-hub.io/status/RMariaDB_1.0-3.tar.gz-1c92fbaf38884cf49b1e5bae4261294e.

Would you consider installing the client library on Solaris? According to anticonf, it's called `mysql56_dev`, see also https://artifacts.r-hub.io/RMariaDB_1.0-3.tar.gz-1c92fbaf38884cf49b1e5bae4261294e/RMariaDB.Rcheck/00install.out.

**Comment by gaborcsardi** [comment]
Seems to be fine now with the `mysql56_dev` package.
