### ISSUE TITLE
Description File could be scanned more thoroughly 

### ISSUE THREAD

**Issue by mbannert** [r-hub/rhub#106]
I get nothing but OKs from 

```
check_on_windows("../tstools_0.3.5.1.tar.gz")
```

but got rejected from CRAN because of: 

2 NOTEs:

* checking CRAN incoming feasibility ... NOTE
Maintainer: ''Matthias Bannert' <bannert@kof.ethz.ch>'

* checking DESCRIPTION meta-information ... NOTE
Maintainer field differs from that derived from Authors@R
  Maintainer: ''Matthias Bannert' <bannert@kof.ethz.ch>'
  Authors@R:  'Matthias Bannert <bannert@kof.ethz.ch>'

I think this is something that could / should be detected.

**Comment by gaborcsardi** [comment]
This is not up to rhub, we don't control this. 

I guess R-devel detects this, R-release does not, apparently.

**Comment by mbannert** [comment]
But wouldn't it be cool if rhub would also offer an R devel check? Is there anything I could to help add this or is it simply not the purpose and mission of rhub?

**Comment by gaborcsardi** [comment]
It does offer it, just `check_on_windows` selects a different one. Just run `rhub::check()` and it will list the platforms, several of them are R-devel.

**Comment by mbannert** [comment]
Ok, sorry for the noise then.
Maybe I just assumed that running on devel was the most common thing and the convenience functions advertised in the GH Readme would do just that.

However, thanks so much for the awesome work and patience.
