### ISSUE TITLE
expected submission and build time

### ISSUE THREAD

**Issue by njtierney** [r-hub/rhub#107]
Hey there!

I'm not sure if this is the current build time, but this is what I just got recently:

![image](https://user-images.githubusercontent.com/6488485/35947595-772b4c1c-0c1d-11e8-913e-9227adbaeee9.png)

**Comment by gaborcsardi** [comment]
THere were no builds for ~ 4 hours I guess.

**Comment by gaborcsardi** [comment]
Yeah, so the system was down for about 4 hours, then is started your build and finished it in 1.5 minutes.
