### ISSUE TITLE
Email sent to spam

### ISSUE THREAD

**Issue by DavisVaughan** [r-hub/rhub#108]
After running `validate_email()`, I sat there refreshing my email for a while only to realize that it had gone to my spam folder. Maybe something in the README or `validate_email()` docs reminding the user to go check their spam folder would be useful?

I also had to completely restart RStudio after I entered the token and validated the email (upon running `check_on_macos()` it still said the email wasn't validated), but thats a separate minor thing.

**Comment by gaborcsardi** [comment]
Thanks! This is caused by a recent DNS change, and we'll fix it soon.
