### ISSUE TITLE
Timeout with valgrind

### ISSUE THREAD

**Issue by lukesonnet** [r-hub/rhub#110]
Sorry for back-to-back issues, but they are quite different.

I also am trying to check my package with valgrind. I can run R CMD check on a linux machine I have access to, but I'd also like to check it using rhub. The main problem is that some of my tests are super slow with valgrind and lead to timeouts on rhub.

I'm aware that I don't want to clog up your resources, but I was wondering if there was a way to only timeout if R CMD check gets stuck on an individual test file called by `testthat.R` or whether looking within `testthat.R` isn't possible.

Thanks for the great package and platform!

**Comment by gaborcsardi** [comment]
If you use testthat, then in the `testthat.R` file, you can filter which files you want to run:
```r
test_check("mypackage", filter = "blah")
```
Then only test files that contain "blah" will run. So you can select the files that you want to run, and then submit the package to r-hub.

Unfortunately the timeout mechanism is dumb, and it just terminates if there is no output. I cannot change that, the supervisor process has no idea what R is doing inside.

**Comment by lukesonnet** [comment]
I thought that might be the case, re: timeout mechanism.

Thanks for the response and the suggestion, feel free to close this or do what you want with it.
