### ISSUE TITLE
Revamp the email validation UI in the R package

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#117]

**Comment by maelle** [comment]
What exactly needs to be done?

**Comment by gaborcsardi** [comment]
More user handholding in general. E.g. a menu when you submit a package with an unvalidated email. I might look at this before the release.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
