### ISSUE TITLE
_R_CHECK_FORCE_SUGGESTS_

### ISSUE THREAD

**Issue by jpritikin** [r-hub/rhub#120]
In [build log](https://builder.r-hub.io/status/OpenMx_2.9.2.tar.gz-f78a2da66e46a16c6e6f3e7b6efb78c7), you can see that the R CMD check fails because there is no way to set _R_CHECK_FORCE_SUGGESTS_ to false. Can you add this option or provide some kind of solution?

**Comment by gaborcsardi** [comment]
```
check(..., env_vars = c("_R_CHECK_FORCE_SUGGESTS_" = "false")
```

**Comment by jpritikin** [comment]
Awesome, thanks.

**Comment by jpritikin** [comment]
I tried your suggestion. It [didn't work](https://builder.r-hub.io/status/OpenMx_2.9.2.tar.gz-d712f732569d4a94a97a4558e22c3118). Am I doing something wrong?

**Comment by gaborcsardi** [comment]
oops, no, I forgot to update that builder, please try it again.

**Comment by gaborcsardi** [comment]
wait, still not good.

**Comment by gaborcsardi** [comment]
Ok, sorry, it should be good now.

**Comment by jpritikin** [comment]
Yeah, seems to work
