### ISSUE TITLE
OS/X binary expects libgfortran*.dylib in a non-default place?

### ISSUE THREAD

**Issue by jpritikin** [r-hub/rhub#122]
The shared library built on r-hub specifies `libgfortran` in `/usr/local/lib`. Is this the default place where `libgfortran` is expected to be found? An informal poll of local OS/X users suggests that `/Library/Frameworks/R.framework` maybe be the more appropriate location?

**Comment by gaborcsardi** [comment]
/usr/local/lib has another gfortran shared lib, that can be used for older R versions. Is that causing problems?

**Comment by gaborcsardi** [comment]
I removed them. I don't understand why they would cause problem, R should just like to its own libs first, by default.
