### ISSUE TITLE
E-mail report or web report include .Rout.fail files?

### ISSUE THREAD

**Issue by brodieG** [r-hub/rhub#127]
Loosely related to #40.

Right now AFAICT there is no way to see the full test run logs.  This would be particularly helpful under failure, where right now you get the last 13 lines that R CMD check provides, and nothing else.

I'm referring to the "pkg.Rcheck/tests/*.Rout.fail" and similar files.  Web only would be fine as far as I'm concerned.

Maybe there is already a way of doing this?  I poked around but couldn't see anything obvious.

**Comment by maelle** [comment]
Same request in (newer) #186

**Comment by brodieG** [comment]
Closed in favor of #186
