### ISSUE TITLE
Installed by an R version with different internals

### ISSUE THREAD

**Issue by whaleshark16** [r-hub/rhub#129]
I'm getting the below errors when I check my package on Debian Linux, R-devel, GCC ASAN/UBSAN:

Error : package ‘glue’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

Error : package ‘stringi’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

**Comment by kylebmetrum** [comment]
I'm seeing this as well (both 'glue' and 'stringi')


```r
> remotes::install_local("mypackage_0.8.11.tar.gz", dependencies = TRUE, INSTALL_opts = "--build")
```

Neither 'glue' nor 'stringi' are installed
```r
> Installing 34 packages: assertthat, backports, base64enc, BH, 
bindr, bindrcpp, cli, crayon, digest, 
dplyr, evaluate, highr, htmltools, jsonlite, knitr, lattice, markdown,
 mime, pillar, pkgconfig, plogr, 
praise, R6, Rcpp, RcppArmadillo, rlang, rmarkdown, rprojroot, 
testthat, tibble, utf8, withr, xml2, yaml
```

`dependencies = TRUE` should only go after uninstalled packages; so assuming that these are already installed somewhere.

The error after trying to install dplyr
```r
Error : package ‘glue’ was installed by an R version with 
different internals; it needs to be reinstalled for use with 
this R version
```

**Comment by ArpitSisodia** [comment]
same error but when i include the libraries. install.packages() worked successfully.


library(reshape)
Error: package or namespace load failed for ‘reshape’:
 package ‘reshape’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

**Comment by saman501** [comment]
[SOLVED] Had same 'different internals' error with my own package 'RTrading'.  
After compiling the code under R-Version 3.4.3, I installed the package on a server with R-Version 3.5.0 and the error was immediately thrown with library('RTrading').  

By updating the client to R-Version 3.5.1,  recompiling the code under this Version and installing the package to the Server with R-Version 3.5.0 again, everything was fine. 

So it's probably good to have the same R-Version when you are working with different machine. Maybe it's time for 'packrat' I guess or does the new 3.**x**.0-99 Version indicate for 'different internals'? 

Interestingly, compiling the package leads to a loading-check: On success. it is installed locally. On faillure,. the old version gets reestablished. But with installing the package on the server, there is no loading check at all, there is only the MD5 checksum. The old working version (compiled from another PC with same R-Version as on the server) gets deleted without any loading check. A bit nasty from the great and much beloved R!

**Comment by ChuliangXiao** [comment]
I had the error on a Linux system. It turned out that I unknowingly used the **R in conda** while I always use the regular R (`module load R`).

**Comment by philippbayer** [comment]
I've had a similar problem now - I was installing the packages for all users of the system via `sudo`, but one particular user still had the problem after manually reinstalling everything. 

Turns out, they had set up their own R-environment which was preferred over the global R-packages - you can check using the `.libPaths()` command in R which folders are preferred by the user's R installation, and then check whether any of them contain the old `glue` etc. version, deleting that fixed the issue

**Comment by ashvinmacaw** [comment]
I have this problem. dplyr package is working fine with Rstudio but when I load the package in Rvisuals in PowerBI then my rscripts fails with message as below

"Error: package or namespace load failed for 'dplyr':
 package 'dplyr' was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted"

**Comment by gaborcsardi** [comment]
@ashvinmacaw That does not seem like an rhub problem, but I guess you'll just need to do what the error message says, i.e. reinstall dplyr in the R version that PowerBI uses.

**Comment by biosurgeon** [comment]
I've suffered from this issue for two days...  but finally I solved it by (R)

update.packages(checkBuilt = TRUE, ask = FALSE)

I hope it works for others..

**Comment by ashvinmacaw** [comment]
> @ashvinmacaw That does not seem like an rhub problem, but I guess you'll just need to do what the error message says, i.e. reinstall dplyr in the R version that PowerBI uses.



> @ashvinmacaw That does not seem like an rhub problem, but I guess you'll just need to do what the error message says, i.e. reinstall dplyr in the R version that PowerBI uses.

@gaborcsardi, Thanks!

I noticed that powerbi uses a library location different than R studio, hence the problem with version conflict.

**Comment by Zola2021** [comment]
Help please!! My R version is 3.6.2 in Mac. I have tried all the different ways to install the xtail package, like from the source or github. But none of them works. Finally, I downloaded it to my computer, then manually install the package. But when I do library(xtail), it fails, and this is what it shows. 

> library(xtail)
Loading required package: DESeq2
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, parApply, parCapply,
    parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget, order, paste, pmax,
    pmax.int, pmin, pmin.int, Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min


Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with 'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians

Loading required package: BiocParallel

Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply, rowsum

Error: package or namespace load failed for ‘xtail’:
 package ‘xtail’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

Please help~~~

**Comment by sajjadasaf** [comment]
> I've suffered from this issue for two days... but finally I solved it by (R)
> 
> update.packages(checkBuilt = TRUE, ask = FALSE)
> 
> I hope it works for others..

Yes, it works. Thank you
