### ISSUE TITLE
pandoc error with badges

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-hub/rhub#130]
I am using the development version of `rhub` for running `R CMD CHECK`. My package succeeds builds on both `Appveyor` and `Travis` CI platforms, and `devtools::check()` succeeds as well. But `devtools::check_rhub()` gives the following error that I am not sure how to resolve. Should I just remove all badges from the `README.md` document before CRAN submission? 

```
Conversion of 'README.md' failed:
   pandoc.exe: Could not fetch https://img.shields.io/badge/Package%20version-0.0.1-orange.svg?style=flat-square
   no store
   CallStack (from HasCallStack):
     error, called at .\System\X509\Win32.hs:56:31 in x509-system-1.6.4-E9zvdZ6nI282vjtOPFYSd1:System.X509.Win32
```

**Comment by gaborcsardi** [comment]
No, it is fine, it is probably fine, either a  pandoc bug or a network failure.
