### ISSUE TITLE
Failure during examples not reported in summary

### ISSUE THREAD

**Issue by jcheng5** [r-hub/rhub#132]
I checked a package before CRAN submission, and a serious error in one of my examples was not reported as an error. You can see the error in the `R CMD check` log, but the email I received from rhub didn't mention it.

https://builder.r-hub.io/status/promises_1.0.0.tar.gz-088e386aeb594577b9f824e621ddc2d7

In case that link expires, here's a screenshot of the relevant portion (starting at line 271):

![image](https://user-images.githubusercontent.com/129551/38707950-95129bcc-3e68-11e8-8af3-b14dca2989ca.png)

Here's the package that causes the problem (it's the use of `library(future); plan(multisession)` in an example that causes the error):

[promises_1.0.0.tar.gz](https://github.com/r-hub/rhub/files/1905219/promises_1.0.0.tar.gz)

**Comment by gaborcsardi** [comment]
I am pretty sure that this is gone. :)
