### ISSUE TITLE
Multiple failures

### ISSUE THREAD

**Issue by MurrayEfford** [r-hub/rhub#134]
When I try check_for_cran, 3/4 platforms give ERRORs or NOTEs for reasons not directly related to the tarball. This is a promising tool, but is it ready for general use?

Build ID: 	openCR_1.2.0.tar.gz-960d33e3d7e942a890fc00784a5a3b3a
Platform: 	Windows Server 2008 R2 SP1, R-devel, 32/64 bit
Submitted: 	13 minutes 30.2 seconds ago
Build time: 	17639 days 21 hours 48 minutes 6.2 seconds    ## !

* checking sizes of PDF files under 'inst/doc' ... NOTE
Unable to find GhostScript executable to run checks on size reduction

Build ID: 	openCR_1.2.0.tar.gz-b2eecd5083354bbf8c2360f65135dbe2
Platform: 	Fedora Linux, R-devel, clang, gfortran
Submitted: 	14 minutes 58.4 seconds ago
Build time: 	14 minutes 52 seconds

Error: package or namespace load failed for â€˜secrâ€™ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called â€˜nlmeâ€™                                 ## no package nlme?
Error : package â€˜secrâ€™ could not be loaded

Build ID: 	openCR_1.2.0.tar.gz-f35ab797681c48ceb40649bb07528990
Platform: 	Debian Linux, R-devel, GCC ASAN/UBSAN
Submitted: 	15 minutes 55.3 seconds ago
Build time: 	15 minutes 44.8 seconds

2001#> Error : package ‘stringi’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version                                     ## stringi problematic not just on Solaris
2002#> ERROR: lazy loading failed for package ‘secr’

**Comment by maelle** [comment]
:wave: @MurrayEfford! Do you still get these errors these days? Quite some progress has been made in the meantime :-)

**Comment by MurrayEfford** [comment]
Yes, it's much improved.
check_for_cran('d:/open populations/openCR_1.3.5.tar.gz',  env_vars = 
    c('_R_CHECK_FORCE_SUGGESTS_' = "false"), show_status = FALSE)
now works on most platforms (openCR_1.3.5.tar.gz is the current version of openCR on CRAN).

However, it throws an arcane preperror on  Debian Linux, R-devel, GCC ASAN/UBSAN that looks like a bug to me. See https://builder.r-hub.io/status/openCR_1.3.5.tar.gz-8cba6470e0204e9fa3ac33bb02673e31

Preparing
   1#> Started by user r-hub Jenkins admin
   2#> Building remotely on 10.2.0.5-86c1b2e7 (slave swarm linux) in workspace /home/ubuntu/workspace/openCR_1.3.5.tar.gz-8cba6470e0204e9fa3ac33bb02673e31
   3#> [openCR_1.3.5.tar.gz-8cba6470e0204e9fa3ac33bb02673e31] $ /bin/sh -xe /tmp/hudson2468646707449101560.sh
   4date -u +%Y-%m-%dT%H:%M:%SZ
   5wget https://builder.r-hub.io/build/in-progress/openCR_1.3.5.tar.gz-8cba6470e0204e9fa3ac33bb02673e31/2019-03-27T20:56:15Z
   6#> --2019-03-27 20:56:15-- https://builder.r-hub.io/build/in-progress/openCR_1.3.5.tar.gz-8cba6470e0204e9fa3ac33bb02673e31/2019-03-27T20:56:15Z
   7#> Resolving builder.r-hub.io (builder.r-hub.io)... 54.241.228.251
   8#> Connecting to builder.r-hub.io (builder.r-hub.io)|54.241.228.251|:443... connected.
   9#> HTTP request sent, awaiting response... 200 OK
  10#> Syntax error in Set-Cookie: r-hub frontend=s%3A6c8acbc1-a0ea-48ca-b68a-e216b5b4f201.8lWtDVXc3T60zzwYoNcjjJnurHu%2FNFkgV%2F1VVkCEWAI; Path=/; Expires=Thu, 28 Mar 2019 06:56:15 GMT at position 0.
  11#> Length: unspecified [application/json]
  12#> Saving to: '2019-03-27T20:56:15Z'
  13#> 0K 1.49M=0s
  14#> 2019-03-27 20:56:15 (1.49 MB/s) - '2019-03-27T20:56:15Z' saved [15]
  15docker run --user docker --rm rhub/rocker-gcc-san bash -c echo $RHUB_PLATFORM
  16export RHUB_PLATFORM=linux-x86_64-debian-gcc

**Comment by gaborcsardi** [comment]
I don't see any error there. Can you copy here the part that you think is an error?

**Comment by MurrayEfford** [comment]
The email relating to this platform has subject "openCR 1.3.5: PREPERROR" and a red header box: I take this as a bad sign. In the Preparing section quoted above I see 10#> Syntax error... that seemed to explain the PREPERROR, but maybe not.

**Comment by gaborcsardi** [comment]
Yeah, I think it was mis-classified.

**Comment by maelle** [comment]
Thanks @MurrayEfford!

**Comment by cosimameyer** [comment]
Hi,
I'm not sure what the outcome of this issue was but I keep getting a similar bug (?) as @MurrayEfford last year when testing check_for_cran() for Ubuntu Linux 16.04 LTS, R-release, GCC and Fedora Linux, R-devel, clang, gfortran.

```
1#> Started by user r-hub Jenkins admin
2#> Building remotely on linux-builder-1.internal.cloudapp.net-8aa666a5 (slave swarm linux) in workspace /home/ubuntu/workspace/overviewR_0.0.2.tar.gz-8baf15d299d24979a851e0a88900d001
3#> [overviewR_0.0.2.tar.gz-8baf15d299d24979a851e0a88900d001] $ /bin/sh -xe /tmp/hudson53215626959147457.sh
4 date -u +%Y-%m-%dT%H:%M:%SZ
5 wget https://builder.r-hub.io/build/in-progress/overviewR_0.0.2.tar.gz-8baf15d299d24979a851e0a88900d001/2020-06-21T19:30:15Z
6#> --2020-06-21 19:30:15-- https://builder.r-hub.io/build/in-progress/overviewR_0.0.2.tar.gz-8baf15d299d24979a851e0a88900d001/2020-06-21T19:30:15Z
7#> Resolving builder.r-hub.io (builder.r-hub.io)... 54.241.228.251
8#> Connecting to builder.r-hub.io (builder.r-hub.io)|54.241.228.251|:443... connected.
9#> HTTP request sent, awaiting response... 200 OK
10#> Syntax error in Set-Cookie: r-hub frontend=s%3A8477e83b-7a48-4c40-a71b-d7f2c99023ed.o1LbImHakJNSZ0y15hh0%2FpsVe6I%2BQq3bpagNMmKJ8YE; Path=/; Expires=Mon, 22 Jun 2020 05:30:15 GMT at position 0.
11#> Length: unspecified [application/json]
12#> Saving to: '2020-06-21T19:30:15Z'
13#> 0K 1.08M=0s
14#> 2020-06-21 19:30:15 (1.08 MB/s) - '2020-06-21T19:30:15Z' saved [15]
```

It's also in line 10 for me -- any help is appreciated! Thank you!

**Comment by gaborcsardi** [comment]
@cosimameyer A container got wild and ate up all the disk, I cleaned it up now, so please resubmit. Thanks!

**Comment by cosimameyer** [comment]
@gaborcsardi, thanks so much! It worked like a charm but now I get the same error again. (Only for Ubuntu Linux 16.04 LTS, R-release, GCC this time)

**Comment by gaborcsardi** [comment]
@cosimameyer You need to tell me the job id to look this up. E.g. a link to the log.

**Comment by cosimameyer** [comment]
@gaborcsardi sure, sorry! Here you go: https://builder.r-hub.io/status/overviewR_0.0.2.tar.gz-0173bd415e57451c87402d40f89c4941. Thanks so much for your help!

**Comment by gaborcsardi** [comment]
This is in your log:

```
* building ‘overviewR_0.0.2.tar.gz’
Installing package into ‘/home/docker/R’
(as ‘lib’ is unspecified)
ERROR: this R is version 3.6.1, package 'overviewR' requires R >= 4.0.0
```

**Comment by cosimameyer** [comment]
Great, that was a good catch, @gaborcsardi! It runs smoothly now. Thanks so much :) (and sorry for the extra work!!)
