### ISSUE TITLE
"R-release" not 3.5.0

### ISSUE THREAD

**Issue by LiNk-NY** [r-hub/rhub#138]
Hi Gabor, @gaborcsardi 
Thanks for working on this utility. 

I'm having an issue when testing a package. 
R-release should be set to `3.5.0`. I've selected the option:
`13: Ubuntu Linux 16.04 LTS, R-release, GCC (ubuntu-gcc-release)`
and I get an error because the VM is using the old release version.
Please see:
http://builder.r-hub.io/status/BiocManager_1.29.52.tar.gz-7eb8da390d734eb58c08f948888d7284

Thanks for looking into it.

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Gábor, 
I looked into it and it seems like R 3.5.0 is not available as a deb package yet. 
https://cloud.r-project.org/bin/linux/ubuntu/xenial/

This means that there is no way to install it using `apt install`.

An alternative is to download the package directly as done via Travis CI. 
See an example build here: 
https://www.travis-ci.org/Bioconductor/BiocManager

Regards,
Marcel

**Comment by maelle** [comment]
I've just noticed this as well, I used `rhub::check_for_cran` and on Ubuntu I got a NOTE because of ORCIDs, which made me realize it used R<3.5.0

**Comment by yutannihilation** [comment]
According to [the official instruction](https://cran.r-project.org/bin/linux/ubuntu/#installation), there's a separate repository for 3.5 now. Does it help?

https://cloud.r-project.org/bin/linux/ubuntu/xenial-cran35/

**Comment by gaborcsardi** [comment]
Fixed in https://github.com/r-hub/rhub-linux-builders/commit/83c9d9cf7d97a9a871c18483d662d747ade2613b
