### ISSUE TITLE
avoid emails for every build

### ISSUE THREAD

**Issue by LiNk-NY** [r-hub/rhub#139]
Hi Gábor, @gaborcsardi

Is there a way to turn off the email notifications for every build?

Being that tests are likely to be run at the command line / RStudio,
the link to the `builder.r-hub.io` should be enough. 

Regards,
Marcel

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
