### ISSUE TITLE
R-Hub just does not do anything

### ISSUE THREAD

**Issue by SteffenMoritz** [r-hub/rhub#142]
I tried the webinterface, I tried the R package.
But after submitting my source package all I get is:

Status for build imputeTS_2.7.tar.gz-e3e22ce10c906e4b1ca207f03c2d39a7
Status: ... 
Duration: ...

With ... not being a placeholder - it is the actual output of the status page.

Afterwards nothing changes at all.
The process seems to be struck somewhere.

**Comment by SteffenMoritz** [comment]
Mh think this is somehow solved. I got a mail with the test results. Just the status page did not show anything.

**Comment by maelle** [comment]
@gaborcsardi if this was a temporary failure can we close this?
