### ISSUE TITLE
LaTeX distribution

### ISSUE THREAD

**Issue by SteffenMoritz** [r-hub/rhub#143]
I got a message
 **! LaTeX Error: File `titlesec.sty' not found.**
for Oracle Solaris 10, x86, 32 bit, R-patched (experimental)

The same problem once occurred on CRAN (with Mac OS).
This happens when you do not install a full distribution on the specific built sever.

**Comment by gaborcsardi** [comment]
Yes, we'll not install a full LaTeX distribution on Solaris. The machine does not have a lot of disk. If the extra style file is needed  for vignettes, please use
```
rhub::check(check_args = "--no-build-vignettes")
```
when checking on Solaris.

If it is for the package manual, then use the `--no-manual` option.

**Comment by gaborcsardi** [comment]
The new `check_on_solaris()` shortcut helps with this: 3256314c5b05be10c03ce631a084e70fb6b2fe99
