### ISSUE TITLE
Missing system libraries & dependency installation problems

### ISSUE THREAD

**Issue by pat-s** [r-hub/rhub#144]
Trying to get `mlr` building on Debian-gcc-devel. Full log: https://builder.r-hub.io/status/original/mlr_2.13.tar.gz-f62eda3981204c1abb63d8b3cd7aa4c5

The following `mlr` dependencies error during installation:

- `gmp`-> "configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.o"

- `openssl`: -> "Configuration failed because openssl was not found. Try installing: deb: libssl-dev (Debian, Ubuntu, etc)"

- `XML`-> "checking for xml2-config... no
Cannot find xml2-config" (already solved in #72 ?)

- `httr` -> because `openssl` is missing

- `rknn` -> because `gmp` is missing

- `shiny`-> "Failed with error:  ‘there is no package called ‘shiny’’"

- `lintr`, `plotly` -> because `httr` is missing

- `mldr` -> because `XML` is missing

- `rgl` -> "checking for GL/glu.h... no
configure: error: missing required header GL/gl.h"

- `clusterSim`, `crs` -> because `rgl` is missing

- `mlrMBO` -> "‘smoof’ are not available for package ‘mlrMBO’"

**Comment by Hong-Revo** [comment]
I'm getting a similar error with openssl as @pat-s, but with Ubuntu instead of Debian.

**Comment by maelle** [comment]
@pat-s @hong-revo is it now working for both of you?

**Comment by maelle** [comment]
:wave: @pat-s @Hong-Revo

**Comment by pat-s** [comment]
It's on my list :)

**Comment by Hong-Revo** [comment]
Sorry for the delay. It seems to be working now, although I've been getting a different error. I'll open another issue for that.

**Comment by pat-s** [comment]
@maelle Windows works fine, on Debian `XML` cannot be installed: https://builder.r-hub.io/status/mlr_2.14.0.tar.gz-7325cd871b5949c6b15eff6e00ccc347#L6311

Even though `libxml2-dev` is installed as a system library. I haven't yet checked what actions need to be taken to get `XML` running on Debian. 

Sorry for the late reply and thanks for your work here!

**Comment by gaborcsardi** [comment]
That's because of this:
```
#> Package openjdk-7-jre-headless is not available, but is referred to by another package.
#> This may mean that the package is missing, has been obsoleted, or
#> is only available from another source
#> E: Package 'openjdk-7-jre-headless' has no installation candidate
```

We need to fix this in sysreqs.

**Comment by bedantaguru** [comment]
Getting the same issues in 'xml2' and 'httr' package

**Comment by ledell** [comment]
I am also getting the same issues when I try to build the *h2o* package:

```
Packages suggested but not available for checking: 'rgl', 'plot3Drgl'
```

**Comment by dchiu911** [comment]
I get same issues with XML on Ubuntu:
```r
#> checking for xml2-config... no
#> Cannot find xml2-config
```
and problem with ModelMetrics on Fedora:
```r
#> * installing *source* package ‘ModelMetrics’ ...
#> ** package ‘ModelMetrics’ successfully unpacked and MD5 sums checked
#> ** using staged installation
#> ** libs
#> /usr/bin/clang++ -std=gnu++11 -I"/opt/R-devel/lib64/R/include" -DNDEBUG -I'/home/docker/R/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c RcppExports.cpp -o RcppExports.o
#> /usr/bin/clang++ -std=gnu++11 -I"/opt/R-devel/lib64/R/include" -DNDEBUG -I'/home/docker/R/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c auc_.cpp -o auc_.o
#> auc_.cpp:2:10: fatal error: 'omp.h' file not found
#> #include
#> ^~~~~~~
#> 1 error generated.
#> make: *** [/opt/R-devel/lib64/R/etc/Makeconf:178: auc_.o] Error 1
#> ERROR: compilation failed for package ‘ModelMetrics’
```

**Comment by nacnudus** [comment]
I get the same issues with testthat on Windows Server

```
#> These will not be installed
#> 'jsonlite' 'markdown' 'mime' 'Rcpp' 'reticulate' 'rlang' 'stringi'
#> 'testthat' 'yaml'
#> Packages suggested but not available: 'reticulate', 'testthat'
```

**Comment by fmannhardt** [comment]
I run into the same issue when trying to check my package with rhub::check_cran:

```
  49Rscript -e library(sysreqs); cat(sysreq_commands("heuristicsmineR/DESCRIPTION"))

  50sysreqs=export DEBIAN_FRONTEND=noninteractive; apt-get -y update && apt-get install -y zlib1g-dev libgmp-dev libxml2-dev make openjdk-7-jre-headless libv8-dev git-core libcurl4-openssl-dev libssl-dev

  51rm heuristicsmineR/DESCRIPTION
```

**Comment by MatthieuStigler** [comment]
I got two errors:

- fatal PrepError for `xml2` on Debian Linux, R-devel, GCC ASAN/UBSAN (see below)
- error on Ubuntu Linux 16.04 LTS, R-release, GCC with `rgl`: _Package suggested but not available: ‘rgl’_

More on the `xml2` error on  Debian Linux, R-devel, GCC ASAN/UBSAN

```
> /usr/include/unicode/ucnv.h:585:1: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type

3185#> 585 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUConverterPointer, UConverter, ucnv_close);

3186#> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

3187#> /usr/include/unicode/ucnv.h:585:1: note: ‘std::unique_ptr’ is only available from C++11 onwards

3188#> 585 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUConverterPointer, UConverter, ucnv_close);

3189#> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

3190#> make: *** [/usr/local/lib/R/etc/Makeconf:177: connection.o] Error 1

3191#> ERROR: compilation failed for package ‘xml2’

3192#> * removing ‘/home/docker/R/xml2’
```

**Comment by BenWinchester** [comment]
Has anyone resolved this issue? I am hitting similar dependency issues on Debian where R packages aren't installing due to missing linux libraries but where only one missing dependency is shown for each install-run attempt.

**Comment by gaborcsardi** [comment]
@BenWinchester which one? This issue is a soup of multiple issues, and I am fairly sure that they have been solved. If something fails for you please open a new issue with the specifics. Thanks!
