### ISSUE TITLE
Difference between check_with_sanitizers() and CRAN checks with sanitizers

### ISSUE THREAD

**Issue by gergness** [r-hub/rhub#145]
Thanks so much for this wonderful service!

After submitting a package I have been checking with `check_with_sanitizers()` to CRAN, I received notification that it failed the tests with their build machines with sanitizers. After some exploration today, I discovered that the difference is that there is no detection of `alloc-dealloc-mismatch` on rhub.

I made a [minimal package](http://github.com/gergness/rookie) to demonstrate this - when run on rhub, there is no error, but on CRAN there would be an error like: 
```
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
      #20 0x7f4294844c70 in getvar /tmp/R/src/main/eval.c:5022:10
      #21 0x7f42947c6d38 in bcEval /tmp/R/src/main/eval.c:6515:20
      #22 0x7f42947a8f39 in Rf_eval /tmp/R/src/main/eval.c:620:8
      #23 0x7f4294800f01 in forcePromise /tmp/R/src/main/eval.c:516:8
      #24 0x7f4294844838 in FORCE_PROMISE /tmp/R/src/main/eval.c:4980:15
      #25 0x7f4294844c70 in getvar /tmp/R/src/main/eval.c:5022:10
      #26 0x7f42947c6d38 in bcEval /tmp/R/src/main/eval.c:6515:20
      #27 0x7f42947a8f39 in Rf_eval /tmp/R/src/main/eval.c:620:8
      #28 0x7f4294800f01 in forcePromise /tmp/R/src/main/eval.c:516:8
      #29 0x7f4294844838 in FORCE_PROMISE /tmp/R/src/main/eval.c:4980:15
      #30 0x7f4294844c70 in getvar /tmp/R/src/main/eval.c:5022:10

  SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/usr/local/lib/R/bin/exec/R+0x50d640) in operator delete(void*)
  ==4548==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
  ==4548==ABORTING
```

I don't fully understand what's going on, but thought I'd bring it to your attention in case it's possible to save someone else.

Thanks again!

**Comment by maelle** [comment]
@gergness does the doc in https://docs.r-hub.io/#rhub-cran-platforms help a bit?

**Comment by gergness** [comment]
Kind of, after a bit of a run around, I was able to recreate CRAN's warning with a docker image from rocker, so I had already found a work-around for rhub's shortcoming here.

I can imagine the difficulty in matching CRAN's system, so would understand if you closed as a "won't fix". I was originally just trying to give information on one instance where this happens in case ya'll are able to fix.

**Comment by maelle** [comment]
@gaborcsardi should this issue be moved to https://github.com/r-hub/rhub-linux-builders?
