### ISSUE TITLE
Certain mirrors not having R 3.5 

### ISSUE THREAD

**Issue by muschellij2** [r-hub/rhub#148]
For example, at
https://builder.r-hub.io/status/spm12r_2.8.0.tar.gz-f032af7c5f8648a1b196171bd4e7c6ed#L128

We see that Oxford mirror doesn't have 3.5 up for Windows:
```r
#> Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
#> cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
```

Not sure the queueing system or selection of repos on the server, but may be useful.

**Comment by gaborcsardi** [comment]
1. That's a warning, and it does not influence the outcome of your build in any way.
2. It is not our selection, base R includes in by default.

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17467
