### ISSUE TITLE
oAuth failure at https://builder.r-hub.io/job

### ISSUE THREAD

**Issue by ms609** [r-hub/rhub#149]
I've submitted a package at https://builder.r-hub.io, which takes me to https://builder.r-hub.io/job.

When I click "Verify maintainer e-mail via GitHub", and enter my oAuth credentials, I hit an error page that contains the string:

`Unexpected token u in JSON at position 0`

The header states `Email not verified`.

**Comment by maelle** [comment]
Did this happen again, and were you successful submitting a package using the `rhub` package? (after running `rhub::validate_email()`)?

**Comment by gaborcsardi** [comment]
Make sure that your primary GitHub email address is visible, otherwise we cannot authenticate you.

**Comment by ms609** [comment]
Having set a 'public e-mail' at https://github.com/settings/profile to match the maintainer e-mail address, authorisation completes successfully.  

Perhaps a message to this effect could be added to https://builder.r-hub.io/job.
Currently the content of this page is merely:
```
Thank you for submitting package Quartet_1.1.0.tar.gz.
Unfortunately something went wrong.
Please check that you uploaded a proper R package.

Error:
cannot verify email address
```

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
