### ISSUE TITLE
check() hangs on Preparing build, see status at...

### ISSUE THREAD

**Issue by jwood000** [r-hub/rhub#150]
Every`check()` that I have tried does not progress past `Preparing build, see status at...`. I have let some of them run for more than 30 minutes with no luck. When I visit the URL, the Status and Duration do not report anything.

This behavior was not occurring yesterday. I thought I would report it just to give a heads up. I will continue testing and report back if anything changes. Thanks.

**Comment by gaborcsardi** [comment]
Thanks, fixed now.

**Comment by gaborcsardi** [comment]
There is  some backlog, though....

**Comment by jwood000** [comment]
@gaborcsardi I really appreciate it. Also, I've been meaning to let you know that `rhub` has been an absolute game changer for developing. Keep up the great work!!
