### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by Robinlovelace** [r-hub/rhub#155]
Hope I didn't crash it!

Reproducible example: click here: https://builder.r-hub.io/advanced

![image](https://user-images.githubusercontent.com/1825120/45814071-5d54f800-bccc-11e8-994e-fd8b70fb30fb.png)

**Comment by gaborcsardi** [comment]
Thanks, up again, investigating cause....

**Comment by Robinlovelace** [comment]
I tried to log-in on Github with an invalid email address. It gave me a message involving json that I cannot remember. That may have crashed it. Good robustness testing. Not exactly a DDoS! Update: still crashing for me...

**Comment by gaborcsardi** [comment]
Thanks, should be OK now, at least it  should not crash....

**Comment by Robinlovelace** [comment]
Great work. Now shows this but does not crash:

![image](https://user-images.githubusercontent.com/1825120/45820702-508dcf80-bcdf-11e8-9e5b-b2c2fc8f0247.png)
