### ISSUE TITLE
Error in gzfile(file, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by Robinlovelace** [r-hub/rhub#157]
Not sure why I got this error after uploading stplanr 0.2.6. Raising issue in case useful.

Line with error: https://builder.r-hub.io/status/stplanr_0.2.6.tar.gz-8bd4f6184e93d3defaf96de19a0df65a#L221

**Comment by gaborcsardi** [comment]
Failed  to install RcppArmadillo, not sure why. Might be a temporary  CRAN glitch.

**Comment by Robinlovelace** [comment]
Update: I cannot see that message but the Windows build still seems to be failing due to missing dependencies https://builder.r-hub.io/status/stplanr_0.2.6.tar.gz-7da24466175ff1682f8a9933e8578264

**Comment by gaborcsardi** [comment]
Thanks, should be OK now.

**Comment by Robinlovelace** [comment]
sf seems to be unavailable on various builds. Closing this specific issue. Let me know if it would be useful to open a new one on dependencies.

on el capitan: https://builder.r-hub.io/status/stplanr_0.2.6.tar.gz-5cc575e09fc64a7f0edfb195083e760a

**Comment by Robinlovelace** [comment]
In case it's of any use, I retried and it still seems to be failing: https://builder.r-hub.io/status/stplanr_0.2.6.tar.gz-7da24466175ff1682f8a9933e8578264

**Comment by gaborcsardi** [comment]
Is it possible that you can't fit in the 500MB quota?

**Comment by Robinlovelace** [comment]
I didn't know there was a quota. I guess so.
