### ISSUE TITLE
Please install codetools on fedora-clang

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#160]
It is a key package for checls, and the platform is in the `check_for_cran()`:

```
Platform:   Fedora Linux, R-devel, clang, gfortran    
Submitted:  5 minutes 56.3 seconds ago        
Build time: 5 minutes 55.4 seconds           

WARNINGS:                 
---------             
* checking re-building of vignette outputs ... WARNING                            
[...]
there is no package called 'codetools'            
Execution halted          
```

**Comment by maelle** [comment]
Recommended packages now get installed on all Linux platforms see https://github.com/r-hub/rhub-linux-builders/commit/b826f59e2d3d5504ba00a2dc3db834d493a8e27d and https://github.com/r-hub/rhub-linux-builders/commit/f7909564974fe7a05dc09a74bd4ad1c3cd504777.
