### ISSUE TITLE
web/browse

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#161]
Would it make sense to rename the `web` method `browse`? It might be a stupid suggestion. The reason for my asking is that I'm used to e.g. the `browse_` functions of `usethis` http://usethis.r-lib.org/reference/index.html#section-browse.

**Comment by maelle** [comment]
Ok will do later this week. 

Should `web` provoke a message about future deprecation?

**Comment by gaborcsardi** [comment]
> Should web provoke a message about future deprecation?

No, it's fine to just redirect...
