### ISSUE TITLE
ERROR: no packages specified

### ISSUE THREAD

**Issue by joshuaulrich** [r-hub/rhub#163]
I get the following error (or similar) on all 3 non-Windows platforms when I `check_for_cran`.  Looks like it is related to [this change in remotes on 2018-08-28](https://github.com/r-lib/remotes/blame/master/R/install.R#L40).

```
 996#> Warning: invalid package ‘/tmp/RtmpbQ0hQS/file1051e37ca38/* building ‘microbenchmark_1.4-5.tar.gz’’
 997#> Error: ERROR: no packages specified
 998#> Error in if (!is_dir(path)) { : missing value where TRUE/FALSE needed
 999#> Calls: ... install_remotes -> vapply -> FUN -> install -> load_pkg_description
1000#> In addition: Warning messages:
1001#> 1: In i.p(...) :
1002#> installation of package ‘/tmp/RtmpbQ0hQS/file1051e37ca38/* building ‘microbenchmark_1.4-5.tar.gz’’ had non-zero exit status
1003#> 2: In normalizePath(path) :
1004#> path[1]="/tmp/RtmpbQ0hQS/file1051e37ca38/* building ‘microbenchmark_1.4-5.tar.gz’": No such file or directory
```

**Comment by gaborcsardi** [comment]
It looks like a package installation failed before this.

**Comment by joshuaulrich** [comment]
I didn't see any indications of an issue before that, but I didn't look through each log with extreme care.  You're the expert. ;-)

Here are the links to the 4 runs generated by my `check_for_cran()` call:

   http://builder.r-hub.io/status/microbenchmark_1.4-5.tar.gz-73c41e4020e24eafb2d40c0af097089d
   http://builder.r-hub.io/status/microbenchmark_1.4-5.tar.gz-fc08ed8b02464be692caaa00271d93bf
   http://builder.r-hub.io/status/microbenchmark_1.4-5.tar.gz-225c7285b501456e88833ec2221eeab1
   http://builder.r-hub.io/status/microbenchmark_1.4-5.tar.gz-e0d1ae444f3746b9a532e66751a635a3

**Comment by gaborcsardi** [comment]
It is from line 1000 above, but  install.packages only throws a warning, and those are printed later.

**Comment by gaborcsardi** [comment]
For the rhub check this is actually not a fatal error, just the binary package is not built.

**Comment by gaborcsardi** [comment]
Fixed in remotes and install-github.me.

**Comment by joshuaulrich** [comment]
Thanks for the prompt fix!
