### ISSUE TITLE
false positive mac os build

### ISSUE THREAD

**Issue by tdhock** [r-hub/rhub#167]
this check failed but the web page has a green positive build http://builder.r-hub.io/status/PeakSegDisk_2018.09.28.tar.gz-7eff9752d4734c158ddeebf6839bbbd5

It says 
```
   Installation failed.
   See ‘/Users/userZqILcLm9/PeakSegDisk.Rcheck/00install.out’ for details.
```
and it would be helpful to have access to that 00install.out file to see what is going on.

thanks

**Comment by tdhock** [comment]
thanks @gaborcsardi 

it would be useful to have a link to the artifacts page at the top of of the build page as well (not just in the email).

about this build, the issue seems to be that BerkeleyDB STL headers are not found. https://artifacts.r-hub.io/PeakSegDisk_2018.09.28.tar.gz-7eff9752d4734c158ddeebf6839bbbd5/PeakSegDisk.Rcheck/00install.out

Is the sysreqsdb not used for the mac os builds? I do not see any mention of sysreqsdb / db_stl on the build page.

I added this new sysreqs entry https://sysreqs.r-hub.io/map/libdb_stl in a recent PR https://github.com/r-hub/sysreqsdb/pull/53 and I was expecting it to be used for mac os builds.

**Comment by gaborcsardi** [comment]
Sorry for the long wait. macOS still does not use sysreqs. Maybe you could download the software at install time? It goes like this:
https://github.com/jeroen/webp/blob/d5a6f6ecc42e99319db1b6a7203984f7c24602f9/configure#L33-L42

It is fairly difficult, maybe @jeroen can help with this?

**Comment by tdhock** [comment]
for that particular package (PeakSegDisk) I abandoned sysreqs etc and I just recoded the parts I needed in standard C++
