### ISSUE TITLE
PREPERROR on check

### ISSUE THREAD

**Issue by JohnMount** [r-hub/rhub#169]
I just got back this PREPERROR by email.  The symptom was the Linux URLs from a `rhub::check_for_cran()` reported back "We're sorry, but something went wrong."  and the Windows one had no more updates after one or two text lines abut launching a container to the cluster.

```
wrapr 1.7.0: PREPERROR
--
Build ID: wrapr_1.7.0.tar.gz-7a5ea96823c2406a93c6ec0146cfa5e6
Platform: Windows Server 2008 R2 SP1, R-devel, 32/64 bit
Submitted: 16 minutes 6.7 seconds ago
Build time: 17842 days 15 hours 44 minutes 5.4 seconds
 
See the full build log: HTML, text, artifacts.
Have questions, suggestions or want to report a bug? 
Please file an issue ticket at GitHub. 
Thank You for using the R-hub builder.
```

**Comment by gaborcsardi** [comment]
Some temporary error with a node, please resubmit.

**Comment by JohnMount** [comment]
Okay, thanks.
