### ISSUE TITLE
Remotes outdated

### ISSUE THREAD

**Issue by ankane** [r-hub/rhub#171]
Hey, it looks like rhub is using remotes 1.1.1.9000. Is it possible to move to remotes 2.0? It's probably not an issue for most packages, but it causes failures for ones that depend on 2.0+.

**Comment by gaborcsardi** [comment]
Ideally, the remotes versions used by rhub should not affect the remotes version used by the package. Remotes being pretty standalone, it is not that hard to fix this.

**Comment by ankane** [comment]
Agree, that would be a much better approach :)

**Comment by gaborcsardi** [comment]
We are using now the `r-hub` remotes branch.

**Comment by ankane** [comment]
Thanks @gaborcsardi

**Comment by ankane** [comment]
Hey @gaborcsardi, it looks like R-hub `remotes` still conflicts with `remotes` in package dependencies.

```
Package required and available but unsuitable version: 'remotes'
```

R-hub version: `1.1.1.9000`
Package version: `>= 2.0.3`

Link: https://builder.r-hub.io/status/jetpack_0.4.3.tar.gz-0c054d8dc9584d6d89ff3081d9af7f89
