### ISSUE TITLE
No artifacts available for Debian Linux

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-hub/rhub#172]
R-hub builder for debian linux doesn't provide artifacts, so difficult to check log files-

![rhub](https://user-images.githubusercontent.com/11330453/48655085-e2187580-e9e0-11e8-941a-e21d5327eb00.gif)

**Comment by gaborcsardi** [comment]
`preperror` means that your build errored before it started the check process, so there are no artifacts.

**Comment by IndrajeetPatil** [comment]
Is it common to get `PREPERROR` for `linux` machines or it's just my package? 

No matter which `linux` system I try (`Debian`, `CentOS`, etc.), I always get `PREPERROR` because one (or many) of the dependencies fails to download.

**Comment by gaborcsardi** [comment]
No, that should not happen, can you show an example?

**Comment by IndrajeetPatil** [comment]
Opened a new issue-
https://github.com/r-hub/rhub/issues/173
