### ISSUE TITLE
Please install: ‘Cairo’ ‘rjags’ ‘INLA’ ‘Rgraphviz’ on Oracle Solaris 10

### ISSUE THREAD

**Issue by gilleskratzer** [r-hub/rhub#175]
It would be great if the  ‘Cairo’ ‘rjags’ ‘INLA’ ‘Rgraphviz’ R packages could be installed on Oracle Solaris 10. Thank you for your help.

**Comment by gaborcsardi** [comment]
If you depend on them, CRAN packages are automatically installed.

**Comment by gilleskratzer** [comment]
hmmm, so I am unsure to understand the error message I get. Do you mean that they are automatically installed ONLY if they are declared on depend? 

Here is the error message I get.

* checking package dependencies ... ERROR
Packages required but not available: ‘Cairo’ ‘rjags’

Packages suggested but not available: ‘INLA’ ‘Rgraphviz’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.

**Comment by gaborcsardi** [comment]
Yes, R-hub probably tried to install them, but their installation failed. See the complete log, above the message you quoted.

**Comment by gilleskratzer** [comment]
Thank you for your quick response. You are right! 
What puzzle me is that I get an error on compilation from CRAN (so after installation of dependence). I did a patch but I am unsure if it does the job, so I would like to test it (and rhub is the perfect tool for that).

So would it means that CRAN is compiling on a different Solaris system than rhub?

**Comment by gaborcsardi** [comment]
> So would it means that CRAN is compiling on a different Solaris system than rhub?

Well, it is not the same machine. We don't have access to CRAN machines.

But we can certainly try to fix the installation of CRAN packages.

**Comment by gilleskratzer** [comment]
Sorry. You mean you need the detailed output. Correct?

https://builder.r-hub.io/status/abn_1.3.tar.gz-857093c9fe77b9f0a185f62c6b992e45

**Comment by gaborcsardi** [comment]
* Cairo just needs the cairo library, I can install that, if it is available fo Solaris.
* rjags is the same, it needs jags 4.
* INLA needs httpuv, which does not compile for some reason. This probably will need a different compiler, which is not available on R-hub.
* Rgraphviz does not compile either. I am not even sure that (R)graphviz can be compiled for Solaris.

The last two are in `Suggests`, so if you set `R_CHECK_FORCE_SUGGESTS=true` in the  `env_vars` argument of `rhub::check()`, then their absence will be ignored.

**Comment by gilleskratzer** [comment]
Thank you very much for your help. 

I will set R_CHECK_FORCE_SUGGESTS=true and test again.

**Comment by gaborcsardi** [comment]
Well, it will still not work, because Cairo and rjags do not work. Also, has to be 'false', sorry.

**Comment by gilleskratzer** [comment]
Ok. Thank you very much for your support and help! rhub is a great tool anyway. Thank you for that!

**Comment by gaborcsardi** [comment]
Current status report

## Cairo

👍  Success. Needs the `CSWsunx11devel` package.

## rjags

👎 Still fails, would need to package up jags for Solaris.

## INLA

👎 This is no on CRAN, but at https://inla.r-inla-download.org/R/ and it is huge. I'll not do this now.

## Rgraphviz

👎 Still fails to compile, also not on CRAN. I'll not fix this now.
