### ISSUE TITLE
Could the texlive installations be made more complete?

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#178]
Or else, could the invocation suppress manual/vignette creation?

Getting the following each and every time is boring:

```r
✔  checking package vignettes in ‘inst/doc’
─  checking running R code from vignettes ...
      ‘anytime-introduction.Rmd’ using ‘UTF-8’ ... OK
    NONE
W  checking re-building of vignette outputs (2s)
   Error in re-building vignettes:
     ...
   ! LaTeX Error: File `extarticle.cls' not found.

   ! Emergency stop.
   <read *>

   Error: processing vignette 'anytime-introduction.Rmd' failed with diagnostics:
   Failed to compile anytime-introduction.tex. See anytime-introduction.log for more info.
   Execution halted

✔  checking PDF version of manual (2s)
```

That was "fedora-gcc-devel", similar issues have bitten me on other systems.  Is there a chance RHub could provide a more uniform experience?

**Comment by eddelbuettel** [comment]
Today on `fedora-rdevel-clang`:

```
LaTeX errors:                       
! LaTeX Error: File `vmargin.sty' not found.
```

**Comment by eddelbuettel** [comment]
Bump

```
! LaTeX Error: File `extarticle.cls' not found.

! Emergency stop.
<read *>

Error: processing vignette 'Rcpp-FAQ.Rmd' failed with diagnostics:
```

**Comment by jackwasey** [comment]
I could use the latex package pdfpages, which is in texlive-latex-recommended on ubuntu.

**Comment by krashkov** [comment]
While checking a package with `devtools::check_rhub()`, I also encountered with this issue. Main parts of the output are as follows

**Platform:  Fedora Linux**

```
tlmgr: An error has occurred. See above messages. Exiting.
! LaTeX Error: File `framed.sty` not found.
```

**Platform:  Ubuntu Linux 16.04 LTS**

```
! LaTeX Error: File `algorithm2e.sty' not found.
```

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
