### ISSUE TITLE
GSL for Solaris

### ISSUE THREAD

**Issue by helske** [r-hub/rhub#179]
I'm trying to test `Rlibeemd` on Solaris via `rhub`, but it looks like there is no GSL installed on Solaris? Would it be possible to install it?

**Comment by eddelbuettel** [comment]
I have the same need for a package of mine.  GSL would be very nice to have on Solaris.

**Comment by gaborcsardi** [comment]
This is finally fixed now.

**Comment by eddelbuettel** [comment]
Was there a technical reason behind it?  Old / limited box?  Limited disk?

**Comment by gaborcsardi** [comment]
Messed up installation.

**Comment by eddelbuettel** [comment]
And now we finally have a cleaner restart?  Nice.

**Comment by gaborcsardi** [comment]
Yeah, you can have your own box if you want :) https://github.com/r-hub/solarischeck/tree/master/packer#readme

**Comment by eddelbuettel** [comment]
Hard pass :)

Error in first URL for packer, it is effectively https://github.com/r-hub/solarischeck/blob/master/packer/packer.io so you miss a leading https:// there.
