### ISSUE TITLE
Feature request: download the built binary

### ISSUE THREAD

**Issue by nacnudus** [r-hub/rhub#180]
Thanks for creating rhub, it makes package release and debug so much easier.

Could the built binaries be downloaded from the rhub machine to local?  That would enable people to install non-CRAN packages even when they can't build them on their local machine due to e.g. office IT constraints.

**Comment by maelle** [comment]
:wave: @nacnudus!

* At the moment you get a link to artefacts in the email, so you can download the built binaries manually.

* Stay tuned for R-hub Continuous Integration, because when it's released, you'll be able to create a CRAN-like repo.

**Comment by nacnudus** [comment]
Ah, I didn't think of that.  Thank you!
