### ISSUE TITLE
SKAT installation problem on Solaris

### ISSUE THREAD

**Issue by zhanxw** [r-hub/rhub#181]
My package `seqminer` (https://cran.r-project.org/web/packages/seqminer/index.html) suggests `SKAT`. 
R-Hub cannot install SKAT (build link: https://builder.r-hub.io/status/seqminer_6.8.tar.gz-e7f98a1cd81fe52a755e827c26569cc9), although CRAN check for SKAT on Solaris works well (https://cran.r-project.org/web/checks/check_flavors.html#r-patched-solaris-x86).

Can R-Hub fix and allow SKAT to be installed on Solaris?

**Comment by gaborcsardi** [comment]
SKAT seems to install just fine now.
