### ISSUE TITLE
Error: No space left on device

### ISSUE THREAD

**Issue by zhanxw** [r-hub/rhub#182]
Similar to https://github.com/r-hub/rhub/issues/104, I encountered the "No space left on device" problem as well (https://artifacts.r-hub.io/seqminer_6.8.tar.gz-a0ab2a3100214289bbbe6db6792025f8/seqminer.Rcheck/00install.out).

**Comment by gaborcsardi** [comment]
This should be fixed. I'll have to do a better job with cleaning up the disk....
