### ISSUE TITLE
Rcpp not available on Solaris

### ISSUE THREAD

**Issue by rstub** [r-hub/rhub#185]
Building [swephR](https://github.com/rstub/swephR) with `rhub::check(platform = "solaris-x86-patched")` I get the ERROR:
```
E  checking package dependencies (2.6s)
   Package required but not available: ‘Rcpp’   
```

Full log: https://builder.r-hub.io/status/swephR_0.1.0.tar.gz-c62c3122b75d4373a7cea25116a8df68#L499

#97 is similar, but given the prevalence of Rcpp this deserves a separate report.

----

CC: https://github.com/rstub/swephR/issues/34

**Comment by rstub** [comment]
I am not sure what has changed, but it is possible again to build packages using Rcpp on Solaris. Thanks a lot!

**Comment by gaborcsardi** [comment]
It was a hardware error with the machine, corrupt memory module.
