### ISSUE TITLE
Not able to load font when building graph in vignette

### ISSUE THREAD

**Issue by thalesmello** [r-hub/rhub#188]
```
Quitting from lines 44-50 (segmentr.Rmd) 
Error: processing vignette 'segmentr.Rmd' failed with diagnostics:
X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 11 could not be loaded
--- failed re-building ‘segmentr.Rmd’
```

Link:
https://builder.r-hub.io/status/segmentr_0.1.1.tar.gz-2fca97d350da490bbb8babf1270a9b9c

Package:
https://github.com/thalesmello/segmentr

**Comment by maelle** [comment]
Related issue https://github.com/r-hub/rhub-linux-builders/issues/14

**Comment by gaborcsardi** [comment]
Seems like this was fedora-clang-devel.

**Comment by gaborcsardi** [comment]
Fedora, Ubuntu and Debian images have more X11 fonts now (once deployed in a couple of minutes). Hopefully this is enough.
