### ISSUE TITLE
Rhub fails on Solaris

### ISSUE THREAD

**Issue by antcalcagni** [r-hub/rhub#190]
Hello,

I have tried compiling my pkg via rhub on Solaris but I found the following error:

`Packages required but not available:
  ‘Rcpp’ ‘rstan’ ‘ggplot2’ ‘cowplot’ ‘RcppEigen’ `

I did not get this error on other platforms.

Thanks

**Comment by gaborcsardi** [comment]
- [x] Rcpp
- [ ] rstan
- [ ] ggplot2
- [ ] cowplot
- [x] RcppEigen

**Comment by gaborcsardi** [comment]
They are all fine.
