### ISSUE TITLE
Status URLs are http vs https

### ISSUE THREAD

**Issue by hrbrmstr** [r-hub/rhub#191]
version 1.0.2

```
> rhub::check_for_cran(show_status = FALSE)
─  Building package
─  Uploading package
─  Preparing build, see status at
   http://builder.r-hub.io/status/sergeant_0.8.0.tar.gz-2396d86765124beb94d80f6d93938de7
   http://builder.r-hub.io/status/sergeant_0.8.0.tar.gz-d69229b2c1b14fc29e93a80ad0d883bd
   http://builder.r-hub.io/status/sergeant_0.8.0.tar.gz-e902ca0097ee45ae8ea514093ac0488f
```

`builder.r-hub.io` does redirect to https on access but that still partially exposes host and request.

I can PR a `sub()` but this looks like the non-https URLs are coming in the response from the server so that may be a better place to handle it.

**Comment by gaborcsardi** [comment]
Fixed by https://github.com/r-hub/rhub-frontend/commit/bac9e02bc671bff109d0a50b6b090e20f4306820
