### ISSUE TITLE
Links in email

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#194]
In the emails from R-hub, I can hover and click on the GitHub link but not on any other links i.e. not on the links related to the build itself. It might be due to Yahoo webmail.

**Comment by maelle** [comment]
I still have this issue, I can't click on links in the email.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
