### ISSUE TITLE
Function to retrieve artifacts

### ISSUE THREAD

**Issue by noamross** [r-hub/rhub#197]
Per discussion on rOpenSci, It would be useful to have a function that would return the URL of the built package.

I would also suggest providing a mechanism to extract the build ID and/or the web address of the page instead of just providing the `web()` method, for those who might want to use the outputs for other purposes.

**Comment by maelle** [comment]
artefacts and build info are kept X days (is it 7 days @gaborcsardi?)

so I wonder whether the method giving URLs should message something in case one calls it more than X days after hum submission? (or is there another date info in the response, that would not be submission time and thus be more appropriate)

**Comment by maelle** [comment]
I see "3-5 days" [here](https://github.com/r-hub/proposal#redundant-services-logging-and-monitoring-weeks-6-7)

Actually it'd be neat if the check objects had a Boolean called `removed` or so, maybe?

**Comment by gaborcsardi** [comment]
They are kept longer currently. But there is no guarantee for that. So if they are not there, you should get an error,  maybe saying that they were removed or not  saved (e.g. if the build was aborted).

**Comment by maelle** [comment]
once they're removed, they no longer returned by `list_my_checks()` I guess, I had not realized that earlier.

**Comment by gaborcsardi** [comment]
Really? They should be returned...

**Comment by maelle** [comment]
Oh, ok! Would it be possible for them to be returned with some indication of whether they were removed? I've just run `rhub::list_my_checks(howmany = 50)` but I only get 20 of them.

**Comment by gaborcsardi** [comment]
> Would it be possible for them to be returned with some indication of whether they were removed?

Not really.

**Comment by gaborcsardi** [comment]
OK, there is an `urls()` method now, that returns the artifact url(s). E.g. 

```r
❯ list_my_checks()
# A tibble: 27 x 13
   package version status  group   id      result email submitted
   <chr>   <chr>   <rhub:> <rhub:> <rhub:> <rhub> <chr> <dttm>
 1 dotenv  1.0.2   warning fe3fa08 39d6a66 W      csar… 2019-03-25 12:48:13
 2 dotenv  1.0.2   warning fe3fa08 49df642 W      csar… 2019-03-25 12:48:13
 3 dotenv  1.0.2   warning fe3fa08 9faacc9 W      csar… 2019-03-25 12:48:13
 4 dotenv  1.0.2   ok      c01ee44 128d0f6 ok     csar… 2019-03-22 13:27:34
 5 dotenv  1.0.2   ok      c01ee44 e449017 ok     csar… 2019-03-22 13:27:34
 6 dotenv  1.0.2   ok      adeb1e4 adeb1e4 ok     csar… 2019-03-22 11:23:36
 7 dotenv  1.0.2   ok      4600562 88fcfb8 ok     csar… 2019-03-22 11:22:09
 8 dotenv  1.0.2   ok      4600562 a6e1a19 ok     csar… 2019-03-22 11:22:09
 9 dotenv  1.0.2   ok      1126bda 18a20ac ok     csar… 2019-03-22 11:18:37
10 dotenv  1.0.2   ok      1126bda c9a596a ok     csar… 2019-03-22 11:18:37
# … with 17 more rows, and 5 more variables: started <dttm>, build_time <time>,
#   platform_name <chr>, platform <list>, builder <chr>

❯ get_check("39d6a66")$urls()
                                                                                  html
1 https://builder.r-hub.io/status/dotenv_1.0.2.tar.gz-39d6a6645ea44844a4365b786a13a1ff
                                                                                           text
1 https://builder.r-hub.io/status/original/dotenv_1.0.2.tar.gz-39d6a6645ea44844a4365b786a13a1ff
                                                                        artifacts
1 https://artifacts.r-hub.io/dotenv_1.0.2.tar.gz-39d6a6645ea44844a4365b786a13a1ff
```

**Comment by gaborcsardi** [comment]
We might make this more sophisticated in the future...
