### ISSUE TITLE
Mixed up messages

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#199]
cf #198 and https://builder.r-hub.io/status/note_1.0.tar.gz-66f4b36baf5d403f97130b1148e73742 in particula https://builder.r-hub.io/status/note_1.0.tar.gz-66f4b36baf5d403f97130b1148e73742#L252

**Comment by maelle** [comment]
The NOTE in https://builder.r-hub.io/status/note_1.0.tar.gz-871828f506904db7b2488b50a7c21f41 is weird too.

**Comment by maelle** [comment]
And https://builder.r-hub.io/status/note_1.0.tar.gz-5cb766e85edc47f5b57ddbe77921ba97 is better :-)

**Comment by gaborcsardi** [comment]
This will be hard to fix, because `R CMD check` is writing to both stdout and stderr (why, oh why?) and there is basically no way for our internal Jenkins scheduler to correctly order them. Maybe there is a Jenkins option that dumps both into the same pipe or sg. I'll take a look....

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
