### ISSUE TITLE
Perl on windows system

### ISSUE THREAD

**Issue by john-harrold** [r-hub/rhub#201]
I'm trying to build a package with platform="windows-x86_64-release". My package requires perl to work and I have the following in the DESCRIPTION file:

SystemRequirements: Perl

However the system doesn't appear to have perl installed. Is there a different place where I should specify that I need perl installed?

**Comment by maelle** [comment]
Thanks for the report! Perl now gets installed on the Windows, see https://github.com/r-hub/rhub-server/commit/822acf78553143c5df2a4bde2906feff143f2783 and https://github.com/r-hub/rhub-server/commit/55de180df83f2faa1a776ba2eaa6582744517a0f.
