### ISSUE TITLE
Check env_vars against possible values?

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#204]
Not sure there can be an exhaustive list? I'm thinking about this because I saw someone report a problem on R-pkg-devel, that was due to missing an underscore in an environment variable name.

**Comment by maelle** [comment]
Probably only makes sense for some environment variable, so doesn't sound very feasible :thinking:

**Comment by gaborcsardi** [comment]
I am not sure what you mean here. Most env vars are documented in the R manuals. E.g. https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools

We probably don't want to duplicate this.

**Comment by maelle** [comment]
I mean in the package not letting people use env vars with typos, and erroring if they do, so one could not write `_R_CHECK_ALL_NON_ISO_C` instead of `_R_CHECK_ALL_NON_ISO_C_`

**Comment by gaborcsardi** [comment]
Oh, I see. THat would make sense, but I would say this is pretty low priority....

**Comment by maelle** [comment]
And are the environment variables documented in that page the only one that could be sent via this argument, e.g. how would I send an API key?

I agree that it's mostly nice to have, not urgent. :-)

**Comment by gaborcsardi** [comment]
> And are the environment variables documented in that page the only one that could be sent via this argument

No, you can set whatever you want.

**Comment by maelle** [comment]
Ok so one could not error, just `stringdist`-compare the env vars names to the names from that CRAN page and if one env var name set by the user is very close but not equal to a CRAN variable, there'd be a message.

**Comment by maelle** [comment]
Or the variables should be either variables from the R manuals / something called via `Sys.getenv()` in the package code, but it's getting too complicated :-D

**Comment by gaborcsardi** [comment]
OK, we are not doing this, it is hard and error-prone.
