### ISSUE TITLE
3rd party software support? - e.g. JAGS

### ISSUE THREAD

**Issue by AndrewLJackson** [r-hub/rhub#205]
Can support for 3rd party packages be added? e.g. many R packages rely on the package [rjags](https://CRAN.R-project.org/package=rjags ) which itself relies on [JAGS](https://sourceforge.net/projects/mcmc-jags/). Packages tested with devtools::check_rhub() with examples that call `rjags` ERROR with "The rjags package is just an interface to the JAGS library
  Make sure you have installed JAGS-4.x.y.exe (for any x >=0, y>=0) from
  http://www.sourceforge.net/projects/mcmc-jags/files
  Execution halted". Additionally, WARNINGS are generated for any vignettes that use `jrags`.

In my case, [SIBER](https://cran.r-project.org/src/contrib/Archive/SIBER/) fails.

**Comment by gaborcsardi** [comment]
JAGS is available now on Windows.

**Comment by AndrewLJackson** [comment]
Great, thanks very much.

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 26 Feb 2019, at 22:54, Gábor Csárdi <notifications@github.com<mailto:notifications@github.com>> wrote:


JAGS is available now on Windows.
