### ISSUE TITLE
error due to failure to downloading a package

### ISSUE THREAD

**Issue by espinielli** [r-hub/rhub#206]
I started a `devtools::check_rhub()` and got a failure (ERROR) on Fedora Linux, R-devel, clang, gfortran as follows:

> * checking package dependencies ... ERROR
> Packages suggested but not available: 'knitcitations', 'covr', 'spelling'

I checked the [logs](https://builder.r-hub.io/status/nvctr_0.1.1.tar.gz-706b3e8210724a0d8ee00683224397f9) and found out the following `ERROR`s:

* lines [463-464](https://builder.r-hub.io/status/nvctr_0.1.1.tar.gz-706b3e8210724a0d8ee00683224397f9#L463-464) for `openssh`
  > #> Error: Error downloading packages:
  > #> Cannot download Packages/o/openssh-7.9p1-3.fc29.x86_64.rpm: All mirrors were tried

* around line [1739](https://builder.r-hub.io/status/nvctr_0.1.1.tar.gz-706b3e8210724a0d8ee00683224397f9#L1739) for `xml2`
   > #> ERROR: configuration failed for package ‘xml2’

* around line [1843](https://builder.r-hub.io/status/nvctr_0.1.1.tar.gz-706b3e8210724a0d8ee00683224397f9#L1843) for `openssl`
   > #> ERROR: configuration failed for package ‘openssl’

* a bunch of `ERROR`s are also mentioned at lines [1867-1887](https://builder.r-hub.io/status/nvctr_0.1.1.tar.gz-706b3e8210724a0d8ee00683224397f9#L1867) adding `RefManageR` to the list above

When running
```r
rhub::check_for_cran(env_vars = c(`_R_CHECK_FORCE_SUGGESTS_` = "false",
    `_R_CHECK_CRAN_INCOMING_USE_ASPELL_` = "false"))
```

I get a WARNING for inability to check a re-building of vignettes

I am in the process to submit to CRAN (my first package) but I do not really know how to get out of it...
Any helps is welcome. Thanks!

**Comment by thebioengineer** [comment]
I am having a similar issue with downloading the lower level command line tools on fedora. The URL is now broken, otherwise I would share it. But it looks like it has an issue with finding the right rpm for openssh

**Comment by gaborcsardi** [comment]
Is there a particular reason why you need Fedora? You can use a Debian or Ubuntu based builder, until this is fixed.

**Comment by thebioengineer** [comment]
Not particularly - I was simply using the defaults when submitting the package for testing. I can skip over it for now.

**Comment by maelle** [comment]
@thebioengineer which default do you mean? Do you mean from the example given in `check()` docs?

```r
check(".")
check("mypackage_1.0.0.tar.gz", platform = "fedora-clang-devel")
```
Thanks!

**Comment by gaborcsardi** [comment]
It is the default for `check_for_cran()` I guess.

**Comment by thebioengineer** [comment]
I've been using devtools::check_rhub, which runs a "default list of CRAN checkers (one for each major platform, and one with extra checks if you have compiled code)". Based on the emails I get back, it is: 
- Windows Server 2008 R2 SP1, R-devel, 32/64 bit,
- Ubuntu Linux 16.04 LTS, R-release, GCC
- Fedora Linux, R-devel, clang, gfortran

**Comment by gaborcsardi** [comment]
@thebioengineer can you please send a link to the logs? All fedora builds I looked at worked fine.

Nevertheless, this seems like an issue with the Fedora machine(s), so I am not sure  what we can do about it....

**Comment by thebioengineer** [comment]
https://builder.r-hub.io/status/tidytuesdayR_0.1.1.tar.gz-f7d59385347d431396624cc91ce5d9b3 - though the link appears to no longer be working

**Comment by gaborcsardi** [comment]
Yes, it seems that the Fedora mirrors are working fine again, so please just try again. 

I'll close this now, please reopen if you have this issue again.
