### ISSUE TITLE
separate `env_vars` for private variables

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#208]
if there were a separate `check_args` argument for private variables, there could be a separate field in the API response, and then one could include non private private variables in default printing methods.

**Comment by gaborcsardi** [comment]
You mean `env_vars`?

**Comment by maelle** [comment]
oops yes

**Comment by gaborcsardi** [comment]
This is not only up to the R package, but the builders should know about it as well, e.g. not to list them in the logs. So this will be postponed until rhub-server is deployed.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
