### ISSUE TITLE
Update rchk?

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#210]
The day started with a note from CRAN to please fix an `rchk` report in my package.

Sadly, the (very helpful) `rchk` instance here did not reproduce the issue, making it less effective in testing the pending fix.  Could the `rchk` container be updated, and (ideally) be kept synchronised between CRAN and rhub?

/cc @kalibera

**Comment by gaborcsardi** [comment]
It was actually updated about a month ago, which is later than the last  commit in the rchk repo. 

What was the issue in particular?

**Comment by eddelbuettel** [comment]
RInside, around line 180 of src/RInside.cpp.  

My use of `Rf_eval` and `Rf_lang2` needs another `PROTECT` as Tomas kindly pointed out when I was lost.

But I sent a beacon of my current repo before making changes and got a clean bill of health :-/ (circa three hours ago).

**Comment by gaborcsardi** [comment]
Yeah, with rchk you need to look at the logs, I am afraid. :( It has:

```
 269#> Function RInside::autoloads()
 270#> [UP] ignoring variable as it has address taken, results will be incomplete
 271#> Function RInside::initialize(int, char const* const*, bool, bool, bool)
 272#> [UP] calling allocating function Rf_eval with argument allocated using Rf_lang2(S:suppressMessages,?) /opt/R-svn/packages/build/pXIQdEI6/RInside/src/RInside.cpp:189
 273#> Function Rcpp::Environment_Impl::find(std::__1::basic_string, std::__1::allocator > const&) const
 274#> [UP] calling allocating function Rcpp::internal::Rcpp_eval_impl(SEXPREC*, SEXPREC*) with a fresh pointer (res ) /opt/R-svn/packages/lib/Rcpp/include/Rcpp/Environment.h:154
 275#> Function Rcpp::Rcpp_protect(SEXPREC*)
 276#> [PB] has possible protection stack imbalance /opt/R-svn/packages/lib/Rcpp/include/Rcpp/protection/Shield.h:25
 277#> Function Rcpp::Rcpp_unprotect(int)
 278#> [PB] has an unsupported form of unprotect with a variable results will be incomplete /opt/R-svn/packages/lib/Rcpp/include/Rcpp/protection/Shield.h:31
 279#> [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /opt/R-svn/packages/lib/Rcpp/include/Rcpp/protection/Shield.h:31
 280#> Analyzed 256 functions, traversed 1293 states.
```

Which is typical, R-hubs rchk usually returns more things than listed on CRAN, I have no idea why. Maybe different settings, maybe CRAN post-processes them.

**Comment by gaborcsardi** [comment]
I guess this was after you fixed he issue you mentioned, this is the last RInside run I could find in the log.

**Comment by eddelbuettel** [comment]
I am so sorry.  I once knew that.   

It's the '272' above, and I have a (untested) fix on the laptop.    So we can close this, or retitle it to maybe make it more explicit what gets returned?   Can you add 'per service' additions to the returned email?

**Comment by gaborcsardi** [comment]
No worries, it is really confusing, and I should have fixed it already. Originally I had no idea what to look for in the output when searching for errors, but I think I have some ideas now, so I'll fix this ASAP.

**Comment by kalibera** [comment]
The reports in the cran checks are a subset of the checks done by `rchk` (the results are a bit filtered, removing some reports that are often false alarms, but of course for the price of potentially missing some true errors). So if you run locally, the output should include what is reported by cran, and after a fix not include it anymore. `rchk` outputs are described in the documentation and - everything printed is an error (except a warning about that the checker run out of memory/states limit when checking a function). If anyone is running `rchk` locally to verify fixes for the problems reported in cran checks, I would indeed recommend to check also the remaining reports.

**Comment by gaborcsardi** [comment]
So it turns out that I have already implemented this a long time ago, but assumed that `bcheck` also outputs `WARNING`, etc. like `maacheck` but apparently it does not... 

I think the output has also changed a bit, e.g. the docs does not mention the `[UP]`, etc. tags.

I think I'll filter for \n\nFunction`, that seems to work.

**Comment by kalibera** [comment]
The docs describes the output so that it can be interpreted by a human, I did not anticipate it would be parsed by external tools.

**Comment by gaborcsardi** [comment]
@eddelbuettel sorry about that. 

I am trying to quota the containers, because the machine runs out of memory, and then all jobs are killed. So this will improve soon, hopefully....

https://github.com/r-hub/rhub-linux-builders/tree/master/ubuntu-rchk
https://cloud.docker.com/u/rhub/repository/docker/rhub/ubuntu-rchk

**Comment by eddelbuettel** [comment]
Maybe you should consider documenting Docker Hub urls for available containers.  It may help spread that very load.

**Comment by gaborcsardi** [comment]
This is fixed now by https://github.com/r-hub/rhub-frontend/commit/e454318a3196c3c426a60b6a260f15593da059c3.

**Comment by eddelbuettel** [comment]
Yay!  Thanks so, also for the pointre to the container.  Running locally now...
