### ISSUE TITLE
Fedora R-devel lacks `file` command, staged installs fail

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#216]
Testing a release candidate of RcppArmadillo I just got

```sh
1223#> ** testing if installed package can be loaded from temporary location
1224#> sh: file: command not found
1225#> Error in system(paste("file", l), intern = TRUE) :
1226#> error in running command
1227#> * removing ‘/home/docker/R/jsonlite’
```

Looks like you need `file`.

**Comment by gaborcsardi** [comment]
I don't think it is good idea to call out to `file`, though. Now basically R depends  on `file`..... anyway, I'll have to add it I suppose....

**Comment by eddelbuettel** [comment]
Yes, saw your post to the list. That's how it goes -- a new dependency.  Thanks for adding it.

**Comment by gaborcsardi** [comment]
Done in https://github.com/r-hub/rhub-linux-builders/commit/c8355b3759e5b4dd78ce6b8d9d297d0e90f8f5ff
