### ISSUE TITLE
Validate email error "Cannot get email address"

### ISSUE THREAD

**Issue by kimnewzealand** [r-hub/rhub#226]
Hi rhub team,

On review of the vignette https://r-hub.github.io/rhub/ as a first time Windows user,  I encountered the following error. Are there some other set up steps needed, and if so perhaps capture in the vignette?

> library(rhub)
Warning message:
package ‘rhub’ was built under R version 3.5.3 
> validate_email()

 Error in fallback_or_stop(fallback, "Cannot get email address") : 
  Cannot get email address

**Comment by gaborcsardi** [comment]
rhub cannot determine your email address, you need to specify it explicitly in `validate_email()`.

**Comment by kimnewzealand** [comment]
Perhaps update the vignette with some additional steps? It states there to use just the function with no params

**Comment by gaborcsardi** [comment]
Hmmm, I don't think the package has a vignette, just yet. You mean the README, perhaps.

**Comment by gaborcsardi** [comment]
And the README does say:
> The package tries to detect your email address using whoami and the maintainer email listed in DESCRIPTION; and if it fails to do this correctly, you'll need to specify it.

**Comment by kimnewzealand** [comment]
I was reviewing this page https://r-hub.github.io/rhub/

**Comment by gaborcsardi** [comment]
Yes, that 's the same as the README.

**Comment by kimnewzealand** [comment]
OK - so what I understood from the docs is that if it fails to detect the email address then you can specify it by selecting it as per the screen shot

**Comment by maelle** [comment]
Thanks @kimnewzealand, really useful to get the perspective of a first-time user! I've edited the vignette draft (which will correspond to the README content) accordingly, hopefully it makes things clearer?
