### ISSUE TITLE
check list improvements

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#228]
It is not really convenient that this is an R6 object, ideally it should just be a tibble. But there are good reasons for being the data frame, in particular that while the check is running, the status is not known and an R6 object can auto-update itself.

Maybe we want:
- [ ] an `as_tibble()` method
- [ ] custom printing of some columns of that tibble
- [ ] more intuitive way to inspect a single check
- [ ] more intuitive way to inspect a check group

**Comment by gaborcsardi** [comment]
Maybe the lists don't need to include all check details, just the table, basically. That would also make them much faster.

**Comment by maelle** [comment]
Yes to all this! Especially getting a more intuitive way to extract single/group checks
