### ISSUE TITLE
Web login

### ISSUE THREAD

**Issue by hughjonesd** [r-hub/rhub#229]
I’d like to be able to check my builds without having to use the R command line client. Would it be possible to have a login page directly on the website?

**Comment by gaborcsardi** [comment]
Have you tried https://builder.r-hub.io/ ?

**Comment by hughjonesd** [comment]
As I understand it, you can only login by uploading a package.
-- 
Sent from Gmail Mobile

**Comment by gaborcsardi** [comment]
Why do you want to log in if you don't want to upload packages?

**Comment by hughjonesd** [comment]
To check my in progress/completed uploads.
-- 
Sent from Gmail Mobile

**Comment by gaborcsardi** [comment]
The logs? You don't need to log in for that. Anyone with the link can see them. That's why it is a random link, so only people who actually know it will be able to see it.

**Comment by maelle** [comment]
I think that @hughjonesd means a web interface equivalent of `list_my_checks()`, where one would access their checks without knowing the URL of each of them.

**Comment by gaborcsardi** [comment]
We'll have a proper CI, where checks are tied to repositories and users. But we won't have a separate login page, etc. for the current one-shot checks.
