### ISSUE TITLE
Better output from valgrind builder

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#23]
This should also just run the 
- tests
- vignettes
- examples
  with valgrind on I suppose.

`R CMD check` is not really needed.

**Comment by jimhester** [comment]
`tools::testInstalledPackage(Ropts = "-d valgrind")` is probably the easiest way to do this.

**Comment by gaborcsardi** [comment]
Cool, I didn't know this. I should use it for the SAN container as well.

**Comment by merliseclyde** [comment]
Is it possible to have configuration for valgrind so that check_with_valgrind  replicates tests in 

`R -d "valgrind --tool=memcheck --leak-check=full" --vanilla < mypkg-Ex.R`

for different versions?    Would like to be able to replicate CRAN Package Check Results for Package XXX under valgrind reports

**Comment by maelle** [comment]
#186

**Comment by eddelbuettel** [comment]
We may need more than this. Quoting from _Writing R Extensions_ 

>   On platforms where 'valgrind' is installed you can build a version of
R with extra instrumentation to help 'valgrind' detect errors in the use
of memory allocated from the R heap.  The 'configure' option is
'--with-valgrind-instrumentation=LEVEL', where LEVEL is 0, 1 or 2.
Level 0 is the default and does not add anything.  Level 1 will detect
some uses(1) of uninitialised memory and has little impact on speed
(compared to level 0).  Level 2 will detect many other memory-use
bugs(2) but make R much slower when running under 'valgrind'.  Using
this in conjunction with 'gctorture' can be even more effective (and
even slower).

It would be sweet to have a builder instrumented for this.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
