### ISSUE TITLE
GPU Builds

### ISSUE THREAD

**Issue by cdeterman** [r-hub/rhub#231]
Are there any plans or ideas on having platform options for those developing R packages leveraging GPU devices?  Ideally this would accommodate both OpenCL and CUDA developers but either would be certainly be helpful.

**Comment by gaborcsardi** [comment]
Technically this is possible, yes, however GPU VMs are very expensive, so we'll need to budget this carefully.

**Comment by gaborcsardi** [comment]
I suppose you would want a Linux VM, is that right?

**Comment by cdeterman** [comment]
@gaborcsardi at a minimum yes.  Ideally we would also have Windows and Mac VMs as well but I would take whatever I could get.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
