### ISSUE TITLE
GSL for macOS

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#234]
Running a check for RcppGSL (via `rhub::check_on_macos()`) I get

```
 243#> checking for gsl-config... no
 244#> configure: error: gsl-config not found, is GSL installed?
 245#> ERROR: configuration failed for package ‘RcppGSL’
```

It would be nice to have GSL installed.

**Comment by MLopez-Ibanez** [comment]
Is there a work-around?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
