### ISSUE TITLE
update pandoc and/or offer multiple versions

### ISSUE THREAD

**Issue by jackwasey** [r-hub/rhub#244]
This is a request on behalf of people who use the 'rticles' package to generate a package vignette, or otherwise need recent pandoc features. I seem to need pandoc >= 2.2 for one vignette in my package 'icd'. https://pandoc.org/releases.html says they are currently on 2.7.1 and the CRAN and r-hub version is about 18 months old (version 1.19).

I understand the need to mimic CRAN (just for some builds?). Is a choice of pandoc version possible? Or maybe it is reasonable to offer the latest pandoc in non-CRAN builds and a version similar to CRAN for `check_for_cran` builds.

r-hub does complete the check but with a warning on re-building vignette outputs, so it's not the end of the world. Workarounds I have considered include: not building that particular vignette on CRAN/r-hub at all (but this means I miss out on automated testing of my most intricate, although not computationally heavy vignette, a JSS paper); and asking r-hub not to build vignettes using the environment variable.

**Comment by maelle** [comment]
@gaborcsardi is this something that should be solved inside packages themselves via `SystemRequirements`?

The entry for Pandoc in sysreqsdb is https://github.com/r-hub/sysreqsdb/blob/master/sysreqs/pandoc.json, would this install the latest version?

**Comment by gaborcsardi** [comment]
We should try to stick to something that CRAN uses.
