### ISSUE TITLE
Test/fix local linux builders on Windows

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#245]

**Comment by maelle** [comment]
Needed before #240, right?

**Comment by gaborcsardi** [comment]
I'll check #240 soon.

**Comment by dpprdan** [comment]
I tried to test `local_check_linux(image = "rhub/debian-gcc-release")` on Windows. Here are some errors I ran into, how I solved them and where I am stuck now. (I hope this is the appropriate issue, if not I can move this somewhere else).

1. Error: "You need bash and Docker to run local Linux checks". 
I have git-bash installed, but it wasn't on the PATH (which is the default, I think). 
Added C:\Program Files\Git\bin to System PATH. 
Suggestion: In vignette, let Windows users first manually check whether `Sys.which("bash")` and `Sys.which("docker")` are not empty and give installation instructions if they are?

2. Error: "C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect" 
Docker daemon was not running. 🤦‍♂ 

3. Error: "Error in library(sysreqs) : there is no package called 'sysreqs'". 
sysreqs was not installed. 
Installed with `devtools::install_github("r-hub/sysreqs")`. 
Suggestion: Add sysreqs to rhub Suggests? 


4. Error: 
```bash
>>>>>==================== Installing system requirements
f8db5e625835c1b466d9450285635c351b48cd2db62c0a2f9e1c7b0122dffb47
bash: C:/Program Files/Git/root/sysreqs.sh: No such file or directory
Build container is ebcd2f5c-a868-11e9-8a48-49cad3603d12-2
Error in run(bash, c(file.path(wd, "rhub-linux.sh"), args), echo = TRUE,  : 
  System command error
```

This is where I am stuck now. There is no `C:/Program Files/Git/root/` directory. Does this from [here](https://github.com/r-hub/rhub/blob/c51e0704ae7011536757f151144415323f4d77b9/inst/bin/rhub-linux.sh#L205)?

**Comment by jolars** [comment]
I'm getting the sysreqs error that @dpprdan got with `rhub/rocker-gcc-san`.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
