### ISSUE TITLE
Installation error concerned to package `cli`

### ISSUE THREAD

**Issue by kikirinrin** [r-hub/rhub#246]
Installation fails in both
`install.packages("rhub")`
 and 
`devtools::install_github("r-hub/rhub").

It seems an object `col_blue` used in `rhub` is not exported by package `cli`.
Does anyone know how to fix this?

Error messages returned were below.
```
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘rhub’ ...
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error : object ‘col_blue’ is not exported by 'namespace:cli'
   ERROR: lazy loading failed for package ‘rhub’
─  removing ‘/private/var/folders/br/g4rpn07d19nfqhbwvgyl9_5h0000gn/T/RtmpPv19Wq/Rinst17c6d3dee0aba/rhub’
         -----------------------------------
   ERROR: package installation failed
```

Thanks,

**Comment by gaborcsardi** [comment]
You need to update cli to 1.1.0.

**Comment by kikirinrin** [comment]
I already have `cli` package but cannot call function `col_blue()`.
```{r}
cli::col_blue
#> Error: 'col_blue' is not an exported object from 'namespace:cli'
```

**Comment by gaborcsardi** [comment]
You have to update it and restart R.

**Comment by kikirinrin** [comment]
Thank you very much @gaborcsardi , it worked!

Can I do this kind of flow in one-action using some options?
Or I always need to update specific package and restart R?

**Comment by maelle** [comment]
@kikirinrin, we've now added the minimal `cli` version to `DESCRIPTION` which means users installing the package will get more automatic updates of dependencies. Thanks for your bug report!

**Comment by kikirinrin** [comment]
@maelle, thank you for improvement!!

**Comment by maelle** [comment]
I didn't even make that PR, #248 :smile_cat:
