### ISSUE TITLE
Mock builds

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#250]
@gaborcsardi I'm wondering about how to best test behavior of the package for builds with some given output (preperror, etc.). Should I work on having mock answers within the package (using `vcr` maybe), should there also be some mock builds in the database, associated with an email address `rhub` developers + Travis would have the token to? :thinking: 

Related to #24

**Comment by gaborcsardi** [comment]
What exactly would be the goal of the mock builds?

**Comment by maelle** [comment]
To be able to test the behavior of `cran_summary()` for groups where one build has a preperror, for instance.

**Comment by maelle** [comment]
The mock build would be there forever contrary to builds that disappear other time.

It'd help with #24

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
