### ISSUE TITLE
library not found for -lquadmath

### ISSUE THREAD

**Issue by bflammers** [r-hub/rhub#254]
Hi there, 

I am getting the following error when building on Rhub macOS 10.11 El Capitan, R-release (experimental):

> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lquadmath
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found closed issue #122 that also concerns libgfortran but I do not know if they are related. 

Any ideas where this is coming from?

**Comment by dselivanov** [comment]
same here - rhub fails to test my https://github.com/dselivanov/rsparse pkg. 
I think this is related to the packages which link to BLAS/LAPACK and have this line in Makevars:
```
PKG_LIBS  = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
```

**Comment by gaborcsardi** [comment]
One solution would be to switch to the CRAN compilers. Or support both, but make CRAN's the default.

**Comment by gaborcsardi** [comment]
Another solution would be to tweak the make flags on the builder, I'll do that.

**Comment by gaborcsardi** [comment]
OK, it seems that this is fixed now, at least RcppSMC failed before and it is fine now.
