### ISSUE TITLE
Handle noisy compiler output

### ISSUE THREAD

**Issue by jackwasey** [r-hub/rhub#255]
One of my packages links to `RcppEigen`, which generates a huge volume ~10,000 lines of noisy but irrelevant warnings (e.g. unknown pragma) by default, as of course required by CRAN. This relates to https://github.com/r-hub/rhub/issues/42 .

With some gymnastics, I can send R CMD INSTALL args via R CMD check args, via `rhub::check`, but these only apply to the tested package itself, not dependencies. There is no way I can find to pass any compiler flags to an rhub docker build. As was suggested in https://github.com/r-hub/rhub/issues/42 , folding sections in the HTML output would be a workaround.

No doubt more complicated would be configurable compiler flags for both package itself and dependencies. Or possibly, optionally passing a custom`~/.R/Makevars` through.

**Comment by jackwasey** [comment]
Is something like this going to work?
```
rhub::check(env_vars = "MAKEFLAGS=\"CXXFLAGS=-no-unknown-pragmas\"")
```
(via https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Creating-shared-objects)

**Comment by gaborcsardi** [comment]
I would guess that it won't work, but why don't you try?

**Comment by jackwasey** [comment]
Will do. The thought occurred to me after the original issue, and haven’t had time to do so yet. Will report back.

**Comment by tbates** [comment]
It would be great if the output had folding sections. On linux, for instance, the user is seldom interested in the 10,000 lines of package install info. All sections could be folded by default to just show a "table of contents".

Also a "go to bottom" button would be great for 20,000 line reports.

not claiming orginality here: Both are travis features

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
