### ISSUE TITLE
Expose check results in a more machine-readable format

### ISSUE THREAD

**Issue by jozefhajnala** [r-hub/rhub#257]
**Current behavior**
Currently publicly exposed methods for investigating `rhub_check` objects seem to be mostly  side-effecting (printing) with different levels of detail, which is great for interactive use.

**Desired feature**
When processing `check` results using code (e.g. for CI/CD purposes) it would however be useful if the results were exposed in a more machine-readable format.

**Further context, use case, examples**
For further context, I currently access the private fields to get to the results like so:

* An [R script that runs the checks](https://gitlab.com/jozefhajnala/jhaddins/blob/experimental/inst/rhubcheck.R) via R-hub and evaluates the results

GitLab CI/CD pipeline context:

* The [.gitlab-ci.yml](https://gitlab.com/jozefhajnala/jhaddins/blob/experimental/.gitlab-ci.yml) that governs the CI/CD pipeline
* An example [of a successful run](https://gitlab.com/jozefhajnala/jhaddins/pipelines/57477509) with checks on 3 platforms

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
