### ISSUE TITLE
Run-time error

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#26]
```r
R> rhub::check()
─  Building package
─  Uploading package
─  Preparing build, see status at
   http://builder.r-hub.io/status/anytime_0.0.1.tar.gz-149112ac0b654cd3bbdd029989d0d33c
Error in ("rcmdcheck" %:::% "check_callback")(top_line = FALSE) : 
  unused argument (top_line = FALSE)
R> 
```

Fresh from GH, current.

**Comment by eddelbuettel** [comment]
This seems to help:

```
1 file changed, 2 insertions(+), 1 deletion(-)
R/status.R | 3 ++-

modified   R/status.R
@@ -55,7 +55,8 @@ make_status_parser <- function(id) {
 
   first <- TRUE
   checking <- FALSE
-  formatter <- ("rcmdcheck" %:::% "check_callback")(top_line = FALSE)
+  #formatter <- ("rcmdcheck" %:::% "check_callback")(top_line = FALSE)
+  formatter <- ("rcmdcheck" %:::% "check_callback")()
   spinner <- c("-", "\\", "|", "/")
 
   spin <- function() {
```

**Comment by gaborcsardi** [comment]
You need newer version of `rcmdcheck`, I should depend on that.

**Comment by eddelbuettel** [comment]
Well that would NOT have helped me:

```r
R> packageVersion("rcmdcheck")
[1] ‘1.2.1’
R> 
```

**Comment by gaborcsardi** [comment]
1.2.1 surely has that argument: 
https://github.com/cran/rcmdcheck/blob/1.2.1/R/callback.R#L9

`packageVersion` is broken, goes to the disk, and you might have another version loaded. Use 
```r
❯ getNamespaceVersion("rcmdcheck")
version
"1.2.1"
```

**Comment by eddelbuettel** [comment]
Come on -- claims of bugs in R Base functions need evidence...

No no, it really is 1.2.1.  

I suspect what might have happened and tripped us here is that I have an earlier GH version also named 1.2.1 which was NOT replaced when a subsequently changed version made it to CRAN, also labeled 1.2.1 but not forcing an upgrade here.

So my bad for trying early versions of your code, and your bad for being bad incrementing minors.  I think Hadley's .9000, .9001, ... is silly as it should just be .1, .2, .3, ... which I have been using _after_ my regular 1.2.3 release numbers to differentiate.  Once at CRAN, a 1.2.3.2 becomes 1.2.4 and everything works _with the default tools_ in base R.
