### ISSUE TITLE
Unable to find GhostScript executable

### ISSUE THREAD

**Issue by samuel-rosa** [r-hub/rhub#263]
I get the following on Windows Server 2008 R2 SP1, R-devel, 32/64 bit:

```
* checking sizes of PDF files under 'inst/doc' ... NOTE
Unable to find GhostScript executable to run checks on size reduction
```

See the full build log at https://builder.r-hub.io/status/spsann_2.2.0.tar.gz-a8dd6c07c3b44b0ab95960c92d311509

**Comment by jfoadi** [comment]
I get exactly the same! Is this NOTE very important? Or, can it be ignored for the time being?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
