### ISSUE TITLE
Building package with rJava dependency fails on rhub::check_for_cran

### ISSUE THREAD

**Issue by gorcha** [r-hub/rhub#265]
When running `check_for_cran()` on a package with an rJava dependency, the rJava build fails on Fedora and Windows.

Fedora Linux, R-devel, clang, gfortran
[Full build log](https://builder.r-hub.io/status/dialr_0.2.0.9004.tar.gz-2c462ff4fbdd45279390d0b34fbc0b0f)
```
1640#> configure: error: Java Development Kit (JDK) is missing or not registered in R
1641#> Make sure R is configured with full Java support (including JDK). Run
1642#> R CMD javareconf
1643#> as root to add Java support to R.
1644#> If you don't have root privileges, run
1645#> R CMD javareconf -e
1646#> to set all Java-related variables and then install rJava.
1647#> ERROR: configuration failed for package ‘rJava’
```

Windows Server 2008 R2 SP1, R-devel, 32/64 bit
[Full build log](https://builder.r-hub.io/status/dialr_0.2.0.9004.tar.gz-f19cecf564a648e3a5199ea12723b994)
```
 476#> ** using staged installation
 477#> ** R
 478#> Error: .onLoad failed in loadNamespace() for 'rJava', details:
 479#> error: JAVA_HOME cannot be determined from the Registry
 480#> Execution halted
```

**Comment by russellpierce** [comment]
I'm hitting the same issue right now (at least for the Windows build).  [Full build log](https://builder.r-hub.io/status/awsjavasdk_0.2.2.tar.gz-fe6b4765d5074873b52d5ff638956de8), [artifacts](https://artifacts.r-hub.io/awsjavasdk_0.2.2.tar.gz-fe6b4765d5074873b52d5ff638956de8).

**Comment by brry** [comment]
Me too, see [artifacts](https://artifacts.r-hub.io/OSMscale_0.5.17.tar.gz-ee6d9f27c8394928b3ff1543a6d1a322/OSMscale.Rcheck/).

I have in the past solved `JAVA_HOME cannot be determined from the Registry` with suppressing multiarch support, see [here](https://bookdown.org/brry/course/packages.html#rjava-on-windows).
