### ISSUE TITLE
Dependencies not available for package (Ubuntu and Fedora)

### ISSUE THREAD

**Issue by samuel-rosa** [r-hub/rhub#269]
When checking the __[febr](https://CRAN.R-project.org/package=febr)__ package on Ubuntu and Fedora, a PREPERROR is issued because important packages cannot be installed.

On Ubuntu Linux there are problems with __rgdal__, __xml2__, __openssl__, __httr__, and __googlesheets__.

```
5570#> 1: In i.p(...) : installation of package ‘rgdal’ had non-zero exit status
5571#> 2: In i.p(...) : installation of package ‘xml2’ had non-zero exit status
5572#> 3: In i.p(...) :
5573#> installation of package ‘openssl’ had non-zero exit status
5574#> 4: In i.p(...) : installation of package ‘httr’ had non-zero exit status
5575#> 5: In i.p(...) :
5576#> installation of package ‘googlesheets’ had non-zero exit status
5577#> 6: In i.p(...) :
5578#> installation of package ‘/tmp/RtmpUmEOlf/file13b24d2cbda/febr_1.0.1.9003.tar.gz’ had non-zero exit status
```

On Fedora Linux there are problems with __rjava__, __xlsxjars__ and __xlsx__.

```
3571#> Warning messages:
3572#> 1: In i.p(...) : installation of package ‘rJava’ had non-zero exit status
3573#> 2: In i.p(...) :
3574#> installation of package ‘xlsxjars’ had non-zero exit status
3575#> 3: In i.p(...) : installation of package ‘xlsx’ had non-zero exit status
3576#> 4: In i.p(...) :
3577#> installation of package ‘/tmp/RtmpipG7vg/file11b59eb9974/febr_1.0.1.9003.tar.gz’ had non-zero exit status
```

The logs can be checked at:

* https://builder.r-hub.io/status/febr_1.0.1.9003.tar.gz-ee513f3217bb4fc7a60ff9d0432f5556
* https://builder.r-hub.io/status/febr_1.0.1.9003.tar.gz-23508cac18524141a4502a68c227fd91

**Comment by gaborcsardi** [comment]
Dependencies are installed automatically, probably an installation failed.
