### ISSUE TITLE
Issue with compiled packages on macOS?

### ISSUE THREAD

**Issue by riccardoporreca** [r-hub/rhub#271]
I am experiencing issues with macOS builds for packages with C++ code, most likely due to how the build tools are setup on macOS (possibly related to [C.3 macOS](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#macOS) in R Installation and Administration).

Examples of packages failing in a similar manner (can be reproduced by using the tar.gz from CRAN)

- [rTRNG](https://CRAN.R-project.org/package=rTRNG) => `fatal error: 'math.h' file not found` ([Full log](https://builder.r-hub.io/status/rTRNG_4.20-1.tar.gz-0da452f3db4b1fb584052f015de87067))
- [RcppEigen](https://cran.r-project.org/package=RcppEigen) => `fatal error: 'wchar.h' file not found` ([Full log](https://builder.r-hub.io/status/RcppEigen_0.3.3.5.0.tar.gz-0581f8e3be0e6cdae3a5ea2c8cb92a83))
- [RcppSMC](https://cran.r-project.org/package=RcppSMC) => `fatal error: 'math.h' file not found` ([Full log](https://builder.r-hub.io/status/RcppSMC_0.2.1.tar.gz-5779dbd43b4b8d5ac461a567e49952ee))

See also https://github.com/rcppsmc/rcppsmc/issues/27

**Comment by gaborcsardi** [comment]
I think this is fixed now, but then you hit #254.

**Comment by riccardoporreca** [comment]
Thanks @gaborcsardi!
