### ISSUE TITLE
Failing to build on solaris (no space left on device)

### ISSUE THREAD

**Issue by vissarion** [r-hub/rhub#277]
I am getting the following error when I try to build a package in Rhub (https://builder.r-hub.io) with Solaris 
```
#> Oracle Corporation SunOS 5.10 Generic Patch January 2005
#> mkdir: Failed to make directory "/export/home/X9e3Zqo/Rtemp"; No space left on device
```
This should admit an easy fix (maybe some clean-up on the server).

**Comment by gaborcsardi** [comment]
Thanks, done. We really should do this automatically: https://github.com/r-hub/rhub/issues/278
