### ISSUE TITLE
Clean up disk space on Solaris, automatically...

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#278]

**Comment by rstub** [comment]
Looks like the disk is full again. See for example https://builder.r-hub.io/status/swephR_0.2.1.tar.gz-d8685b8f2b5543f78424574f4ec26d55

**Comment by gaborcsardi** [comment]
Thanks, cleaned up. I am adding a cron job for this RIGHT NOW (!).

**Comment by gaborcsardi** [comment]
Fixed now.
