### ISSUE TITLE
strange error trying to load  ‘BiocInstaller’ in Fedora,  Ubuntu

### ISSUE THREAD

**Issue by rmendels** [r-hub/rhub#279]
See:

https://builder.r-hub.io/status/rerddapXtracto_0.3.5.tar.gz-ee30f11edf2c4057828eb8fc347c811b

https://builder.r-hub.io/status/rrerddapXtracto_0.3.5.tar.gz-280871d4a5ba4ff0b396d003cae48e7d

The error is:

Error in loadNamespace(name) : there is no package called ‘BiocInstaller’

The problem here is that is not in my namespace nor in the namespace of any package I use.  There is no use of BioConductor at all.

**Comment by halpo** [comment]
Another for confirmation.
https://builder.r-hub.io/status/purrrogress_0.1.0.tar.gz-a42742a843da487090c00e6a2dc19876

**Comment by krivit** [comment]
Confirming: https://builder.r-hub.io/status/ergm.ego_0.5.tar.gz-364b2b0cd91847eb8a93d5b694726963

My package doesn't require BioConductor either, but, in any case, the problem appears to be on https://builder.r-hub.io/status/ergm.ego_0.5.tar.gz-364b2b0cd91847eb8a93d5b694726963#L125 :
```
 125#> > source('https://bioconductor.org/biocLite.R')
 126#> Error in eval(quote({ :
 127#> With R version 3.6 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
 128#> Calls: source ... local -> eval.parent -> eval -> eval -> eval -> eval
 129#> Execution halted
```

**Comment by TolisChal** [comment]
I get the same error, i.e. "Error in loadNamespace(name) : there is no package called ‘BiocInstaller’ " for all the linux os except in Debian Linux, R-release, GCC.
Here is a typical check https://builder.r-hub.io/status/volesti_1.0.2.tar.gz-036fe6295961cbb67166caeb7fee6283

**Comment by michaelspence** [comment]
I get the same error here
https://builder.r-hub.io/status/LeMaRns_0.1.0.tar.gz-da511730ecdf46ba9c34d6b72f92a408 
for all the linux os.

It does however work on Windows.

**Comment by gaborcsardi** [comment]
Thanks for the reports! Linux should be good now.

**Comment by gaborcsardi** [comment]
All platforms should be ok now: https://github.com/r-hub/devops-issues/issues/43

Please report if you happen to find errors. Thanks.
