### ISSUE TITLE
Problem installing the R package 'RcppEigen' on macOS 10.9 Mavericks, R-oldrel (experimental)

### ISSUE THREAD

**Issue by TolisChal** [r-hub/rhub#280]
WhenI try to check my package in `macOS 10.9 Mavericks, R-oldrel (experimental)` it fails to install `RcppEigen' and finally I get the error message:
`#> Package required but not available: ‘RcppEigen’ `

and the package fails to be built.
Details https://builder.r-hub.io/status/volesti_1.0.2.tar.gz-ee3aac08dbc8b7ebff850ed3fa2755e6

**Comment by gaborcsardi** [comment]
This is known. That's a very old builder, that we should probably remove.
