### ISSUE TITLE
do not print env vars

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#283]
until we get "secure" env vars.

**Comment by jennybc** [comment]
To elaborate, a command like this:
```
rhub::check(env_vars = Sys.getenv("SECRET_THING", names = TRUE))
```
 leads to logs that contain lines like:
```
setting SECRET_THING to secret_secret_secret_secret (Windows)
echo SECRET_THING=secret_secret_secret_secret (Linux)
```
and console output with a similar line.

In general, it's nice to see the env vars in the log. If it's not too hard, maybe only suppress printing if the user supplies env vars?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
