### ISSUE TITLE
Issue building systemfonts on Windows

### ISSUE THREAD

**Issue by thomasp85** [r-hub/rhub#286]
When checking https://github.com/r-lib/systemfonts it fails to install with the following error:

```
#> C:/Rtools34/mingw_32/bin/g++ -shared -s -static-libgcc -Lc:/R/local330/lib/i386 -o systemfonts.dll tmp.def systemfonts.o init.o win/FontManagerWindows.o -L../windows/cairo-1.16.0/lib/i386 -lbz2 -lfreetype -lharfbuzz -lfreetype -lpng -lbz2 -lz -Lc:\R\local330/lib/i386 -Lc:\R\local330/lib -LC:/PROGRA~1/R/R-3.6.0/bin/i386 -lR
 418#> ../windows/cairo-1.16.0/lib/i386/libfreetype.a(ftbzip2.o):(.text+0x2b): undefined reference to `BZ2_bzDecompressEnd'
 419#> ../windows/cairo-1.16.0/lib/i386/libfreetype.a(ftbzip2.o):(.text+0x337): undefined reference to `BZ2_bzDecompressEnd'
 420#> ../windows/cairo-1.16.0/lib/i386/libfreetype.a(ftbzip2.o):(.text+0xf6): undefined reference to `BZ2_bzDecompress'
 421#> ../windows/cairo-1.16.0/lib/i386/libfreetype.a(ftbzip2.o):(.text+0x388): undefined reference to `BZ2_bzDecompressInit'
 422#> collect2.exe: error: ld returned 1 exit status
 423#> ../windows/cairo-1.16.0/lib/i386/libfreetype.a(ftbzip2.o):(.text+0x595): undefined reference to `BZ2_bzDecompressInit'
 424#> no DLL was created
```

This error cannot be reproduced locally nor on win-builder so it appears to be related to how the r-hub windows environment is set up (potentially linking to an old bz2 library instead of the one provided by the package)

**Comment by gaborcsardi** [comment]
This is how it is set up, in particular, `local330.zip` is supposed to contain most (all?) libraries CRAN uses. What exactly does your package need?

**Comment by jeroen** [comment]
@gaborcsardi I think the problem is that this build of R somehow adds the `-Lc:/R/local330/lib/i386` flag all the way at the front such that it gets preference over the package `PKG_LIBS`?

@thomasp85 can you add a link to winbuilder output to see what the linking step looks like there?

**Comment by thomasp85** [comment]
https://win-builder.r-project.org/O4obXHDo9vWl/00install.out
