### ISSUE TITLE
R-hub not installing java correctly, can't check package using RJDBC

### ISSUE THREAD

**Issue by nfultz** [r-hub/rhub#288]
Migrated from R OpenSci slack:

Does R-hub support java/rjava ? My package check was fine on winbuilder but failed on r-hub; it had a line about not installing the JRE, and then could not find the remotes package futher down:
```E: Package 'openjdk-7-jre-headless' has no installation candidate:```

Log is here -
https://builder.r-hub.io/status/original/AWR.Athena_2.0.7-0.tar.gz-c45e58b938fc8b1d05518265104db55f

**Comment by jeroen** [comment]
Probably need to update here: https://github.com/r-hub/sysreqsdb/blob/master/sysreqs/java.json

**Comment by gaborcsardi** [comment]
I think we probably need to run `R CMD javareconf`

**Comment by maelle** [comment]
Possibly related #265
