### ISSUE TITLE
R CMD check errored but build reports success

### ISSUE THREAD

**Issue by nealrichardson** [r-hub/rhub#291]
https://builder.r-hub.io/status/arrow_0.14.0.tar.gz-d5c634e414994adcaef57d3fcef00605 reports "success" but `R CMD check` actually errored: https://builder.r-hub.io/status/arrow_0.14.0.tar.gz-d5c634e414994adcaef57d3fcef00605#L2636

**Comment by gaborcsardi** [comment]
This seems like a bug in `R CMD check`, or CRAN serving a corrupt file.

**Comment by nealrichardson** [comment]
I guess there's two issues, right? (1) whatever caused `embedded nul in string: '\xd6/KR\0\005isdKR\0\005is'` and (2) the fact that `Execution halted` didn't fail the build. Maybe the first one is on R CMD check or CRAN, but the second one sounds to me like an issue with the Jenkins job configuration.

**Comment by nealrichardson** [comment]
Ran into this again: `check` ERRORed but the build reported SUCCESS https://builder.r-hub.io/status/arrow_0.15.1.tar.gz-eae23a523e8726239588880ac98d00ae#L2186. Looks like uploading artifacts from the build failure is involved: `Build step 'Send files or execute commands over SSH' changed build result to SUCCESS`

Update: the email I got this time did correctly report ERROR, it was just the web app that showed "success" at the top of the logs.

**Comment by gaborcsardi** [comment]
> Build step 'Send files or execute commands over SSH' changed build result to SUCCESS

That means that the scheduler successfully performed all steps of the build, and it does not reflect the outcome of `R CMD check`.
