### ISSUE TITLE
Windows machines should define CXX14 and CXX14STD

### ISSUE THREAD

**Issue by DavisVaughan** [r-hub/rhub#292]
R packages requiring C++14 currently do not pass on rhub, but do pass on win-builder. Even though both use RTools34, on win-builder `CXX14` and `CXX14STD` are defined. That prevents you from getting this error, which you do get on rhub:

```
C++14 standard requested but CXX14 is not defined
```

The suggestions from Jeroen is to set the following in `~/.R/Makevars.win` (or is it just `~/.R/Makevars`? I'm not sure):

- `CXX14 = g++`
- `CXX14STD = -std=gnu++1y`
- We are not sure about `gnu++1y`, which win-builder might be setting to `gnu++14` instead, but I think either will work.

See this issue for a little bit more information:
https://github.com/r-windows/r-testing/issues/1#issue-379473228

**Comment by gaborcsardi** [comment]
@jeroen would it make sense to set these by default in the Windows build?

**Comment by jeroen** [comment]
Yes I think it makes sense to mimic what Cran does. You need the same think
for the rstan package.

**Comment by gaborcsardi** [comment]
@jeroen Sorry, what I mean is to set it up in the Windows installer by default? If windows packages are built by rtools, and rtools supports this, then why not set it in the default Makevars?

**Comment by jeroen** [comment]
This is up to r-core, not me. But the c++14 support in gcc 4.9.3 is incomplete so that's probably why it isn't advertised. Some things work but some other features do not.

**Comment by BINBINCC** [comment]
Please in 
Linux，how to define CXX14 and CXX14STD

**Comment by gaborcsardi** [comment]
Can these set via environment variables?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
