### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiaodaigh** [r-hub/rhub#293]
I hve been getting this error

```
-  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  rhub error
```

is it because rhub is down?

I tried to upload to `https://builder.r-hub.io/` and I get the following

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

**Comment by gaborcsardi** [comment]
Thanks, should be ok now.

**Comment by malcolmbarrett** [comment]
I'm now having this error (on both the pkg and site) as well. Not sure if the root problem is the same; happy to open a new issue if not

**Comment by gaborcsardi** [comment]
Thanks! Still working on migrating to bigger disks. Should be OK now.

**Comment by malcolmbarrett** [comment]
Thanks for the quick fix @gaborcsardi! Now all good on my end. R-hub is a lifesaver, so thanks to the team for all the hard work :)

**Comment by DyfanJones** [comment]
Hi all,  has this issue been resolved? I am getting the same  error:
```
─  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  rhub error
```

**Comment by kylebaron** [comment]
I had been getting the error the past couple of days; had a check work early this AM but now getting the error again.

```r
> check_for_cran()
─  Building package
─  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  rhub error
```

**Comment by DyfanJones** [comment]
Tried to check my package manually by uploading source code to:  https://builder.r-hub.io/
and i am getting the same error as @xiaodaigh 
```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

**Comment by jonathan-taylor** [comment]
Getting similar errors -- this worked an hour or so, but now does not:

> rhub::check_on_windows("~/git-repos/selectiveR/selectiveInference_1.2.5.tar.gz", email="jetaylor74@gmail.com")
─  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  rhub error
>

**Comment by gaborcsardi** [comment]
@jonathan-taylor please try again, it should be fixed.

**Comment by idblr** [comment]
Getting similar errors today on both the package (CRAN and Github dev versions) and website. I tried both `check_for_cran()` and `check()` functions.

>  rhub::check_for_cran()
> Building package
> Uploading package
> Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
>    rhub error

After uploading to https://builder.r-hub.io/ and I get a similar error to the OP

**Comment by cjvanlissa** [comment]
I'm also getting this, for https://github.com/cjvanlissa/pema

```
> rhub::check_for_cran()
-  Building package
-  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  rhub error
```

This is a package that uses compiled `stan` code, so my best guesses are that this might be due to either compiled code, or due to the size of all the included libraries.

**Comment by gaborcsardi** [comment]
How big is your source package?

**Comment by gaborcsardi** [comment]
Great! Btw. in the future please open a new issue instead of commenting on an old one. There is a good chance that we miss comments on closed issues.
