### ISSUE TITLE
Warning when testing checkpoint on Windows, but package installs succcessfully

### ISSUE THREAD

**Issue by Hong-Revo** [r-hub/rhub#298]
Hi Maelle/Gabor,

This is with the [checkpoint](https://github.com/RevolutionAnalytics/checkpoint) package which I've just taken over, whee.

When I run `rhub::check_for_cran()`, the Ubuntu and Fedora tests run OK, but Windows reports a warning when building a vignette:

```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
--- re-building 'checkpoint.Rmd' using rmarkdown
Quitting from lines 158-168 (checkpoint.Rmd) 
Error: processing vignette 'checkpoint.Rmd' failed with diagnostics:
arguments imply differing number of rows: 1, 0
--- failed re-building 'checkpoint.Rmd'
```

However, when I run `devtools::install(build_vignettes=TRUE)`, it installs without a problem. This is on a Windows 10 machine.

Looking at the `checkpoint.Rmd` vignette, lines 158-168 are

```
 ```{r checkpoint, warning=FALSE}
## Create a folder to contain the checkpoint
## This is optional - the default is to use ~/.checkpoint

dir.create(file.path(tempdir(), ".checkpoint"), recursive = TRUE, showWarnings = FALSE)

## Create a checkpoint by specifying a snapshot date

library(checkpoint)
checkpoint("2017-04-01", project = example_project, 
           checkpointLocation = tempdir())
```

As far as I can tell, there shouldn't be a problem with this code. Is there something odd about the tempdir location on the Rhub Windows machine?

**Comment by gaborcsardi** [comment]
I am not sure if this is about `tempdir()`, the error if about differing number of _rows_. So maybe it is coming from the `checkpoint()` call?

**Comment by Hong-Revo** [comment]
Yes, sorry, that's what I meant. The only difference in the arguments to `checkpoint` is the value of `tempdir`.

You can see the artifacts here: https://artifacts.r-hub.io/checkpoint_0.4.7.tar.gz-3df2e55bbbdf40dcb51effce7e8fcd0a/checkpoint.Rcheck/

Actually, I see now that installing the package also worked on RHub, it's only R CMD check that failed. Is there a way to replicate what RHub does on my own machine?

**Comment by Hong-Revo** [comment]
Probably an internal checkpoint issue
