### ISSUE TITLE
Possible to check validity of URLs?

### ISSUE THREAD

**Issue by hongooi73** [r-hub/rhub#299]
When I submit a package to CRAN, it checks that any URLs in the code and documentation are valid. This is actually quite a nice feature, as it helps prevent link rot.

Is it possible to do the same on RHub? I've found a few times that a package will pass the checks here but then CRAN will detect a bad link.

**Comment by maelle** [comment]
Not an answer regarding R-hub, but ICYMI there's a `check_package_urls()` function in https://github.com/hrbrmstr/hrbraddins#whats-in-the-tin

**Comment by gaborcsardi** [comment]
Doesn't `--as-cran`, i.e. `check_for_cran()` check for these?

**Comment by Hong-Revo** [comment]
Hi guys, no, `check_for_cran()` doesn't pick this up. To test this, you can just pick any of your repos, add a nonsense URL to the readme, and send it to RHub. The check should pass just fine.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
