### ISSUE TITLE
Email validation 

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#30]
I built on a machine yesterday. I acquired a token.  I use it for more than one build.

Today I need a new token.  On the same machine.  Really?

**Comment by gaborcsardi** [comment]
I assume this is all about from the command line.

I don't think you need a new token, at least this is not intended. You just need to add the old token to the new machine:

```
validate_email(email = <email>, token = <token>)
``` 

If your email address is different, though, then you do need another token, tokens belong to email addresses currently.

**Comment by eddelbuettel** [comment]
No, actually all in R for once.

Tokens are local to the machine, and stored persistently?  I don't know rappdirs well enough -- I 'ls -ltr'-ed on the box and found nothing it had left behind.

One token per email is best.  Same token on workstation at home, work, on laptop, ...

**Comment by gaborcsardi** [comment]
Yes, tokens are stored locally. They are stored in an OS-dependent directory:
```r
❯ rappdirs::user_data_dir("rhub", "rhub")
[1] "/Users/gaborcsardi/Library/Application Support/rhub"
```

It might also happen that `rappdirs` fails on some strange platforms, like in a minimal docker container. What is your `user_data_dir()`? 

Btw. later I'll add some functions to list them, delete them, etc.

**Comment by eddelbuettel** [comment]
[Vanilla Ubuntu 16.04, no tricks.

`.local/share/rhub` -- but `validated_emails.csv` has an empty string as token for my email.

**Comment by gaborcsardi** [comment]
OK, could be a bug then, I'll take a look.

**Comment by eddelbuettel** [comment]
See my updated comment.  Agreed that is a bug,

**Comment by gaborcsardi** [comment]
Hmmm, in should indeed.

**Comment by gaborcsardi** [comment]
Actually, `check()` just calls `validate_email()`, which adds the email to the list, so I am not sure what went wrong for you. Just tried it, and it works fine.

Nevertheless, I'll add checks so that empty tokens are not added to the file.

**Comment by eddelbuettel** [comment]
Any packages besides `rhub` itself I should reinstall?

**Comment by gaborcsardi** [comment]
I don't think so. 

I am rewriting the whole validating emails part now. It was messy and confusing. So hopefully it will be much better soon. 

It is unfortunately pretty hard to test interactive code....

**Comment by eddelbuettel** [comment]
Agreed on the testing. I'll give it another quick spin last this morning.

**Comment by gaborcsardi** [comment]
Thanks! Hopefully it is better now.
