### ISSUE TITLE
Error in rbind(deparse.level, ...) :    numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by rmsharp** [r-hub/rhub#301]
This looks almost identical to #259, which is closed. When testing the local version of https://github.com/rmsharp/nprcmanager, I get the following.

> cran_prep$cran_summary()
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

Debugging quickly provides the following:

Browse[3]> 
debug: result <- do.call("rbind", lapply(x, rectangle_status))
Browse[3]> str(lapply(x, rectangle_status))
List of 3
 $ windows-x86_64-devel:'data.frame':	1 obs. of  7 variables:
  ..$ type     : chr "NOTE"
  ..$ message  : chr "checking CRAN incoming feasibility ... NOTE\nMaintainer: 'R. Mark Sharp <rmsharp@me.com>'\n\nNew submission\n\n"| __truncated__
  ..$ hash     : chr "f6a81a3b267893075828b3aecf56f409"
  ..$ package  : chr "nprcmanager"
  ..$ version  : chr "0.5.30"
  ..$ submitted: chr "2019-09-27T04:38:13.579Z"
  ..$ platform : chr "windows-x86_64-devel (r-devel)"
 $ ubuntu-gcc-release  :'data.frame':	1 obs. of  7 variables:
  ..$ type     : chr "NOTE"
  ..$ message  : chr "checking CRAN incoming feasibility ... NOTE\nMaintainer: ‘R. Mark Sharp <rmsharp@me.com>’\n\nNew submission\n\n"| __truncated__
  ..$ hash     : chr "f6a81a3b267893075828b3aecf56f409"
  ..$ package  : chr "nprcmanager"
  ..$ version  : chr "0.5.30"
  ..$ submitted: chr "2019-09-27T04:38:13.579Z"
  ..$ platform : chr "ubuntu-gcc-release (r-release)"
 $ fedora-clang-devel  :'data.frame':	1 obs. of  4 variables:
  ..$ package  : chr "nprcmanager"
  ..$ version  : chr "0.5.30"
  ..$ submitted: chr "2019-09-27T04:38:13.579Z"
  ..$ platform : chr "fedora-clang-devel (r-devel)"
Browse[3]>

**Comment by maelle** [comment]
Sorry, IIRC it might be fixed in the GitHub version only, not on CRAN yet. Can you try after `remotes::install_github("r-hub/rhub")`? Thanks!

**Comment by rmsharp** [comment]
That has solved the problem. I should have tried that. Now I have to figure out why CRAN packages a failing to load some of the time.
