### ISSUE TITLE
HiCseg not installed on solaris

### ISSUE THREAD

**Issue by jamesdalg** [r-hub/rhub#309]
* checking package dependencies ... ERROR
Package required but not available: ‘HiCseg’

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.

**Comment by gaborcsardi** [comment]
It probably does not build/compile on Solaris, and the log contains the error message why.

**Comment by jamesdalg** [comment]
I'll try checking HiCseg. CNVScope is my package, which depends on HiCseg.

**Comment by gaborcsardi** [comment]
It is in your log for CNVScope.

**Comment by gaborcsardi** [comment]
There is no GSL it seems.

```
* installing *source* package ‘HiCseg’ ...
** package ‘HiCseg’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/opt/csw/bin/gcc -I"/opt/R/R-3.6.0/lib/R/include" -DNDEBUG -I/usr/local/include -I.  -I/opt/cdw/include -I/usr/local/include  -fPIC  -O2  -c HiCseg_linkR.c -o HiCseg_linkR.o
HiCseg_linkR.c:11:28: fatal error: gsl/gsl_matrix.h: No such file or directory
compilation terminated.
gmake: *** [/opt/R/R-3.6.0/lib/R/etc/Makeconf:167: HiCseg_linkR.o] Error 1
ERROR: compilation failed for package ‘HiCseg’
* removing ‘/export/home/XYfiCmk/R/HiCseg’
```

**Comment by jamesdalg** [comment]
I was just about to post it a second before you did. Is there a way to install a solaris dependency? Here are some installation instructions I found for Solaris 10:
https://www.opencsw.org/packages/CSWgsl-dev/
It appears to be only about 4 lines of commands.

**Comment by gaborcsardi** [comment]
This is finally fixed now.
