### ISSUE TITLE
build passes on r-hub solaris but fails on CRAN

### ISSUE THREAD

**Issue by tdhock** [r-hub/rhub#311]
I expected that r-hub solaris should report a fail for these builds, but they passed: 
- https://builder.r-hub.io/status/nc_2019.10.19.tar.gz-8b46d2a02a6340bcb313eeec96e404f3
- https://builder.r-hub.io/status/nc_2019.10.19.tar.gz-db58a706bd8f4ae09869dc9b9b23cd96

The CRAN failure report is https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/nc-00check.html

This is a problem for me because I don't have access to a solaris machine, and I am using R-hub to make sure my pkg is OK before CRAN submission, so in this case I have no way of knowing when my pkg is ready for CRAN submission.

Am I using R-hub incorrectly? Is there some way I can make `r-hub::check_on_solaris` do the same thing as CRAN solaris checks?

**Comment by gaborcsardi** [comment]
> Am I using R-hub incorrectly? 

Well, how are you using it? E.g. did you use `--as-cran`? Maybe CRAN uses that.

> Is there some way I can make r-hub::check_on_solaris do the same thing as CRAN solaris checks?

That is hard to know, because we don't know what the CRAN solaris checks do. :( 

It could just because of the difference in the R versions, or maybe `--as-cran`, so I would try that first.

**Comment by tdhock** [comment]
thanks for the tip, I didn't know that I need to tell rhub to use --as-cran.
```
> rhub::check_on_solaris("~/R/nc_2019.10.19.tar.gz", check_args="--as-cran")
-  Uploading package
-  Preparing build, see status at
   https://builder.r-hub.io/status/nc_2019.10.19.tar.gz-c7f8bffce2bc42c0915e54585e1ee240
-  Build started
-  Downloading package
-  Setting up home directory
-  Running check
-  Installing package dependencies
-  Running R CMD check
-  using log directory /export/home/XAiEcEH/nc.Rcheck (14m 16.5s)
-  using R version 3.6.0 (2019-04-26)
-  using platform: i386-pc-solaris2.10 (32-bit)
-  using session charset: UTF-8
-  using option --as-cran
v  checking for file nc/DESCRIPTION
-  this is package nc version 2019.10.19
W  checking CRAN incoming feasibility (10.7s)
   Maintainer: Toby Dylan Hocking <toby.hocking@r-project.org>
   
   Insufficient package version (submitted: 2019.10.19, existing: 2019.10.19)
   
   Days since last update: 3
v  checking package namespace information
v  checking package dependencies (1.3s)
v  checking if this is a source package
v  checking if there is a namespace
v  checking for executable files
v  checking for hidden files and directories
v  checking for portable file names
v  checking for sufficient/correct file permissions
v  checking serialization versions
v  checking whether package nc can be installed (2s)
v  checking installed package size
v  checking package directory
E  checking for future file timestamps (1.3s)
   This system is set to the wrong time: please correct
      system: 2019-10-31 22:24 (UTC)
     correct: 2019-10-31 21:24 (UTC)
   
    
> 
```

**Comment by gaborcsardi** [comment]
It is off indeed, even though it is running NTP. :(

**Comment by gaborcsardi** [comment]
OK, I made another attempt to fix this. Will see if it'll last in a day or so.

**Comment by gaborcsardi** [comment]
Seems like I managed to fix the time. A reboot might still restore the wrong time, we'll see.
