### ISSUE TITLE
PREPERROR on Ubuntu Linux 16.04 LTS, R-release, GCC not on other platforms

### ISSUE THREAD

**Issue by rmsharp** [r-hub/rhub#313]
Although it looks like some CRAN packages that I am dependent on are not available on the Ubuntu Linux 16.04 LTS platform because of openssl not being found. I have attached the link to the log and the first error report I found within that log.

https://builder.r-hub.io/status/nprcmanager_0.5.36.tar.gz-fb46dabf93c74cd5a92180909c2dd786#L6223

3245#> ------------------------- ANTICONF ERROR ---------------------------
3246#> Configuration failed because openssl was not found. Try installing:
3247#> * deb: libssl-dev (Debian, Ubuntu, etc)
3248#> * rpm: openssl-devel (Fedora, CentOS, RHEL)
3249#> * csw: libssl_dev (Solaris)
3250#> * brew: openssl@1.1 (Mac OSX)
3251#> If openssl is already installed, check that 'pkg-config' is in your
3252#> PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
3253#> is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
3254#> R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
3255#> --------------------------------------------------------------------
3256#> ERROR: configuration failed for package ‘openssl’

**Comment by gaborcsardi** [comment]
It failed because it failed to install the openssl dependency because of a missing system requirement:
```
#> * installing *source* package ‘openssl’ ...
#> ** package ‘openssl’ successfully unpacked and MD5 sums checked
#> ** using staged installation
#> Using PKG_CFLAGS=
#> ------------------------- ANTICONF ERROR ---------------------------
#> Configuration failed because openssl was not found. Try installing:
#>  * deb: libssl-dev (Debian, Ubuntu, etc)
#>  * rpm: openssl-devel (Fedora, CentOS, RHEL)
#>  * csw: libssl_dev (Solaris)
#>  * brew: openssl@1.1 (Mac OSX)
#> If openssl is already installed, check that 'pkg-config' is in your
#> PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
#> is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
#> R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
#> --------------------------------------------------------------------
#> ERROR: configuration failed for package ‘openssl’
#> * removing ‘/home/docker/R/openssl’
```

Probably a temporary error in the system requirements lookup. Please submit the package again.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
