### ISSUE TITLE
unable to load shared object /R/Rcpp/libs/x64/Rcpp.dll

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#314]
Currently I always get an error for Windows, when I run check_for_cran().

I don't know what causes the issue with the shared object.

**Comment by gaborcsardi** [comment]
Maybe this is a recent binary incompatibility. I updated R-devel, can you please try again? Thanks.

**Comment by ycphs** [comment]
Thank you. Now it works fine.
