### ISSUE TITLE
Fedora Linux, R-devel, clang, gfortran

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#315]
Currently the rebuild of the of vignette outputs delivers a warning. 

Error: processing vignette 'Introduction.Rnw' failed with diagnostics:
Running 'texi2dvi' on 'Introduction.tex' failed.
LaTeX errors:
! LaTeX Error: File <framed.sty' not found.

**Comment by ycphs** [comment]
Could you provide a more complete installation texlive for fedora?
Should I change some parameter?

**Comment by gaborcsardi** [comment]
Do you actually need to build the manual and vignettes on Fedora? I suggest you use `--no-build-vignettes --no-manual` on Fedora.

**Comment by ycphs** [comment]
If you run check_for_cran(), it would be great if this two options are set automatically. Otherwise you have to check the every platform separate with different parameters and the benefit of check_for_cran is gone.

**Comment by gaborcsardi** [comment]
That is a good point.

**Comment by ycphs** [comment]
I prepare a pull request

**Comment by ycphs** [comment]
Please check my [pull request](https://github.com/r-hub/rhub/pull/316).

Thank you for your support.
