### ISSUE TITLE
" Stream error in the HTTP/2 framing layer"

### ISSUE THREAD

**Issue by mdsumner** [r-hub/rhub#32]
I don't have anything to offer here, just listing this in case it's helpful. 

I submitted check runs today from a different machine (Windows), same email, by first using validate_email(). 

On second machine  (also Windows) I can't get it to work. 
```R
devtools::install_github("r-hub/rhub")
#Skipping install of 'rhub' from a github remote, the SHA1 (41a09fa4) has not changed since last install.
rhub::validate_email("<me@email.com>")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer

```

Try with token from earlier today. 

```R
rhub::validate_email("<me@email.com>", "<a token of my extreme>")
#Token added for ‘<me@email.com>’

 rhub::check_on_windows()
#─  Building package
#─  Uploading package
#Error in curl::curl_fetch_memory(url, handle = handle) : 
 # Stream error in the HTTP/2 framing layer
```

I tried again moving across to Debian, installing from github then validate_email - I got the new token and proceeded ok. 

Thanks!

**Comment by jeroenooms** [comment]
@gaborcsardi does this still happen after you disabled HTTP2 on the server??

**Comment by gaborcsardi** [comment]
I disabled it about an hour ago (again, it crept back, nginx config is autogenerated), I hope these happened before that. 

@mdsumner can you please try it now?

**Comment by jeroenooms** [comment]
<img width="665" alt="screen shot 2016-10-05 at 3 12 00 pm" src="https://cloud.githubusercontent.com/assets/216319/19114396/19805d28-8b0e-11e6-8fa6-f63a8a7e321f.png">

**Comment by jeroenooms** [comment]
Your server is still advertising HTTP/2 support.

**Comment by gaborcsardi** [comment]
OK, should be off now. 

I had to turn it off for all dokku web apps.....

**Comment by mdsumner** [comment]
"Build started ..." -  working now, thanks!

**Comment by gaborcsardi** [comment]
OK, I fixed this in my own dokku installation, so it should not come up again.  To be extra sure, I'll also disable http2 in the R package: #29

**Comment by jeroenooms** [comment]
I would recommend against disabling HTTP/2 on the client, so that you will catch server problems if they (re)appear. Other http/rhub clients might also default to HTTP/2 if the server has it enabled.

**Comment by jeroenooms** [comment]
You can just enable HTTP/2 on OSX:

```
brew install curl --with-nghttp2
```
```r
install.packages("curl", type = "source")
```

**Comment by jeroenooms** [comment]
You're not anticipating browser clients? Or is this a separate API?

**Comment by gaborcsardi** [comment]
True with OSX.

Also, I'll just add the r-hub monitoring tool to check that http2 is disabled on the server for now. 

OK, no disabling in the client. :)

Re other clients, the file upload part is a separate API. In the browser it is a proper file upload (there is no API client in the browser or sg like that), in the CLI it is a single JSON POST with an embedded file.

I have never seen problems with the file upload, although I have no idea which browsers do http/2 by default.

**Comment by jeroenooms** [comment]
Most browsers now support HTTP/2 however wikipedia says: 

> ... most client implementations (Firefox,[25] Chrome, Safari, Opera, IE, Edge) have stated that they will only support HTTP/2 over TLS, which makes encryption de facto mandatory.

You're using the non https API right? In that case browsers will default to HTTP 1.1

**Comment by jeroenooms** [comment]
No wait you must be using https, otherwise curl wouldn't use HTTP/2 either...

**Comment by gaborcsardi** [comment]
Yeah, it is https only. It is 2016. :)

**Comment by jeroenooms** [comment]
OK well in that case expect browsers to use HTTP/2 if it is enabled :)

**Comment by gaborcsardi** [comment]
I suspect that it is a combination of the POST and libcurl that ticks it off, because _a lot_ of people use dokku for web apps, and even more people use nignx, and the dokku maintainer hasn't seen this issue before. I get it that it is an nginx bug, but I strongly suspect that browsers do not trigger it.

**Comment by jeroenooms** [comment]
Yeah, it's some combination of `libcurl` with `libnghttp2` that is triggered by `dokku` with `nginx` for particular `POST` requests. Good luck debugging that =)
