### ISSUE TITLE
preperror

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#321]
preperror for Fedora Linux, R-devel, clang, gfortran

https://builder.r-hub.io/status/original/openxlsx_4.1.3.9007.tar.gz-421794defdef45458ff301393c669f1f

completed for Windows Server 2008 R2 SP1, R-devel, 32/64 bit

**Comment by phargarten2** [comment]
Duplicate of #318.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
