### ISSUE TITLE
Error when running local check with rhub/debian-clang-devel

### ISSUE THREAD

**Issue by jromanowska** [r-hub/rhub#322]
Hi,
I'm trying to check locally our package and specifically, we want to reproduce an error that was found by CRAN checks, on debian-clang-devel image. Unfortunately, I get the following error and don't know how to proceed... It seems like it cannot find deb.debian.org - when I go to this address in my browser, it actually gets redirected to http://ftp.debian.org/debian/, but I'm not sure whether that's the source of my problem...

```
check.out <- local_check_linux(".", image = "rhub/debian-clang-devel", check_args = "--as-cran", artifacts = "TMP")
─  Building package

Container name: f8099b9f-2751-4ee6-a763-9495351173ee-2
It will _not_ be removed after the check.

R-hub Linux builder script v0.10.0 (c) R Consortium, 2018-2019

Package: /tmp/RtmpHVTb7a/file65a03a1a57b5/Haplin_7.7.0.tar.gz
Docker image: rhub/debian-clang-devel
Env vars: 
R CMD check arguments: --as-cran
Sysreqs platform: linux-x86_64-debian-clang

>>>>>==================== Installing system requirements
c8c75a7ae8c4cc4ceb683d795dc4f3f3922a76acb6ec17b375c95b2d7c51cec9
Err:1 http://deb.debian.org/debian testing InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/testing/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package git-core
E: Unable to locate package pandoc
E: Unable to locate package pandoc-citeproc
Build container is f8099b9f-2751-4ee6-a763-9495351173ee-2
Error in run(bash, c(file.path(wd, "rhub-linux.sh"), args), echo = TRUE,  : 
  System command error
```

**Comment by gaborcsardi** [comment]
Seems like an error with the Debian servers, probably temporary.

**Comment by jromanowska** [comment]
That's what I thought, so I'll wait and see...

**Comment by jromanowska** [comment]
Hi, I think the problem is somewhere else. When I go to the address http://deb.debian.org/debian/dists/testing/InRelease, it's all there - no problem, but I can't seem to get it to work when I invoke local_check_linux. I'm new to docker - only installed it right before I used rhub. Should I set some specific parameters so that the docker image generated by local_check_linux has internet access? Maybe that's the problem?

**Comment by gaborcsardi** [comment]
Could be. Can you try to start up the container manually, and see if you can download that page? Something like

```
docker run -ti rhub/debian-clang-devel bash
```

and then 

```
wget http://deb.debian.org/debian/dists/testing/InRelease
```

**Comment by jromanowska** [comment]
I didn't get the "wget" command to work, but when I write "ping google.com", I get " Temporary failure in name resolution". Then, I tried running
`docker run -ti --net=host rhub/debian-clang-devel bash`
and I get an instant response from ping

**Comment by gaborcsardi** [comment]
OK, so maybe you could try to set `host` as a default somewhere? IDK how that is done, or if it is possible.

**Comment by jromanowska** [comment]
As I've said, I'm new to docker - I have no idea how could I set it. Isn't it easier if you could point to the line in your code (is it "rhub-linux.sh"?) where I can set it locally on my computer?

**Comment by gaborcsardi** [comment]
No, I cannot do that because that's not the appropriate setting for everyone. What is your OS?

**Comment by jromanowska** [comment]
I wanted to set it locally on my computer. I'm using Ubuntu 18.04

**Comment by gaborcsardi** [comment]
See "DISABLE THE DEFAULT BRIDGE NETWORK" here: https://docs.docker.com/v17.09/engine/userguide/networking/#the-default-bridge-network

**Comment by jromanowska** [comment]
I couldn't really find the file that they describe in this help document, but with the help of my colleague, I created a script that pulls one of the rhub images and I manually ran checks in it.
Thus, I'm closing this issue.
Thank you for the time you spent to help me here!

**Comment by gaborcsardi** [comment]
For reference, I believe that the file is `/etc/docker/daemon.json` on Linux.

**Comment by maelle** [comment]
@jromanowska Good luck! Once your problem on CRAN is fixed, would you be interested in writing a short post for the [R-hub blog](https://blog.r-hub.io/) explaining your journey to fixing it? It could be interesting to other package maintainers to hear about how you went about it. 

At the moment the R-hub blog doesn't show authors of posts but this will change + for a guest post we'd add a sentence at the beginning of the post to be sure there are links to your online presence.

**Comment by jromanowska** [comment]
> For reference, I believe that the file is `/etc/docker/daemon.json` on Linux.

Yes, that's correct, but I couldn't find it in my system :)

**Comment by gaborcsardi** [comment]
@jromanowska You can try to create it.

**Comment by gaborcsardi** [comment]
But I am not sure what the right thing is here. Maybe rhub should expose docker arguments? That would probably make sense. Here is an issue for it: https://github.com/r-hub/rhub/issues/324

**Comment by jromanowska** [comment]
It's not an easy decision - but I'm happy that you'll discuss this! :)
Thanks again!

**Comment by jromanowska** [comment]
> @jromanowska Good luck! Once your problem on CRAN is fixed, would you be interested in writing a short post for the [R-hub blog](https://blog.r-hub.io/) explaining your journey to fixing it? It could be interesting to other package maintainers to hear about how you went about it.
> 
> At the moment the R-hub blog doesn't show authors of posts but this will change + for a guest post we'd add a sentence at the beginning of the post to be sure there are links to your online presence.

@maelle - I guess I could write something, but I don't know whether I can make it before the New Years...

**Comment by maelle** [comment]
@jromanowska np, I'll open an issue in the R-hub blog so we don't forget, but of course you can still say no later if you don't have time next year ever, totally understandable!

**Comment by maelle** [comment]
(in the meantime please keep notes about the process :wink:)

**Comment by jromanowska** [comment]
Great! No, no, when I say "yes", it means yes :)

**Comment by maelle** [comment]
Cool, thanks a ton, but really no pressure, that's what I mean!
