### ISSUE TITLE
Note when submitting new R package

### ISSUE THREAD

**Issue by uczhn** [r-hub/rhub#323]
**RE: Note when submitting new R package**

I am in the process of releasing a  R package to CRAN.  Local  checks on my computer was successful with no errors, warnings or notes. However, when submitted to CRAN I get a **Note** regarding the maintainer's email address. I have checked the required format  and it was correct. I have also changed the format of the  maintainer's details and  local checks were successful, but it came back with the same Note from CRAN as shown below:

checking CRAN incoming feasibility ... NOTE
  Maintainer: 'Alias Alias <alias.alias@nottingham.ac.uk>'

Can any body tell me what the problem is?
Thanks in advance

**Comment by gaborcsardi** [comment]
That is not a problem, you can submit your package. Well, assuming that this is not your real email address, because CRAN will probably not publish a package with an address like this. :)

**Comment by uczhn** [comment]
Thank you for your comment. However I released it with my valid email address and got a message with the note regarding the maintainer's email address. My question is, will be package be accepted with the note? 
Thanks again.

**Comment by gaborcsardi** [comment]
Yes, every new package has this note, it basically means that the package is new.

**Comment by uczhn** [comment]
Thanks a lot,  you have been very helpful. 
I appreciate it.
