### ISSUE TITLE
Email validation: check() looks in DESCRIPTION and validate_email() in git config

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#33]
First, I got:
```r
> validate_email()
Please check your emails for the R-hub access token
token: *********
Token added for ‘hb@aroma-project.org’
```
and then immediately after I got:
```r
> check()
‘henrikb@braju.com’ is not validated, validating now.
Please check your emails for the R-hub access token
token: 
```
I see that `validate_email()` defaults to Git for my email address, whereas, I assume, `check()` looks at the email address in the `DESCRIPTION` file.

Also, the validation for ‘henrikb@braju.com’ never reaches me. I never have issues with this address. Prior to trying the rhub package, I tried to the online submission and I did recieved a short validation code that worked there.  So, not sure what's going on - could the fact that I did that online validation somehow block the authentication here?

The workaround is to override the DESCRIPTION email as:
```r
> check(email="hb@aroma-project.org")
[...]
```
which works.

PS. This is all looks neat :)

**Comment by gaborcsardi** [comment]
OK, I guess the functions around the validated emails should be more elaborated. I'll add a better UI for the interactive() version.
