### ISSUE TITLE
Trying to reproduce UBSAN error of CRAN package bigstatsr

### ISSUE THREAD

**Issue by privefl** [r-hub/rhub#330]
Trying to reproduce UBSAN error of CRAN package bigstatsr: https://cran.r-project.org/web/checks/check_results_bigstatsr.html.

I downloaded the tag.gz from CRAN and ran `rhub::check_with_sanitizers("bigstatsr_1.0.1.tar.gz")`.

I'm getting this: https://builder.r-hub.io/status/bigstatsr_1.0.1.tar.gz-be07b51f1e5245a29edc11fc9932c19e.
I don't know how to interpret this and I don't get the same error as on CRAN (don't get any ERROR? Just a WARNING not sure where).
I'm having a hard time interpreting these build results, and there is no artifact produced.

Can anyone help please?

**Comment by maelle** [comment]
@privefl sorry for not helping. I read [elsewhere](https://reside-ic.github.io/blog/debugging-and-fixing-crans-additional-checks-errors/) that you were able to solve the issue, can you explain how / close this? Thanks!

**Comment by privefl** [comment]
I was able to reproduce the issue using docker locally, as explained in the blog post you mention.

**Comment by maelle** [comment]
Cool! Can this issue be closed or is there anything we could add to the functions in https://r-hub.github.io/rhub/articles/local-debugging.html / their docs?

**Comment by privefl** [comment]
I was not trying to seek help for any possible way to reproduce this issue.

This was more: I tried with `rhub::check_with_sanitizers()`, I didn't get the same output as reported by CRAN, and I didn't know how to interpret the results of {rhub}.

**Comment by maelle** [comment]
Ok, could you tell us where in the docs you would have expected more/different information? Thanks.

**Comment by privefl** [comment]
It would be nice to get the artifacts produced so that it is clearer where the error comes from.
Thanks.

**Comment by gaborcsardi** [comment]
@privefl I believe that there is a link to the artifacts in the email you got.

**Comment by privefl** [comment]
There is always a link to it.
But most of the times it results in a 404 error.
E.g. https://artifacts.r-hub.io/bigsnpr_1.2.0.tar.gz-db3d8049514647b5948deef51d2fb55b.

**Comment by gaborcsardi** [comment]
Is that for an UBSAN build? That's a bug then.

**Comment by privefl** [comment]
Yes, but other builds as well, e.g. Solaris, Windows, CentOS.

**Comment by gaborcsardi** [comment]
That should only happen if there are no artifacts, because the build failed before it could actually start running the checks, or because the build was aborted.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
