### ISSUE TITLE
BiocManager fails to install for Debian Linux, R-devel, clang, ISO-8859-15 locale

### ISSUE THREAD

**Issue by damienchallet** [r-hub/rhub#332]
see lines 89-99 of

https://builder.r-hub.io/status/ghyp_1.5.8.tar.gz-387010ab3432dcf08dc336e1a7ca4009

**Comment by lorenzwalthert** [comment]
I get a similar problem with the GitHub version of `rhub` and the latest image `rhub/debian-clang-devel`.
```
Error: package or namespace load failed for 'BiocManager':
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: if (version[, 1:2] != version) return(sprintf("version '%s' must have two components, e.g., '3.7'", 
  error: argument is of length zero
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/docker/R/BiocManager'
```

 Here is the full [log.txt](https://github.com/r-hub/rhub/files/4177155/log.txt).

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
