### ISSUE TITLE
Bad error message in `list_my_checks`

### ISSUE THREAD

**Issue by dmurdoch** [r-hub/rhub#334]
I have run several checks on `rgl` recently, using the maintainer email `murdoch@stats.uwo.ca`.  If I run `list_my_checks()` without specifying that email address, `email` defaults to `murdoch.duncan@gmail.com`, which account has been verified according to `validate_email()`, but I get the error:

```
> list_my_checks()
Error in query("LIST BUILDS EMAIL", params = list(email = email, token = email_get_token(email))) : 
  Email address not validated
```

The message should probably say something like 

`No checks found for email murdoch.duncan@gmail.com`

instead.

**Comment by gaborcsardi** [comment]
Are you sure that `murdoch.duncan@gmail.com` has the right token? E.g. if you re-validated it on another machine, then it will not have the right token on this one, because one email address can only have one token currently.

**Comment by dmurdoch** [comment]
That's not the issue.  I'm only using one machine.  Just to be sure, I just re-validated it and got the same result.

**Comment by dmurdoch** [comment]
Just did some tracing.  The message `Email address not validated` is in raw characters in `response$content` received from the call to `GET()` in `query()` called from `list_my_checks()`:

```
Browse[3]> rawToChar(response$content)
[1] "{\"result\":\"error\",\"message\":\"Email address not validated\"}"
```

**Comment by gaborcsardi** [comment]
According to the server the @gmail.com email is pending validation. Does `validate_email()` finish successfully for you?

**Comment by dmurdoch** [comment]
I don't remember seeing a problem.  I will try again now:

```
> library(rhub)
> validate_email()

── Choose email address to (re)validate (or 0 to exit) 

1: ✓  murdoch@stats.uwo.ca
2: ✓  murdoch.duncan@gmail.com
3:    New email address

Selection: 2
Please check your emails for the R-hub access token.
Token: 1ce53...d7d7f3a8f
Token added for ‘murdoch.duncan@gmail.com’
```

Looks as though it worked (I edited out the middle of the token, that's not what I received).

**Comment by dmurdoch** [comment]
Not sure what I've done wrong, but I'm again getting the message

```
> list_my_checks()
Error in query("LIST BUILDS EMAIL", params = list(email = email, token = email_get_token(email))) : 
  Email address not validated
```

It's using the `murdoch.duncan@gmail.com` address, which has been validated (and re-validated a few minutes ago).

**Comment by gaborcsardi** [comment]
Run rhub::list_validated_emails() and make sure that the token is the one
you received in the _last_ email after you have run rhub::validate_email()

**Comment by dmurdoch** [comment]
Yes, same token in both cases.  I just removed my older email address (that I rarely use; it's not the one given by `whoami::email_address()` so it only lists one, and I get the most recent token but no luck with `list_my_checks()`.

**Comment by amirmasoudabdol** [comment]
I'm experiencing the same problem. I've used rhub while back, and now I'm getting all sort of strange errors. I've revalidated my email but I cannot get it to work for some reason. Although my email is freshly validated, I'll get this:

```
> rhub::list_my_checks()
Error in get_endpoint(endpoint, params) : 
  Cannot find token, email address is not validated?
```

And none of my builds go through. Any thoughts?

**Comment by gaborcsardi** [comment]
Investigating...

**Comment by gaborcsardi** [comment]
This is indeed a bug in `list_my_checks()`, if you validate a new address, `list_my_check()` does not work until you submit a checks. 

I have fixed your case now, please try again. 

As for the checks, they should go through eventually. If you see them in `list_my_checks()` then there is no need to resubmit them.

**Comment by amirmasoudabdol** [comment]
It seems some of my build went thought but I guess that's because of your intervention, right? Before that, they looked pretty much stuck!
