### ISSUE TITLE
Documentation for env_vars is inconsistent

### ISSUE THREAD

**Issue by elinw** [r-hub/rhub#336]
The env_vars parameter requires a character vector. This is not reflected in the documentation for the parameter. See PR  #335   I didn't look everywhere or regenerate the man files but if you agree I can do that if you want.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
