### ISSUE TITLE
Encoding and GET_PLATFORMS rhub error

### ISSUE THREAD

**Issue by ms609** [r-hub/rhub#340]
When I run `rhub::check()`, `check_on_debian`, `check_for_cran()` or related functions from within Rstudio on my package [`TreeSearch`](https://github.com/ms609/TreeSearch) I see

```
No encoding supplied: defaulting to UTF-8.
Error in query("GET PLATFORMS", as = "text") : rhub error
```

Platform: Windows 10. 
Version: rhub_1.1.1.9000.tar.gz (current GitHub release)
My package's description contains 
`Encoding: UTF-8`

If this is the same issue as #293, #297, #319, is it possible to provide a more informative error message?

**Comment by gaborcsardi** [comment]
This is not related to your package, the web app has crashed. It is up again now.
