### ISSUE TITLE
ERROR: Package suggested but not available

### ISSUE THREAD

**Issue by samuel-rosa** [r-hub/rhub#341]
I am getting the following error for package __pedometrics__ on the following test environments:

* Ubuntu Linux 16.04 LTS, R-release, GCC
* Fedora Linux, R-devel, clang, gfortran

```
* checking package dependencies ... ERROR
Package suggested but not available: ‘spsurvey’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
```

The log show that this is due to a missing dependency of package __spsurvey__:

```
6322#> ERROR: dependency ‘sf’ is not available for package ‘spsurvey’
6323#> * removing ‘/home/docker/R/spsurvey’
```

The logs are available at:

* https://builder.r-hub.io/status/pedometrics_0.6.6.9010.tar.gz-d7f9e259b42e48cca0f50f60389869de
* https://builder.r-hub.io/status/pedometrics_0.6.6.9010.tar.gz-ea8005c7929844dfa2e6cbedbec9f552

**Comment by gaborcsardi** [comment]
sf fails to install on these platforms.
