### ISSUE TITLE
Error in library

### ISSUE THREAD

**Issue by uczhn** [r-hub/rhub#345]
I have developed an R  package on windows  called mdas and all local RCMD checks were successful. Checks on CRAN server (Fedora Linux, R-devel, clang, gfortran) were also successful with no notes, warnings nor error messages. After submission, I received and email with a PREPERROR message as shown below:

**Error in library(mdas) : there is no package called ‘mdas’
Execution halted
Build step 'Execute shell' marked build as failure
Pinging https://builder.r-hub.io/build/FAILURE/mdas_0.0.1.tar.gz-17ca0f80a628481ba6a82a5d88762967/2020-02-11T16:45:52Z
{"status":"ok"}
Finished: FAILURE**

Can any one provide me with any suggestions on how to fix this issue please. 
I will be very greateful for any suugestions on how to go about this.
Thanks in anticipation

**Comment by gaborcsardi** [comment]
The mdas installation failed. Look at the log to see why.

**Comment by uczhn** [comment]
Thank you very much for your timely response. Let me check the log file once more. Cheers

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
