### ISSUE TITLE
specify R version for package build and check 

### ISSUE THREAD

**Issue by elong0527** [r-hub/rhub#347]
I might missed the option and misunderstood the purpose of rhub package. 

Is there a way to specify the R version using rhub to check/build an R package? 

I want to ensure my package can be run on previous R versions as discussed in tidyverse. 

https://www.tidyverse.org/blog/2019/04/r-version-support/

**Comment by gaborcsardi** [comment]
This blog post summarizes the purpose: https://blog.r-hub.io/2019/03/26/why-care/

`rhub::platforms()` lists all available platforms.

**Comment by elong0527** [comment]
Thanks for the post. I wish the feature to specify the R version can be added in a future release. 

It will be very useful for an organization to ensure the support of multiple R versions. 

For example, the code below only works in R > 3.5.0 per this link https://r.789695.n4.nabble.com/duplicated-factor-labels-td4738053.html

```
xf <- factor(x, levels = c("Male", "Man", "male", "Female"),
        labels = c("Male", "Male", "Male", "Female"))
```
