### ISSUE TITLE
Upcoming R 4.0

### ISSUE THREAD

**Issue by hongooi73** [r-hub/rhub#348]
I just got an email from CRAN saying that one of my packages is failing the checks on R-devel. Basically, R 4.0 will be switching the default `stringsAsFactors` arg to `data.frame/read.table` to `FALSE`. They suggest checking with "a very current r-devel (r77865 or later)" to pick up any issues.

Now this is a great change to `data.frame` and `read.table`, but it's a bit hard to check if you don't want to install R-devel locally. I just tried Rhub, and it looks like it's still using r77847. What would be involved in getting it to use the latest R-devel?

**Comment by gaborcsardi** [comment]
It is updated regularly.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
