### ISSUE TITLE
Add gcc9 platform?

### ISSUE THREAD

**Issue by zhanxw** [r-hub/rhub#349]
My package `seqminer` failed the check in recent CRAN pretest.
https://win-builder.r-project.org/incoming_pretest/seqminer_7.9_20200227_000648/Debian/00check.log

Since the test was performed using gcc9, can rhub add a platform with gcc9?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
