### ISSUE TITLE
PREPERROR: Debian Linux, R-devel, GCC ASAN/UBSAN

### ISSUE THREAD

**Issue by FranciscoPalomares** [r-hub/rhub#353]
![image](https://user-images.githubusercontent.com/39648210/76311786-fec17680-62d1-11ea-942f-4c174ecf8d9e.png)

Link text: https://builder.r-hub.io/status/original/SSLR_0.9.0.tar.gz-e6e47acee7934c658922ac70b28bc9d8

**Comment by gaborcsardi** [comment]
The compilation of the xgboost package failed, I am not sure what we can do about that.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
