### ISSUE TITLE
PREPERROR Windows Server 2008 R2 SP1, R-devel, 32/64 bit

### ISSUE THREAD

**Issue by samuel-rosa** [r-hub/rhub#355]
It seems that there are packages missing on Windows. Is there anything that I can do?

```
 177#> * checking package namespace information ... OK
 178#> Packages required but not available:
 179#> 'dplyr', 'glue', 'pedometrics', 'readr', 'sf', 'stringr'
 180#> Packages suggested but not available:
 181#> 'bookdown', 'DT', 'knitr', 'latticeExtra', 'magrittr', 'pander',
 182#> 'rgdal'
 183#> VignetteBuilder package required for checking but not installed: 'knitr'
 184#> * checking package dependencies ... ERROR
 185#> The suggested packages are required for a complete check.
```

Log: https://builder.r-hub.io/status/febr_1.0.3.9004.tar.gz-627c5082708b49a19d55040c5e760463

**Comment by ice4prince** [comment]
I have the same error about this; No error when I check on my local windows....


> 

Windows Server 2008 R2 SP1,   R-devel, 32/64 bit
Package required but not available: 'stringr'
Package suggested but not available: 'testthat'
: Failed to install 'remotes' from GitHub:
  JSON: EXPECTED value GOT "
Execution halted
Error in loadNamespace(name) : there is no package called 'remotes'

Log:[https://builder.r-hub.io/status/original/mixIndependR_0.2.1.tar.gz-555f4408703949b8a21f5715f93557aa](url)

**Comment by gaborcsardi** [comment]
Same as #356, it should be fixed now.
