### ISSUE TITLE
Error in Windows Server 2008 R2 SP1, R-devel, 32/64 bit

### ISSUE THREAD

**Issue by FranciscoPalomares** [r-hub/rhub#356]
The Description field should not start with the package name,
  'This package' or similar.
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Packages required but not available:
  'parsnip', 'plyr', 'dplyr', 'magrittr', 'stringr', 'Rcpp', 'tibble',
  'purrr', 'rlang', 'tidyr', 'proxy', 'generics', 'globals', 'RANN',
  'foreach', 'RSSL', 'RcppArmadillo'

Packages suggested but not available:
  'doParallel', 'tidyverse', 'xgboost', 'covr', 'kknn', 'randomForest',
  'caret', 'tidymodels', 'e1071', 'C50', 'kernlab', 'testthat',
  'ranger', 'knitr', 'rmarkdown'

VignetteBuilder package required for checking but not installed: 'knitr'

The suggested packages are required for a complete check.

Link: https://builder.r-hub.io/status/original/SSLR_0.9.0.tar.gz-aeed5b3dfa52476189a4e3ce4271aa7d

**Comment by gaborcsardi** [comment]
This should be fixed now.
