### ISSUE TITLE
Problems with packages unavailable; rhub (see #354).

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#358]
This is really issue #354 but that issue has been closed.  I tried adding a comment to #354 anyway (the documentation indicates that this is possible) but have got no response.

To summarise:  I submitted a package to rhub, via the check() function, in order to build a Windoze binary.  A previous version of this package built with no problems. However the new submission threw an error "Package required but not available: 'ggplot2'".

After some to-ing and fro-ing, Gábor Csárdi posted:  "I have updated the remotes version R-hub uses, please try again."  He then closed issue #354.  I tried again
(twice) and got the error:

Packages required but not available:
  'lme4', 'brms', 'glmmTMB', 'GLMMadaptive', 'Rcpp', 'rmutil',
  'ggplot2', 'ggforce', 'gdata'

So a whole *lot* of packages have become unavailable, not just ggplot2!!!

Is there anything that I can do? I have tried emailing Gábor Csárdi directly, but have received no response.  I hope he has not come down with Covid-19!!!

**Comment by gaborcsardi** [comment]
What's the id of your build?

I certainly did not receive any email from you, and would rather not joke about that.

**Comment by rolfTurner** [comment]
Sorry.  It's certainly no joke.  I was seriously apprehensive; probably unnecessarily apprehensive, but the way things are going ....

The email that I sent to you is in my "Sentmail" folder, so it *looks* like I really did sent it.

The build ID for my most recent attempt is:

Build ID: | ldEst_5.1-8.tar.gz-0b65a317ec3f44e7bb8ab23ae8ed6bb7

Thanks for looking into this.

**Comment by gaborcsardi** [comment]
OK, good news and bad news.

I started a rebuild for that job. You may or may not get another email about it. It still fails with the ggplot2 issue, so I guess it is still not fixed in remotes?

```
The downloaded binary packages are in
	C:\Users\USERWruRXwEVFU\AppData\Local\Temp\RtmpCOsjm0\downloaded_packages
installing the source packages 'ggplot2', 'lifecycle', 'shiny'

trying URL 'https://cran2.r-pkg.org/src/contrib/ggplot2_3.3.0.tar.gz'
Content type 'application/x-tar' length 3031461 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

trying URL 'https://cran2.r-pkg.org/src/contrib/lifecycle_0.2.0.tar.gz'
Content type 'application/x-tar' length 164455 bytes (160 KB)
downloaded 160 KB
==================================================

trying URL 'https://cran2.r-pkg.org/src/contrib/shiny_1.4.0.1.tar.gz'
Content type 'application/x-tar' length 3168008 bytes (3.0 MB)
==================================================
downloaded 3.0 MB

* installing *source* package 'ggplot2' ...
** package 'ggplot2' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'lifecycle'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'ggplot2'
* removing 'C:/Users/USERWruRXwEVFU/R/ggplot2'
```

The good news is that in the meanwhile the binary is available for lifecycle, so if you start a new build now, it should work.

**Comment by gaborcsardi** [comment]
Re private email, I think what happened is that you sent it to both my email address and the GH issue's email address, and I only get those once, from GH.

**Comment by rolfTurner** [comment]
I just tried a new build and it worked!!!  Yayyyyyy!

Thanks very much.  Harmony is restored to the universe, at least for the time being. :-)

**Comment by gaborcsardi** [comment]
Yeah, unfortunately the remotes bug will come back to bite us again, I am sure. R-hub is switching to pak soonish, that will solve these issues.
