### ISSUE TITLE
check error

### ISSUE THREAD

**Issue by qinwf** [r-hub/rhub#359]
<img width="546" alt="s" src="https://user-images.githubusercontent.com/7472151/76640421-dd3ee400-658a-11ea-8496-46a982f96237.png">

https://builder.r-hub.io/status/re2r_1.0.0.tar.gz-545bef1d718f49e7aae2f514b43b454c

**Comment by gaborcsardi** [comment]
There is a long queue, you can check on your package from R:
```r
❯ ch <- rhub::get_check("re2r_1.0.0.tar.gz-545bef1d718f49e7aae2f514b43b454c")
❯ ch

── re2r 1.0.0: CREATED

  Build ID:   re2r_1.0.0.tar.gz-545bef1d718f49e7aae2f514b43b454c
  Platform:   Debian Linux, R-release, GCC
  Submitted:  2h 40m 14.7s ago
```

**Comment by qinwf** [comment]
Ok. Got result for `06cb64081f4bdb8c2ff186e24817560c`: PREPERROR

It is not a good experience to wait 6 hours to get PREPERROR and to know the build system is not working. 

If the check system itself is not working, it is really hard to tell whether the result from the check is reliable.
