### ISSUE TITLE
PREPERROR: Fedora Linux, R-Devel, Clang and GCC

### ISSUE THREAD

**Issue by sharlagelfand** [r-hub/rhub#361]
Both Clang and GCC Fedora Linux with R-Devel are failing to install `sf` (seems similar to #357, maybe?)

```
#> checking proj_api.h usability... no
#> checking proj_api.h presence... no
#> checking for proj_api.h... no
#> configure: error: proj_api.h not found in standard or given locations.
#> ERROR: configuration failed for package ‘sf’
```

Fedora Linux, R-devel, GCC log: https://builder.r-hub.io/status/opendatatoronto_0.1.2.9000.tar.gz-5adcddee631145b4b95cb3446a5ef110
Fedora Linux, R-devel, Clang log: https://builder.r-hub.io/status/opendatatoronto_0.1.2.9000.tar.gz-d5b09346a8a0459f8166fa04a2a3e5fc

**Comment by marcusyoung** [comment]
I have exactly the same issue.

**Comment by gaborcsardi** [comment]
Well, it is not possible to install sf on our Fedora container. So this result is  expected. Your users will see the same if they try to install the package on this  version of Fedora.

However, we should really update our Fedora version.

**Comment by marcusyoung** [comment]
Right, I understand, but makes rhub unusable for testing our packages. Which is a shame.

**Comment by gaborcsardi** [comment]
@marcusyoung Actually, we do have a recent Fedora, Fedora 31, and sf installs on it fine, so you'd need to show us in your log why it failed to install.

**Comment by marcusyoung** [comment]
Attached.
[otpr_0.4.1.tar.gz-98e1a148a5ba4114b891c60d3bc04c00.txt](https://github.com/r-hub/rhub/files/4697715/otpr_0.4.1.tar.gz-98e1a148a5ba4114b891c60d3bc04c00.txt)

**Comment by dpprdan** [comment]
I have the same issue on Fedora 33
[opencage_0.2.0.tar.gz-9ba591a1ebed441f98d7fa95f1c71607.txt](https://github.com/r-hub/rhub/files/5973156/opencage_0.2.0.tar.gz-9ba591a1ebed441f98d7fa95f1c71607.txt)

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
