### ISSUE TITLE
Operation failed with error: eServerError (elcapitan macos)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [r-hub/rhub#363]
Something is wrong with the server:

https://builder.r-hub.io/status/irace_3.4.tar.gz-349ee5a42d574695a9c012185d577124

**Comment by gaborcsardi** [comment]
CRAN macOS binaries are broken...

**Comment by gaborcsardi** [comment]
Actually, this is something else.

**Comment by gaborcsardi** [comment]
Seems to be good now, please try again. Thanks!

**Comment by MLopez-Ibanez** [comment]
It works. Thanks.

**Comment by MLopez-Ibanez** [comment]
It is broken again: https://builder.r-hub.io/status/original/irace_3.4.tar.gz-32c7824315524c52bb3df15e859569f8

**Comment by gaborcsardi** [comment]
Thanks, I restarted that worker again, and it works now, I'll investigate why this happens.

**Comment by MLopez-Ibanez** [comment]
I'm now getting a different error: https://builder.r-hub.io/status/original/eaf_2.0.tar.gz-549eda0b550b4451b0f338c41d32281a

**Comment by gaborcsardi** [comment]
Try again please. This is a hardware failure and we'll replace the disk in our server this week.
