### ISSUE TITLE
solaris missing from platforms() 

### ISSUE THREAD

**Issue by mcdonohue** [r-hub/rhub#365]
`check_on_solaris()` is not working for me with error:

```
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
```

And solaris doesn't show up on `rhub::platforms()`

**Comment by gaborcsardi** [comment]
https://twitter.com/rhub_/status/1245491942231851013

**Comment by mcdonohue** [comment]
Thank you, Gábor. I didn't think to check Twitter first.
