### ISSUE TITLE
Windows Server 2008 R2 SP1, R-devel, 32/64 bit: 'data.table' not available

### ISSUE THREAD

**Issue by DyfanJones** [r-hub/rhub#370]
Hi all,

I am getting an unusual error message when trying to check my package on rhub windows server:

> checking package dependencies ... ERROR
Package required but not available: 'data.table'

The logs are [here](https://builder.r-hub.io/status/RAthena_1.9.0.tar.gz-842a493f60674fafa4781b10d15d5399) for more information.

If this has already been raised my apologises but I couldn't find a similar issue.

If you need any more information please let me know.

**Comment by gaborcsardi** [comment]
Look at the log to see why R-hub failed to compile `data.table`.

Maybe this workaround works:
https://github.com/r-hub/rhub/issues/367#issuecomment-621757715

**Comment by DyfanJones** [comment]
Thanks for replying back so quickly i will give it a run now.

**Comment by DyfanJones** [comment]
Perfect this has worked for windows server 👍
