### ISSUE TITLE
PREPERROR: Linux: Build timed out (after 10 minutes)

### ISSUE THREAD

**Issue by DyfanJones** [r-hub/rhub#371]
Hi all,

I am having an issue were the Ubuntu and Fedora linux builds are timing out. 

> Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted

Fedora Linux, R-devel, clang, gfortran logs [here](https://builder.r-hub.io/status/RAthena_1.9.0.tar.gz-a5aa00f9c14d4c9ebdacb8707f1c89ab)

Ubuntu Linux 16.04 LTS, R-release, GCC logs [here](https://builder.r-hub.io/status/RAthena_1.9.0.tar.gz-0c3e29373f8e40fdb172292b3cb69024)

I am unsure how to resolve this, any help with this would be amazing.

**Comment by gaborcsardi** [comment]
```
2252#> * installing *source* package ‘arrow’ ...
2253#> ** package ‘arrow’ successfully unpacked and MD5 sums checked
2254#> ** using staged installation
2255#> *** Successfully retrieved C++ source
2256#> *** Building C++ libraries
2257#> **** cmake
2258#> **** arrow
2259#> Build timed out (after 10 minutes). Marking the build as failed.
```

@nealrichardson do you think is it possible that arrow takes more than ten minutes to build?

**Comment by DyfanJones** [comment]
Possibly, I believe the arrow package attempts to build `Apache Arrow` for R to call with `install.package` however I am not 100% sure. I will raise a ticket on their github to confirm this.

**Comment by gaborcsardi** [comment]
No need to raise a ticket, that's the normal behavior. I am just wondering if it can take more than 10 minutes without any output.

**Comment by DyfanJones** [comment]
@gaborcsardi I believe it does yes. My travis build takes roughly 20 min to build and run all of the unit test (unit test connect to AWS rest api). From memory the unit test roughly take 5 minutes to run. If you need precise time measurement please let me know.

**Comment by nealrichardson** [comment]
Yes, `arrow` does take over 10 minutes to build from source on Linux: https://cran.r-project.org/web/checks/check_results_arrow.html

If you can set environment variables, `LIBARROW_BINARY=true` will greatly speed things up. Alternatively, with `ARROW_R_DEV=true`, it will still be slow building from source, but it will print more output, in case that's preferable.

**Comment by gaborcsardi** [comment]
Thanks! I already increased the time limit to 20 minutes on Linux, hopefully that's enough. 

@DyfanJones You might still want to try `LIBARROW_BINARY=true` to speed things up, use the `env_vars` argument of `rhub::check()`.

**Comment by DyfanJones** [comment]
Thanks everyone, i will run it again and let you know if your changes have  fixed the issue. If not i will test it again the environmental variables to increase the build time

**Comment by DyfanJones** [comment]
@gaborcsardi it look like it timed out again [log](https://builder.r-hub.io/status/RAthena_1.9.0.tar.gz-f17444f3e8354529a2e5d00c459eb05f). I will try setting the environment variables suggested by @nealrichardson

**Comment by DyfanJones** [comment]
With the environmental variable `LIBARROW_BINARY=true` test ran successfully. Thanks you both for your help. I will close this ticket now.

**Comment by gaborcsardi** [comment]
@nealrichardson would it make sense to set `LIBARROW_BINARY=true` on R-hub in general? I guess this makes sense for packages depending on arrow. And if you want to test building arrow from source, you can always override with an explicit `env_vars = c(LIBARROW_BINARY = "FALSE")`.

**Comment by nealrichardson** [comment]
Yeah @gaborcsardi I think it would be a good idea. We have pretty thorough CI using r-hub images to ensure that the binaries will work there, and when installing `arrow` as a dependency of another package, there's no value in testing that `arrow` builds from source.
