### ISSUE TITLE
Difference between macos-highsierra-release and idem-cran

### ISSUE THREAD

**Issue by fcorra** [r-hub/rhub#372]
Hi,
_I’ve posted this problem on the r-package-devel mailing list at the start of the week (macOS flat namespace)._

I submitted a package to CRAN that I developed in Debian 10, GCC 8, R 3.5. The package needs compilation and links to gdal and proj. It was accepted, and passed all CRAN checks but not those for macOS and OS X flavours ([package](https://CRAN.R-project.org/package=uFTIR); [check results](https://cran.r-project.org/web//checks/check_results_uFTIR.html)).

The problem for the r-release-osx-x86_64 platform (macOS 10.13.6, Apple LLVM version 10.0.0 (clang-1000.10.44.4); GNU Fortran (GCC) 8.2.0) looks like:

    ** testing if installed package can be loaded from temporary location
    Error: package or namespace load failed for ‘uFTIR’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '.../libs/uFTIR.so':
     dlopen(.../libs/uFTIR.so, 6): Symbol not found: _jpeg_resync_to_restart
     Referenced from: .../libs/uFTIR.so
     Expected in: flat namespace
     in .../libs/uFTIR.so
    Error: loading failed

CRAN checks have similar results for the r-oldrel-osx-x86_64 platform (Xcode 8.2.1, clang 4.0.0, GNU Fortran 6.1). However, the not-found symbol is _H5P_CLS_DATASET_CREATE_ID_g

I don’t use any of the objects directly (one comes from libjpeg and the other from HDF5) but they are related with gdal.

I used rhub to reproduce the problem and I got the same output (symbol not found: _jpeg_resync_to_restart) when I send the package to the macos-highsierra-release-cran platform. However, the problem vanishes when I use the macos-highsierra-release (brew) platform. I think that it is a problem with the linked libraries, and I will probably need to adjust the Makevars file(?). However, I’m not quite sure whether this is the problem or not and if it is how to solve it. I couldn't find the difference between the two rhub platforms, thus I though that you could give me an idea… 

The Makevars that works for homebrew but not for the CRAN settings is:

    CXX_STD = CXX11
    PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS) `pkg-config --cflags gdal`
    PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) `pkg-config --libs gdal`

I will appreciate your help.

F.

**Comment by gaborcsardi** [comment]
Hi, it seems that it works properly if you explicitly link to the libraries that the gdal library links to. I.e. if I change your `PKG_LIBS` line to this: 
```
PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) `pkg-conf\
ig --libs gdal` -ljpeg -lpcre -lpng -lproj
```
that works, on R-hub at least.

It seems that the CRAN `/usr/local/lib/libgdal.a` does not include all of its dependencies. 

FWIW the rgdal package ends up with these libraries after its `configure` script: ```
PKG_LIBS= -L/usr/local/lib -lgdal -L/usr/local/lib -lproj -lsqlite3 -lexpat -ljpeg -lpng -llzma -lz -lpthread -ldl -lpcre -lcurl -liconv -L/usr/local/lib -lxml2 -lz -L/usr/local/lib -llzma -lpthread -liconv -lm -L/usr/local/lib -lproj
```

The configure script is here: https://github.com/cran/rgdal/blob/master/configure.ac

**Comment by gaborcsardi** [comment]
It seems that the key is to include the libs from `gdal-config`:

```
rhubs-Mac:err rhub$ gdal-config --libs
-L/usr/local/lib -lgdal
rhubs-Mac:err rhub$ gdal-config --dep-libs
-L/usr/local/lib -lproj -lsqlite3 -lexpat -ljpeg -lpng -llzma -lz -lpthread -ldl -lpcre -lcurl -liconv -L/usr/local/lib -lxml2 -lz -L/usr/local/lib -llzma -lpthread -liconv -lm
```

I don't know if `gdal-config` will be available on all platforms, though.

**Comment by fcorra** [comment]
Hi,
Thank you so very much! I copied rgdal configure.ac, modified the AC_CONFIG_SRCDIR to target my exports and run autoconfig. The package installs successfully in both platforms macos-highsierra-release and macos-highsierra-cran.
I will start from here removing from configure.ac all the libs that I don't use.

Thank you once again.
