### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#373]
Which platforms have cmake installed?  

I see it being used in CRAN packages (all the way back to qbase) so I assumed it to be present, alas 

> #> cannot find cmake

Could it be installed on all platforms, or maybe all Linux platforms?

**Comment by eddelbuettel** [comment]
Adding it to SystemRequirements helped.  (It's optional use for me, but seemingly required on rhub.)

I guess we can close this because the behavior is pretty much what is mandated by WRE ("if you may need it, stick it in SystemRequirements").  I got side-tracked by others using it without declaring it.  Magic.

**Comment by eddelbuettel** [comment]
On macos (with `platform="macos-highsierra-release-cran"`) I get 

> #> cannot find cmake

even with `cmake` in `SystemRequirements:`.

**Comment by gaborcsardi** [comment]
That builder mirrors CRAN's macOS, and CRAN's macOS does not have cmake, either. E.g: https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/symengine-00install.html

**Comment by eddelbuettel** [comment]
Ok, I place that somewhere between _fair_ and _how frustrating_.  So ... what does one do on macOS?

**Comment by gaborcsardi** [comment]
The point of this builder is to get a sense whether your package will work
on CRAN's macOS machine.

The other macOS builder uses brew, which is a setup that most users would
use. (We think.)

You can probably convince CRAN to install cmake on their machine, and then
of course we'll install it as well.

**Comment by eddelbuettel** [comment]
Sure.  After all these years I am aware of all the hyopotheticals of what CRAN _might_ do _under certain circumstances_ if one asks _very kindly_ etc pp.  I found my luck varies by platform too.  We'll see. 

But my question was more pragmatic as the non-macOS user that I am:  what do others do to survive without `cmake` on the platform?   From `grep()` ing `SystemRequirements:` in what `CRAN_package_db()` returns, five packages declare `cmake`.  At least one other I know uses it but does not declare it.   In short, do you (as a source of knowledge) do what 'best practise' is over there?

**Comment by gaborcsardi** [comment]
I don't know. Some of them just fail to build, like the one I linked.

**Comment by gaborcsardi** [comment]
_Users_ will be probably able to install these packages, though, assuming they have the compilers set up. They just need `brew install cmake` and they are ready to go. Having the macOS binaries for them would be nice of course.

**Comment by gaborcsardi** [comment]
@s-u Simon, do you think that the CRAN macOS machine could have cmake installed? Or is this something that you intentionally left out for some reason? 

FWIW it seems that the Linux machines have it, and although win-builder does not mention it explicitly, it also seems to have it.

Thanks!

**Comment by s-u** [comment]
@gaborcsardi Gabor, the build machine has it - the location for cmake on macOS is `/Applications/CMake.app` since the official distribution of `cmake` is an application. It has the GUI as well as the command line tool, the latter being presumably what you need is called as `/Applications/CMake.app/Contents/bin/cmake` (see cmake docs). That said, `cmake` is notoriously used wrongly in packages since you have to force it to use the flags from R which `cmake` does very reluctantly, so only recommended for expert users.

**Comment by gaborcsardi** [comment]
Oh, great, thanks!

**Comment by eddelbuettel** [comment]
Can you alias it? Maybe `alias cmake=/Applications/CMake.app/Contents/bin/cmake` ?

**Comment by gaborcsardi** [comment]
OK, for the record I installed it at the same place. Which is the default, anyway.

**Comment by eddelbuettel** [comment]
I think we can close this.  Thanks all!
