### ISSUE TITLE
PREPERROR: Windows Server 2008: Agent went offline during the build

### ISSUE THREAD

**Issue by DyfanJones** [r-hub/rhub#375]
Hi all,

I am coming across an unusual error where "Agent went offline during the build" and causing "ERROR: Node is being removed"

```
#> Agent went offline during the build
1543#> ERROR: Node is being removed
1544#> Build step 'Windows PowerShell' marked build as failure
1545#> Pinging https://builder.r-hub.io/build/FAILURE/noctua_1.7.0.tar.gz-6a905a3cda2c43cb8b04dba4ac996e1f/2020-05-14T12:37:41Z
1546#> {"status":"ok"}
1547#> Finished: FAILURE
``` 

Here is the full [log](https://builder.r-hub.io/status/noctua_1.7.0.tar.gz-6a905a3cda2c43cb8b04dba4ac996e1f)

**Comment by gaborcsardi** [comment]
Interesting. First time I have seen this. The builder is definitely online. Can you please try again? Thanks.

**Comment by DyfanJones** [comment]
Thanks, I will give it another run now

**Comment by DyfanJones** [comment]
I have done a rerun and the build was successful. Not a 100% sure what caused the issue before however i am happy to close the issue down.

**Comment by gaborcsardi** [comment]
MOst likely an intermittent network error.
