### ISSUE TITLE
Unable to load Rcpp.dll when rebuilding vignette on Windows

### ISSUE THREAD

**Issue by Hong-Revo** [r-hub/rhub#384]
I just got some errors with `check_for_cran()` on the Windows part:

```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
--- re-building 'generics.Rmd' using rmarkdown
unable to load shared object 'C:/Users/USEROeZpFrjuAf/AppData/Local/Temp/RtmpqSF9yx/RLIBS_17ac554b4dcb/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.
Error: processing vignette 'generics.Rmd' failed with diagnostics:
```

https://builder.r-hub.io/status/AzureStor_3.2.1.tar.gz-04c34776e7a1422ab7ee6e5c79408343

My package doesn't use Rcpp, it looks like it's triggered when loading rmarkdown or one of its dependencies. The checks on Ubuntu and Fedora run without problems.

**Comment by gaborcsardi** [comment]
```
> library(Rcpp)
Error: package or namespace load failed for 'Rcpp' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/csard/R/win-library/4.1/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```
This build of Rcpp is not compatible with this build of R-devel. Let me try a newer R-devel build.

**Comment by gaborcsardi** [comment]
Yeah, it works with a news R-devel build, let me update on R-hub as well.

**Comment by gaborcsardi** [comment]
OK, should be good now.

**Comment by Hong-Revo** [comment]
This is weird, I'd have thought that Rcpp's own checks would have uncovered any incompatibilities with R versions.

**Comment by gaborcsardi** [comment]
I don't think this was an "official" ABI change. Probably something accidental in R.
