### ISSUE TITLE
Error on 'sf' install (similar to #357 and #361)

### ISSUE THREAD

**Issue by ianjonsen** [r-hub/rhub#386]
Hi, 

I am my R package depends on sf (ideally v 0.9-3) but I am getting consistent PREPERROR's across a number of platforms (`Debian-gcc-devel`,` ubuntu-gcc-release`, `ubuntu-gcc-devel`, `fedora-clang-devel`). This seems to be due to PROJ library headers not being found in the expected location:
```
#> checking proj.h usability... no
3968#> checking proj.h presence... no
3969#> checking for proj.h... no
3970#> checking proj_api.h usability... no
3971#> checking proj_api.h presence... no
3972#> checking for proj_api.h... no
3973#> configure: error: proj_api.h not found in standard or given locations.
3974#> ERROR: configuration failed for package ‘sf’
```

This issue appears to be the same as reported in #357 and #361, though for different platforms. 
Full build log is [here](https://builder.r-hub.io/status/foieGras_0.6-06.tar.gz-170dd8f184064d24932711688173f296) 

I have had build success on `Debian-clang-devel`, so the issue is not consistent across all platforms. Is there any way to specify required libraries such as GDAL, PROJ, GEOS in the rhub::check() call?

Thanks, Ian

**Comment by gaborcsardi** [comment]
Hopefully this has been fixed since.
