### ISSUE TITLE
Having a lot of difficulties with rhub

### ISSUE THREAD

**Issue by vnijs** [r-hub/rhub#389]
I LOVE what you are doing with rhub but unfortunately my success rate with getting stuff built has been pretty low. As an example, radiant.data (link below) has been on CRAN for years and I can't recall a time when it got through more than 1 or 2 of the checks on rhub to pass. I realize this package has a lot of dependencies but it might be a good use case for challenging packages to build and test :)

https://github.com/radiant-rstats/radiant.data

**Comment by gaborcsardi** [comment]
Can you please be more specific? I checked the last check for radiant.data and that seems to have been ok on Ubuntu Linux.

**Comment by vnijs** [comment]
Thanks for the reply @gaborcsardi. I got 5-6 emails with big red "error" at the top although some seemed to still succeed when I look at the html link now. If the logs are not sufficient, I'll post more information next time I use rhub. Thanks again for providing this service!
