### ISSUE TITLE
Exploratory Graph Analysis Package EGA

### ISSUE THREAD

**Issue by MariaPanteliPsychology** [r-hub/rhub#392]
Hello, 

I am trying to use the EGAnet package to run some network analysis. However, I have the following errors could not find function "itemIdent" do you know how to solve them?

Thank you, 
Maria

**Comment by gaborcsardi** [comment]
Which errors?

**Comment by MariaPanteliPsychology** [comment]
could not find function "itemIdent"

**Comment by gaborcsardi** [comment]
This is the repository of the rhub R package (https://r-hub.github.io/rhub/) and the R-hub service (https://docs.r-hub.io/). Are you using R-hub? If yes, and you get an error, then please link to the R-hub build log. (The link is in the email you got.)

If not, then try asking for help at https://community.rstudio.com, and include your code and the error message in the post.

**Comment by maelle** [comment]
The package you are referring to is developed on GitHub too https://github.com/hfgolino/EGAnet/issues and it seems the function you are referring to was merged with another one into a new function cf the package changelog https://github.com/hfgolino/EGAnet/blob/043801bf45a8cb3430f013848d664c0399814d34/NEWS#L139

**Comment by MariaPanteliPsychology** [comment]
Dear Maelle thank you very much for the info. I have found this document for item stability. https://www.rdocumentation.org/packages/EGAnet/versions/0.9.0/topics/itemStability 


I am using the codes, however I have this error. Do you have any idea on how to fix it?

Thank you, 

Maria
![image](https://user-images.githubusercontent.com/67906322/86600196-6948a180-bfa8-11ea-9e45-14f2ceecfec3.png)

![image](https://user-images.githubusercontent.com/67906322/86600191-65b51a80-bfa8-11ea-8853-f29339776ef9.png)

**Comment by maelle** [comment]
No sorry, this repository is for help about R-hub, not general R questions, so please use 

* https://community.rstudio.com/ as recommended by @gaborcsardi 
* the issue tracker of the package you are using

See also https://sctyner.me/post/2019-2-17-rhelp/
