### ISSUE TITLE
Feature request: integrating with Travis-CI

### ISSUE THREAD

**Issue by evanbiederstedt** [r-hub/rhub#394]
Hi there

Thanks for the great tool!

I've been testing an R package with C++ bindings, and it's useful for CRAN submissions to understand how the package builds on the 32-bit Oracle Solaris platform (especially as this is proprietary software). 

I would like to know how easy it would be to integrate this with Travis-CI builds, and if this isn't possible, to make a feature request. (I'm happy to help out.)

My naïve idea would be that users could do the following with a verified email account:

```
after_success:
  - git config --global user.name "FIRST LAST"
  - git config --global user.email NAME@gmail.com
  - git config --global --list
   - Rscript - e 'rhub::check_on_solaris("NAME@gmail.com")'
```

Thankfully, this doesn't work. 

How could one set this up with Travis?

**Comment by maelle** [comment]
https://jozef.io/r107-multiplatform-gitlabci-rhub/ might provide some inspiration (not on Travis though).

**Comment by evanbiederstedt** [comment]
This is very help @maelle, thank you!

**Comment by gaborcsardi** [comment]
Travis is gone, and the next gen of Docker images will be easier to use on GHA.
