### ISSUE TITLE
data.table package not available ?

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [r-hub/rhub#395]
I am checking a package for submission to CRAN, but keep getting the error that the data.table package is not available. Seems to be available on CRAN for R 4.0+, so not sure what the problem is?

Thanks

Here is the message:

Build ID:SightabilityModel_1.4.tar.gz-97870bd7e22249b192bb61f44d003676Platform:Windows Server 2008 R2 SP1, R-devel, 32/64 bitSubmitted:3 minutes 27.4 seconds agoBuild time:3 minutes 12.2 seconds | Build ID: | SightabilityModel_1.4.tar.gz-97870bd7e22249b192bb61f44d003676 | Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit | Submitted: | 3 minutes 27.4 seconds ago | Build time: | 3 minutes 12.2 seconds
-- | -- | -- | -- | -- | -- | -- | -- | --
Build ID: | SightabilityModel_1.4.tar.gz-97870bd7e22249b192bb61f44d003676
Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit
Submitted: | 3 minutes 27.4 seconds ago
Build time: | 3 minutes 12.2 seconds
ERRORS:* checking package dependencies ... ERROR Package suggested but not available: 'data.table'  The suggested packages are required for a complete check. variable _R_CHECK_FORCE_SUGGESTS_ to a false value. Checking can be attempted without them by setting the environment  See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual.

**Comment by gaborcsardi** [comment]
This is because data.table is not available as a binary package for R-devel, on CRAN. You can tell R to build it from source like this:

rhub::check(
  platform="windows-x86_64-devel",
  env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
)

E.g. https://github.com/r-hub/rhub/issues/367#issuecomment-621757715

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks... Carl
