### ISSUE TITLE
Pass flags to R CMD check

### ISSUE THREAD

**Issue by hadley** [r-hub/rhub#4]
e.g. `--use-valgrind`

**Comment by izmirlig** [comment]
How about -fno-common

**Comment by ekalosak** [comment]
I'm also curious about how to pass e.g. `-fno-common` to `R CMD check`, as it's a required flag for gcc10 compliance.

**Comment by gaborcsardi** [comment]
@ekalosak That's not a flag for `R CMD check`. If is a compiler flag, so you can (temporarily) put it in your package's `Makevars` file.

**Comment by ekalosak** [comment]
@gaborcsardi thank you for your quick response.
For others who are interested, the following adds `-fno-common` to the CFLAGS in a temporary Makevars - useful for running checks on code with native routine bindings. 
```
withr::with_makevars(
  c(
    "CFLAGS"="-Wall -pedantic -fdiagnostics-color=always -fno-common"
  ),
  devtools::check()
)
```
