### ISSUE TITLE
Email reports: Add HTML and / or text results as attachments

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#40]
Currently, the emailed package reports contains:

> R.utils 2.4.0: OK
> Build ID: R.utils_2.4.0.tar.gz-689a6bbb5b5eeeeffeaf398f04521dd9
> Platform: Debian Linux, R-devel, GCC
> Submitted:    3 minutes 57.1 seconds ago
> Build time:   2 minutes 12.2 seconds
> See the full build log: HTML, text.
> 
> Thank You for using the R-hub builder.

I think it would be useful if the actual text log / output would be attached to the email as well.  The reason why this could be useful is that you'll be able to search old messages for old results and exact sessionInfo() etc, e.g. did I have that error in the past and if so on what version of the package and R?  To keep the message clean, this could be done as an email attachment.

**Comment by jeroenooms** [comment]
Hmm I don't think this is a good idea. I rather not have my inbox flooded with hundreds (thousands) of build logs...

**Comment by jeroenooms** [comment]
Perhaps you can make it opt-in somehow though.

**Comment by gaborcsardi** [comment]
I agree with Jeroen. 

Once we have a proper CI, with users, instead of throwing away everything, we can store the logs "forever" in a database, that we can potentially make searchable. 

The emailed logs and then searching the emails is a rather inefficient makeshift solution imo.

**Comment by HenrikBengtsson** [comment]
@jeroenooms, just to be clear: I'm talking about add attachments to the messages already sent by r-hub.  I'm not talking about additional email messages.

I'm using Gmail as my client, so for me there would be very little difference in visual space occupied if those logs were to be attachments.  Also, Gmail is pretty awesome when it comes to search, i.e. search attachments quite well.  However, I am aware of other clients that parses and displays certain types of attachment at the end of the message.  For those users, adding attachments my clutter things up.  Size-wise (as in kB) it should make no difference.

A "forever" log sounds like a nice feature with lots of potentials.

PS. Damn, rhub is super sweet :)

**Comment by gaborcsardi** [comment]
@HenrikBengtsson The log output is potentially several hundreds of kilobytes, so we don't want to send that out, in attachments or otherwise. 

> Size-wise (as in kB) it should make no difference.

I am not sure what you are suggesting then. Would you like to get 
1. the same stuff as right now, but in an attachment?
2. the same stuff, plus R CMD check output in attachment?
3. the same stuff, plus the full build log in an attachment?
4. Sg. else?

**Comment by HenrikBengtsson** [comment]
First, this is not super important for me, so please keep this FR low priority.  I also posted it in case others come here and have the same wish.  In the past there has been cases where I wish the email reports from win-builder had at least the R CMD check output attached so I could go back an compare when surprising notes/warns/errors all of a sudden show up.

I was thinking about the same full text logs (e.g. https://builder.r-hub.io/status/original/R.utils_2.4.0-9000.tar.gz-4a90c76dae3649aa8a66c2afeb823833), but if those are too big just the R CMD check output would be useful. That would allow you to at least do a bit of local search and they also carry information about the R version that was run (which is missing from the current messages).

(feel free to close this issue)

**Comment by gaborcsardi** [comment]
This is useful feedback, don't worry. :)

> I was thinking about the same full text logs

Yes, that is too big I am afraid. With binary dependencies it will be MUCH shorter, but still. Maybe R CMD check output as an attachment is OK. 

But again, hopefully this will be fixed by 
1. giving access to build artifacts, e.g. install.out, and 
2. keeping the logs in a DB, like on a CI.

**Comment by gaborcsardi** [comment]
Btw. I'll also add a proper "Build system information" section to the logs.

**Comment by HenrikBengtsson** [comment]
Those plans / features sounds great.

In case someone sees this issue, it's worth mentioning that the email reports you get when there is a NOTE, a WARNING or an ERROR do indeed contain information about what those are.  Here's what the email for a WARNING + NOTE will look like:

![rhub_warning](https://cloud.githubusercontent.com/assets/1616850/19787685/f95b997a-9c58-11e6-879e-5021fff5cac8.png)

This is definitely helpful and it'll allow you to search your emails for similar errors in the past.  My original post was based on my experience only having tested packages with all OK, so I didn't know about this feature - duh.

**Comment by HenrikBengtsson** [comment]
I just ran into a real-world example where it would be convenient to have also the following information in the emails:
```
R Under development (unstable) (2016-10-21 r71553)
```
and maybe also `Platform: x86_64-pc-linux-gnu (64-bit)`.

I submitted a package to CRAN which "bounced" due to a `http://www.r-project.org/...` URL in `inst/CITATION`.  The above R-devel version didn't check for this.  This was using:
```r
rhub::check_for_cran()
```
which uses `platform = "fedora-clang-devel"` for R-devel.  Running:
```r
rhub::check(platform = "debian-gcc-devel", check_args = "--as-cran")
```
the HTTP mistake caught because it runs:
```
R Under development (unstable) (2016-10-26 r71594)
```

Knowing the exact R-devel / R-patched version running is useful for the user and a bit tedious to find if you need to scan through the logs.  (I know, a 1st world problem).

**Comment by gaborcsardi** [comment]
@HenrikBengtsson Indeed, the exact R version should be kept. No question about that.

Ideally, the build images will change less often once they stabilize. I'll change them once a week or some other similar schedule....

**Comment by gaborcsardi** [comment]
I'll open a new issue for this: #111
