### ISSUE TITLE
Check for invalid file URI

### ISSUE THREAD

**Issue by llrs** [r-hub/rhub#401]
Hi, I submitted a package and got a message/note that was not caught by rhub:

Found the following (possibly) invalid file URI:
     URI: CODE_OF_CONDUCT.md
       From: README.md

Perhaps this check could be added when running `rhub::check_for_cran()`?

**Comment by gaborcsardi** [comment]
Yeah, need to set `_R_CHECK_CRAN_INCOMING_CHECK_FILE_URIS_` to `TRUE` it seems, https://github.com/wch/r-source/blob/9d1f32c02783585c62ee403f5197b16809a74366/src/library/tools/R/QC.R#L7540

Unfortunately what cran does is AFAICT undocumented, e.g. this is not documented here: https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools

Do you want to submit a PR?

**Comment by llrs** [comment]
I'll darft a PR. However I think it would be better if this is make more transparent on the R/CRAN level (not sure where to raise the issue).
