### ISSUE TITLE
Rcpp on macOS fails

### ISSUE THREAD

**Issue by mattocci27** [r-hub/rhub#402]
I see Rcpp on Solaris works [#185](https://github.com/r-hub/rhub/issues/185), but does not seem to work on  macOS. I tested several packages and got the same errors. Those packages pass other platforms in R-hub and cran macOS check (r-release-macos-x86_64). 

- [https://builder.r-hub.io/status/ranger_0.12.1.tar.gz-05e9a2289903ed5fc49d58286b9e71f5](https://builder.r-hub.io/status/ranger_0.12.1.tar.gz-05e9a2289903ed5fc49d58286b9e71f5)

- [https://builder.r-hub.io/status/ztpln_0.1.1.tar.gz-7867b493289236c8c6b0699e8e655b12](https://builder.r-hub.io/status/ztpln_0.1.1.tar.gz-7867b493289236c8c6b0699e8e655b12)

- [https://builder.r-hub.io/status/mvabund_4.1.3.tar.gz-565d44a9072a9064216ba4245b0cb929](https://builder.r-hub.io/status/mvabund_4.1.3.tar.gz-565d44a9072a9064216ba4245b0cb929)

 ```

 #> Error in dyn.load(file, DLLpath = DLLpath, ...) :

 #> unable to load shared object '/Users/userIIucpL3D/R/Rcpp/libs/Rcpp.so':

 #> dlopen(/Users/userIIucpL3D/R/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR

 #> Referenced from: /Users/userIIucpL3D/R/Rcpp/libs/Rcpp.so

 #> Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib

 #> in /Users/userIIucpL3D/R/Rcpp/libs/Rcpp.so

 #> Calls: ... asNamespace -> loadNamespace -> library.dynam -> dyn.load

 #> Execution halted

 #> ERROR: lazy loading failed for package ‘ranger’

 ```

**Comment by gaborcsardi** [comment]
Fixed by updating to R 4.0.2. 

This is an Rcpp bug, CRAN Rcpp binaries built with R 4.0.2 are not compatible with R 4.0.0 that we had on the macOS machines. (https://www.mail-archive.com/r-devel@r-project.org/msg42398.html)
