### ISSUE TITLE
check_with_sanitizers - PREPERROR

### ISSUE THREAD

**Issue by gagolews** [r-hub/rhub#404]
Hi! Excellent work on this service, super useful for the solaris build chain.

This time though I'm getting the following error message quickly after a call to `check_with_sanitizers`:

![image](https://user-images.githubusercontent.com/3193581/89000629-5a26ec00-d2e7-11ea-9f5f-7acdd4dc69a2.png)

```
Status for build genieclust_0.9.4.tar.gz-a8b1456f4ec3482abf89b33f72146b53
Status: error
Duration: 1 seconds
Preparing

   1#> Started by user r-hub Jenkins admin

   2#> Building remotely on linux-builder-2.internal.cloudapp.net-31108a3d (slave swarm linux) in workspace /home/rhub/workspace/genieclust_0.9.4.tar.gz-a8b1456f4ec3482abf89b33f72146b53

   3#> java.io.IOException: Failed to mkdirs: /home/rhub/workspace/genieclust_0.9.4.tar.gz-a8b1456f4ec3482abf89b33f72146b53

   4#> at hudson.FilePath.mkdirs(FilePath.java:1191)

   5#> at hudson.model.AbstractProject.checkout(AbstractProject.java:1267)

   6#> at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)

   7#> at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)

   8#> at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)

   9#> at hudson.model.Run.execute(Run.java:1741)

  10#> at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)

  11#> at hudson.model.ResourceController.execute(ResourceController.java:98)

  12#> at hudson.model.Executor.run(Executor.java:410)

  13#> Pinging https://builder.r-hub.io/build/FAILURE/genieclust_0.9.4.tar.gz-a8b1456f4ec3482abf89b33f72146b53/2020-07-31T04:32:32Z

  14#> {"status":"ok"}

  15#> Finished: FAILURE
```

url: https://builder.r-hub.io/status/genieclust_0.9.4.tar.gz-a8b1456f4ec3482abf89b33f72146b53

**Comment by gaborcsardi** [comment]
Thanks! Should be fixed now.

**Comment by gagolews** [comment]
Awesome.

However, I received an email like:

![image](https://user-images.githubusercontent.com/3193581/89024068-0ed70280-d314-11ea-9d5d-440c3dea24b4.png)


but the status (see https://builder.r-hub.io/status/genieclust_0.9.4.tar.gz-c422065b934a44009fc531b0e17354d0) says 'success'.

**Comment by gaborcsardi** [comment]
Because of this:
```
10775#> Warning messages:
10776#> 1: In i.p(...) :
10777#> installation of package ‘checkmate’ had non-zero exit status
10778#> 2: In i.p(...) : installation of package ‘BBmisc’ had non-zero exit status
10779#> 3: In i.p(...) :
10780#> installation of package ‘emstreeR’ had non-zero exit status
10781#> >
```

**Comment by gagolews** [comment]
Aaah, right, okay, thanks!

**Comment by gaborcsardi** [comment]
I am not sure why this is, possibly our container has an older R-devel. Let me try to re-build it.

**Comment by gaborcsardi** [comment]
Yeah, our base container hasn't been up updated for 5 months, let me build one from scratch: https://hub.docker.com/r/rocker/r-devel-san

**Comment by gaborcsardi** [comment]
@gagolews OK, updated it, please try again.

**Comment by gagolews** [comment]
Hmmm... I'm receiving some mixed signals here...

The system sent 2 emails, one after another:


![image](https://user-images.githubusercontent.com/3193581/89119515-8df84200-d49e-11ea-9a03-4ce282c2429f.png)


![image](https://user-images.githubusercontent.com/3193581/89119522-951f5000-d49e-11ea-9d38-20f49cbd92c5.png)


Both include a link to https://builder.r-hub.io/status/genieclust_0.9.5.tar.gz-580c56b0378845749c60eda49cd472ca

Plus I was wondering where I can find the asan/ubsan results? They don't seem to be present amongst the artifacts https://artifacts.r-hub.io/genieclust_0.9.5.tar.gz-580c56b0378845749c60eda49cd472ca/ ?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
