### ISSUE TITLE
Confused with PREPERROR

### ISSUE THREAD

**Issue by biplab44** [r-hub/rhub#405]
When I check my r package for Solaris platform using rhub I received an email that says "HDLSSkST 1.0.1: PREPERROR", but in the logs, everything seems to be ok. Did I miss something? For all other platforms, I received emails that say, "HDLSSkST 1.0.1: OK". 
```
HDLSSkST 1.0.1: PREPERROR
Build ID: | HDLSSkST_1.0.1.tar.gz-11aca98b90c8431b8cebaeddb7d04f21
Platform: | Oracle Solaris 10, x86, 32 bit, R-release
Submitted: | 12.2 seconds ago
Build time: | 6 seconds
 
See the full build log: HTML, text, artifacts.
Have questions, suggestions or want to report a bug? Please file an issue ticket at GitHub. Thank You for using the R-hub builder

 https://builder.r-hub.io/status/HDLSSkST_1.0.1.tar.gz-11aca98b90c8431b8cebaeddb7d04f21
```

**Comment by gaborcsardi** [comment]
PREPERROR means that an error happens before the check could start. Please submit your job again, I think I fixed the issue with the Solaris machine.

**Comment by biplab44** [comment]
thanks
