### ISSUE TITLE
PREPERROR

### ISSUE THREAD

**Issue by JR-EvolEcol** [r-hub/rhub#406]
Hi, I'm getting some messages that are apparently contradictory. I receive emails with PREPERROR notification after running check_win_devel() and check_rhub() on the updated version of my R package. Meanwhile I also receive a check log at win-builder which appears to be all fine. I'm not able to decipher the information in the PREPERROR report, so I hope you can help.

Links:
https://builder.r-hub.io/status/MHCtools_1.3.0.tar.gz-94ca18b922664cc0954b552b07f18121
https://win-builder.r-project.org/wymSLta3qR87/

All the best,
Jacob Roved

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
