### ISSUE TITLE
Python and reticulate

### ISSUE THREAD

**Issue by tseppelt** [r-hub/rhub#407]
I'm trying to check our package [motifr](https://github.com/marioangst/motifr/) using rhub. The package uses [reticulate](https://github.com/rstudio/reticulate) to make a Python package accessible to R. Unfortunately, I'm encountering difficulties with reticulate/Python:

* [Windows build](https://builder.r-hub.io/status/motifr_0.2.0.tar.gz-9efa62007c0a4e23a042f6e9462deca0)
* [Log files](https://github.com/marioangst/motifr/issues/40#issuecomment-683266702)

Crucial are the following lines:
On **Windows Server 2008 R2 SP1, R-devel, 32/64 bit**:
```
Installation of Python not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```
On **Fedora Linux, R-devel, clang, gfortran:**
```Error: Python module sma was not found.

Detected Python configuration:

python:         /usr/bin/python3
libpython:      /usr/lib64/libpython3.8.so.1.0
pythonhome:     //usr://usr
version:        3.8.5 (default, Aug 12 2020, 00:00:00)  [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
numpy:           [NOT FOUND]
networkx:       [NOT FOUND]

python versions found: 
 /usr/bin/python3
 /usr/bin/python

Execution halted
```
On **Ubuntu Linux 16.04 LTS, R-release, GCC**:
```
Error: Python shared library not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
Execution halted
```

Calling ``reticulate::install_miniconda()`` is probably a good advice. However, I don't really want to include this in our package (see [reticulate manual](https://rstudio.github.io/reticulate/articles/package.html) as it would be messing up the set-up for real users. Is there a possibility to provide an rhub-specific set-up script?

I would greatly appreciate if someone could point me to a manual for using reticulate/Python with rhub.

**Comment by henry090** [comment]
Reticulate is not well organized in the R hub. GitHub Actions are way better. However, CRAN relies on rhub, so it is better to submit and see any note beforehand.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
