### ISSUE TITLE
Platform: Windows Server 2008 R2 SP1, R-devel, 32/64 bit, Error in loadNamespace(name): there is no package called 'withr'

### ISSUE THREAD

**Issue by DyfanJones** [r-hub/rhub#410]
Hi All,

I am coming across an error and warning when testing my package on rhub `Windows Server 2008 R2 SP1, R-devel, 32/64 bit`.

Code executed:
```r
rhub::check(
  platform="windows-x86_64-devel",
  env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always",  LIBARROW_BINARY="true") 
)
```
`LIBARROW_BINARY` has been set to "true" given advice from: https://github.com/r-hub/rhub/issues/371

Returning Error and warning:
```
* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > library(noctua)
  > 
  > library(testthat)
  > test_check("noctua")
  Error in loadNamespace(name) : there is no package called 'withr'
  Calls: test_check ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
  Execution halted
```

```
* checking package dependencies ... WARNING
Skipping vignette re-building
Package suggested but not available for checking: 'knitr'

VignetteBuilder package required for checking but not installed: 'knitr'
```
Full log report: https://builder.r-hub.io/status/noctua_1.8.1.tar.gz-1b5290036ab141fbb1e4987f59813c52

Any help with this would be very much appreciated (thanks in advanced :D )

Possible related issue: https://github.com/r-hub/rhub/issues/374

**Comment by gaborcsardi** [comment]
Yes, this is a common issue with `install.packages(). Workaround: https://github.com/r-hub/rhub/issues/367#issuecomment-621757715

**Comment by DyfanJones** [comment]
Hi @gaborcsardi when I run:

```r
rhub::check(
  platform="windows-x86_64-devel",
  env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
)
```
I get the same error/warning: https://builder.r-hub.io/status/noctua_1.8.1.tar.gz-982d5918b70a4704b53221c61f7e707a

**Comment by DyfanJones** [comment]
@gaborcsardi Just want to give a quick update. I have re-ran the code:

> ```r
> rhub::check(
>   platform="windows-x86_64-devel",
>   env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
> )
> ```
 
And the package was successfully ran on rhub. Thanks for any extra work you have been doing behind the scenes. I will close this ticket as the issue is resolved.
