### ISSUE TITLE
PREPERROR Ubuntu, Fedora: ERROR: dependencies are not available

### ISSUE THREAD

**Issue by SavaryGraph** [r-hub/rhub#412]
When I check an R package ('graph4lg') using rhub::check(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")) and choosing either an Ubuntu or Fedora platform, I obtain the following PREPERROR: 
ERROR: dependencies ‘adegenet’, ‘pegas’, ‘sf’ are not available for package ‘graph4lg’

The complete log is here: https://builder.r-hub.io/status/graph4lg_1.0.1.tar.gz-3ea301c32e5442a5a436bea811e1bafe 

Checking with Windows or Debian platforms, or using winbuilder or locally, I do not obtain these errors. 

What can be the cause for such an error?

I apologize in advance if a similar issue was already solved. The main solution I found was to always compile and install packages when checking, but it does not appear sufficient in my case.

Thanks
Paul

**Comment by gaborcsardi** [comment]
This:
```
#> checking GDAL version >= 2.0.1... no
#> configure: error: sf is not compatible with GDAL versions below 2.0.1
#> ERROR: configuration failed for package ‘sf’
#> * removing ‘/home/docker/R/sf’
```

This old Ubuntu has a very old gdal library, so sf will not work on it.

**Comment by SavaryGraph** [comment]
Thank you for this quick answer.

Do you know if it can explain an error due to sf::st_write() on Ubuntu platform using a gdal library > 3.0.0?

Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Dataset already exists.

Error obtained even when the directory where the dataset should be created is empty.

Thanks
Paul

**Comment by gaborcsardi** [comment]
I don't know.

**Comment by SavaryGraph** [comment]
Ok, no problem.
This ubuntu platform uses R 3.6. I will update R and check again
Thank you
Regards
Paul

**Comment by SavaryGraph** [comment]
I checked on Ubuntu 20.04 with R 4.0.2 and this error disappeared.

Thanks
Paul
