### ISSUE TITLE
solaris-x86-patched-ods pkg-config problem?

### ISSUE THREAD

**Issue by gothub** [r-hub/rhub#413]
Testing the 'redland' package on solaris-x86-patched-ods produces this error, shown in
https://builder.r-hub.io/status/redland_1.0.17-13.tar.gz-6516818e794e42c0b0a6102b76a9b6e4
```
 557#> checking with pkg-config for the system ICU4C... sh: gnome-config: not found
 558#> sh: gnome-config: not found
 559#> no
```
Then later, when the `configure` script is invoked:
```
1918#> * installing *source* package ‘redland’ ...
1919#> ** using staged installation
1920#> sh: gnome-config: not found
1921#> sh: gnome-config: not found
1922#> Package redland was not found in the pkg-config search path.
1923#> Perhaps you should add the directory containing `redland.pc'
1924#> to the PKG_CONFIG_PATH environment variable
1925#> No package 'redland' found
1926#> Using PKG_CFLAGS=
1927#> Using PKG_LIBS=-lrdf
1928#> ------------------------- ANTICONF ERROR ---------------------------
1929#> Configuration failed because redland was not found. Try installing:
1930#> * deb: librdf0-dev (Debian, Ubuntu, etc)
1931#> * rpm: redland-devel (Fedora, EPEL)
1932#> * brew: redland (OSX)
```

It appears that Solaris supports `pkg-config` command, which is what `configure` is trying to call. Here is the Solaris man page: https://docs.oracle.com/cd/E36784_01/html/E36870/pkg-config-1.html

What is 'gnome-config' and how can this be added to the solaris-x86-patched-ods rhub platform?

Thanks for your help!

**Comment by gaborcsardi** [comment]
This is a known solaris bug and it happens if the library is not available. Solaris does not have redland.

**Comment by gothub** [comment]
@gaborcsardi thanks for the quick feedback. Previous versions of our R `redland` package have build and passed the CRAN package checks, so there must be some library out there that CRAN is using.

Any idea on what CRAN is doing to build this library?

@jeroen any clues regarding librdf and Solaris 10?

**Comment by gothub** [comment]
It looks like librdf (or redland-dev?) is not listed at the OpenCSW https://www.opencsw.org/get-it/packages/, and of course
not in https://github.com/r-hub/solarischeck/blob/master/sysreqs.txt.

Not sure how our R `redland` package has passed the Solaris CRAN build/test.

**Comment by gaborcsardi** [comment]
IDK what CRAN is using, maybe you can ask them? It is possible that they installed it manually.

**Comment by gothub** [comment]
OK, will do. I'll post back here with whatever I find out.

**Comment by gaborcsardi** [comment]
Great, thanks!

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
