### ISSUE TITLE
R CMD check requires 'checkbashisms' for compiled packages

### ISSUE THREAD

**Issue by gothub** [r-hub/rhub#414]
https://builder.r-hub.io/status/redland_1.0.17-13.tar.gz-0a87263b135749f386e1c44259ba3fe8

`R CMD check` now requires that a `configure` script need to pass a 'checkbashism' check to help determine if the script is portable.

The R `redland` package build at https://builder.r-hub.io/status/redland_1.0.17-13.tar.gz-0a87263b135749f386e1c44259ba3fe8 generated this warning, as `checkbashisms` wasn't available:
```
1880#> * checking top-level files ... WARNING
1881#> A complete check needs the 'checkbashisms' script.
1882#> See section ‘Configure and cleanup’ in the ‘Writing R Extensions’
1883#> manual.
``` 
This command is available from:
- macOS/brew - checkbashisms'
- Ubuntu - devscripts
- Debian - devscripts
- Fedora - devscripts-checkbashisms

How should I proceed in order to implement a fix?
Is this an internal fix to Rhub, or should I submit a PR to 'https://github.com/r-hub/sysreqsdb'
for 'checkbashisms.json' and add 'checkbashisms' to my R package `DESCRIPTION` system requirements?

**Comment by maelle** [comment]
@gaborcsardi related PR https://github.com/r-hub/rhub-linux-builders/pull/47

**Comment by SteffenMoritz** [comment]
checkbashisms script seems to be present on most machines now.

Only for  Platform: | Fedora Linux, R-devel, clang, gfortran  I encountered the error today.

Platform: | Fedora Linux, R-devel, clang, gfortran

WARNINGS:* checking top-level files ... WARNING A complete check needs the 'checkbashisms' script. See section ‘Configure and cleanup’ in the ‘Writing R Extensions’ manual.

**Comment by gothub** [comment]
@SteffenMoritz @maelle thanks!

**Comment by MatthieuStigler** [comment]
The problem happens also on `Oracle Solaris 10, x86, 32 bit, R-release` and `Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6`.

**Comment by gaborcsardi** [comment]
@MatthieuStigler AFAIK there is no such script for Solaris, so just ignore that failure. Or do not run that check on Solaris at all.

**Comment by MatthieuStigler** [comment]
@gaborcsardi Thanks for the quick answer! I still need to run solaris as it is one of the platforms monitored on CRAN (and was the only platform creating a problem), but will ignore that warning in the future! 

Thanks for the great work with rhub, very useful!

**Comment by gaborcsardi** [comment]
What I meant is to skip that check when checking on Solaris. I.e. do not use `check_for_cran()` or `--as-cran`, CRAN does not use it, either, on Solaris. Or yeah, just ignore that result.

**Comment by MatthieuStigler** [comment]
Oh I see! So I am using it from `devtools::check_rhub()`, should I then pass `check_args` to it, as in `devtools::check_rhub(..., check_args="")`? Thanks!

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
