### ISSUE TITLE
Non Portable Flags in Solaris Build

### ISSUE THREAD

**Issue by christopherkenny** [r-hub/rhub#415]
Hello,

When checking a build of the R package redist (with sf and spdep dependencies removed), we are coming across the following NOTE: 
```
> checking compilation flags used ... NOTE
  Compilation used the following non-portable flag(s):
    ‘-march=pentiumpro’
```

However, when looking in the contents of the Makevars.in file, we have a pretty standard set up for a package that relies on Rcpp and Rmpi. [Additionally, this links to the file directly](https://github.com/kosukeimai/redist/blob/no-geo-solaris/src/Makevars)
```
PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CXXFLAGS)
```

To my knowledge, this shouldn't be creating the march flag above. Is it possible that this compiler flag is being created by the Solaris machine's options?

[The link to the full check is here.](https://builder.r-hub.io/status/redist_2.0.2.tar.gz-c0e874f6da334100a2a87ad09bb8662e)

Any confirmation that this is (or is not) related to the Rhub machine itself would be very appreciated.

Thanks,
Chris

**Comment by gaborcsardi** [comment]
Yes, `-march=pentiumpro` is indeed a flag that was/is used by the R installation itself. 

I am not sure why the check catches that, it should not, I think.

**Comment by christopherkenny** [comment]
Thank you very much.
