### ISSUE TITLE
Server status

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#418]
The server seems quite unstable in the last few days.

Whenever I run the following code 
```
rhub::check_for_cran()
rhub::check(platform = 'ubuntu-rchk')
rhub::check_with_sanitizers()
```

I get the following error message
```
No encoding supplied: defaulting to UTF-8.
Error in query("GET PLATFORMS", as = "text") : rhub error
```

But the error message depends on the query:
```
list_my_checks()
```
results in
```
No encoding supplied: defaulting to UTF-8.
Error in query("LIST BUILDS EMAIL", params = list(email = email, token = email_get_token(email))) : 
  rhub error
```

Is there a way to check the status of the server? Maybe a new function?

**Comment by gaborcsardi** [comment]
Thanks for the report, I am investigating.

**Comment by hongooi73** [comment]
Not sure if it's related, but the Linux checks have been very slow in the last few days. Like 3-4 hours to do what takes 5 minutes on Windows.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
