### ISSUE TITLE
Windows check gets maintainer addresses confused

### ISSUE THREAD

**Issue by hongooi73** [r-hub/rhub#419]
On running `rhub::check_for_cran()`, I got the following result from the Windows check:

![image](https://user-images.githubusercontent.com/11328890/95899770-bb396880-0ddc-11eb-83ab-53c919d00602.png)

Notice how it's got the old and new addresses mixed up (this is a submission to change the maintainer email address). The old maintainer should be my Microsoft account, and the new one my Gmail account. The Fedora and Debian checks didn't have this problem

https://builder.r-hub.io/status/AzureRMR_2.3.6.tar.gz-f4ff1cf20fd5461ab91583180263a84f

**Comment by hongooi73** [comment]
Hm, I just noticed that that previous check technically got the new maintainer right, although the old one is weirdly constructed. Here's another example where both the old and new addresses are wrong:

![image](https://user-images.githubusercontent.com/11328890/95901282-d4431900-0dde-11eb-89be-d98ab27533b9.png)

https://builder.r-hub.io/status/AzureRMR_2.3.5.9000.tar.gz-5677e5e7002345299ee673b545422c09

**Comment by gaborcsardi** [comment]
I think this is a bug in our scheduler, it sometimes mixes up stdout and stderr. Maybe we could redirect stderr to stdout for the `R CMD check` part.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
