### ISSUE TITLE
Aggregate _compiler_ warnings?

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#42]
Ok, here is one from the _crazy Uncle Bob department_:
- those of us writing with C/C++ consume an API
- we also sometimes provide one
- these do change and once in a while compiler warnings arise and change
- sometimes it also happens just because the compiler changes

Case in point it just took me 'too long' to catch it before a release that Conrad had deprecated a certain setting in Armadillo.

And when we do 'R CMD check' we _do not see the compiler output_ (which we do see when running `R CMD INSTALL`).  But we have it in `00Install.out`.  

Could you just grep and count the word `Warning`?

**Comment by gaborcsardi** [comment]
Good idea.

**Comment by eddelbuettel** [comment]
I guess in practice one may need to control for how the `gcc` and `clang` families emit these.  Effectively we don't have any others.  We do have `gcc` from 4.4.* up to 6.1.* right now so the format may change slightly.

This would indeed be nice to have.

**Comment by richfitz** [comment]
Of possible use, in [rcmdshlib](https://github.com/richfitz/rcmdshlib) I have some fairly cheesy code to extract and summarise compiler warnings.  It's tested on clang and gcc

**Comment by gaborcsardi** [comment]
While this is a good idea, it is fiddle-y to implement. As a minimum, we should keep the 00install.out as an artifact, I'll open an issue for that: #112 

Maybe we could also print it to the screen, but that would work best if the HTML output had foldable sections.
