### ISSUE TITLE
Drive is full on Windows machine

### ISSUE THREAD

**Issue by hongooi73** [r-hub/rhub#420]
At least that's what I assume, given this warning:

![image](https://user-images.githubusercontent.com/11328890/96149528-260daf80-0f55-11eb-9aa4-fcd6c5fcf8d9.png)

https://builder.r-hub.io/status/AzureQstor_1.0.1.tar.gz-44c5dd6fd6ca4d06a922ff720fda50af

**Comment by gaborcsardi** [comment]
Hmmm, it is not actually full, so I am not sure what this is. 

There is a quota, do you think that you are using more than 1GB space? The package plus its dependencies do not seem big.

**Comment by hongooi73** [comment]
> There is a quota, do you think that you are using more than 1GB space? The package plus its dependencies do not seem big.

That could be it. I'm changing the maintainer email address for all my packages and taking the opportunity to recheck them, so I've probably used up my quota. There's about 15 packages.

Btw, check your emails... I sent you one a couple of days ago 😊

**Comment by gaborcsardi** [comment]
Yeah, but the quota is per submission, so it should not be. Maybe it did run out of space temporarily, but since then the some jobs ended, and the space was cleaned up.

**Comment by hongooi73** [comment]
Given there is a quota (something I wasn't aware of until now), is there a way to free up space?

**Comment by gaborcsardi** [comment]
The quota is for a single submission, so you usually do not need to worry about it. It is only an issue if your package + its dependencies need more than 1GB for the check.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
