### ISSUE TITLE
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)), : rhub error

### ISSUE THREAD

**Issue by sbgraves237** [r-hub/rhub#422]
I'm getting Issue # 297, opened last year 2019-09-05 and subsequently closed:  
 
rhub::check_for_cran()
─  Building package
─  Uploading package
No encoding supplied: defaulting to UTF-8.
Error in query("SUBMIT PACKAGE", 
   data = list(email = unbox(email), 
   token = unbox(email_get_token(email)),  : 
      rhub error

This is using R version 4.0.3 Running under: macOS Catalina 10.15.7.  I can provide the full sessionInfo() if you want that.  Thanks.  Spencer Graves

**Comment by gaborcsardi** [comment]
Are you online? What does `rhub::platforms()` say? What does `traceback()` say after the error?

**Comment by sbgraves237** [comment]
On 2020-10-17 08:43, Gábor Csárdi wrote:
> Are you online? What does |rhub::platforms()| say? What does 


 > rhub::platforms()
debian-clang-devel:
   Debian Linux, R-devel, clang, ISO-8859-15 locale
debian-gcc-devel:
   Debian Linux, R-devel, GCC
debian-gcc-devel-nold:
   Debian Linux, R-devel, GCC, no long double
debian-gcc-patched:
   Debian Linux, R-patched, GCC
debian-gcc-release:
   Debian Linux, R-release, GCC
fedora-clang-devel:
   Fedora Linux, R-devel, clang, gfortran
fedora-gcc-devel:
   Fedora Linux, R-devel, GCC
linux-x86_64-centos6-epel:
   CentOS 6, stock R from EPEL
linux-x86_64-centos6-epel-rdt:
   CentOS 6 with Redhat Developer Toolset, R from EPEL
linux-x86_64-rocker-gcc-san:
   Debian Linux, R-devel, GCC ASAN/UBSAN
macos-highsierra-release:
   macOS 10.13.6 High Sierra, R-release, brew
macos-highsierra-release-cran:
   macOS 10.13.6 High Sierra, R-release, CRAN's setup
solaris-x86-patched:
   Oracle Solaris 10, x86, 32 bit, R-release
solaris-x86-patched-ods:
   Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6
ubuntu-gcc-devel:
   Ubuntu Linux 16.04 LTS, R-devel, GCC
ubuntu-gcc-release:
   Ubuntu Linux 16.04 LTS, R-release, GCC
ubuntu-rchk:
   Ubuntu Linux 16.04 LTS, R-devel with rchk
windows-x86_64-devel:
   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
windows-x86_64-oldrel:
   Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit
windows-x86_64-patched:
   Windows Server 2008 R2 SP1, R-patched, 32/64 bit
windows-x86_64-release:
   Windows Server 2008 R2 SP1, R-release, 32/64 bit


> |traceback()| say after the error?

 > traceback()
6: stop(create_condition(response, "error", call = call))
5: report_error(response)
4: query("SUBMIT PACKAGE", data = list(email = unbox(email), token = 
unbox(email_get_token(email)),
        package = unbox(unname(m[, "package"])), version = unbox(unname(m[,
            "version"])), platform = platform, env = as.list(env_vars),
        check_args = unbox(paste(check_args, collapse = " ")), file = 
unbox(base64_enc(buf))))
3: submit_package(email, pkg_targz, platform = platform, check_args = 
check_args,
        env_vars = env_vars)
2: check(path = path, platform = platforms, email = email, check_args = 
check_args,
        env_vars = env_vars, ...)
1: rhub::check_for_cran()


	  Thanks.
	  Spencer Graves

**Comment by gaborcsardi** [comment]
From the logs it seems like you are trying to submit a file that is 840MB, which is probably a mistake?

**Comment by sbgraves237** [comment]
Hi, Gábor:


	  I had a file that was 625MB, listed in .gitignore but not 
.Rbuildignore.  I moved it out of the package, and 
"rhub::check_for_cran()" worked.  Thanks.


	  Secondarily, the instructions on "Preparing your package for a CRAN 
submission" at:


https://github.com/ThinkR-open/prepare-for-cran


includes, "DESCRIPTION file should have a cph (copyright holder)."  I 
added a "cph" field.  Now, I'm getting, "Unknown, possibly mis-spelled, 
fields in DESCRIPTION: 'cph'".


	  Either these instructions should be changed or "R CMD check" 
shouldn't flag this.


	  Thanks again,
	  Spencer Graves

**Comment by gaborcsardi** [comment]
We have not much to do with what `ThinkR-open/prepare-for-cran` suggests or what `R CMD check` does.

FWIW this is how to add a `cph` field:
https://github.com/r-lib/testthat/blob/12a39de9270c983c77ad82020295f1fb643c29e3/DESCRIPTION#L9-L10
