### ISSUE TITLE
Error: processing vignette ... failed with diagnostics: there is no package called 'utf8'

### ISSUE THREAD

**Issue by sbgraves237** [r-hub/rhub#423]
rhub::check_for_cran() on ["https://github.com/sbgraves237/Ecfun"](https://github.com/sbgraves237/Ecfun) failed with "Error: processing vignette 'ForecastingNuclearProliferation.Rmd' failed with diagnostics:
there is no package called 'utf8'".  However, ['utf8' is on CRAN](https://cran.r-project.org/web/packages/utf8/index.html).  

Do I need to do anything with this?  

I assume you would want to know.  Thanks for your work supporting this valuable piece of the R ecology.  Spencer Graves

**Comment by gaborcsardi** [comment]
This ia a bug in `install.packages()` and it happens when CRAN does not have a windows binary available. This is a workaround: https://github.com/r-hub/rhub/issues/367#issuecomment-621757715
