### ISSUE TITLE
Check results differ for package submission and check_for_cran()

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#424]
This is the note from the function of the package

```
* checking installed package size ... NOTE
  installed size is  8.7Mb
  sub-directories of 1Mb or more:
    extdata   1.1Mb
    libs      6.6Mb
```

The release check for CRAN packages gets the following warning:

```
Found the following significant warnings:
  read_workbook.cpp:576:29: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 8 [-Wformat-overflow=]
  read_workbook.cpp:506:31: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 8 [-Wformat-overflow=]
```

It would be really helpful, if the submission tests are the same as the test in the package.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
