### ISSUE TITLE
unexpected warnings/notes using check_on_linux()

### ISSUE THREAD

**Issue by juliasilge** [r-hub/rhub#43]
This looks like such a useful project! I saw the announcement for r-hub and decided to try it for [tidytext](https://github.com/juliasilge/tidytext), since we are getting ready for an imminent new release. I use Travis and appveyor and the current version passes on those without any warnings or anything. When I used `check_on_linux` on my current version of tidytext, I got these results:
https://builder.r-hub.io/status/tidytext_0.1.2.tar.gz-a1ff84f579ba44748cc304c60f7102fc

It seems to have quit from building a vignette because of a font? Also there is a NOTE about dplyr in Imports that we don't see on other platforms.

Are these what you would expect me to see? I sort of expected to see the same results I get from building on Travis.

**Comment by gaborcsardi** [comment]
Yes, the font is a known problem, I'll hopefully fix it soon.

The NOTE is because you have Imports: plyr in your DESCRIPTION, but you don't actually use the 'plyr' package for anything.

**Comment by juliasilge** [comment]
Yes, I understand that that is what it meant; I just was puzzled because I hadn't seen that NOTE anywhere else (locally, on Travis, etc). It turns out that, in fact, we did remove the code that depended on plyr at some point so [this was an unnecessary Imports](https://github.com/juliasilge/tidytext/commit/e236ad241e9d6daaec5f0c8dfc5f66a9263b2d34). So I guess using r-hub already improved my package!

I am still rather perplexed that I didn't see this NOTE anywhere else before now? But thank you all!

**Comment by gaborcsardi** [comment]
I don't know how Travis missed this, it has some customized settings for the checks I think.

Btw. I also fixed the font problem I believe.

**Comment by juliasilge** [comment]
I ran `check_on_linux()` again and it all looks great now!

https://builder.r-hub.io/status/original/tidytext_0.1.2.tar.gz-93ed606e408f49a4a50fe883fdffbc92
