### ISSUE TITLE
Failing to load Bioconductor packages

### ISSUE THREAD

**Issue by llrs** [r-hub/rhub#430]
Hi! many thanks for this service, r-hub has been very useful to check my packages.

I think this is a separate issue from #38, might be related. But when I submit packages on rhub that have some packages of Bioconductor I often get an error.

> * checking package dependencies ... ERROR
  'Biobase', 'GO.db', 'GSEABase', 'org.Hs.eg.db', 'reactome.db', 'utf8'
Packages suggested but not available:

I am not sure to what it is related as sometimes the packages I submit are build correctly. But I just wanted to document that from time to time it happens.

Some additional detail in case they help:
Build ID: | BaseSet_0.0.14.tar.gz-a0
Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit

**Comment by gaborcsardi** [comment]
Can you tell us where the log of the build is?

**Comment by llrs** [comment]
It is a 2 year old issue, I don't remember anything else aside from what it is written here. That's why I closed the issue.

**Comment by gaborcsardi** [comment]
Oh, right, sry, I missed that the notification was for the close.
