### ISSUE TITLE
PROJERROR: Unable to install package dependency "sf"

### ISSUE THREAD

**Issue by WayneGitShell** [r-hub/rhub#431]
Release patch for package GWSDAT. 
Error building on CRAN - as it fails to install package dependency "sf". See details here: 
https://builder.r-hub.io/status/original/GWSDAT_3.0.4.tar.gz-8461dd5b9bd146a3ba022c862b884ba2

**Comment by WayneGitShell** [comment]
On closer inspection it looks like GDAL is outdated on the CRAN version.

**Comment by WayneGitShell** [comment]
See 3340# below.. 
checking for gdal-config... /usr/bin/gdal-config
3337#> checking gdal-config usability... yes
3338#> configure: GDAL: 1.11.3
3339#> checking GDAL version >= 2.0.1... no
3340#> configure: error: sf is not compatible with GDAL versions below 2.0.1

**Comment by SimonDedman** [comment]
Wayne did changing your DESCRIPTION file Imports to

> rgdal (>= 2.0.1),

Help at all? I've just hit the same issue & this was my first thought. Cheers!

**Comment by WayneGitShell** [comment]
Hi Simon, 

The issue is indeed related to sf needing  rgdal (>= 2.0.1) to work..  However I don't think I changed anything - I merely raised the issue with CRAN and I think they have fixed something behind the scenes... 

there is no reference to rgdal (>= 2.0.1), in the description file: https://github.com/WayneGitShell/GWSDAT/blob/master/DESCRIPTION

Wayne

**Comment by SimonDedman** [comment]
Ooh good point, if you're only importing sf you won't have rgdal explicitly so defo not your fault. Thanks!

**Comment by WayneGitShell** [comment]
@SimonDedman  did you get the issue with sf sorted? Im updating my package and getting the following error messages related to importing sf: https://builder.r-hub.io/status/GWSDAT_3.0.6.tar.gz-1afd2ea7540d463e8d1d62bc33df3e0d

**Comment by SimonDedman** [comment]
@WayneGitShell I believe I just ignored it - IIRC this is a problem within the builder environment only, not with your package (necessarily). Just got my package uploaded to CRAN so evidently it wasn't a blocking point.

**Comment by WayneGitShell** [comment]
@SimonDedman  thanks for the quick reply. I've had issues with sf imports before. 

Did you need to do anything or did your package get uploaded automatically despite the error message?

**Comment by SimonDedman** [comment]
@WayneGitShell I think I just uploaded it successfully regardless.

**Comment by LHMarshall** [comment]
@SimonDedman @WayneGitShell just wondering how did you upload your packages to CRAN successfully? 

I got the following E-mail after submitting very early on Monday UK time:

Dear maintainer,
 
package dssd_0.2.2.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/dssd_0.2.2_20210222_100833/Windows/00check.log>
Status: 1 ERROR
Debian: <https://win-builder.r-project.org/incoming_pretest/dssd_0.2.2_20210222_100833/Debian/00check.log>
Status: OK

when I check...
* checking package dependencies ... ERROR
Package required but not available: 'sf'

It said to reply-all to the E-mail (which only actually generated a reply address to cran-submissions@r-project.org) if I thought this was a false positive, so I did but as yet haven't heard anything. I sent the reply on Monday morning. Wondering if I should try a fresh submission...

Any advice appreciated, thanks!

**Comment by SimonDedman** [comment]
Hi Laura,

I'm surprised because I could have sworn I put a note about this in my submission to CRAN but all email chain evidence points to that being not true. FWIW from my experience the CRAN folks were super helpful and nice; I suspect you could point them towards this thread and make the case that - as far as we can tell - it seems this build test failure is due to a setup issue in the builder and not your package itself.

Laura if you have enough excess gumption, it might be good to try to contact whomever's in charge of this problem, feasibly the win-builder people? Even if it doesn't lead to a quick resolution, simply raising a ticket gives us (& future us-es) an issue URL to point to.

Cheers!

**Comment by WayneGitShell** [comment]
ligges@statistik.tu-dortmund.de is the Maintainer of binary packages for Windows.

**Comment by SimonDedman** [comment]
Ah, that's Uwe, one of the main folks who'll be scrutinising your package (so to speak). So he should be understanding!

**Comment by LHMarshall** [comment]
Thanks both @SimonDedman @WayneGitShell I'll let you know how I get on!

**Comment by LHMarshall** [comment]
New checks are being triggered now after contacting Uwe so fingers crossed!

**Comment by LHMarshall** [comment]
My original package was uploaded after second lot of checks was triggered. I have since uploaded another package with sf dependency without this issue.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
