### ISSUE TITLE
solaris-x86-patched: ‘qpdf’ is needed for checks on size reduction of PDFs

### ISSUE THREAD

**Issue by DyfanJones** [r-hub/rhub#432]
Hi All,

When testing my package on `solaris-x86-patched` and `solaris-x86-patched-ods` I get the following warning message:

```
> checking for unstated dependencies in examples ... OK
   WARNING
  ‘qpdf’ is needed for checks on size reduction of PDFs

> checking top-level files ... NOTE
  Files ‘README.md’ or ‘NEWS.md’ cannot be checked without ‘pandoc’ being installed.
```

Full logs: https://builder.r-hub.io/status/noctua_1.9.1.tar.gz-d4806f2ef5cd420abcd41bd61c0b5b43

This message doesn't appear on other linux systems. Could this issue be related to https://github.com/r-hub/rhub/issues/46 ? 

Any advice on this would be greatly appreciated.

Many thanks in advance.

**Comment by gaborcsardi** [comment]
I installed qpdf, so it should be ok now.

**Comment by DyfanJones** [comment]
@gaborcsardi thanks for fast response as always. Just re-ran and I get no warning message. I will close this ticket now 👍
