### ISSUE TITLE
dbplyr fails to install on rhub Windows Server, causing check failure

### ISSUE THREAD

**Issue by torfason** [r-hub/rhub#433]
I am getting errors on `rhub::check_for_cran()` because the `dbplyr` package fails to install on the following platform:

  * Windows Server 2008 R2 SP1, R-devel, 32/64 bit

The error message that seems to relate to the installation of `dbplyr` is:

```
 410#> ==================================================
 411#> trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.1/dbplyr_2.0.0.zip'
 412#> Content type 'application/zip' length 760117 bytes (742 KB)
 413#> ==================================================
 414#> downloaded 742 KB
 415#> Error in desc[1L, "Type"] : subscript out of bounds
 416#> Calls: ... force -> i.p -> .install.winbinary -> unpackPkgZip -> %in%
 417#> In addition: Warning messages:
 418#> 1: In unzip(zipname, exdir = dest) :
 419#> 2: In unzip(zipname, exdir = dest) :
 420#> write error in extracting from zip file
 421#> write error in extracting from zip file
 422#> Execution halted
```

The check concludes with an error message for `dplyr` and `RSQLite` as well (`Packages required but not available: 'RSQLite', 'dplyr', 'dbplyr'`), but I can't find a corresponding error for those packages. So those could either be independent issues or they could be consequences of the error installing `dbplyr`.

**Comment by gaborcsardi** [comment]
There was probably an incompatible change in R-devel recently. Can you please try again?

**Comment by torfason** [comment]
That was fast! Yes this works now, many thanks!
