### ISSUE TITLE
check() : Preparing build, see status at... and function hangs

### ISSUE THREAD

**Issue by danieltompsett** [r-hub/rhub#435]
Hello
I am currently trying to run checks on my package using rhub on R studio. With devtools installed, a local check is successful with 1 note.

However when I run check_with_rdevel() function with rhub I always get 

-  Building package
-  Uploading package
-  Preparing build, see status at
and then a url to check the status of my build.

However the function then simply wont go further, the rotating slash keeps moving but the function seems to stall.
when I go to to the URL  the page crashes and says "were sorry but something went wrong"

This actually occured even when I went through the site https://builder.r-hub.io/ itself.

Would anyone have an idea as to why this is happening? Could it be on their side? Or is there something about my function that 
could be causing this? even if the tarball successfully builds and passes the local check?

Thank you

**Comment by gaborcsardi** [comment]
You can query the status with the rhub package, e.g.

```r
❯ rhub::get_check("cli_2.1.0.9001.tar.gz-0d11716c614b41a1854020a866a180d4")

── cli 2.1.0.9001: NOTE

  Build ID:   cli_2.1.0.9001.tar.gz-0d11716c614b41a1854020a866a180d4
  Platform:   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
  Submitted:  4d 18h 24m 27s ago
  Build time: 4m 32.2s

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: 'G�bor Cs�rdi <csardi.gabor@gmail.com>'

  Version contains large components (2.1.0.9001)

❯ checking for future file timestamps ... NOTE
  unable to verify current time

0 errors ✔ | 0 warnings ✔ | 2 notes ✖
```

**Comment by danieltompsett** [comment]
Thank you
I shall try that and see how it goes
