### ISSUE TITLE
Confused with PREPERROR 

### ISSUE THREAD

**Issue by biplab44** [r-hub/rhub#437]
When I check my r package for windows platform using rhub I received an email that says "HDLSSkST 2.0.0: PREPERROR", but in the logs, everything seems to be ok and finished with success (Finished: SUCCESS). Did I miss something? For all other platforms, I received emails that say, "HDLSSkST 2.0.0: OK".

```
HDLSSkST 2.0.0: PREPERROR
--
Build ID: | HDLSSkST_2.0.0.tar.gz-6755c6278b894262b0d089eacd747399
Platform: | Windows Server 2008 R2 SP1, R-release, 32/64 bit
Submitted: | 5.7 seconds ago
Build time: | 4 seconds

https://builder.r-hub.io/status/original/HDLSSkST_2.0.0.tar.gz-6755c6278b894262b0d089eacd747399
```

**Comment by gaborcsardi** [comment]
I did some cleanup, try again, please. Thanks!

**Comment by biplab44** [comment]
thanks
