### ISSUE TITLE
On platform Fedora Linux, R-devel, clang, gfortran (name: fedora-clang-devel): Can't verify system time.

### ISSUE THREAD

**Issue by phargarten2** [r-hub/rhub#439]
Thank you for the opportunity to check packages virtually before sending them to CRAN. I got this note about the inability to check for system time. 

```
> On fedora-clang-devel (r-devel)
checking for future file timestamps ... NOTE
unable to verify current time
```

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
