### ISSUE TITLE
gfortran missing from CentOS?

### ISSUE THREAD

**Issue by fmichonneau** [r-hub/rhub#44]
I wanted to take rhub for a spin and tried it with build 7: "CentOS 6 with Redhat Developer Toolset, R from EPEL (linux-x86_64-centos6-epel-rdt)". A couple of my package dependencies failed to compile because gfortran couldn't be found:
` /opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.2.1/ld: cannot find -lgfortran`

Full log available here: https://builder.r-hub.io/status/rotl_3.0.1.901.tar.gz-ea226d88dd8043318f456248485b07c7

**Comment by gaborcsardi** [comment]
Thanks for reporting! 

I updated the CentOS 6 RDT image, it should be OK now.

**Comment by fmichonneau** [comment]
yes, it seems to work. Thanks!
