### ISSUE TITLE
Message in Terminal : "The install-github.me service is deprecated, please stop using it."

### ISSUE THREAD

**Issue by statnmap** [r-hub/rhub#444]
I launched `rhub::local_check_linux()` and I got this error :
```
Cannot load the sysreqs package :(  Install it with
R -q -e "source('https://install-github.me/r-hub/sysreqs')"
```
Thus, I run this line of code in the Terminal and got this message
```
> source('https://install-github.me/r-hub/sysreqs')
The install-github.me service is deprecated, please stop using it.
```

Also, I had to install it as `sudo` user, but this may be specific to my Ubuntu installation.

**Comment by gaborcsardi** [comment]
You can ignore that message, it does not mean that the package was not installed.
