### ISSUE TITLE
Mail says PREPERROR but build log says SUCCESS

### ISSUE THREAD

**Issue by baktoft** [r-hub/rhub#445]
First off, thanks for this awesome tool!
However, I am getting mixed signals on some of my runs. As subject indicates, I get different results for the same build in mail vs build log. See images below. 
Full build log available here: https://builder.r-hub.io/status/yaps_1.2.2.9003.tar.gz-e8f306bd41a24d90a1921d46ff0c8d48

Any advice will be highly appreciated.
Thanks,
\hb

![image](https://user-images.githubusercontent.com/22369824/105827025-c26a3800-5fc1-11eb-9bcf-8f31b16dd51c.png)

![image](https://user-images.githubusercontent.com/22369824/105827079-d31aae00-5fc1-11eb-92da-68a76108f2ed.png)

**Comment by gaborcsardi** [comment]
Yes, that is misleading indeed. PREPERROR means that R-hub could not run the tests, probably because some dependency failed to install. Look at the detailed logs to see what exactly happened.

**Comment by baktoft** [comment]
Indeed it seems to be missing 'devtools' and 'xml2' for installing 'vdiffr'. 
![image](https://user-images.githubusercontent.com/22369824/105830590-f9dae380-5fc5-11eb-9876-b46e72219af0.png)

I have 'vdiffr' in DESCRIPTION Suggests and use `if(requireNamespace("vdiffr", quietly = TRUE)){ ...tests...}` for these particular tests. Furthermore, I am using `rhub::check_for_cran(env_vars = c('_R_CHECK_FORCE_SUGGESTS_' = "false"))` when checking on r-hub. 

Is there anything I can do to fix this?

**Comment by gaborcsardi** [comment]
Check in the log why they failed to install.

**Comment by gaborcsardi** [comment]
Yeah, xml2 does not compile, I am not sure why.

**Comment by baktoft** [comment]
It seems to boil down to `xml2` failing to install.
![image](https://user-images.githubusercontent.com/22369824/105832855-b6ce3f80-5fc8-11eb-8996-3f2321498e26.png)

Additionally, `devtools` report missing dependencies `roxygen2` and `rversions` - both of these in turn depends on `xml2`.

**Comment by gaborcsardi** [comment]
In any case, this container is somewhat old, so let me try to update it.

**Comment by baktoft** [comment]
Thanks! While you are at it, `rhub/ubuntu-gcc-release` seems to need an update too. On this, `xml2` and `openssl` fails to install.

**Comment by TNonet** [comment]
Hi,

I seem to be facing a very similar issue. 

I submitted a "rhub::check_with_sanitizers()" test to rhub this morning.
After a few minutes, I received this in an email, but the logs (https://builder.r-hub.io/status/L0Learn_2.0.2.tar.gz-d7ff3723487940dfa2a77d0bbdb1d6b7) say "success".

![image](https://user-images.githubusercontent.com/30328457/112390279-0a58c300-8cc4-11eb-8b61-f472992e7fa9.png)

However, when I search for "error" in this log file (to see if there is a dependency issue), the only errors seem to be at the end when rhub/docker is attempting to remove files.

If anyone has any advice or insights into this issue, it would be greatly appreciated.

A wonderful tool!

**Comment by gaborcsardi** [comment]
@TNonet your issue is the same as #448 I think, and it is indeed a bug.

**Comment by SimonDedman** [comment]
Throwing a +1 on the pile:
![image](https://github.com/r-hub/rhub/assets/4599748/615a8e88-9c66-4bd0-9845-e075e96208f3)

Build success and [only 1 match to "ERROR" during find-in-page](https://builder.r-hub.io/status/movegroup_2024.02.01.tar.gz-53144fd3982b47f991a944ac83c50dbc), 

> L1060: echo R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
