### ISSUE TITLE
Sorting data

### ISSUE THREAD

**Issue by Financebro1** [r-hub/rhub#446]
I have some data from robinhood and yahoo finance that i would like to sort. I would like to add the endofday column to my yahoo data. Any tips on how to do this?. Here is my code so far.

library(tidyverse)
library(lubridate)
library(tidyquant)

# Vector with names of all unpacked files
# Set an address of a directory with unpacked csv files (1st parameter)
lof <- list.files("robintrack-popularity-history/tmp/popularity_export", full.names = TRUE)

# This function reads and transforms one file
read_data <- function(file){
  
  # get stock name from the name of the file
  stock <- file %>% 
    str_split("/") %>% 
    unlist() %>% 
    last() %>% 
    str_remove(".csv")
  
  read_csv(file,
           col_types = "Td"
           ) %>% 
    mutate(
      date = date(timestamp)
    ) %>% 
    arrange(timestamp) %>% 
    group_by(date) %>% 
    drop_na() %>% 
    summarise(
      endofday = last(users_holding),
      meanday = mean(users_holding)
    ) %>% 
    mutate(
      stock = stock
    )
}

robinhood <- lof %>% 
  map_dfr(read_data)

# Explicit NAs
robinhood <- robinhood %>% 
  complete(date,stock) %>% 
  arrange(stock,date)

save(robinhood, file = "robinhood.RData")

#####################################
# Add data from Yahoo

library(tidyquant)

date_range <- robinhood$date %>% 
  range()

get_yahoo <- function(ss, dr = date_range){
  q <- getSymbols(ss, 
                  from = as.character(dr[1]),
                  to = as.character(dr[2]),
                  warnings = FALSE,
                  auto.assign = FALSE,
                  return.class = "xts")
  
  time_q <- time(q)
  
  q <- q %>% as_tibble()
  
  names(q) <- names(q) %>% 
    str_split("\\.") %>% 
    map_chr(function(x) x[2])
  
  q %>% 
    mutate(
      stock = ss,
      date = time_q
    )
}

get_yahoo_safely <- safely(get_yahoo)

yahoo <- robinhood %>% 
  distinct(stock) %>% 
  pull(stock) %>%
  map(get_yahoo_safely) %>% 
  map_dfr(function(x) x$result)

data_ry <- robinhood %>% 
  left_join(.,yahoo)

save(data_ry, file = "data_ry.RData")

# Yahoo finance data

aapl1 <- tq_get(c('TXMD','NRZ','BABA','AMZN','MSFT','GOOGL','ZNGA','GM','NKE','FB','V','SNE','PYPL',
                  'CRM','AZN','NVDA','DIS','ET','WMT','APHA','PLUG','AAPL','GE','SNAP','NFLX',
                  'SPCE','KO','JNJ','LUV','SIRI','BAC','PENN','AMD','WKHS','SQ',
                  'SAVE','BA','DAL','SBUX','NOK','MRO','UAL','INTC','KOS','XOM',
                  'TWTR','PFE','RCL','MFA','JBLU','NCLH','TSLA','T','INO',
                  'CRON','F','CGC','GPRO','FCEL','BB','MGM',
                  'ACB','CCL','AAL','AMC','GME','NAKD','ZOM','IDEX','GNUS',
                  'VOO','SPY','PSEC','ARKK','NNDM','CPRX','IVR','BLNK','SLV',
                  
                  'GEVO','GUSH'),
               from = "2017-01-01",
               to = "2018-03-01",get = "stock.prices")

**Comment by gaborcsardi** [comment]
This does not seem to be related to the rhub package. For general R or tidyverse questions see the R-help mailing list or the RStudio community forum at https://community.rstudio.com/
