### ISSUE TITLE
Unable to install package 'sf' by missing of `proj_api.h`

### ISSUE THREAD

**Issue by gaospecial** [r-hub/rhub#447]
```
2040#> checking proj.h usability... no
2041#> checking proj.h presence... no
2042#> checking for proj.h... no
2043#> checking proj_api.h usability... no
2044#> checking proj_api.h presence... no
2045#> checking for proj_api.h... no
2046#> configure: error: proj_api.h not found in standard or given locations.
2047#> ERROR: configuration failed for package ‘sf’
2048#> * removing ‘/home/docker/R/sf’
```

the complete log is at: https://builder.r-hub.io/status/ggVennDiagram_0.5.tar.gz-eed521c19322493ba8567cd1d20b917a  

The error only found in **Fedora Linux, R-devel, clang, gfortran**, but not in **Windows Server 2008 R2 SP1, R-devel, 32/64 bit** or **Ubuntu Linux 20.04.1 LTS, R-release, GCC**.

**Comment by WayneGitShell** [comment]
I'm facing the same issue here as well trying to release "GWSDAT" package which imports "sf". 
https://builder.r-hub.io/status/GWSDAT_3.0.6.tar.gz-1afd2ea7540d463e8d1d62bc33df3e0d 

@gaospecial  - have you received any updates on this issue?

**Comment by gaospecial** [comment]
> I'm facing the same issue here as well trying to release "GWSDAT" package which imports "sf".
> https://builder.r-hub.io/status/GWSDAT_3.0.6.tar.gz-1afd2ea7540d463e8d1d62bc33df3e0d
> 
> @gaospecial - have you received any updates on this issue?

not yet. I guess it depends on the server configuration and must be fixed in server side.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
