### ISSUE TITLE
Package dependency ERROR only on Windows Server R-devel

### ISSUE THREAD

**Issue by YajnaC** [r-hub/rhub#449]
Hi,
I ran a rhub::check_for_cran() for my package, and I keep getting this error for 'utf8' package dependency on platform Windows Server 2008 R2 SP1, R-devel, 32/64 [bit.](https://builder.r-hub.io/status/tvmediation_1.0.0.tar.gz-5a2596d27da2f71c765c142af3c82961)

***** checking package dependencies ... ERROR
Package required but not available: 'utf8.'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.****

I looked through the log file and it says:
 292#> Package which is only available in source form, and may need
 293#> compilation of C/C++/Fortran: 'utf8'
 294#> These will not be installed

I am using ggplot2, which has a dependency on utf8. I tried adding utf8 as a required package in the DESCRIPTION file and keep getting the same error.

The package check is successful on Debian Linux, R-devel, GCC, and Debian Linux, R-devel, clang, ISO-8859-15 locale. On Fedora and UBUNTU, the check gives a minor note of new submission. Initial R CMD check using devtools renders 0 notes, warnings, and errors.

How can I resolve this? Appreciate your help
![Windows_error](https://user-images.githubusercontent.com/54639743/109404193-ad225980-7931-11eb-8893-f9a10e81ac9e.jpg)
.

Best,
Yajna

**Comment by gaborcsardi** [comment]
utf8 has no windows binary for R-devel: https://cran.rstudio.com/web/packages/utf8/

solution: https://github.com/r-hub/rhub/issues/367#issuecomment-621700118

**Comment by gaborcsardi** [comment]
Also, this is an `install.packages()` bug, so you can report it to R core if you want.

**Comment by YajnaC** [comment]
Thank you!
