### ISSUE TITLE
Macos unknown platform

### ISSUE THREAD

**Issue by elinw** [r-hub/rhub#450]
I think this maybe a new version of #368 .

 Maybe the shortcut has changed again? I'm not sure how to tell if that's the case.

**Comment by kingaa** [comment]
Yes, this is still a problem.
```
> library(rhub)
> check_on_macos()
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
> rhub:::check_shortcut_platforms$macos
[1] "macos-elcapitan-release"
> platforms()
...
macos-highsierra-release:
  macOS 10.13.6 High Sierra, R-release, brew
macos-highsierra-release-cran:
  macOS 10.13.6 High Sierra, R-release, CRAN's setup
...
```

**Comment by ColinFay** [comment]
Having this very same issue right now too.

**Comment by gaborcsardi** [comment]
The workaround is to select a platform manually.

**Comment by gaborcsardi** [comment]
R-hub does not have macOS machines now, you can try GitHub Actions, or https://github.com/r-hub/rhub2.

**Comment by micha-silver** [comment]
Thanks
