### ISSUE TITLE
ERROR: compilation failed for package ‘OpenMx’

### ISSUE THREAD

**Issue by NicholasDanks** [r-hub/rhub#452]
On the Oracle Solaris 10, x86, 32 bit, R-release (solaris-x86-patched) build, the OpenMX package is failing to build: 

```#> dV_dtheta2P = dV_dtheta2.selfadjointView() * _P;

14416#> ^

14417#> omxGREMLfitfunction.cpp:1272:26: error: ‘_Scale’ was not declared in this scope

14418#> infoMat(hrn,hcn) = _Scale*0.5*tr2 + _Scale*pullAugVal(2,a1,a2);

14419#> ^

14420#> gmake: *** [/opt/csw/lib/R/etc/Makeconf:181: omxGREMLfitfunction.o] Error 1

14421#> ERROR: compilation failed for package ‘OpenMx’
```

The repercussions of which are that packages rsvg and semPlot cannot load.

**Comment by gaborcsardi** [comment]
I am not not sure you think this is a bug in the R-hub config? Is seems that this code just does not work on this platform. This is also what CRAN sees: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/OpenMx-00install.html

**Comment by NicholasDanks** [comment]
Thanks. I will close the issue.
