### ISSUE TITLE
Latex errors when using rhub::check_for_cran()

### ISSUE THREAD

**Issue by LisaGotzian** [r-hub/rhub#453]
Hi all,

we're using your package to check our package before submitting it to CRAN. While we love the functionality, we'd like to report a bug, proposably in regards to the Latex installation on your server.
When I'm checking the package, there's an error when generating the Latex manual, for windows as in the screenshot, for Ubuntu and Fedora as well.
<img width="553" alt="Screen Shot 2021-03-28 at 17 12 16" src="https://user-images.githubusercontent.com/39851567/112757143-c11cb200-8fe8-11eb-9316-13cc741d0962.png">

```
* checking PDF version of manual without hyperrefs or index ... ERROR
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...   
* checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  ‘scicloud-manual.tex’                                 
```          

Our research suggests that this is due to missing fonts (probably) as described in this question on stackoverflow, probably 
- `inconsolata.sty` and
- `upquote.sty`

https://stackoverflow.com/questions/10819959/diagnosing-r-package-build-warning-latex-errors-when-creating-pdf-version 

We are fairly sure this is not due to an error on our side, and we've investigated this error in depth. 😅

**Comment by gaborcsardi** [comment]
> We are fairly sure this is not due to an error on our side, and we've investigated this error in depth. 😅

The machine has a full LaTeX installation and it does have these files. The message

> ! LaTeX Error: There's no line here to end.

certainly does not seem like an error that is because of a missing `inconsolata.sty` or `upquote.sty`. that would look like 

```
! LaTeX Error: File `xy.sty' not found
```

I also get the very same error on macOS for your package.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
