### ISSUE TITLE
check_on_centos() broken

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rhub#455]
```
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
```

Do you support CentOS 7 on rhub? Any plans to do so? I think this would be interesting because the platform is rather ... mature.

**Comment by gaborcsardi** [comment]
Yeah, hard coding the platform names in these helper functions was not a good idea. 

Considering the CentOS 7 EOL is 2024 and CentOS 8 EOL is 2021, it indeed makes sense to a CentOS 7 container. 

OTOH it is a pain in the neck that many system reqs are so old, that a lot of packages do not build on it.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
