### ISSUE TITLE
Cannot install httr - missing openssl

### ISSUE THREAD

**Issue by cb4ds** [r-hub/rhub#456]
I'm receiving failed builds because biomaRt cannot be installed without httr which is missing the required openssl library.  It seems this system library went missing sometime yesterday (4/7) on all three servers used for CRAN checking (linux, fedora, win).  

Example failed build log:

https://builder.r-hub.io/status/DGEobj_1.0.2.9004.tar.gz-0193f94363544cd798b8d8bc1a55fe8f
4280#> ERROR: dependency ‘openssl’ is not available for package ‘httr’

**Comment by cb4ds** [comment]
Seems to be resolved this morning, closing.  It would be excellent if there were a place to see when the underlying builds are updated to know if this is correlated with work going on in the backend!

**Comment by gaborcsardi** [comment]
There is no missing openssl here, the check actually started and failed in the vignette, see below. 

```
1375#> * checking for unstated dependencies in 'tests' ... OK
1376#> * checking tests ...
1377#> Running 'testthat.R'
1378#> OK
1379#> * checking for unstated dependencies in vignettes ... OK
1380#> * checking package vignettes in 'inst/doc' ... OK
1381#> * checking re-building of vignette outputs ... WARNING
1382#> Error(s) in re-building vignettes:
1383#> --- re-building 'DGEobj_Overview.Rmd' using rmarkdown
1384#> trying URL 'http://ftp.ncbi.nlm.nih.gov/geo/series/GSE120nnn/GSE120804/suppl/GSE120804_counts.txt.gz'
1385#> Content type 'application/x-gzip' length 1886996 bytes (1.8 MB)
1386#> ==================================================
1387#> downloaded 1.8 MB
1388#> trying URL 'http://ftp.ncbi.nlm.nih.gov/geo/series/GSE120nnn/GSE120804/suppl/GSE120804_geo_sample_annotation_edit.csv.gz'
```

**Comment by cb4ds** [comment]
Thanks, I was seeing errors yesterday with openssl and libxml2, seems to be resolved today.  Apologies for the spurious issue.

**Comment by cb4ds** [comment]
@gaborcsardi I'm still finding some builds can't install biomaRt because of openssl - this seems to now only be happening on the Ubuntu Linux 20.04.1 LTS, R-release, GCC build:

#> --------------------------- [ANTICONF] --------------------------------
4067#> Configuration failed because openssl was not found. Try installing:
4068#> * deb: libssl-dev (Debian, Ubuntu, etc)
4069#> * rpm: openssl-devel (Fedora, CentOS, RHEL)
4070#> * csw: libssl_dev (Solaris)
4071#> * brew: openssl@1.1 (Mac OSX)
4072#> If openssl is already installed, check that 'pkg-config' is in your
4073#> PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
4074#> is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
4075#> R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
4076#> -------------------------- [ERROR MESSAGE] ---------------------------
4077#> tools/version.c:1:10: fatal error: openssl/opensslv.h: No such file or directory
4078#> 1 | #include
4079#> | ^~~~~~~~~~~~~~~~~~~~
4080#> compilation terminated.

https://builder.r-hub.io/status/DGEobj_1.0.2.9005.tar.gz-c24394cc2a77415eaa5a4ab3eb29cdc8

**Comment by cb4ds** [comment]
Same just now on Fedora Linux:
https://builder.r-hub.io/status/DGEobj_1.0.2.9005.tar.gz-68f80f3e642849bf9b6c0fce63987370

**Comment by gaborcsardi** [comment]
System requirements of Bioconductor packages are not currently supported. But I added an exception for biomaRt, so hopefully it works now: https://github.com/r-hub/sysreqsdb/blob/master/cran/biomaRt.json

**Comment by cb4ds** [comment]
Thanks, I'll try again!

**Comment by cb4ds** [comment]
Thanks so much, appreciate the exception.  Builds for CRAN are working as expected again :-)  Have a wonderful day @gaborcsardi

**Comment by gbrsales** [comment]
I believe I'm hitting the same error again:

> ERROR: dependency ‘openssl’ is not available for package ‘httr’

Full log here: <https://builder.r-hub.io/status/topologyGSA_1.4.8.tar.gz-f6939f9fc887422aba497ae190b663e5>
