### ISSUE TITLE
Check fails on Fedora Linux, R-devel because ‘rasterVis’ is not available

### ISSUE THREAD

**Issue by sjmgarnier** [r-hub/rhub#458]
When checking a package with Fedora Linux, R-devel that depends on `rasterVis`, I receive the following error:

> `* checking package dependencies ... ERROR
> 
> Package suggested but not available: ‘rasterVis’`

According to the CRAN package check results for `rasterVis`, there is no reason why that package should not be available on R-devel for Fedora (all checks passing). It is not a big issue, I just wanted to signal it.

**Comment by gaborcsardi** [comment]
Look at your log to see why rasterVis failed to install.

**Comment by sjmgarnier** [comment]
`ERROR: dependency ‘terra’ is not available for package ‘rasterVis’`

**Comment by gaborcsardi** [comment]
Sure, but `terra` also failed to install for some reason, look more up in the log.

**Comment by sjmgarnier** [comment]
````
#> configure: GDAL: 3.1.4 
#> configure: pkg-config proj exists, will use it
#> configure: using proj.h.
#> configure: PROJ: 6.3.2
#> checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
#> configure: error: libproj not found in standard or given locations.
#> ERROR: configuration failed for package ‘terra’
#> * removing ‘/home/docker/R/terra’
````

**Comment by gaborcsardi** [comment]
`proj-devel` should be automatically installed: https://sysreqs.r-hub.io/pkg/terra
See the log why it was not.

**Comment by sjmgarnier** [comment]
I see no error related to `proj-devel`. It is listed in the `#> Installed:` section of the log. 

Doing a search for the word "error" returns the following problems (in addition to those mention above): 

````
#> checking PROJ version >= 4.8.0... yes
#> /usr/bin/ld: cannot find -lsqlite3
#> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
#> ./configure: line 3259: ./proj_conf_test2: No such file or directory
````

````
#> * installing *source* package ‘htmlwidgets’ ...
#> ** package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
#> ** using staged installation
#> ** R
#> ** inst
#> ** byte-compile and prepare package for lazy loading
#> 'getOption("repos")' replaces Bioconductor standard repositories, see
#> '?repositories' for details
#> replacement repositories:
#> CRAN: https://cloud.r-project.org
#> Failed with error: ‘there is no package called ‘shiny’’
````

**Comment by gaborcsardi** [comment]
Apparently, on Fedora `proj-devel` needs `sqlite-devel`: https://github.com/r-hub/sysreqsdb/commit/09905d23255aa75229b7e1896668e8bedf4263c1

So this should work now.

**Comment by sjmgarnier** [comment]
@gaborcsardi It wouldn't be fun if all systems worked the same way :-) 

Testing now.

**Comment by sjmgarnier** [comment]
Looks like it's working indeed.
