### ISSUE TITLE
I've used devtools::check_rhub() successfully for this package but now I'm getting an error

### ISSUE THREAD

**Issue by wkostelecki** [r-hub/rhub#459]
See error below using devtools 2.4.0:

> devtools::check_rhub()
√  checking for file 'C:\Users\wkost\Documents\GitHub\visa-chart-components\packages\charts-R/DESCRIPTION' ...
-  preparing 'visachartR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'visachartR_1.0.2.tar.gz'
   
-  Uploading package
Error in query("SUBMIT PACKAGE", data = list(email = unbox(email), token = unbox(email_get_token(email)),  : 
  Email address not validated

**Comment by gaborcsardi** [comment]
You need to validate your email address. Please see the docs.

**Comment by wkostelecki** [comment]
I validated the email address already once and was able to use check_rhub() successfully about a week ago.
I ran `rhub::validate_email("email address", "token from email")` now but I'm still seeing the same error after trying again.

**Comment by gaborcsardi** [comment]
Only the latest token is valid, maybe you are using an older one. `rhub::list_validated_emails()` lists all validated emails on your computer. Make sure that you are the maintainer of the package, or supply the `email` argument to `rhub::check()`. 

To help more, you would need to show me what you are doing, e.g. the repo of the package and the exact output you get.

**Comment by gaborcsardi** [comment]
It might be an error on our end, investigating...

**Comment by gaborcsardi** [comment]
I thought you might have seen this issue: https://github.com/r-hub/rhub/issues/334#issuecomment-821109956

But it does not seem so. Do you still have problems? Can you run 

```
rhub::list_my_checks()
```
?

**Comment by wkostelecki** [comment]
I'm still getting the same error with `devtools::check_rhub(email = "email1@gmail.com")`
It just gives me the error immediately (is it supposed to email a new token?).

It looks like the email is validated (green tick next to it when running `rhub::validate_email()`

I tried `devtools::check_rhub(email = "email2@gmail.com")` using another email (which I had validated from maybe a few years ago) and that worked fine.

`list_my_checks(email = "email2@gmail.com")` works for email2 but using the first email, I get this error:
```
> rhub::list_my_checks(email = "email1@gmail.com")
Error in query("LIST BUILDS EMAIL", params = list(email = email, token = email_get_token(email))) : 
  Email address not validated
```

Anyway, I'm running these checks on behalf of the package maintainer (and before realising that `check_rhub()` has an email argument) so I'm happy to proceed using the second/working email going forward.

I'm guessing that going through the steps in `rhub::validate_email()` would have solved my problem though.

**Comment by wkostelecki** [comment]
Anyway, thanks for checking -- rhub is such a useful service!

**Comment by gaborcsardi** [comment]
Yes, email2 is validated, email1 is not, so you could just validate it. Or keep using email2.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
