### ISSUE TITLE
windows-x86_64-oldrel: qpdf is missing

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#46]
The `qpdf` software is missing from:
- Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit (windows-x86_64-oldrel)

resulting in the following WARNING:

```
* checking for unstated dependencies in examples ... OK
 WARNING
'qpdf' is needed for checks on size reduction of PDFs
```

Example: https://builder.r-hub.io/status/doFuture_0.2.1-9000.tar.gz-268be624dcf84854a35aa0f7ccafd2f0

I've also check the other Windows versions and they do _not_ have this problem:
- Windows Server 2008 R2 SP1, R-devel, 32/64 bit (windows-x86_64-devel)
- Windows Server 2008 R2 SP1, R-patched, 32/64 bit (windows-x86_64-patched)
- Windows Server 2008 R2 SP1, R-release, 32/64 bit (windows-x86_64-release)

**Comment by gaborcsardi** [comment]
Thanks! Will add. I think it is actually missing for all (builder machine is the same), but the checks are different for different R versions.

**Comment by gaborcsardi** [comment]
Fixed now.
