### ISSUE TITLE
Feature request, email validated in multiple computers

### ISSUE THREAD

**Issue by llrs** [r-hub/rhub#463]
I've been using the same email on CRAN and r-hub for work and personal projects so I use rhub on both my laptop and the computer work. I understand from #459  and https://github.com/r-hub/rhub/issues/334#issuecomment-579821398 that there is no way to have the same email validated on two different computers.

How could I save the same token on two computers? Otherwise I keep having to validate each time I want to use r-hub and have switched between work and other projects.

**Comment by gaborcsardi** [comment]
You can use the same token, look it up on one computer, and then supply it to `rhub::validate_email()` on the other computer. The tokens are only tied to email addresses, not computers.

**Comment by llrs** [comment]
Great many thanks!
