### ISSUE TITLE
Test logs not collected in ASAN build

### ISSUE THREAD

**Issue by david-cortes** [r-hub/rhub#468]
I tried uploading a package to check with `Debian Linux, R-devel, GCC ASAN/UBSAN`:
https://builder.r-hub.io/status/MatrixExtra_0.1.3.tar.gz-87a36c9c6d7e6fcfd5a9245e81328a4d

The package checks correctly, but the artifacts from `tests/` are not collected:
https://artifacts.r-hub.io/MatrixExtra_0.1.3.tar.gz-87a36c9c6d7e6fcfd5a9245e81328a4d

At some point in the logs for `Saving artifacts` I see this:
```
2885docker rm MatrixExtra_0.1.3.tar.gz-87a36c9c6d7e6fcfd5a9245e81328a4d-3

2886#> Error: No such container: MatrixExtra_0.1.3.tar.gz-87a36c9c6d7e6fcfd5a9245e81328a4d-3
```

**Comment by gaborcsardi** [comment]
This builder does not run `R CMD check`, so there is no check directory. The output from the sanitizer goes to the screen, and it seems that for your build there was no output.
