### ISSUE TITLE
installation of package 'stringi' had non-zero exit status

### ISSUE THREAD

**Issue by xiayh17** [r-hub/rhub#470]
Hi,

My package have checked by 

```
rhub::check_for_cran()
```
The result seems ok
https://builder.r-hub.io/status/AnnoProbe_0.1.1.tar.gz-94038f22805843e4bbc8f5b6b9dbb6cf
![image](https://user-images.githubusercontent.com/17431830/118645236-3e0e2000-b811-11eb-8469-ca1f79316296.png)

And

```
devtools::check_win_devel()
```
Look good too.
https://win-builder.r-project.org/cYMDL1QLHJ79/00check.log
![image](https://user-images.githubusercontent.com/17431830/118645285-4f572c80-b811-11eb-965a-bd55136af9b4.png)

But CRAN report that an ERROR in My package,
I check my package in the same platform

```
rhub::check_for_cran(
          platform="windows-x86_64-devel",
          env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
        )
```

I get the same ERROR here
https://builder.r-hub.io/status/AnnoProbe_0.1.1.tar.gz-ec1069c7f6414a8fb616f05214596650
![image](https://user-images.githubusercontent.com/17431830/118644701-a8729080-b810-11eb-8b41-278d77829056.png)

Many Thanks !

**Comment by gaborcsardi** [comment]
Thanks, should be fixed.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
