### ISSUE TITLE
Bioconductor does not yet build and check packages for R version 4.2

### ISSUE THREAD

**Issue by buehlere** [r-hub/rhub#471]
When building for Windows Server 2008 R2 SP1, R-devel, we get a strange error about Bioconductor not yet building for R version 4.2. This seems to be be an issue with setting up the container for testing rather than building our package. Any ideas what might might be happening? Please let me know if there is any other information I can provide! 

- error: `Error: Bioconductor does not yet build and check packages for R version 4.2; see
  https://bioconductor.org/install
Execution halted` 
- text-link: https://builder.r-hub.io/status/original/wCorr_1.9.0.tar.gz-e610d895ffc773f6b07e15a9c54d69c7

Thanks for the help!

**Comment by jasonmoy28** [comment]
Same issue

**Comment by rafzamb** [comment]
Same issue

**Comment by xiayh17** [comment]
Same issue

**Comment by ilyakorsunsky** [comment]
Same Issue

**Comment by glgrabow** [comment]
ditto....

**Comment by ncchung** [comment]
I encountered this issue too on rhub.
Relatedly, you can't install any bioconductor packages on r-devel (currently, 4.2)

**Comment by SandraCastroPearson** [comment]
Same issue.

**Comment by palmjulia** [comment]
Same here.

**Comment by ycphs** [comment]
Same here

**Comment by ksurana21** [comment]
Same issue. Any one found a solution?

**Comment by ablack3** [comment]
Same issue.

**Comment by nanhung** [comment]
Can I submit the package to CRAN with this error?

**Comment by gorkang** [comment]
> Can I submit the package to CRAN with this error?

I think you do. I submitted a package without issues despite this error.

**Comment by SandraCastroPearson** [comment]
I think it should work. I submitted my package and it's on CRAN now. Not sure if this will change in the future.

**Comment by pachoning** [comment]
Same issue

**Comment by JiscaH** [comment]
Same issue, now for R version 4.3

**Comment by georgiosseitidis** [comment]
Same  issue, for R version 4.3

**Comment by fritzbayer** [comment]
Same issue nor for R version 4.3. Given the amount of people reporting this issue here, they should be aware of it. 
Hence, I will submit regardless.

**Comment by glgrabow** [comment]
This issue will not nullify a submission. I have just ignored it.

**Comment by gaborcsardi** [comment]
This is a warning that you can ignore, it is coming from another package that we use to install Bioconductor packages. Hopefully we can improve this in the future.
