### ISSUE TITLE
Cannot check package on MacOs

### ISSUE THREAD

**Issue by pakjiddat** [r-hub/rhub#472]
I ran the command:

`devtools::check_rhub(platforms = c("macos-highsierra-release"))`

And got the following error:

```
checking CRAN incoming feasibility ...Error in aspell(files, filter = list("dcf", ignore = ignore), control = control,  : 
  No suitable spell-checker program found
Execution halted
```
I got an email reporting that there were no errors. But the log file showed that the package check did not complete. Also the package tests cases were not run. Here is a [link](https://builder.r-hub.io/status/original/wordpredictor_1.0.0.tar.gz-bc9763caef3d4027bd7a43c4e9795372) to the log file:

**Comment by tbates** [comment]
same here (see line 955(

```
Running R CMD check

 942#> 'getOption("repos")' replaces Bioconductor standard repositories, see
 943#> '?repositories' for details
 944#> replacement repositories:
 945#> CRAN: https://cloud.r-project.org
 946#> * using log directory ‘/Users/userYbIZP4my/umx.Rcheck’
 947#> * using R version 4.1.0 (2021-05-18)
 948#> * using platform: x86_64-apple-darwin17.0 (64-bit)
 949#> * using session charset: UTF-8
 950#> * using option ‘--as-cran’
 951#> * checking for file ‘umx/DESCRIPTION’ ... OK
 952#> * this is package ‘umx’ version ‘4.9.0’
 953#> * package encoding: UTF-8
 954#> * checking CRAN incoming feasibility ...Error in aspell(files, filter = list("dcf", ignore = ignore), control = control, :
 955#> No suitable spell-checker program found
 956#> Execution halted
```

Which then reports as "success" in the mailed report :-(

> umx 4.9.0: OK

**Comment by pakjiddat** [comment]
I added a build argument to the check_rhub command for excluding the spell check. The check completed without problems. But the spell checking was disabled. I used the following command:

`devtools::check_rhub(platforms = c("macos-highsierra-release"), env_vars = c(`_R_CHECK_FORCE_SUGGESTS_` = "true", `_R_CHECK_CRAN_INCOMING_USE_ASPELL_` = "false"))`

**Comment by matthieu-bruneaux** [comment]
I encountered the same issue when running `rhub::check_for_cran(platform = "macos-highsierra-release")` for a package currently in development (https://gitlab.com/matthieu-bruneaux/isotracer).

The R CMD check seems to halt because no suitable spell-checker program was found, but the check report says "success". As mentioned in the comments above, disabling spell checking might be a solution to complete the R CMD check. However, I think the main issue is that the mailed report just mentions "success" so the fact that the R CMD check did not complete remains unknown to any user who relies on the mailed report and does not manually check the logs.

This is the output accessible at https://builder.r-hub.io/status/isotracer_0.7.6.9000.tar.gz-b0c03ff5f83046898fd5a98fee78b05e:
```
============== Running R CMD check
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org

* using log directory ‘/Users/useruHcd4HOJ/isotracer.Rcheck’
* using R version 4.1.0 (2021-05-18)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘isotracer/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘isotracer’ version ‘0.7.6.9000’
* package encoding: UTF-8
* checking CRAN incoming feasibility ...Error in aspell(files, filter = list("dcf", ignore = ignore), control = control,  : 
  No suitable spell-checker program found
Execution halted
Saving artifacts
Cleaning up user and home directory
SSH: Connecting from host [R-hubs-Mac-2.local]
SSH: Connecting with configuration [files] ...
SSH: Disconnecting configuration [files] ...
SSH: Transferred 3 file(s)
Build step 'Send files or execute commands over SSH' changed build result to SUCCESS
Pinging https://builder.r-hub.io/build/SUCCESS/isotracer_0.7.6.9000.tar.gz-b0c03ff5f83046898fd5a98fee78b05e/2021-08-02T11:54:53Z
{"status":"ok"}
Finished: SUCCESS
```

**Comment by datawookie** [comment]
@gaborcsardi would you like me to take a look at this issue?

**Comment by gaborcsardi** [comment]
I think `devtools::check_rhub()` adds `--as-cran` to `R CMD check`, but is never used on CRAN macOS machines I believe. You can use 
```r
rhub::check(platform = c("macos-highsierra-release"))
```
instead.

**Comment by datawookie** [comment]
Cool! Thanks, I'll check that out @gaborcsardi and let you know! :+1:
