### ISSUE TITLE
libsbml installation request

### ISSUE THREAD

**Issue by sn248** [r-hub/rhub#475]
My package `r2sbml` (https://github.com/sn248/r2sbml) requires `libsbml` to be installed for compilation. 

Could I request `libsbml` be installed on r-hub machines? For windows, Jeroen has kindly provided the static libs (https://github.com/rwinlib/libsbml), which let's me test using CRAN's windows builder so I am all set for windows.

Thanks!
Satya

**Comment by gaborcsardi** [comment]
Should work on Linux now, please try.

**Comment by sn248** [comment]
Thank you!
