### ISSUE TITLE
Cannot link to 'float' package on Windows

### ISSUE THREAD

**Issue by david-cortes** [r-hub/rhub#477]
I've been trying to check some packages in the Windows build (Windows Server 2008 R2 SP1, R-devel, 32/64 bit) which link to the `float` package: https://github.com/wrathematics/float

(This is a dynamic-link library which basically provides float versions of BLAS and LAPACK)

For some reason, it seems in R-Hub this package compiles as a dependency, but then the package being checked (which links to `float`) doesn't find the generated DLL:
https://builder.r-hub.io/status/recometrics_0.1.0.tar.gz-42b09ada83cc519325d8351406fb32b3
https://builder.r-hub.io/status/MatrixExtra_0.1.6.tar.gz-ca66f1565e3f2ff0b3362cfef0cdf6b5

For comparison, this is the winbuilder log - it does not show any DLL-related error:
https://win-builder.r-project.org/9R4oGclN3811/

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
