### ISSUE TITLE
routine PREPERRORs on Linux platforms

### ISSUE THREAD

**Issue by bbolker** [r-hub/rhub#478]
I've been doing a lot of testing of the [glmmTMB package](https://github.com/glmmTMB/glmmTMB) on r-hub. Everything is working fine, except ... it routinely (always?) is returning PREPERROR status for the Linux platforms we've tried (the standard CRAN-check platforms: Ubuntu/R-release, Fedora/R-devel, Debian/R-devel/UBSAN), despite the fact that the checks *seem* to complete OK.  I can always go and dig through the output to see what happened, but it would be more convenient if the returned-status e-mails listed NOTE rather than PREPERROR (as occurs for the Windows checks).

Here's an example (Fedora/r-devel): https://builder.r-hub.io/status/glmmTMB_1.1.2.tar.gz-48d632cc90914f819081e0703e864b30

Is there a reason why this is happening/way to work around it? It may be clear from the output for someone who knows what they're looking at, but searching through nearly 22K lines of logs without an idea what I'm looking for is a little daunting ...

**Comment by gaborcsardi** [comment]
I think this is probably #448.

**Comment by bbolker** [comment]
thanks, sorry I didn't find that one.
