### ISSUE TITLE
WISH: Add link to artifacts on build page

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#479]
Please consider linking to the artifacts from the build page, e.g. 
link to https://artifacts.r-hub.io/sparrpowR_0.2.2.tar.gz-1f952bc90f124af48215a47bba547f93/ from somewhere on the https://builder.r-hub.io/status/sparrpowR_0.2.2.tar.gz-1f952bc90f124af48215a47bba547f93 page.

Similarly, have `rhub::check()` output the artifacts URL(s), e.g. at the very end.

**Comment by gaborcsardi** [comment]
From the command line the simplest is 
```r
rhub::last_check()$urls()$artifacts
```

**Comment by HenrikBengtsson** [comment]
Thanks, I didn't know - that's useful.

PS. I'm also thinking about the use case when someone else shares the "build page" URL (e.g. an issue tracker). Then it would be handy to if it would be easy to access the artifacts URL.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
