### ISSUE TITLE
OK announced despite test failure?

### ISSUE THREAD

**Issue by reikoch** [r-hub/rhub#48]
The output of [https://builder.r-hub.io/status/haven_1.0.0.tar.gz-47bb539018694285987de1144c436f02] looks confusing:
overall success is reported but the last line of the log reads "Finished: FAILURE".

**Comment by gaborcsardi** [comment]
Yes, seems like a bug. The status is reported correctly to the web app:
```
#> Pinging https://builder.r-hub.io/build/FAILURE/haven_1.0.0.tar.gz-47bb539018694285987de1144c436f02/2016-10-28T14:28:12Z
```
but then the web-app does sg wrong. Thanks for reporting it!

**Comment by gaborcsardi** [comment]
This is one of the rare cases when the start of `R CMD check` has been announced, but it does not start successfully.

I think it should be fixed now with https://github.com/r-hub/rhub-frontend/commit/3c98e34db84327c0c47659bc3930c533963c513f but it is hard to test....

Let me know if you have more troubles.

**Comment by reikoch** [comment]
Retested - works fine now!
