### ISSUE TITLE
check with an earlier version of an upstream package?

### ISSUE THREAD

**Issue by bbolker** [r-hub/rhub#480]
Suppose I suspect that recent release `x.y.z.new` of an upstream package `up_pkg` might have broken my package `my_pkg` on platform `P`. If I were testing locally or on a CI platform with flexible configuration I would do something like `remotes::install_version("up_pkg", version = "x.y.z.old")` after installing package dependencies, and before running checks, to confirm my suspicion.

Is there a way to achieve this, or the equivalent?

In this case `my_pkg` = glmmTMB, `up_pkg` = RcppEigen, `x.y.z.new` = 0.3.3.9.1, `x.y.z.old` = 0.3.3.7.0, `P` = "Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6"

**Comment by gaborcsardi** [comment]
Add this to your package `DESCRIPTION`:

```
Remotes: cran/RcppEigen@0.3.3.7.0
```
Btw, it is much simpler to debug Solaris issues if you have a local VM. You can get a VirtualBox or VMWare image from here: https://files.r-hub.io/solaris/ and then update R on it like it: https://github.com/r-hub/solarischeck/tree/master/packer#using-the-vm

**Comment by bbolker** [comment]
thanks!
