### ISSUE TITLE
zip not found

### ISSUE THREAD

**Issue by sjentsch** [r-hub/rhub#484]
When testing my package on r-hub, I get the following error message:

Error in utils::zip(fleNme, "data.bin", flags = "-r9Xq") : 
  argument 'zip' must be a non-empty character string

zip defaults to Sys.getenv("R_ZIPCMD", "zip")

It appears as if the string returned by Sys.env is empty on the following OSes:
Fedora Linux, R-devel, clang, gfortran
Fedora Linux, R-devel, GCC

**Comment by nunotexbsd** [comment]
@sjentsch

I'm with same problem on other R program:

```
> export(mtcars, "mtcars.tsv.zip")
Error in utils::zip(cfile2, files = basename(filename)) :
  argument 'zip' must be a non-empty character string
> Sys.getenv("R_ZIPCMD", "zip")
[1] ""
```

Any clues how to fix?
Cheers

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
