### ISSUE TITLE
Install error for 'solaris-x86-patched-ods' or 'Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6'

### ISSUE THREAD

**Issue by dchristop** [r-hub/rhub#486]
Hi there,

I am struggling with next problem:

* the r package passes all other OS checks
* it fails for 'Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6'

See next logs from 'rhub builder':

_Error: .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/opt/R/R-4.1.1/lib/R/library/tcltk/libs/tcltk.so':
  ld.so.1: R: fatal: libtcl8.3.so: open failed: No such file or directory
Execution halted_

_* using R version 4.1.1 (2021-08-10)
* using platform: i386-pc-solaris2.10 (32-bit)
* using session charset: UTF-8
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘archetypal’ can be installed ... ERROR
Installation failed._

I have found that the "tcltk" issue also exists for other cases.

Is there any resolution about it?

Thank you,

Demetris

PS My package has been removed from CRAN due to that failure last year.

**Comment by gaborcsardi** [comment]
This might be a bug on the R-hub machine. I don't know if it is possible to make tcltk work with the ODS setup. I would think yes, and will give it a try. 

Is your package in a public repo?

**Comment by dchristop** [comment]
Yes it was there:

https://cran-archive.r-project.org/web/checks/2020/2020-10-22_check_results_archetypal.html

Now it is here:

https://github.com/dchristop/archetypal

I saw that the MAC OS problem has been fixed.

Now I face the Solaris one...

Anyway, any help is welcome.

**Comment by gaborcsardi** [comment]
This seems like a different problem, and I think you can submit your package to CRAN. The tcltk error is likely an issue on the R-hub machine.

**Comment by gaborcsardi** [comment]
OK, I fixed the issue on R-hub, and you package checks clean now. THanks for the report!

**Comment by dchristop** [comment]
A great Thank You!
:)
