### ISSUE TITLE
check() hangs at "Preparing build" on Solaris (patched and patched-ods)

### ISSUE THREAD

**Issue by luco00** [r-hub/rhub#488]
Hi,
please, I am facing some problems testing my package on Solaris platforms. This is likely related to issues #150 and #435.
Basically, whenever I run the command:

```
rhub::check(platform = "solaris-x86-patched")
```

the function stops at `Preparing build, see status at`. The "wheel" is spinning, but it will idle for more than half-an-hour with no results. Checking the link provided, the web page's "Duration" and "Status" fields are empty; the page crashes after a while reporting a generic error.

I also tried to check with the `get_check` command: it provides the "Build ID", the "Platform" and "Submitted" information only.

I face the same behavior with `"solaris-x86-patched-ods"` platform, or selecting the Solaris platforms via interactive selection after running `rhub::check()`. Other platforms seems to be ok for me, and I am able to successfully run `rhub::check_for_cran()`.

I tried installing the `rhub` package both from CRAN and from GitHub (devel version), but had no luck.

(PS: In any case, thank you for the **amazing** package! It's a game changer!)

**Comment by hckiang** [comment]
I can confirm I am seeing the same problem here. Even using the web interface won't work.

**Comment by gaborcsardi** [comment]
We have a hardware issue with our macOS (intel) and Solaris builders, and we are working with the cloud provider on a fix: https://twitter.com/rhub_/status/1445779632767193090
