### ISSUE TITLE
package passes rhub platform check but fails CRAN

### ISSUE THREAD

**Issue by alyssarosemartin** [r-hub/rhub#489]
Hello,

I am trying to figure out why our package (rnpn) fails CRAN, for fedora-clang-devel ([CRAN report](https://cran-archive.r-project.org/web/checks/2021/2021-10-10_check_results_rnpn.html)) but passes `rhub::check_for_cran(platforms = "fedora-clang-devel") ` 

Report 1 - when our DEV geoserver (which the tests hit) is up: https://builder.r-hub.io/status/rnpn_1.2.2.tar.gz-c12bbc2769244eb29f57abe5d4dc8fe6

Report 2 - when our DEV geoserver is down: https://builder.r-hub.io/status/rnpn_1.2.2.tar.gz-4e3f185e0219400f9c4e9fe4a8263fdd

(it also passes `rhub::check_for_cran` with no issue)

Grateful for any suggestions/directions to try!

**Comment by gaborcsardi** [comment]
> Is there something in the report that shows you it only failed one machine? 

Click on "check results archive" at https://cran.rstudio.com/web/packages/rnpn/ It seems to me that this is the latest one.

I would skip all API tests on CRAN, and would use GitHub Actions or another CI instead.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
