### ISSUE TITLE
Ensure cmake system requirement on all platforms

### ISSUE THREAD

**Issue by astamm** [r-hub/rhub#494]
As stated in the doc, *at the moment, R-hub only uses `sysreqsdb` to install system requirements on Linux platforms. For macOS and Windows, at the moment, to ensure system requirements are installed, you might open an issue asking for its installation on the platform directly especially for commonly used third-party software*.

I would very much appreciate if CMake which is listed already in `sysreqsdb` could be installed automatically on all platforms, not only Ubuntu.

Thanks for your nice work.

**Comment by gaborcsardi** [comment]
Hi, which platform is it not installed on? Is it installed on the corresponding CRAN platform?

**Comment by astamm** [comment]
Hi Gabor,

It cannot be found at least on

- Windows Server 2008 R2 SP1, R-devel, 32/64 bit
- Debian Linux, R-devel, GCC ASAN/UBSAN

On Fedora Linux, R-devel, clang, gfortran, it seems that CMake does not create a `lib` folder when installing but a `lib64` folder instead. I have to find a way to fix this on my side. At least Cmake is found there and also on Ubuntu Linux 20.04.1 LTS, R-release, GCC.

I have not tested other R-Hub platforms.

It is installed on win-builder. I do not know about other CRAN platforms.

Thanks.

**Comment by gaborcsardi** [comment]
On Debian it should be installed automatically if a package requests it. If this fails for you please point me to a build log. I installed it on Windows.

**Comment by astamm** [comment]
Thanks Gabor. It works indeed on Windows now. As for Debian, here is the log that I get: https://builder.r-hub.io/status/original/nloptrcmake_2.0.0.tar.gz-53b95e19753848e085dac8b5be040c3a

**Comment by gaborcsardi** [comment]
Thanks! Something has changed in Debian:
```
E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bullseye' to 'bookworm'
```
Seems like the `rhub/rocker-gcc-san` is not updated daily, let me update it manually.

**Comment by gaborcsardi** [comment]
I have just updated it, so it should work again.

**Comment by astamm** [comment]
All working. Thank you very much.
