### ISSUE TITLE
Package CRAN check error, but status successful

### ISSUE THREAD

**Issue by davidechicco** [r-hub/rhub#495]
Hi all
I just used rhub to check my package for CRAN with the following command:
`rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`

And I received an email with the following error on Windows Server 2008 R2 SP1, R-devel, 32/64 bit:
```
* checking package dependencies ... ERROR
Package required but not available: 'diffcoexp'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

Surprisingly then, the [HTML page says that the build status is successful](https://builder.r-hub.io/status/easyDifferentialGeneCoexpression_0.3.tar.gz-0724ae50aede4b4eb9e5c3d7883b4105).
What is going on?

Should I worry about this error and try to fix it? If yes, how?

Or can I just forget about it?

Thanks

**Comment by gaborcsardi** [comment]
Yes, that is somewhat confusing, it means that the check procedure was successfully finished and the result was a check error. I assume you got an email that said that as well. Or you can check it from R:

```r
❯ rhub::get_check("easyDifferentialGeneCoexpression_0.3.tar.gz-0724ae50aede4b4eb9e5c3d7883b4105")

── easyDifferentialGeneCoexpression 0.3: ERROR

  Build ID:   easyDifferentialGeneCoexpression_0.3.tar.gz-0724ae50aede4b4eb9e5c3d7883b4105
  Platform:   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
  Submitted:  30m 11.8s ago
  Build time: 21m 22.2s

❯ checking package dependencies ... ERROR
  Package required but not available: 'diffcoexp'

  See section 'The DESCRIPTION file' in the 'Writing R Extensions'
  manual.

❯ checking CRAN incoming feasibility ... NOTE

  New submission
  Maintainer: 'Davide Chicco <davidechicco@davidechicco.it>'

1 error ✖ | 0 warnings ✔ | 1 note ✖
```

As for the error, I believe this is an `install.packages` bug, when it is installing a mixture of binary and source packages it messes up the order, that is why a dependency was not installed. You can try this:

```r
rhub::check(..., env_vars = c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))
```

**Comment by davidechicco** [comment]
Hi @gaborcsardi, thanks for your reply and your message.

> As for the error, I believe this is an install.packages bug, when it is installing a mixture of binary and source packages it messes up the order, that is why a dependency was not installed. You can try this:
>
> `rhub::check(..., env_vars = c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`

I see. What's the difference between this command and the command I originally used `rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`?

**Comment by gaborcsardi** [comment]
Slightly different set of checks, but that should not affect this issue. Can you just re-run your original check? The `install.packages()` bug is triggered by some combinations of binary and source packages, but not by others. So it is possible that now there is a binary package available (or the opposite), and the error does not come up. 

In any case, if other platforms are OK, you can submit your package to CRAN, they'll run Windows tests on submission, anyway.

**Comment by davidechicco** [comment]
I just re-run the same command and I obtained exactly the same error. I also tried to submit the package to CRAN anyway but its execution [generated another error](https://win-builder.r-project.org/incoming_pretest/easyDifferentialGeneCoexpression_0.3_20211129_222101/Windows/00check.log), due to a missing internet connection in that moment that I think I cannot fix.
Any additional suggestion?

**Comment by gaborcsardi** [comment]
You need to change your examples so they don't need internet.

**Comment by davidechicco** [comment]
> You need to change your examples so they don't need internet.

Easy to say it ;-) Actually the real scope of my package is to download gene expression data...

Anyway, I was somehow able to solve this problem, even if I cannot explain why. I'll share this information anyway in case it can be useful for someone else.
The problem related to the Matrix library differs when I use different versions of R: the problem happens when I use `R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"`, and it does not happen when I use `R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"`. Everything goes smoothly when I use R v4.1.0

Perhaps it was a bug of R v4.0.3 that the developers then fixed. 

Thanks to everybody who helped anyway
