### ISSUE TITLE
Windows: tempdir() is reported as non-existing in package tests

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#50]
With `check_on_windows()` I get:
```r
─  checking tests ...  Running 'tempdir.R'
   Warning message:
   running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD BATCH --vanilla  "tempdir.R" "tempdir.Rout"' had status 1 
    ERROR
   Running the tests in 'tests/tempdir.R' failed.
   Last 13 lines of output:
     Type 'q()' to quit R.
     
     > path <- tempdir()
     > print(path)
     [1] "C:\\Windows\\TEMP\\Rtmp6595Wk"
     > print(file.info(path))
                                   size isdir mode mtime ctime atime  exe
     C:\\Windows\\TEMP\\Rtmp6595Wk   NA    NA <NA>  <NA>  <NA>  <NA> <NA>
     > print(file_test("-d", path))
     [1] FALSE
     > stopifnot(file_test("-d", path))
     Error: file_test("-d", path) is not TRUE
     Execution halted
```
Note that `tempdir()` is non-existing according to the above.  The full output is https://builder.r-hub.io/status/upkg_1.0.tar.gz-9186beb9c951478a9ca674b069e8b87c

The package tested, a minimal reproducible package, is https://github.com/HenrikBengtsson/upkg/tree/rhub-tempdir

**Comment by kylebmetrum** [comment]
I've been getting same thing with `file.exists(tempdir())`  returning `FALSE`.

**Comment by HenrikBengtsson** [comment]
This is true for all Windows versions:

* Windows Server 2008 R2 SP1, R-devel, 32/64 bit (windows-x86_64-devel)
* Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit (windows-x86_64-oldrel)
* Windows Server 2008 R2 SP1, R-patched, 32/64 bit (windows-x86_64-patched)
* Windows Server 2008 R2 SP1, R-release, 32/64 bit (windows-x86_64-release)

**Comment by HenrikBengtsson** [comment]
And for completeness, if you do the same for `tempfile()` you'll see that that also fails, which most likely is because `tempdir()` doesn't exist.  Here's the output (only) if you do that:
```r
─  checking tests ...  Running 'tempfile.R'
   Warning message:
   running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD BATCH --vanilla  "tempfile.R" "tempfile.Rout"' had status 1 
    ERROR
   Running the tests in 'tests/tempfile.R' failed.
   Last 13 lines of output:
     [1] "C:\\Windows\\TEMP\\Rtmpus51hd\\file9fc68b81ef8"
     > print(file.info(pathname))
                                                    size isdir mode mtime ctime
     C:\\Windows\\TEMP\\Rtmpus51hd\\file9fc68b81ef8   NA    NA <NA>  <NA>  <NA>
                                                    atime  exe
     C:\\Windows\\TEMP\\Rtmpus51hd\\file9fc68b81ef8  <NA> <NA>
     > print(file.exists(pathname))
     [1] FALSE
     > print(file_test("-f", pathname))
     [1] FALSE
     > stopifnot(file_test("-f", pathname))
     Error: file_test("-f", pathname) is not TRUE
     Execution halted
```

**Comment by kylebmetrum** [comment]
`?file.exists` suggests that it might be a permissions issue(?); I was able to read and write from `tempdir()` with no problem, but my exists check came back `FALSE`.

**Comment by gaborcsardi** [comment]
:+1: Fixing soon. Indeed, I run the check with a restricted user, and I made it too restricted....

**Comment by HenrikBengtsson** [comment]
I see.

I'm surprised that R doesn't have some kind of fall back for `tempdir()`, say, to a local folder, or give an informative error about it.

**Comment by gaborcsardi** [comment]
Should be OK, please reopen if any more troubles!

**Comment by HenrikBengtsson** [comment]
Thxs. Confirming it works with my toy test package as well as R.utils where I first noticed the problem.

**Comment by gaborcsardi** [comment]
Great! Thanks for checking!
