### ISSUE TITLE
`qpdf` missing in Windows Server 2022, R-devel, 64 bit

### ISSUE THREAD

**Issue by lionelvoirol** [r-hub/rhub#501]
Hi, 

I am trying to check the  [`simts`](https://github.com/SMAC-Group/simts) package using `rhub` using `check_for_cran()`

It appears that the tool `qpdf` is missing on Windows Server 2022, R-devel, 64 bit.

I've read the previous issues regarding similar issue on other environments and other related stackoverflow posts. Apparently, you previously fixed this exact problem on other environments by manually installing it. Could you please similarly do it or, if it is not the same issue, advise me how to solve this?

Thanks a lot.

**Comment by lionelvoirol** [comment]
Find the built log [here](https://builder.r-hub.io/status/simts_0.2.0.tar.gz-7997d98321be49eba6286cc285471537)

**Comment by gaborcsardi** [comment]
I installed it, please try again.

**Comment by lionelvoirol** [comment]
Thanks a lot. will try it now and keep you posted.

**Comment by lionelvoirol** [comment]
Hi again @gaborcsardi. Just received the feedback from the built on WIndows Server 2022: The build find `qpdf` installed and  there is no more `Warning`! Thanks a lot!
