### ISSUE TITLE
Adapt `local_check_linux()` to run with docker alternative like `podman` ?

### ISSUE THREAD

**Issue by cderv** [r-hub/rhub#505]
I tried `podman` which is an alternative for `docker`, and from doc it was supposed to be a 1-1 equivalent mainly , meaning something that run with `docker` runs with `podman`

https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users

I did a quick test: 
* I add this in `rhub-linux.sh` (by modifying my local install of **rhub**)
````sh
docker() {
    /usr/bin/podman "$@"
}
````
* then I ran `rhub::local_check_linux(image = "rhub/debian-gcc-devel")`

Everything worked as expected, (except running manually the image at the end because it seems that `podman` does not use name but only id). 

Anyway, having a way to configure a docker alternative would be great to benefit from this feature of running local checks in container. 

Just throwing the idea for this, either for support or just a switch that could allow advanced _at your own risk_ usage.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
