### ISSUE TITLE
ERROR: dependencies ‘Rcpp’, ‘RcppArmadillo’ are not available

### ISSUE THREAD

**Issue by astamm** [r-hub/rhub#506]
Hi. When I check my package on the platform `Debian Linux, R-devel, GCC ASAN/UBSAN`, I get a prep-error telling me that dependencies `Rcpp` and `RcppArmadillo` are not available. I have checked packages before and it is the first time I see this message: https://builder.r-hub.io/status/original/fdacluster_0.1.0.tar.gz-ffc97a410cfe421db64ede14278d3adf

**Comment by gaborcsardi** [comment]
The compiler fails to compile Rcpp, I will need to update the container image.

**Comment by astamm** [comment]
Thanks. It is also affecting the Docker image containing a build with sanitisers.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
