### ISSUE TITLE
New 'extptr.as.ref' argument in identical()

### ISSUE THREAD

**Issue by andrew-plowright** [r-hub/rhub#507]
Hello, I have an `identical` method in [my library](https://github.com/andrew-plowright/TileManager/blob/0f213a6bcce4bc4b6d0f5e6672660409e09c22c5/R/tileScheme-methods.R#L198). I recently started getting a warning message regarding a new `extptr.as.ref` argument that [was added to R-devel](https://developer.r-project.org/blosxom.cgi/R-devel/2021/12/01) in December.

```
* checking for code/documentation mismatches ... WARNING
identical
                 TRUE, ignore.bytecode = TRUE, ignore.environment =
                 FALSE, ignore.srcref = TRUE, extptr.as.ref = FALSE)
  Code: function(x, y, num.eq = TRUE, single.NA = TRUE, attrib.as.set =
Codoc mismatches from documentation object 'identical':
  Docs: function(x, y, num.eq = TRUE, single.NA = TRUE, attrib.as.set =
                 TRUE, ignore.bytecode = TRUE, ignore.environment =
                 FALSE, ignore.srcref = TRUE)
  Argument names in code not in docs:
    extptr.as.ref
```

I tried adding the `extptr.as.ref` argument to my documentation, but now I get a new warning:

```
  Documented arguments not in \usage in documentation object 'identical':

    'extptr.as.ref'
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.
```

So it seems that a warning is being generated both with or without the `extptr.as.ref` in my documentation. Any help would be appreciated, thanks!

**Comment by gaborcsardi** [comment]
This does not seem to be a question about R-hub or the rhub package. Maybe https://community.rstudio.com/ or the R-package-devel mailing list are more appropriate venues for this question?
