### ISSUE TITLE
pandoc and qpdf not being installed on R-release for Mac M1 makes rhub return a WARNING and a NOTE

### ISSUE THREAD

**Issue by sjentsch** [r-hub/rhub#509]
For Apple Silicon (M1), macOS 11.6 Big Sur, R-release, `pandoc` and `qpdf` don't seem to be available / installed and the following WARNING and a further NOTE are returned:
```
* checking data for ASCII and uncompressed saves ... OK
 WARNING
‘qpdf’ is needed for checks on size reduction of PDFs
```
```
* checking top-level files ... NOTE
Files ‘README.md’ or ‘NEWS.md’ cannot be checked without ‘pandoc’ being installed.
```
I don't know whether the solution proposed at the end of https://github.com/jgm/pandoc/issues/6960 is feasible to solve the problem with `pandoc`?

**Comment by gaborcsardi** [comment]
I installed them.

**Comment by sjentsch** [comment]
Thanks!
