### ISSUE TITLE
Ubuntu: Unable to find GhostScript executable to run checks on size reduction

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#51]
I get:
```
* checking sizes of PDF files under ‘inst/doc’ ... NOTE
Unable to find GhostScript executable to run checks on size reduction
```
on 
* Ubuntu Linux 16.04 LTS, R-release, GCC (ubuntu-gcc-release)

It does work on:
* Ubuntu Linux 16.04 LTS, R-devel, GCC (ubuntu-gcc-devel)
* Debian Linux, R-release, GCC (debian-gcc-release)
* CentOS 6, stock R from EPEL (linux-x86_64-centos6-epel)

Those are the only other ones I've tested.

Package test log: https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-4a7ec140506c434699544ce8679dc2fa

**Comment by gaborcsardi** [comment]
I don't understand this. I don't think any of the Linux images have ghostscript. Why doesn't this come up always then?

**Comment by HenrikBengtsson** [comment]
# Checks where GhostScript is missing

* [linux-x86_64-ubuntu-gcc](https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-4a7ec140506c434699544ce8679dc2fa)
* [linux-x86_64-fedora-clang](https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-474e787a9fa0469bae39d942ef760831)


# Checks where its all OK
* [linux-x86_64-centos6-epel](https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-9e9cf63ba9db4090a9ddf769e305a946)
* [linux-x86_64-debian-gcc](https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-972cc560bfc543c2967b22362f168619)
* [linux-x86_64-ubuntu-gcc](https://builder.r-hub.io/status/R.oo_1.20.0-9000.tar.gz-18f3ff2e58364dc886417e8269230b56)


Those were all run around 2016-10-31 04:00Z.

However, did you fix this? Because, around 2016-10-31 20:00Z I get all OK for all Linux instances.

**Comment by gaborcsardi** [comment]
> However, did you fix this? Because, around 2016-10-31 20:00Z I get all OK for all Linux instances

Not intentionally. But I did build new images for all platforms, for another reason. I should include the container version (or at least the hash) in the "status" output. So much to do! :)

Actually, only the CentOS6 container has ghostscript:
```
jenkins@jenkins:~$ docker run -t rhub/ubuntu-gcc-devel which ghostscript
jenkins@jenkins:~$ docker run -t rhub/fedora-clang-devel which ghostscript
which: no ghostscript in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
jenkins@jenkins:~$ docker run -t rhub/debian-gcc-devel which ghostscript
jenkins@jenkins:~$ docker run -t rhub/centos6-epel which ghostscript
/usr/bin/ghostscript
```

So I am not sure what is going on here. Anyway, if it is working, that's good....

**Comment by HenrikBengtsson** [comment]
Note that [it's looking for `gs` by default](https://github.com/wch/r-source/blob/trunk/src/library/tools/R/admin.R#L1054-L1066) - not `ghostscript`.  At least on R-devel, which I've only checked.

**Comment by gaborcsardi** [comment]
Yeah, good idea, but that does not change anything:
```
jenkins@jenkins:~$ docker run -t rhub/ubuntu-gcc-devel which gs
jenkins@jenkins:~$ docker run -t rhub/fedora-clang-devel which gs
which: no gs in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
jenkins@jenkins:~$ docker run -t rhub/debian-gcc-devel which gs
jenkins@jenkins:~$ docker run -t rhub/centos6-epel which gs
/usr/bin/gs
```

**Comment by gaborcsardi** [comment]
In the R source code it seems that qpdf is used by default, but not gs, at least this is the default right now. So I suggest we close this until it comes up again. Then I'll install gs on all images.

**Comment by gaborcsardi** [comment]
Yeah, this is happening again.... need gs.

**Comment by gaborcsardi** [comment]
I just added ghostscript to all images in https://github.com/r-hub/rhub-linux-builders/commit/5dd16da8a94ae5d7bdd7b49c79ddaff4d383f76f

It will take a couple of hours to update. Please reopen if you still have issues.

**Comment by samuel-rosa** [comment]
I am having this issue with the __spsann__ package on the following platform:

* [Windows Server 2008 R2 SP1, R-devel, 32/64 bit](https://builder.r-hub.io/status/spsann_2.2.0.tar.gz-3a56075849984aa5aeb6d994628d1805)

**Comment by gaborcsardi** [comment]
@samuel-rosa this is a closed issue about a different platform. Can you pls open a new one? Thanks.
