### ISSUE TITLE
cmake not found on linux-x86_64-fedora-clang and linux-x86_64-ubuntu-gcc

### ISSUE THREAD

**Issue by jranke** [r-hub/rhub#511]
Installation of the 'symengine' package fails on this platform because of this:

https://builder.r-hub.io/status/mkin_1.1.0.tar.gz-3e91f7ad09404f83a3d94cca799056ca#L6525

**Comment by gaborcsardi** [comment]
Sry, closed accidentally.

Yes, that's an R-hub bug, it only considers the dependencies of the CRAN version of your package when looking up system requirements, and that version does not need symengine:

```r
❯ pak::pkg_deps_explain("mkin", "symengine", dependencies = TRUE)
x symengine

❯ pak::pkg_deps_explain("jranke/mkin", "symengine", dependencies = TRUE)
mkin -> nlmixr -> symengine
```

I added an exception for mkin, so it should work now.

**Comment by jranke** [comment]
Thanks for your quick action on this! Yes, symengine is a new dependency of the version tested. I just reran this an now another system requirement (GMP) is missing...

https://builder.r-hub.io/status/mkin_1.1.0.tar.gz-9698ca07071344d793dac303e91e5328#L13050

**Comment by gaborcsardi** [comment]
OK, I added GMP as well, pls try again.

**Comment by jranke** [comment]
Sorry, should have checked right away, mpfr is necessary as well....

https://builder.r-hub.io/status/mkin_1.1.0.tar.gz-61860efdedd44877b2d310349dbb2404#L13121
