### ISSUE TITLE
Check on R-devel on Windows fails during test phase, time out?

### ISSUE THREAD

**Issue by jranke** [r-hub/rhub#512]
I have no idea why this fails, I don't see any clue in the build log

https://builder.r-hub.io/status/mkin_1.1.0.tar.gz-7a0d47e9722249fc98fc81de87b9acdd

or the artifacts

https://artifacts.r-hub.io/mkin_1.1.0.tar.gz-7a0d47e9722249fc98fc81de87b9acdd/mkin.Rcheck/tests/testthat.Rout.fail

Is there a timeout?

**Comment by gaborcsardi** [comment]
A timeout would kill the whole check, not just the tests. This seems like a crash during the test cases. Use a different reporter to see where the crash happens:

```
test_check(..., reporter = "summary")
```

**Comment by jranke** [comment]
OK, thanks. I believe this means I need to run the tests locally. The tests run fine on Linux (local, travis, r-hub) and Winbuilder with R-release, so it seems I need to install R-devel on Windows to see what happens with R-devel on Winbuilder and r-hub...

**Comment by gaborcsardi** [comment]
No, you don't need to run it locally, just modify that line in `testthat.R` as I suggested and then at least you will see where it crashes.

**Comment by jranke** [comment]
Ah, now I see what you mean! Thanks!

**Comment by jranke** [comment]
Well, I followed your advice, and now I get

```
✔  checking for unstated dependencies in 'tests'
─  checking tests (850ms)
E  Running 'testthat.R' (4m 22s)
   Running the tests in 'tests/testthat.R' failed.
   Complete output:
     > library(testthat)
     > library(mkin)
     Loading required package: parallel
     > 
     > test_check("mkin", reporter = "summary")
✔  checking for unstated dependencies in vignettes
✔  checking package vignettes in 'inst/doc'
─  checking running R code from vignettes
     'FOCUS_D.rmd' using 'UTF-8'... OK
     'FOCUS_L.rmd' using 'UTF-8'... OK
     'mkin.rmd' using 'UTF-8'... OK
     'twa.rmd' using 'UTF-8'... OK
    NONE
✔  checking re-building of vignette outputs (18.3s)
✔  checking PDF version of manual (16.9s)
   
─  Done with R CMD check
─  Cleaning up files and user
```
I guess it fails in the setup script. I will check using r-devel on Windows.

**Comment by gaborcsardi** [comment]
You need to look at at `testthat.Rout` file in the artifacts, that's where testthat's output is.

**Comment by jranke** [comment]
I only get a `testthat.Rout.fail` containing

```
R Under development (unstable) (2022-02-21 r81789 ucrt) -- "Unsuffered Consequences"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(mkin)
Loading required package: parallel
> 
> test_check("mkin", reporter = "summary")
```

and nothing more... It seems testthat does not get to the stage where it reports something.

**Comment by gaborcsardi** [comment]
Yeah, then it does seem like it crashes in the setup file.

**Comment by jranke** [comment]
Thanks for your help anyways! I learned a lot :)

**Comment by jranke** [comment]
rhub is cool

**Comment by gaborcsardi** [comment]
Unfortunately this is hard to debug without access to a Windows machine, but at least you can try R-devel on win-builder as well, to see if this might be specific to R-hub, or not.

**Comment by jranke** [comment]
R-devel on winbuilder also just fails without any more info

**Comment by jranke** [comment]
R-devel on Windows is up and running over here now, I have a virtual Windows machine that I can use for this kind of stuff.

**Comment by jranke** [comment]
OK, I need to get Rtools 4.2, how often do you update Rtools on your windows machines?

**Comment by gaborcsardi** [comment]
No often, but rtools version very-very rarely matters. Especially if you don't have any compiled code.

**Comment by jranke** [comment]
I do rely on compiled code, but it does seem to be something else. Still investigating...

**Comment by jranke** [comment]
In some cases nlmixr (one of the packages that mkin uses as a backend) crashes the R instance on current R-devel on Windows... Therefore my test setup script never completes and I only get a `testthat.Rout.fail` file.
