### ISSUE TITLE
email case sensitive

### ISSUE THREAD

**Issue by rkrug** [r-hub/rhub#514]
It seems that email validation is case sensitive. 
This does not make much sense as email addresses are not case sensitive.

This has cost me some time before I figured that accident out.

Would it be possible, to make all email addresses lowercase before the validation, so that capitalisation does not matter any more?

Thanks,

Rainer

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
