### ISSUE TITLE
[cran org] RCurl mirror several versions behind

### ISSUE THREAD

**Issue by MichaelChirico** [r-hub/rhub#515]
_(not 100% sure this is the right place to file such an issue, apologies in advance)_

I noticed that the RCurl mirror is quite far behind CRAN:

https://github.com/cran/RCurl [1.95-4.12]
https://cran.r-project.org/web/packages/RCurl/index.html [1.98-1.6]

According to the archive, that's 6 versions missing: https://cran.r-project.org/src/contrib/Archive/RCurl/

**Comment by gaborcsardi** [comment]
Fixed now. The system is not very robust for the case when CRAN manually removes a version that was previously published. Then we keep trying to download that version, and keep failing, as it was completely removed from CRAN. I need to remove those manually from the DB.
