### ISSUE TITLE
Update GLPK version in windows-x86_64-release

### ISSUE THREAD

**Issue by ntamas** [r-hub/rhub#517]
The `windows-x86_64-release` image contains a copy of GLPK 4.47, which is more than 10 years old now. Would it be possible to update it to a more recent version? The new version of `igraph` depends on GLPK 4.57 or later because it uses `glp_at_error()` and this was added in GLPK 4.57 only (which is also more than 6 years old). If GLPK 4.47 is installed in the image because it matches the version used in the CRAN build environment, then are there any plans to update the CRAN build environment to a newer version in the foreseeable future?

Note that other builders seem to use more recent GLPK versions (4.65 or so), and apparently `rtools-packages` [also contains GLPK 4.65](https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-glpk/PKGBUILD). The commit message even mentions that `glpk` was added because of `igraph`, but it seems like this version is not installed in `windows-x86_64-release` by default.

**Comment by ntamas** [comment]
I don't know how R-Hub processes the `SystemRequirements` field in the package metadata, but it seems like GLPK is missing from https://github.com/r-hub/sysreqsdb/tree/master/sysreqs for Windows. RStudio's database adds an entry for GLPK: https://github.com/rstudio/r-system-requirements/tree/master/rules

**Comment by gaborcsardi** [comment]
What version of GLPK does CRAN's Windows have?

R-hub does not use `SystemRequirements` on Windows.

**Comment by gaborcsardi** [comment]
It seems that the last version of the glpkAPI package was built with GLPK 4.47, so most likely that is indeed the version available on CRAN.

I can't speak for CRAN, but I would think that it will not be updated.

**Comment by ntamas** [comment]
Can we use a vendored GLPK then when compiling igraph, or is that against CRAN policy? We vendor GLPK 5.0 in C-igraph and it has been patched to get rid of `abort()` and `printf()` calls.

**Comment by gaborcsardi** [comment]
AFAIK it is against policy. OTOH some packages do this already. Other packages download static libs from https://github.com/rwinlib

**Comment by ntamas** [comment]
OK, how about newer R versions then -- is R-devel going to have a newer GLPK version? If it will, I probably won't bother with vendoring GLPK and just work around the issue by disabling the branch that uses `glp_at_error()`. I'm asking because `igraph` builds successfully in win-builder with R-devel so it seems like there's a newer version of GLPK there.

**Comment by gaborcsardi** [comment]
The coming R 4.2.0 will use a newer version:
https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/toolchain_libs/mxe/src/glpk.mk

**Comment by ntamas** [comment]
Thanks for the info; I'll just probably work around the older GLPK version then for the time being and looking forward to R-devel.
