### ISSUE TITLE
install linux packages from repository where available?

### ISSUE THREAD

**Issue by bbolker** [r-hub/rhub#518]
I don't know if this is covered somewhere, but:  tests of one of my packages on platforms with CRAN binaries (Windows, MacOS) usually take about 10 minutes from start to finish. On the Linux platforms they take about 70 minutes, due to the length of time required to install all of the package dependencies from source. Would there be any way to enable an option to install packages from Michael Rutter's repository described at https://cran.r-project.org/bin/linux/ubuntu/ ? It would save a *lot* of computational effort and waiting ...

**Comment by gaborcsardi** [comment]
They are only available for one R-hub platform, and it is not trivial to integrate them into `install.packages()`/remotes/pak.

I suggest that you use Docker and the R-hub containers directly. If you work inside the container, then you don't need to wait for dependency installation at all.

**Comment by bbolker** [comment]
OK, thanks.
