### ISSUE TITLE
deprecated advice in local_linux_check?

### ISSUE THREAD

**Issue by bbolker** [r-hub/rhub#519]
The first time I ran `local_linux_check()` it failed because I didn't have the `sysreqs` package and suggested this:

```
$ R -q -e "source('https://install-github.me/r-hub/sysreqs')"
> source('https://install-github.me/r-hub/sysreqs')
The install-github.me service is deprecated, please stop using it.
```

Perhaps this should be changed to something like `remotes::install_github("r-hub/sysreqs")` ?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
