### ISSUE TITLE
Not receiving mail with token

### ISSUE THREAD

**Issue by ricoderks** [r-hub/rhub#522]
Hi,

I tried twice to validate my email address, but I didn't receive an email. Also not in my spam folder. I think there are two options. Or, there is an issue on your side or my company is filtering out the mail. I know that they filter out a lot of mail so it doesn't even reach the spam folder. Can you tell me from which email address I should receive the token? I hope I can talk to the IT guys to see if they can let this one through.

Cheers, Rico

**Comment by gaborcsardi** [comment]
support AT rhub.io 

If you send me your email address in private, I can check what happened to the email. I can also send you a token manually.

**Comment by ricoderks** [comment]
Thanks! I'll send you an email.

Cheers, Rico
