### ISSUE TITLE
Inconsistent LaTeX installs on different platforms 

### ISSUE THREAD

**Issue by gregfrog** [r-hub/rhub#523]
The pdfpages LaTeX package is not available on all RHub-provided platforms.  It appears to be missing from the Fedora clang and gcc devel versions.  For example this Fedora run https://builder.r-hub.io/status/WebAnalytics_0.9.5.tar.gz-ae6e2964bbe54dca8aa50238ebdc35f8 fails, not finding the package, but this Debian build https://builder.r-hub.io/status/WebAnalytics_0.9.5.tar.gz-c73e99562b7c40bea42555bfec77e0c6 succeeds.

**Comment by gregfrog** [comment]
It looks like the problem is that on Debian and Ubuntu, pdfpages is part of the texlive-latex-recommended package and on Fedora the packages must be installed individually.  I didn't get an answer when I asked which packages are present in the CRAN build environment, so the outstanding question must be what does CRAN install?  When I add TIKZ graphics to a vignette (coming some time in the not too distant future) I'll know more.

**Comment by gregfrog** [comment]
Looks like the relevant Fedora meta package is texlive-collection-latexrecommended

**Comment by bbolker** [comment]
I've had related problems with Fedora builds on r-hub in the past and eventually gave up trying ...

**Comment by gregfrog** [comment]
> I've had related problems with Fedora builds on r-hub in the past and eventually gave up trying ...

Ben,
The Fedora docker file does not install the texlive recommended latex packages (texlive-collection-latexrecommended), the Debian one does (package texlive-latex-recommended).  There appear to be other missing packages.  The CRAN build apears to install everything from TexLive.

Greg

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
