### ISSUE TITLE
ubuntu-rchk: "ERROR: too many states (abstraction error?)"

### ISSUE THREAD

**Issue by JiscaH** [r-hub/rhub#525]
When running rhub::check(platform = ''ubuntu-rchk''), I get the following error messages:

* 
About to run xvfb-run rchk.sh sequoia_2.3.14.tar.gz
/home/docker
Error : Bioconductor does not yet build and check packages for R version 4.3; see
  https://bioconductor.org/install
...
* DONE (sequoia)
ERROR: too many states (abstraction error?) in function strptime_internal
ERROR: too many states (abstraction error?) in function RunGenCollect
Analyzed 1 functions, traversed 1 states.

To reproduce this error, the package with which it occurred can be found here: https://github.com/JiscaH/sequoia/tree/devel

**Comment by gaborcsardi** [comment]
None of these are real errors, you can ignore them.

**Comment by JiscaH** [comment]
Great, thanks for the fast reply!
