### ISSUE TITLE
validate_email() documentation mis-specifies config location

### ISSUE THREAD

**Issue by ms609** [r-hub/rhub#528]
The documentation of `validate_email()` in `R/email.R@9,10` contains the text
```R
#' On your current platform the file is at
#' \Sexpr{rhub:::email_file()}`
```

The Sexpr is executed when the package is compiled – so when downloading the binary package from CRAN, it reads
 >   On your current platform the file is at C:\Users\CRAN\AppData\Local/rhub/rhub/validated_emails.csv.

I'm not sure what the most appropriate fix is: perhaps we need a wrapper for `email_file()` that detects that the package is being built on CRAN, and perhaps replaces the string `C:\Users\CRAN\AppData\Local` with `%APPDATA%`?

**Comment by gaborcsardi** [comment]
I think this was fixed by #434.
