### ISSUE TITLE
Fedora Linux Building using R 4.3 (?)

### ISSUE THREAD

**Issue by JSchoenbachler** [r-hub/rhub#529]
Hey all, I was running `devtools::check_rhub` and kept getting a "PREPERROR" only on Fedora Linux:

https://builder.r-hub.io/status/seeker_1.0.0.tar.gz-98a5ba63ca2d47f5805b6ca6e7e9debf

```

Build ID: | seeker_1.0.0.tar.gz-98a5ba63ca2d47f5805b6ca6e7e9debf
-- | --
Platform: | Fedora Linux, R-devel, clang, gfortran

```

The error throughout the run reads: 
```
#> Error : Bioconductor does not yet build and check packages for R version 4.3; see

[4099](https://builder.r-hub.io/status/seeker_1.0.0.tar.gz-98a5ba63ca2d47f5805b6ca6e7e9debf#L4099)#> https://bioconductor.org/install
```
However, the current version of R is 4.2, not 4.3.

I'm not exactly sure what's going on here, so any feedback would be appreciated!

**Comment by JSchoenbachler** [comment]
Here is also another run that is more recent:

https://builder.r-hub.io/status/seeker_1.0.0.tar.gz-6005fab6428a4ded9a39ed0ecee1be30

**Comment by gaborcsardi** [comment]
Nothing is going wrong, 4.3.0 is not released yet. Unreleased versions need version numbers as well. Bioconductor does not support R 4.3.x yet, and that error is ignored.
