### ISSUE TITLE
check_for_cran() and check_with_rdevel() are broken

### ISSUE THREAD

**Issue by dankelley** [r-hub/rhub#530]
I get as below.  The list of available platforms seems to be quite limited.  I am using rhub-1.1.1 with "R Under development (unstable) (2022-06-27 r82528" on macOS "Version 12.5 Beta (21G5056b)".

```R
> library(rhub)
> check_with_rdevel()
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
> check_for_cran()
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
> rhub::platforms()
macos-highsierra-release:
  macOS 10.13.6 High Sierra, R-release, brew
macos-highsierra-release-cran:
  macOS 10.13.6 High Sierra, R-release, CRAN's setup
macos-m1-bigsur-release:
  Apple Silicon (M1), macOS 11.6 Big Sur, R-release
solaris-x86-patched:
  Oracle Solaris 10, x86, 32 bit, R-release
solaris-x86-patched-ods:
  Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6
```

**Comment by gaborcsardi** [comment]
> Hi all, unfortunately we temporarily need to stop our Windows and Linux builders, to sort out some billing issues. Hopefully we'll be able to turn them back on soon. We'll tweet here once we have more information.

https://twitter.com/rhub_/status/1542039387369885698

**Comment by lionelvoirol** [comment]
Thanks for the update @gaborcsardi . Looking forward to some news ! Thanks!

**Comment by adriancorrendo** [comment]
Thanks @lionelvoirol for posting this issue and @gaborcsardi for taking care. I remarked the issue too since I'm releasing a package update but can't do it due to this problem. Looking forward to hear news about it. Best and thanks!

**Comment by gaborcsardi** [comment]
You don't technically need R-hub to release a package to CRAN. They have their own checks.

**Comment by adriancorrendo** [comment]
> You don't technically need R-hub to release a package to CRAN. They have their own checks.

Thanks, @gaborcsardi ! Sure, in fact, that's what I just did. I used the available platforms with rhub and complemented with some local checking. But I have to say I find rhub::check_for_cran() super handy to run all tests before submitting to CRAN. Best!
