### ISSUE TITLE
Confused with follwing error

### ISSUE THREAD

**Issue by biplab44** [r-hub/rhub#532]
Following error has been showed. How can I fix the problem?
```
check_on_linux()
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
```
I am trying to check my new r-package `ctmva`.

**Comment by gaborcsardi** [comment]
See #530

**Comment by biplab44** [comment]
Unfortunately, Problem remains same

**Comment by gaborcsardi** [comment]
Yes, I know. The explanation is in the referenced issue: https://github.com/r-hub/rhub/issues/530#issuecomment-1171569958
