### ISSUE TITLE
I wasn't able to reproduce the CRAN clang asan ubsan warnings and errors using the Fedora rhub docker image

### ISSUE THREAD

**Issue by mlampros** [r-hub/rhub#534]
First of all thank you for making this repository publicly available.

I currently have clang asan ubsan issues with a couple of my RcppArmadillo packages (OpenImageR, fastGLCM) and I used one of the rhub docker images (`rhub/fedora-clang-devel-san`) to reproduce and fix these issues. I wasn't sure if I have to open the issue here or in the [rhub-linux-builders](https://github.com/r-hub/rhub-linux-builders) repository

I realized that reproducing the clang-asan-ubsan issues is not feasible because currently the rhub dockerfile uses by default the [fedora:33 docker image](https://github.com/r-hub/rhub-linux-builders/blob/master/fedora/Dockerfile#L3) whereas the latest [Fedora version is 37 ](https://en.wikipedia.org/wiki/Fedora_Linux_release_history). I was able to retrieve this fedora version also from the [Docker API](https://hub.docker.com/v2/repositories/library/fedora/tags)

I am aware of the [related rhub issue](https://github.com/r-hub/rhub/issues/464) where the fedora version was set to version 33 in the Dockerfile, because I received initially also the `R_HOME ('/opt/R-devel/lib64/R') not found` error and during my search on the web I stumbled upon the cause which I also describe in the README.md file of the [repository that I created (by including the url's)](https://github.com/mlampros/fedora_clang_rdsan#fedora_clang_rdsan). This seems to be a 'glibc' issue (as mentioned in the thread). The temporary solution (proposed in the thread) was to include one of the following two commands in the docker run command (runtime):

* `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined`
* `--security-opt seccomp=unconfined`

What I did in my repo was to include an [R script](https://github.com/mlampros/fedora_clang_rdsan/blob/master/fedora_latest_version.R) to retrieve the latest Fedora version (currently 37) using the Docker API and to also slightly modify the 3 related Dockerfiles from the [rhub-linux-builders](https://github.com/r-hub/rhub-linux-builders) repository ([Dockerfile_fedora](https://github.com/mlampros/fedora_clang_rdsan/blob/master/Dockerfile_fedora), [Dockerfile_fedora_clang](https://github.com/mlampros/fedora_clang_rdsan/blob/master/Dockerfile_fedora_clang), [Dockerfile_fedora_clang_san](https://github.com/mlampros/fedora_clang_rdsan/blob/master/Dockerfile_fedora_clang_san)). Thank you for all your work. Then I created a [new Docker image](https://hub.docker.com/repository/docker/mlampros/fedora_clang_san) based on the latest fedora version which by default installs the LLVM-Clang version 14.0.5 which is close to the one used currently [by CRAN (14.0.6) on Fedora 34](https://www.stats.ox.ac.uk/pub/bdr/memtests/README.txt). This docker image is created using a [Github action](https://github.com/mlampros/fedora_clang_rdsan/blob/master/.github/workflows/gh_action.yml)

Based on [this docker image](https://hub.docker.com/repository/docker/mlampros/fedora_clang_san) I was able to reproduce the CRAN Clang asan ubsan issues in both packages (OpenImageR, fastGLCM) [both from the command line and from within an R session](https://github.com/mlampros/fedora_clang_rdsan#how-to-use-the-asan-ubsan-docker-image)

I don't know how rhub works internally but there might be a quick fix using one of the two runtime commands 

* `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined`
* `--security-opt seccomp=unconfined`

I'll ping the ones that might be interested in this issue (based on [issue 464](https://github.com/r-hub/rhub/issues/464) and [issue 462](https://github.com/r-hub/rhub/issues/462))
@gaborcsardi
@maelle

**Comment by gaborcsardi** [comment]
Thanks, this is very valuable! We hope to improve the container that runs the ASAN checks in the near future.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
