### ISSUE TITLE
help with GDAL dep

### ISSUE THREAD

**Issue by mdsumner** [r-hub/rhub#537]
I'm completely lost as to what *should* work, if I try to check with sanitizers (with hypertidy/vapour). 

```R
rhub::check_with_sanitizers(show_status=F)
─  Building package
Error: Build failed, unknown error, standard output:
* checking for file ‘vapour/DESCRIPTION’ ... OK
* preparing ‘vapour’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘vapour’ ...
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘vapour’
* removing ‘/tmp/RtmpbMxZSU/Rinst3d4be3d67cf49/vapour’
      -----------------------------------
ERROR: package installation failed
```

and if I try to build a docker image starting with just the libproj dep (so I can install libgdal-dev or cmake it from source)

```
FROM rhub/rocker-gcc-san
RUN apt update && apt upgrade -y
RUN apt install -y  git g++ libproj-dev cmake pkg-config 

...
The following packages have unmet dependencies:
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.39.2-1) but 3.39.3-1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

I've tried manual intervention in the container to try to figure it out but I'm at a loss. Appreciate any help, thank you.

**Comment by mdsumner** [comment]
I figuredout my Dockerfile build, I think - was using a cache. 

For the `rhub::check_with_sanitizers()` is it reasonable for me to expect GDAL support? Or do I just go with the custom build? I'm happy either way, apologies for the noise while I'm learning.

**Comment by mdsumner** [comment]
A real problem I think is that the sanitzers build doesn't end up with a <pkg>.Rcheck/ folder in the artifacts: 

https://artifacts.r-hub.io/vapour_0.9.0.tar.gz-7facc5fe7fd54820875635dec9775af6/

```R
 rhub::check(".", platform = "linux-x86_64-rocker-gcc-san",show_status = F)
```

When I run ` r rhub::check(".", platform = "fedora-clang-devel",show_status = F)` I get that folder with check and test and example artifacts, which I fhink I need to see the UBSAN errors CRAN are seeing.  My run for that was 'vapour_0.9.0.tar.gz-e65bc3a469c3488197b2cd647e656662'

but, UBSAN doesnt have that folder

![image](https://user-images.githubusercontent.com/4107631/190886228-5337575e-70a1-4e02-98dc-056ca855c373.png)

TY  I'm exploring the actual Dockerfile so I might slowly get to where I need.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
