### ISSUE TITLE
check_for_cran() uses wrong windows releases

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#54]
It uses "win-oldrel", leading to a failure for me when `check_on_windows()` works fine.

I would like to suggest the use of the release version on windows too.

**Comment by eddelbuettel** [comment]
Re-upping this.  Just ran a `check_for_cran()` (on a micro-package, so easy pass) but Windows still uses old-rel.  That is still wrong / less useful.   Splitting Linux between r-devel and r-release, and clang and gcc, is awesome.  You could do two Windows runs (release and devel) or just one, but doing old-rel is weird.  And, sorry to repeat this, less relevant.   Maybe devel on Windows too?

**Comment by gaborcsardi** [comment]
Yes, good point. I think it is good practice to check if it works with oldrel, but you are right, this is function is about CRAN, so we'll omit oldrel.

**Comment by eddelbuettel** [comment]
Right, and `check_for_cran()` _does_ need a Windows check, but either release or devel (or both) is more relevant than oldrel (which is valuable, but secondary).
