### ISSUE TITLE
 rhub latex error: `framed.sty' not found

### ISSUE THREAD

**Issue by karlottakleve** [r-hub/rhub#541]
Hi,
I am getting Latex errors when checking R package code via:
devtools::check_rhub(build_args = c('--compact-vignettes=both'))

but only for Fedora and Windows, not for Ubuntu.  What can I do about this and how can I change the Latex configuration on rhub? On my own computer, I don't get this error during the build.

Many thanks!
Karlotta

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Platform: Fedora Linux, R-devel, clang, gfortran

* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
--- re-building ‘grmsem.Rmd’ using rmarkdown
! LaTeX Error: File `framed.sty' not found.

! Emergency stop.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Platform Windows: Server 2022, R-devel, 64 bit
....
#> ! Sorry, but C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe did not succeed.
...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
