### ISSUE TITLE
Missing `httr` and `keyring` when testing package check --as.cran over 'debian-clang-devel'

### ISSUE THREAD

**Issue by eblondel** [r-hub/rhub#542]
Hello, thanks so much for this plateform.
I'm trying to use rhub to do specific check for CRAN to implement a change request received by CRAN team (see https://github.com/eblondel/geometa/issues/200 for the issue occuring with **debian-clang-devel**)

I run rhub through R with `rhub::check_for_cran(path = ".", platforms = "debian-clang-devel")`
Result is here: https://builder.r-hub.io/status/geometa_0.7-1.tar.gz-7e7716d429dc48ed82e232b3d92f0fe6

I get a failure due to missing `httr` and `keyring` package installs. I know `keyring` require some specific systems libs (`libsecret-1-dev`), could it be the reason? but then for `httr` i've no idea what's wrong.

Thanks in advance for your help

**Comment by gaborcsardi** [comment]
I removed `pandoc-citeproc`, can you try again? Thanks.

**Comment by eblondel** [comment]
Many thanks for your prompt support @gaborcsardi yes it works now :-)
