### ISSUE TITLE
pandoc error --Incompatible API versions --  only on Fedora

### ISSUE THREAD

**Issue by ethanbass** [r-hub/rhub#545]
Hi,
I'm trying to check one of my R packages with rhub and I'm getting a pandoc-related error trying to build the vignette on both Fedora builds that does appear on any other platforms (e.g. Windows & Ubuntu). 

The error:

```
* checking re-building of vignette outputs ... [31s/113s] ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘chromatographR.Rmd’ using rmarkdown
pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,20] but attempted to decode with [1,17,0,4].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:113:48 in pandoc-types-1.17.0.4-4aoSpZT0JGfLcwVLdW8mUx:Text.Pandoc.JSON
Error running filter /usr/bin/pandoc-citeproc:
Filter returned error status 1
Error: processing vignette 'chromatographR.Rmd' failed with diagnostics:
pandoc document conversion failed with error 83
--- failed re-building ‘chromatographR.Rmd’

SUMMARY: processing the following file failed:
  ‘chromatographR.Rmd’

Error: Vignette re-building failed.
Execution halted
```

Here is the full log (https://builder.r-hub.io/status/original/chromatographR_0.4.5.tar.gz-b6da6608142b43d985adc655b4776dc3)

I did find several references to this error message on google, including this thread (https://groups.google.com/g/linux.debian.bugs.dist/c/X5illh6tEBY) where they imply that this could be an issue with the way pandoc is compiled?

I apologize if this is somehow an issue with my package and not an actual bug. If so, it seems like there's still an interaction with something about the way the Fedora machines are configured since it works on most other operating systems I've tested. Thanks!!

Update: I downloaded Fedora 36 ARM 64 in a virtual machine to test my package and was not able to reproduce this error.

**Comment by pboesu** [comment]
I am getting  the same error for a package with a PDF vignette (full log here: https://builder.r-hub.io/status/deBInfer_0.4.4.tar.gz-fa577af166804d8fbe1ffbc4ff52c72c).

The package completes R CMD Check without this or any other issues on win builder and on Ubuntu/MacOS/Windows via github actions (https://github.com/pboesu/debinfer/actions/runs/3472567454).
