### ISSUE TITLE
Windows image fails because of lack of suitable spell-checker

### ISSUE THREAD

**Issue by dramanica** [r-hub/rhub#546]
When I run `check_on_cran()`, the Windows checks return success. However, looking at the logs, I get:
```
#> * checking CRAN incoming feasibility ...
#> Error in aspell(files, filter = list("dcf", ignore = ignore), control = control, :
#> No suitable spell-checker program found
#> Execution halted
```
So, two issues:
First, aspell does not work properly on Windows (the checks work fine on Linux, and they succeed on Windows if I set `_R_CHECK_CRAN_INCOMING_USE_ASPELL_`='false').
Second, the error is not caught, and a success is reported despite execution being halted.

**Comment by ethanbass** [comment]
Yes, I'm seeing this as well. Here is the report: https://builder.r-hub.io/status/chromatographR_0.4.5.tar.gz-71f3c5848dd84062a45edf0ed68d7015

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
