### ISSUE TITLE
Erroring on Linux due to missing GTK2

### ISSUE THREAD

**Issue by lbusett** [r-hub/rhub#55]
Hi. First of all, great work ! Really nice to be able to check on multiple platforms at once ! Thanks !

Secondly, I'm having some problems on checks on linux: My package checks-out ok on Windows (besides a problem with MikTex), but on Linux I get these kind of errors:

1629#> * installing *source* package ‘RGtk2’ ...
1630#> ** package ‘RGtk2’ successfully unpacked and MD5 sums checked
1631#> checking for pkg-config... /usr/bin/pkg-config
1632#> checking pkg-config is at least version 0.9.0... yes
1633#> checking for INTROSPECTION... no
1634#> checking for GTK... no
1635#> configure: error: GTK version 2.8.0 required
1636#> ERROR: configuration failed for package ‘RGtk2’
1637#> * removing ‘/home/docker/R/RGtk2’

I'm in need of RGtk2 to build a GUI, but then build fails due to missing GTK2 lib. Is there any way to make so that it is installed "on the fly" ? It's already in my "system requirements", but I can't manage to have it configured properly. (Full log here: [https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-5c001e7668084a64b79a934f2297b765])

regards, 

Lorenzo

**Comment by gaborcsardi** [comment]
Hi, we need to add libgtk2 to the system requirements database, at https://github.com/r-hub/sysreqsdb

Do you know which DEB / RPM packages you need? Is the source code of your package available? I would need to see what you have in the DESCRIPTION file.

**Comment by lbusett** [comment]
Hi, thanks for the reply !

required packages on DEB:

libcairo2-dev, libatk1.0-dev, libpango1.0-dev, libgtk2.0-dev, libglib2.0-dev  (plus libcurl4-openssl-dev, libgdal-dev, libproj-dev but they seem to already work)

on RPM:

libcairo2-devel, libatk1.0-devel, libpango1.0-devel, gtk2-devel, glib2-devel (plus libcurl4-devel, gdal-devel, proj-devel)

DESCRIPTION is here:

[](https://github.com/lbusett/MODIStsp/blob/cran-mirror/DESCRIPTION)

thanks in advance,  
Lorenzo

**Comment by gaborcsardi** [comment]
- [ ] libcairo2-dev
- [ ] libatk1.0-dev
- [ ] libpango1.0-dev
- [ ] libgtk2.0-dev
- [ ] libglib2.0-dev
- [x] libcurl4-openssl-dev
- [x] libgdal-dev
- [x] libproj-dev

**Comment by gaborcsardi** [comment]
Seems to be OK now: 
https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-00b5a95699274fb8808517314e3b016f#L56

Let me know if you have problems on some platform.

**Comment by lbusett** [comment]
Hi, 
   unfortunately, it seems we are still missing gtk2 lib: 

4877#> * installing *source* package ‘MODIStsp’ ...
4878#> Package gtk+-2.0 was not found in the pkg-config search path.
4879#> Perhaps you should add the directory containing `gtk+-2.0.pc'
4880#> to the PKG_CONFIG_PATH environment variable
4881#> No package 'gtk+-2.0' found
4882#> Package gtk+-2.0 was not found in the pkg-config search path.
4883#> Perhaps you should add the directory containing `gtk+-2.0.pc'
4884#> to the PKG_CONFIG_PATH environment variable
4885#> No package 'gtk+-2.0' found
4886#> Using PKG_CFLAGS=
4887#> Using PKG_LIBS=

In the line of the "build" installing the required packages I now have: 

echo apt-get update && apt-get install -y libatk1.0-dev libproj-dev libglib2.0-dev libcairo2-dev libpango1.0-dev gdal-bin make libcurl4-openssl-dev libgdal-dev libgeos-dev libxml2-dev pandoc pandoc-citeproc libpng-dev libssl-dev zlib1g-dev

so, the "other" packages I signalled you are there (libcairo2-dev, libglib2.0-dev , libpango1.0-dev, libatk1.0-devel), while "libgtk2.0-dev" seems still to be missing. 

Lorenzo

**Comment by gaborcsardi** [comment]
Ooops, messed up the GTK+ regex, should be OK now.

**Comment by lbusett** [comment]
Ok. Checking now, thanks !

**Comment by lbusett** [comment]
Perfect ! Now "check_on_linux" gives me a clean install.
I'll try the other platforms and let you know !

thanks,

Lorenzo

**Comment by lbusett** [comment]
Even if I don't think it's related to the previous problem, I signal you that with check_on_fedora() I get this error : 

1781#> About to run xvfb-run R CMD check MODIStsp_1.3.0.tar.gz
1782#> * using log directory ‘/home/docker/MODIStsp.Rcheck’
1783#> * using R Under development (unstable) (2016-10-30 r71610)
1784#> * using platform: x86_64-pc-linux-gnu (64-bit)
1785#> * using session charset: UTF-8
1786#> * checking for file ‘MODIStsp/DESCRIPTION’ ... OK
1787#> * checking extension type ... Package
1788#> * this is package ‘MODIStsp’ version ‘1.3.0’
1789#> * checking package namespace information ... OK
1790#> * checking package dependencies ...Warning: unable to access index for repository https://bioconductor.org/packages/3.5/data/annotation/src/contrib:
1791#> cannot download all files
1792#> ERROR
1793#> Packages required but not available:
1794#> ‘gdalUtils’ ‘rgdal’ ‘rgeos’ ‘XML’ ‘xml2’ ‘httr’ ‘pacman’

**Comment by gaborcsardi** [comment]
That's not the problem here, but one of these packages failed to install. Do you have the full build log?

**Comment by lbusett** [comment]
It's here: 
https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-6ede068a2e8a456f82c148b1b3afed13

**Comment by lbusett** [comment]
Also seeing a problem on openssl: 

#> ---------------------------------------------

 595#> The OpenSSL library that is required to
 596#> build git2r was not found.
 597#> Please install:
 598#> libssl-dev (package on e.g. Debian and Ubuntu)
 599#> openssl-devel (package on e.g. Fedora, CentOS and RHEL)

**Comment by gaborcsardi** [comment]
> Also seeing a problem on openssl:

Which platform?

**Comment by lbusett** [comment]
Also on Fedora.

On CENTOS, instead, openssl seems to be ok. 

I get however a similar problem of missing packages, although with less packages:
(only ‘gdalUtils’ ‘rgdal’ ‘rgeos’)

#> ERROR: dependencies ‘gdalUtils’, ‘rgdal’, ‘rgeos’ are not available for package ‘MODIStsp’
5836#> * removing ‘/home/docker/R/MODIStsp’
5837#> >
5838#> >
5839#> Warning messages:
5840#> 1: In utils::install.packages(...) :
5841#> installation of package ‘rgdal’ had non-zero exit status
5842#> 2: In utils::install.packages(...) :
5843#> installation of package ‘rgeos’ had non-zero exit status
5844#> 3: In utils::install.packages(...) :
5845#> installation of package ‘gdalUtils’ had non-zero exit status
5846#> 4: In utils::install.packages(...) :
5847#> installation of package ‘/tmp/Rtmp8Lww83/remotesa55116c973/MODIStsp’ had non-zero exit status

Full log: 

https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-09c827540de949f89e018a6895f5b63f

**Comment by lbusett** [comment]
Ok... rpm build of `proj` seems also to require: `proj-epsg` and  `proj-nad`

also, on fedora and centos: library for "libpango" is probably just `pango`, and libcurl should be `libcurl-devel` instead than `libcurl4-devel` 

what a mess... tomorrow I'll try to boot-up a Fedora VM, so that I can properly check these...

**Comment by gaborcsardi** [comment]
Thanks! Sorry for the delay. proj4 installs cleanly now on all Fedora and CentOS platform, using these dependencies: https://github.com/r-hub/sysreqsdb/blob/master/sysreqs/libproj.json

I'll check these in a minute:
- [ ] gdalUtils
- [ ] rgdal
- [ ] rgeos
- [ ] XML
- [ ] xml2
- [ ] httr
- [ ] pacman

**Comment by gaborcsardi** [comment]
`XML` and `xml2` should be OK already: https://sysreqs.r-hub.io/pkg/XML https://sysreqs.r-hub.io/pkg/xml2

**Comment by lbusett** [comment]
Thanks! I'll try it this afternoon and let you know.

**Comment by gaborcsardi** [comment]
The reason for the errors (some of them at least) is that RPM-based distros don't have `libpango1.0-devel` and `libatk1.0-devel`. They have `pango-devel` and `atk-devel`. Nevertheless I'll check the other packages as well.

**Comment by gaborcsardi** [comment]
`MODIStsp` installs fine now: https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-47dfe86aff914ffc9cbd4a8b19fb263e

Please re-open if not. I'll also see if I can get `framed.sty` for the vignette.

**Comment by lbusett** [comment]
Thank you very much. Trying to keep track of all the different names of packages in Linux distros must be a mess... 

A brief report: 

**check_on_linux**: OK - Although the mail I receive says "PREPERROR", the build is ok. 
(https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-bb624f2ff0ff4feb82e317336721217b)

**check_on_fedora**: seems OK - only the problem aboute "framed.sty", now. 

**check_on_CENTOS**: Errored on rgeos installation (

10919#> ** building package indices
10920#> ** testing if installed package can be loaded
10921#> Error in dyn.load(file, DLLpath = DLLpath, ...) :
10922#> unable to load shared object '/home/docker/R/rgeos/libs/rgeos.so':
10923#> /home/docker/R/rgeos/libs/rgeos.so: undefined symbol: rgeos_nearestpoints
10924#> Error: loading failed
10925#> Execution halted
10926#> ERROR: loading failed
10927#> * removing ‘/home/docker/R/rgeos’)- 

https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-af3ce13bd6444f1ab21456af9dfbdae1

**check_on_windows**: Errored with this "Infinite loop" error: 

 178#> Error in inDL(x, as.logical(local), as.logical(now), ...) :
 179#> unable to load shared object 'C:/Users/USEROetUvsqzTb/R/RGtk2/libs/x64/RGtk2.dll':
 180#> LoadLibrary failure: The specified module could not be found.
 181#> Warning: Failed to load RGtk2 dynamic library, attempting to install it.
 182#> Please install GTK+ from http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip
 183#> If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
 184#> IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN

https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-f291cde7d162456d8a1a81865481a0bf#L7122

This is an error I already had beforfe - related to GTK+ isntallation on Windows (I'm sorry, it wasn't apparent before because I had an error in my Imports)

Lorenzo

**Comment by lbusett** [comment]
I forgot to mention: 

devtools::build_win() goes well on the same package 

https://win-builder.r-project.org/SmWVy1jMfF6l/

**Comment by gaborcsardi** [comment]
The R-hub win builder machine does not have Gtk yet.

**Comment by lbusett** [comment]
oks, no problem. It was just to let you know !
