### ISSUE TITLE
Cargo is not installed on `Windows Server 2022, R-devel, 64 bit` 

### ISSUE THREAD

**Issue by eitsupi** [r-hub/rhub#550]
First, thank you for maintaining this excellent service.

Recently cargo has been available on CRAN builders (r-rust/hellorust#12) and several packages have been compiled using cargo.
https://cran.r-project.org/package=string2path
https://github.com/yutannihilation/string2path

However, there seems to be no cargo on the Windows R-hub builder.

**Comment by JosiahParry** [comment]
I too, would like to thank you for the service! Particularly useful as I don't have a windows machine. 

I came across this issue this week. I attempted to check my Rust based R packge using R Hub. Compilation failed because cargo is not available. Is there a plan on adding it? 

Thanks!

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
