### ISSUE TITLE
Facing Problem to publish my first package

### ISSUE THREAD

**Issue by Fredysessie** [r-hub/rhub#551]
I'm trying to create my first package but i'm having only one error regarding to 00.install.out 

Error in library(httr2) : aucun package nommé 'httr2' n'est trouvé

![image](https://user-images.githubusercontent.com/89697268/222890372-38d656ce-6200-433e-821c-33f4c7de1d1f.png)

![image](https://user-images.githubusercontent.com/89697268/222891060-8c25bdf2-8da4-4c31-aadd-3d2566dad230.png)

**Comment by gaborcsardi** [comment]
This is the issue tracker of the rhub R package, and your problem does not seem to be related to this package. I suggest you post on https://community.rstudio.com/. Also, seems like you want to import another package in yours, so I suggest reading this chapter: https://r-pkgs.org/dependencies-mindset-background.html
