### ISSUE TITLE
Yen symbol in my console and script window

### ISSUE THREAD

**Issue by neuro-jo** [r-hub/rhub#552]
I can't seem to type a backslash into RStudio's console or script window. Copy/paste functions still paste \ as a yen symbol, though when I type \ in any browser, document or the "find" bar in R, it reflects as a \ and not a Yen symbol

**Comment by gaborcsardi** [comment]
I understand that this is annoying, but nevertheless it is not an issue with the rhub R package or R-hub, so I suggest you ask at https://community.rstudio.com/
