### ISSUE TITLE
Some errors occur when submitting R packages

### ISSUE THREAD

**Issue by chuiqin** [r-hub/rhub#553]
Thank you for developing such a useful tool. However, today I found that whether I submit my R package through the website (https://builder.r-hub.io/) or submit my R package through the R package rhub, it shows `We're sorry, but something went wrong`. Even after waiting 3 hours, r-hub can't successfully check my R package. Before that, r-hub only took about 15 minutes to check my R package. I resubmitted an R package that I was sure could be checked successfully on r-hub, but it still didn't work. Looking forward to your reply! Thanks!
![image](https://user-images.githubusercontent.com/65839548/226565869-a703e016-d1e6-4985-9c4f-51be1d6c871b.png)

**Comment by gaborcsardi** [comment]
There are a lot of jobs waiting, I am afraid that you'll need to wait for the email from R-hub.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
