### ISSUE TITLE
Deldir 1.0-8 PREPERROR

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#557]
I tried to build a Windoze binary of a new version (1.0-8) of my deldir package using

library(rhub)
xxx <- check("deldir_1.0-8.tar.gz",platform="windows-x86_64-release")

At the 5th step (" Downloading and unpacking package file") the progress indicator just spins and spins, endlessly.  I finally hit control-C to stop the process.

I've tried severarl times.  Each time I get an email with the subject line "deldir 1.0-8 PREPERROR".  I have looked at the build log, but it is pretty opaque to me. The crucial issue seems to be
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
At C:\Users\USERALnRsdCoaQ\slave.ps1:127 char:5
+     [void]$Process.Start()
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

and similar "Exceptions".  I have no idea what this means or what to do about it.
Can anyone advise me?

After a while I gave up on rhub and built the Windoze binary using Winbuilder.
That worked fine; no errors or warnings resulted.  So whatever the problem is with rhub, it would appear to be subtle.

The problem is not urgent, since I got the Windoze binary built by other means,
but I *would* like to understand what is going on.

**Comment by gaborcsardi** [comment]
Thanks for the report! Hopefully this is now fixed, can you try one more time? Thanks!

**Comment by rolfTurner** [comment]
On Tue, 2 May 2023 06:26:07 +0000
Gábor Csárdi ***@***.***> wrote:

> Thanks for the report! Hopefully this is now fixed, can you try one
> more time? Thanks!
> 

Tried it just now, and all went smoothly.  Thanks hugely.  This is what
I call *service*!!! 😊️

cheers,

Rolf

-- 
Honorary Research Fellow
Department of Statistics
University of Auckland
Stats. Dep't. (secretaries) phone:
         +64-9-373-7599 ext. 89622
Home phone: +64-9-480-4619
