### ISSUE TITLE
Sanitizer image defaults to gnu++98

### ISSUE THREAD

**Issue by fhenz** [r-hub/rhub#559]
Hello,
since R 4.3, `C++17` is the default and CMD check raises a note if an older standard (e.g. `C++11`) is specified.
Consequently I removed this from my package, but when submitting via `check_with_sanitizers` I get compiler errors and I see in the logs that g++ receives `-std=gnu++98`.
I am not super familiar with docker but I assume this is because the original r-devel-san image has `CXXSTD=-std=gnu++98` hardcoded?

For now I workaround this by re-adding the `C++11` specification for just the sanitizer image check and removing it again afterwards (I guess you could also just specify `C++17` since that shouldn't raise a note with CMD check).

**Comment by Konrad1991** [comment]
I have the same issue. However, I cannot use the workaround. My package needs RcppArmadillo and the installation of RcppArmadillo fails as it needs C++11.

**Comment by stephematician** [comment]
I have also had this issue attempting to build a package that uses [cpp11](https://github.com/r-lib/cpp11).

I can 'workaround' this by setting `PKG_CXXSTD` in Makevars, however this has to be removed for any CRAN submission.

On a side note - g++ doesn't support some important features of AddressSanitiser (like container overflow)... clang seems like a better option,

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
