### ISSUE TITLE
Error while installing "cairoDevice"

### ISSUE THREAD

**Issue by lbusett** [r-hub/rhub#56]
Hi, 

   on Linux builds, I get an error while installing the "cairoDevice" package - maybe related to the virtual machine being "headless" ? 

1334#> ** R
1335#> ** demo
1336#> ** preparing package for lazy loading
1337#> ** help
1338#> *** installing help indices
1339#> ** building package indices
1340#> ** testing if installed package can be loaded
1341#> Error : .onLoad failed in loadNamespace() for 'cairoDevice', details:
1342#> call: fun(libname, pkgname)
1343#> error: GDK display not found - please make sure X11 is running
1344#> Error: loading failed
1345#> Execution halted
1346#> ERROR: loading failed

**Comment by gaborcsardi** [comment]
Can you please always have a link to the _full_ log. I think this happens when the package is installed, and that runs without X11. Only the check has X11. Clearly a bug.

**Comment by lbusett** [comment]
Here it is: 
https://builder.r-hub.io/status/MODIStsp_1.3.0.tar.gz-7fa7d2d82c0e4cedbc335e0e20ec4307

sorry, I thought of simplifying your life by sending only the relevant lines... 

Lorenzo

**Comment by gaborcsardi** [comment]
`cairoDevice` should be OK now, thanks for the report!

**Comment by lbusett** [comment]
Yes, seems to be working now ! Thanks !
