### ISSUE TITLE
'Something went wrong'

### ISSUE THREAD

**Issue by DesiQuintans** [r-hub/rhub#561]
Tried to [check a new package](https://builder.r-hub.io/status/sift_1.0.0.tar.gz-21f4b257ea652acb4f96eeb5c22058c1) and received this error:

![image](https://github.com/r-hub/rhub/assets/3200601/bfbc2b1b-dd5c-4d7d-bb78-ebbc87ca8937)

> We're sorry, but something went wrong.
> 
> If you are the application owner check the logs for more information.

It's similar to https://github.com/r-hub/rhub/issues/293, hopefully an easy fix! R-Hub is great <3

**Comment by jromanowska** [comment]
I have the same problem! :-/

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
