### ISSUE TITLE
ANTICONF ERROR on Debian Linux, R-devel, GCC ASAN/UBSAN

### ISSUE THREAD

**Issue by LixiangZhang** [r-hub/rhub#567]
Hi,

When running the check, i.e. rhub::check_for_cran(), the only error we received is PREPERROR (ANTICONF ERROR on Debian Linux, R-devel, GCC ASAN/UBSAN). Here is the log link: https://builder.r-hub.io/status/original/OTclust_1.0.5.tar.gz-d33e6ed4f8e24792871fac5539861dd2

It seems the some dependency packages can not be properly installed on Debian Linux. Could you please help take a look? Thanks a lot!

Best,
Lixiang

**Comment by LixiangZhang** [comment]
PS: It seems similar issue also happened on Ubuntu Linux 20.04.1 LTS, R-release, GCC. Log link: https://builder.r-hub.io/status/original/OTclust_1.0.5.tar.gz-84e8bee677b948a38d834f8c71564cb8

**Comment by gaborcsardi** [comment]
Fixed here: https://github.com/r-hub/sysreqsdb/commit/9d0cea2fa1becb4fe6edf8b7995ba1c6e5f9214c

**Comment by nie23wp8738** [comment]
> Fixed here: [r-hub/sysreqsdb@9d0cea2](https://github.com/r-hub/sysreqsdb/commit/9d0cea2fa1becb4fe6edf8b7995ba1c6e5f9214c)

What does this mean?

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
