### ISSUE TITLE
Checks fail on Ubuntu Linux 20.04.1 LTS as ‘raster’, ‘sf’, ‘terra’, ‘animation’, ‘rasterVis’ are not available

### ISSUE THREAD

**Issue by azvoleff** [r-hub/rhub#569]
Trying to test a package on Ubuntu Linux 20.04.1, R-release I get a PREPERROR as as ‘raster’, ‘sf’, ‘terra’, ‘animation’, ‘rasterVis’ are not available (they fail to install). [This is the check](https://builder.r-hub.io/status/original/gfcanalysis_1.8.0.tar.gz-fea864f6ffc24bbba9977cfcd2b3d810).

Could be related to #458

**Comment by gaborcsardi** [comment]
This is because:
```
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Package 'libav-tools' has no installation candidate
E: Unable to locate package swftools
```

Should be fixed by https://github.com/r-hub/sysreqsdb/commit/7098b7c4bb8302359b72a1e95a922b36185fb742 and https://github.com/r-hub/sysreqsdb/commit/4609f9ae2516349c82f06d9be544f37d96e76233

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
