### ISSUE TITLE
README: Mention validate_email() in plain text too

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#57]
Just noticed that `validate_email()` is only mentioned as part of a screenshot image, but it's not part of the README text per se.  Not possible to search (and not visible if you don't see the image - which happened when I told someone else to try out `rhub`).

**Comment by gaborcsardi** [comment]
Makes sense. `check()` will ask you to validate your email, though, AFAIR.

**Comment by HenrikBengtsson** [comment]
Yup, `check()` did that, but the person was checking a package where it was his student who was listed as the maintainer and then the only options is to quit / escape ("by pressing ENTER" or something).  That's when I referred him to try to run `validate_email()` first.

**Comment by gaborcsardi** [comment]
Thanks, this is useful. So the help text in this case could point out that you can also supply an `email` argument to `check()`, I think.

**Comment by HenrikBengtsson** [comment]
Ah... brain is still mushy from jet lag and election PTSD.  So, you're saying instead of having him do:
```r
validate_email() # once
check(email = "joe@doe.org")
```
he could have just done:
```r
check(email = "joe@doe.org")
```

**Comment by gaborcsardi** [comment]
Yes, and since the default of `email` is the maintainer, the latter is almost the same, because even if you do the former, you still need to specify `email`. (Or change it in DESCRIPTION.)

Nevertheless the interactive help screen should be better and it should 
* suggest using `email=`, and 
* offer using one of your validated emails.

**Comment by HenrikBengtsson** [comment]
Those options sounds user friendly, especially for first timers.

**Comment by gaborcsardi** [comment]
I will just revamp the UI, based on the experience so far: #117
