### ISSUE TITLE
Checks fail on `RPostgreSQL` due to missing `libpq-fe.h` header

### ISSUE THREAD

**Issue by averissimo** [r-hub/rhub#571]
Package failing on build: [RPostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/) (CRAN)

This is happening on 3 of the platforms with `rhub::check_for_cran`:

- `Fedora Linux, R-devel, clang, gfortran` - [build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-7af08fe67ab84a389ef533bed7fe798d)
- `Ubuntu Linux 20.04.1 LTS, R-release, GCC` - [build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-767fa945bc024cda98995cd840601d80)
- `Debian Linux, R-release, GCC` - [build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-eeb12bdd2b534f09a08d6f0f6e5775b3)

For ubuntu this should fix the problem: `sudo apt-get install libpq-dev`

note: `Windows Server 2022, R-devel, 64 bit` ([build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-1b62b31c074f423398a3a16a408d35b5)) and `Windows Server 2022, R-release, 32/64 bit` ([build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-18bb0fd78c4946b8878b0894d5dc47f2)) were successfully

**Comment by gaborcsardi** [comment]
Thanks, fixed here: https://github.com/r-hub/sysreqsdb/commit/d8424555abd6b06bbfdacfba448f68a51dab4453

Should be good now.

**Comment by averissimo** [comment]
Thanks for the quick reply, I see that the problem is solved on Ubuntu builds, but not in Fedora [build](https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-8348ea1ecba944af83e6f7d010a3d70a)

> ```
>using C compiler: ‘clang version 14.0.5 (Fedora 14.0.5-2.fc36)’
> /usr/bin/clang -I"/opt/R-devel/lib64/R/include" -DNDEBUG -I  -I/usr/local/include    -fpic  -g -O2  -c RS-DBI.c -o RS-DBI.o
> /usr/bin/clang -I"/opt/R-devel/lib64/R/include" -DNDEBUG -I  -I/usr/local/include    -fpic  -g -O2  -c RS-PQescape.c -o RS-PQescape.o
> In file included from RS-PQescape.c:7:
> ./RS-PostgreSQL.h:23:14: fatal error: 'libpq-fe.h' file not found
> #    include "libpq-fe.h"
>              ^~~~~~~~~~~~
> 1 error generated.
> make: *** [/opt/R-devel/lib64/R/etc/Makeconf:191: RS-PQescape.o] Error 1
> ERROR: compilation failed for package ‘RPostgreSQL’
> * removing ‘/home/docker/R/RPostgreSQL’
> ```

**Comment by gaborcsardi** [comment]
I cannot check this now, but hopefully this fixes it for RPM distros: https://github.com/r-hub/sysreqsdb/commit/91075e18efeb9ca6e1cb2f4184c4911843484c77

**Comment by averissimo** [comment]
I confirm it works on Fedora. https://builder.r-hub.io/status/original/shiny.telemetry_0.2.0.tar.gz-d8dc9a5772984a3da811673a6404df44

Thanks

**Comment by gaborcsardi** [comment]
Thanks for the report!
