### ISSUE TITLE
rhub::check() stalls

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#572]
I have been trying to build a Windoze binary of my package "deldir"  via

yyy <- check("deldir_1.0-11.tar.gz",platform="windows-x86_64-release")

The procedure gets to a state where it says it is "Downloading and unpacking package file",
and the slash and backslash spin or alternate endlessly.  Eventually it times out and  I get an email from rhub with subject line "deldir 1.0-11: PREPERROR".

This email directs me to a URL:

https://builder.r-hub.io/status/deldir_1.0-11.tar.gz-31df1c6bdd2b4665b0f89dbd756f021b

There is a great deal of material displayed, with a number of "Exceptions" listed, but this material is completely opaque to me.  It ends by saying "#> Finished: FAILURE".

Can anyone guide me as to how to track down what is going wrong or as to how to get the build to run to completion?

**Comment by gaborcsardi** [comment]
Thanks, can you try again please?

**Comment by rolfTurner** [comment]
On Sun, 19 Nov 2023 07:37:39 +0000
Gábor Csárdi ***@***.***> wrote:

> Thanks, can you try again please?

Did so and it went like a train!  Thanks.
-- 
Honorary Research Fellow
Department of Statistics
University of Auckland
Stats. Dep't. (secretaries) phone:
         +64-9-373-7599 ext. 89622
Home phone: +64-9-480-4619
