### ISSUE TITLE
R won't build with MKL suggested options using ICX/ICPX

### ISSUE THREAD

**Issue by atb1r21** [r-hub/rhub#574]
Hi,

Intel One API are moving away from ICC/ICPC towards ICX/ICPX (they mainly have moved away from it already).

When trying to build R today I have been doing the following with the Intel Classic Compiler (ICC):

export CC=icc
export FC=ifort
export F77=ifort
export CXX=icpc
export CXXFLAGS="-std=c++17"
export CFLAGS=-O3

./configure --prefix=/local/software/R/4.3.1/install/ --with-blas=-qmkl=parallel --with-lapack=-qmkl=parallel --enable-R-shlib --with-x=no --with-pcre1 --with-cairo

make -j16
make install

Which works without issues, aside from obvious complaints that I shouldn't be using ICC as it is deprecated.

When I do the same but 

**export CC=icx**
export FC=ifort
export F77=ifort
**export CXX=icpx**
export CXXFLAGS="-std=c++17"
export CFLAGS=-O3

./configure --prefix=/local/software/R/4.3.1/install/ --with-blas=-qmkl=parallel --with-lapack=-qmkl=parallel --enable-R-shlib --with-x=no --with-pcre1 --with-cairo

make -j16 

It fails to build and stops at: 

installing 'sysdata.rda'
Error in rep(alist(a = ), ndim) : invalid 'length.out' argument
Calls: loadNamespace -> parseNamespaceFile -> unique -> unique.matrix
Execution halted
make[4]: *** [sysdata] Error 1
make[4]: Leaving directory `/mainfs/local/software/R/4.3.1/source/R-4.3.1/src/library/tools'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/mainfs/local/software/R/4.3.1/source/R-4.3.1/src/library/tools'
make[2]: *** [R] Error 1
make[2]: Leaving directory `/mainfs/local/software/R/4.3.1/source/R-4.3.1/src/library'
make[1]: *** [R] Error 1
make[1]: Leaving directory `/mainfs/local/software/R/4.3.1/source/R-4.3.1/src'
make: *** [R] Error 1

I have experienced this error with R 4.3.1 and R 4.3.2 today, using the 2023.2 Intel one API compilers and MKL.

Is there a known fix for the above, or is this a new bug?

**Comment by gaborcsardi** [comment]
This issue does not seem to have much to do with R-hub, so I am going to close it.
