### ISSUE TITLE
Build timed out (after 20 minutes). Marking the build as failed.

### ISSUE THREAD

**Issue by yamagubed** [r-hub/rhub#575]
Hi,

I was running rhub::check_for_cran() to get my own package ready for CRAN, but I got the following message and the check failed:
Build timed out (after 20 minutes). Marking the build as failed.
Build was aborted

The full build log is here:
https://builder.r-hub.io/status/psBayesborrow_1.0.0.tar.gz-532e7d4a891a41a6afbaf6ad7efe4f32#L8196

I appreciate if you could help me solve this error.

**Comment by gaborcsardi** [comment]
Yes, there is a timeout of 20 minutes if your build does not produce any output. Try to modify your tests or examples or vignettes that are taking more than 20 minutes. You can break them up, and/or make them produce some output.

If they are not supposed to take that long, then this is probably a freeze in your check.

**Comment by yamagubed** [comment]
Thank you for your prompt reply. I've checked that tests or examples or vignettes don't take more than 20 mins. The following is a part of the build log I can see the error, so do you think there is a freeze in the check?

Running R CMD check
8159#> About to run xvfb-run R CMD check --as-cran psBayesborrow_1.0.0.tar.gz
8160#> 'getOption("repos")' replaces Bioconductor standard repositories, see
8161#> 'help("repositories", package = "BiocManager")' for details.
8162#> Replacement repositories:
8163#> CRAN: https://cloud.r-project.org
8164#> * using log directory ‘/home/docker/psBayesborrow.Rcheck’
8165#> * using R Under development (unstable) (2023-12-26 r85738)
8166#> * using platform: x86_64-pc-linux-gnu
8167#> * R was compiled by
8168#> clang version 14.0.5 (Fedora 14.0.5-2.fc36)
8169#> GNU Fortran (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
8170#> * running under: Fedora Linux 36 (Container Image)
8171#> * using session charset: UTF-8
8172#> * using option ‘--as-cran’
8173#> * checking for file ‘psBayesborrow/DESCRIPTION’ ... OK
8174#> * this is package ‘psBayesborrow’ version ‘1.0.0’
8175#> * package encoding: UTF-8
8176#> * checking CRAN incoming feasibility ... [6s/30s] NOTE
8177#> Maintainer: ‘Yusuke Yamaguchi ’
8178#> New submission
8179#> License components with restrictions and base license permitting such:
8180#> MIT + file LICENSE
8181#> File 'LICENSE':
8182#>
8183#> Possibly misspelled words in DESCRIPTION:
8184#> RCT (16:155)
8185#> RCTs (16:224)
8186#> confounders (16:407)
8187#> * checking package namespace information ... OK
8188#> * checking package dependencies ... OK
8189#> * checking if this is a source package ... OK
8190#> * checking if there is a namespace ... OK
8191#> * checking for executable files ... OK
8192#> * checking for hidden files and directories ... OK
8193#> * checking for portable file names ... OK
8194#> * checking for sufficient/correct file permissions ... OK
8195#> * checking serialization versions ... OK
8196#> * checking whether package ‘psBayesborrow’ can be installed ...Build timed out (after 20 minutes). Marking the build as failed.
8197#> Build was aborted
8198#> Pinging https://builder.r-hub.io/build/FAILURE/psBayesborrow_1.0.0.tar.gz-532e7d4a891a41a6afbaf6ad7efe4f32/2024-01-29T03:28:40Z
8199#> {"status":"ok"}
8200#> Finished: FAILURE

**Comment by gaborcsardi** [comment]
Seems like it takes a long time to compile the package? Is that possible?

**Comment by yamagubed** [comment]
Yes, the compile would take more than 20 min.
