### ISSUE TITLE
PREPERROR: Debian Linux, R-devel, GCC ASAN/UBSAN 

### ISSUE THREAD

**Issue by nie23wp8738** [r-hub/rhub#576]
![WechatIMG1558](https://github.com/r-hub/rhub/assets/149007914/f14124c3-ae20-4ba9-9570-d014991525a2)
HTML:[https://builder.r-hub.io/status/HDNRA_1.0.0.tar.gz-0cc20e94585040308e9220555270a1e2](url)

From the above link, the status is success, but I still this problem.

**Comment by gaborcsardi** [comment]
What is your question?

**Comment by gaborcsardi** [comment]
I am sorry, you will have to be more specific? What is the error you see in the log? The preperror itself might be nothing. Did you see an installation or other error? If yes, what is the error message?

**Comment by nie23wp8738** [comment]
> I am sorry, you will have to be more specific? What is the error you see in the log? The preperror itself might be nothing. Did you see an installation or other error? If yes, what is the error message?

This the error when I ran this code: results <- rhub::check_for_cran().
And I want to use this code results$cran_summary() to summary of my results, because of the error, it did not work.

**Comment by gaborcsardi** [comment]
You need to look at the log file to see if there is an error. I took a quick look and it seems to me that there is no error, but you might see this false positive: #445.

**Comment by nie23wp8738** [comment]
> You need to look at the log file to see if there is an error. I took a quick look and it seems to me that there is no error, but you might see this false positive: #445.

<img width="790" alt="image" src="https://github.com/r-hub/rhub/assets/149007914/8954f5fe-ac70-4532-9b03-9872b12b40ca">
This is my error

**Comment by nie23wp8738** [comment]
> You need to look at the log file to see if there is an error. I took a quick look and it seems to me that there is no error, but you might see this false positive: #445.

<img width="1079" alt="image" src="https://github.com/r-hub/rhub/assets/149007914/47fdf399-e6b5-43ba-bad9-a32129af24bd">
another error

**Comment by gaborcsardi** [comment]
Those are not errors with your R package. You need to look at the output of `R CMD check`.

**Comment by nie23wp8738** [comment]
> Those are not errors with your R package. You need to look at the output of `R CMD check`.

<img width="538" alt="image" src="https://github.com/r-hub/rhub/assets/149007914/a57c7c65-1f4c-4008-a7c5-a7b074c04a5c">
I'm a new r package developer, I just know how to do it。
That the error in 00check.log after  run R CMD check --as-cran HDNRA_1.0.0.tar.gz

**Comment by nie23wp8738** [comment]
> Those are not errors with your R package. You need to look at the output of `R CMD check`.

<img width="801" alt="image" src="https://github.com/r-hub/rhub/assets/149007914/0c6f0bf0-2474-4f84-b117-2daaf8ad2da7">
this is the results after run rhub::list_my_checks(email = "nie23.wp8738@e.ntu.edu.sg")
