### ISSUE TITLE
jags does not appear to be installed on Fedora Linux, R-devel, clang, gfortran

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [r-hub/rhub#578]
Doing a package check using  devtools;:check_rhub()

Fedora Linux, R-devel, clang, gfortran fails with message ...

ERROR: dependency ‘R2jags’ is not available for package ‘BTSPAS’
* removing ‘/home/docker/R/BTSPAS’
Warning messages:
1: In i.p(...) : installation of package ‘rjags’ had non-zero exit status
2: In i.p(...) : installation of package ‘R2jags’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/Rtmpn5SWFU/file12f62f21e46/BTSPAS_2024.4.1.tar.gz’ had non-zero exit status
> 
> 

* installing *source* package ‘rjags’ ...
** package ‘rjags’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
configure: WARNING: pkg-config file for jags 4 unavailable
configure: WARNING: Consider adding the directory containing `jags.pc`
configure: WARNING: to the PKG_CONFIG_PATH environment variable
configure: Attempting legacy configuration of rjags
checking for jags... no
configure: error: "automatic detection of JAGS failed. Please use pkg-config to locate the JAGS library. See the INSTALL file for details."
ERROR: configuration failed for package ‘rjags’
* removing ‘/home/docker/R/rjags’

See https://builder.r-hub.io/status/original/BTSPAS_2024.4.1.tar.gz-ed4a5d245f014c3895b10f4cd13d79d5

Thanks
Carl Schwarz

**Comment by gaborcsardi** [comment]
System dependencies are installed as needed, you need to declare them in the `SystemRequirements` field of your package. 

That said, I suggest you try https://github.com/r-hub/rhub2 instead.

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks for your reply, but mmm..the Description file does contain the
following line

SystemRequirements: JAGS

So not clear why it cannot find it?

Carl

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
