### ISSUE TITLE
PREPERROR: package `Matrix` non-zero exit status on  Debian Linux, R-devel, GCC ASAN/UBSAN

### ISSUE THREAD

**Issue by emmekeaarts** [r-hub/rhub#580]
Hi, 

Doing a package check using devtools;:check_rhub() on Debian Linux, R-devel, GCC ASAN/UBSAN, it fails because the package Matrix (and all other packages that depend on Matrix, such as MCMCpack) has a non-zero exit status: 

#> ERROR: dependency ‘MCMCpack’ is not available for package ‘mHMMbayes’

In addition: Warning messages:
1: In i.p(...) : installation of package ‘Matrix’ had non-zero exit status
 2: In i.p(...) :
 installation of package ‘MatrixModels’ had non-zero exit status
 3: In i.p(...) :
 installation of package ‘survival’ had non-zero exit status
 4: In i.p(...) :
 installation of package ‘quantreg’ had non-zero exit status
 5: In i.p(...) :
 installation of package ‘MCMCpack’ had non-zero exit status
 Execution halted

Digging in further: 
 Creating a generic function for ‘chol2inv’ from package ‘base’ in package ‘Matrix’
2923#> Creating a generic function for ‘diag’ from package ‘base’ in package ‘Matrix’
2924#> Creating a generic function for ‘zapsmall’ from package ‘base’ in package ‘Matrix’
2925#> Error in rematchDefinition(definition, fdef, mnames, fnames, signature) :
2926#> methods can add arguments to the generic ‘zapsmall’ only if '...' is an argument to the generic
2927#> Error: unable to load R code in package ‘Matrix’

Any ideas? 

See https://builder.r-hub.io/status/mHMMbayes_1.1.0.tar.gz-c8cc71f81f2444839a458251a5068caf

Thanks, 
Emmeke Aarts

**Comment by gaborcsardi** [comment]
I suggest you try the new version of the rhub package from https://github.com/r-hub/rhub:
```
pak::pkg_install("r-hub/rhub")
```

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
