### ISSUE TITLE
Install pandoc

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#582]
Always? Should be fast enough.

**Comment by danielinteractive** [comment]
Agree that this would be important, I also just got
```
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
```
on `clang18`.

**Comment by chrismainey** [comment]
> Agree that this would be important, I also just got
> 
> ```
> Error running filter pandoc-citeproc:
> Could not find executable pandoc-citeproc
> ```
> 
> on `clang18`.

Also receiving this, missing pandoc-citeproc on ubuntu clang and 'linux (R-devel)' to Ubuntu 22.04.4. 
Checks on same package complete fine on windows with R-devel, other linux versions with R-current, and mac OS with R-current and R-devel.

**Comment by gaborcsardi** [comment]
@danielinteractive @chrismainey Can you please link to a failing build? Thanks!

**Comment by gaborcsardi** [comment]
Never mind, this should be fixed now: https://github.com/gaborcsardi/FunnelPlotR/actions/runs/9018187734/job/24778227972

Please reopen or open another issue if you still have problems with Pandoc. Thanks!
