### ISSUE TITLE
No 'xz' package installed on GCC13 container

### ISSUE THREAD

**Issue by shikokuchuo** [r-hub/rhub#600]
On the new GitHub actions runners.

For example, please see the run here: https://github.com/shikokuchuo/nanonext/actions/runs/8743264562/job/23993440021

I was under the impression that 'xz' can be assumed to be available (as is the case on all CRAN test machines).

Thanks.

**Comment by gaborcsardi** [comment]
You need to specify your package's system requirements in your `DESCRIPTION` file.e

**Comment by shikokuchuo** [comment]
Thanks Gabor. But that still won't make it available within the container, unless I'm missing something?

**Comment by gaborcsardi** [comment]
Yes, see e.g. 
https://github.com/gaborcsardi/nanonext/commit/14cddb980430bb83efe67388d30704654851180e
https://github.com/gaborcsardi/nanonext/actions/runs/8744330605/job/23996949056#step:5:1156

**Comment by shikokuchuo** [comment]
I had no idea the setup was so advanced! Thanks for taking the time to test it. I've added 'xz' to SystemRequirements and it works for me as well.
