### ISSUE TITLE
rhub error on some platforms

### ISSUE THREAD

**Issue by NicChr** [r-hub/rhub#602]
Hi, I'm getting the following error on some platforms, e.g. ubuntu-clang:

Error in `dyn.load(file, DLLpath = DLLpath, ...)`: unable to load shared object '/github/home/R/x86_64-pc-linux-gnu-library/4.5/collapse/libs/collapse.so':
  libc++.so.1: cannot open shared object file: No such file or directory

The rhub run can be found here: https://github.com/NicChr/cheapr/actions/runs/8779659032/job/24088092947

I'm not sure why I'm getting the error but it seems to happen when calling some collapse functions, which is the main dependency of my package.

**Comment by gaborcsardi** [comment]
Yes, I believe that this is a bug and it happens because the `clang-asan` cache is used for the other builds. 

You can clear the cache manually and re-run the failed builds as a workaround for now.

**Comment by NicChr** [comment]
Thanks for the quick response, I cleared all the caches and re-ran ubuntu-clang which did indeed pass. 
In fact all of them passed with the exception of gcc13 which gave the warning:

❯ checking compilation flags used ... WARNING
  Compilation used the following non-portable flag(s):
    ‘-Werror=format-security’ ‘-Wno-parentheses’
    ‘-Wp,-D_FORTIFY_SOURCE=3’
  including flag(s) suppressing warnings

**Comment by gaborcsardi** [comment]
> Thanks for the quick response, I cleared all the caches and re-ran ubuntu-clang which did indeed pass.
In fact all of them passed with the exception of gcc13 which gave the warning:

I am not sure what your question is here. AFAICT CRAN does not use gcc13 to do checks any more, and probably in the meanwhile R got some new checks for compiler flags, so you get this warning. You can safely ignore these if that's your question.

**Comment by NicChr** [comment]
Many thanks, I'm a bit of a noob so not sure what a compiler flag is really. In any case it's good to know I can ignore them, thanks!

**Comment by gaborcsardi** [comment]
Compiler flags are command line options to the compiler, to change its behavior. E.g. using `-Wno-parentheses` will make the compiler emit warnings that suggest some code changes wrt. parentheses. 

`R CMD check` warns for non-portable compiler flags. When they created the gcc13 check flavour, they used `-Wno-parentheses` and at that time `R CMD check` did not warn for this flag. The current R(-devel) version does, but since they are not using gcc13 any more, they never see this.

We should probably remove gcc13, or mark it as archived or unused.

**Comment by CorradoLanera** [comment]
Just to report my current experience:

rhub fail to:

- install `{renv}` (r-hub/actions/platform-info@v1) on:
  - atlas ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512104015#step:4:17))
- install `{pak}`  (r-hub/actions/setup-deps@v1) on:
  - gcc13 ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512106628#step:5:151))
  - mkl ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512106628#step:5:151))
  - nosuggests ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512107727#step:5:151))
  - valgrind ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512107727#step:5:151))
- strange error in downloading `{renv}` while using `{renv}` to install `{pak}`  (r-hub/actions/setup-deps@v1)  on:
  - intel ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512106628#step:5:151))
- install `{stringi}` (r-hub/actions/setup-deps@v1) on:
  - windows devel ([here](https://github.com/CorradoLanera/CrossClustering/actions/runs/8913217913/job/24512105610#step:5:4366))

**Comment by gaborcsardi** [comment]
@CorradoLanera Those look like completely different errors to me.

You can't use a repo with renv currently: https://github.com/r-hub/rhub/issues/596

stringi is broken on R-devel: https://cran.r-project.org/web/checks/check_results_stringi.html

**Comment by CorradoLanera** [comment]
ok, thanks!

**Comment by gaborcsardi** [comment]
The cache key issue is now fixed in r-hub/actions v1.1.7 (https://github.com/r-hub/actions/blob/main/NEWS.md), so I am closing this now.
