### ISSUE TITLE
rhub error on windows building package 'terra'

### ISSUE THREAD

**Issue by paul-carteron** [r-hub/rhub#605]
Hi, I'm getting the following error on Windows (R-devel) :

```
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/RUNNER~1/AppData/Local/Temp/Rtmpye3fNX/pkg-lib19542f843a61/terra'
```

Build can be found [here](https://github.com/paul-carteron/happign/actions/runs/8967409459/job/24624892252).

There's a lot of `undefined reference` when building [terra](https://github.com/rspatial/terra) from source, which I don't understand.

Thanks in advance !

**Comment by gaborcsardi** [comment]
terra does not work on R-devel Windows currently: https://cran.rstudio.com/web/checks/check_results_terra.html

**Comment by paul-carteron** [comment]
Oh, that's why ! Thanks.
