### ISSUE TITLE
Guidance on which machines to use; JAGS not available on some machines

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [r-hub/rhub#607]
This is a continuation of a previous bug report.
I converted to rhub v.2, and did a rhub_check on my BTSPAS package.

(a) This gives a long list of machines. I choose all of them. THis is likely overkill. 
Please provide some guidance in documentation, or function, on which machines to use in a package check.
For example, I suspect that for most users submitting a package the first 4 machines are enough?

(b) My BTPSAS package needs JAGS.
Some of the machines don't have JAGS installed/not available. 
Please provide guidance on which machine do NOT have JAGS installed.

THanks
Carl Schwarz

**Comment by gaborcsardi** [comment]
CRAN chooses the platforms, not us: 
https://cran.r-project.org/web/checks/check_flavors.html
https://cran.r-project.org/web/checks/check_issue_kinds.html

Re JAGS, it is pre-installed on the Ubuntu libc++ containers, installed on demand automatically on the other Ubuntu VMs and containers, and Fedora does not have JAGS, so it is currently not availables for those. I guess it is now needed by enough packages that I can build a package for Fedora 38, so it'll be installed on demand there as well.

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks ... those links were most helpful in understanding what the various
machines on rhub check and which I can likely safely ignore.
Carl.
