### ISSUE TITLE
No permissions for user data directory on Windows

### ISSUE THREAD

**Issue by noamross** [r-hub/rhub#61]
I have a package that uses `rappdirs::user_data_dir` to create a directory and a local database in it. This occurs during `.onLoad()`, when it checks for presence of the database, and if it doesn't exist, creates it.  This results in a failure on r-hub when installing on Windows.  From [my `00install.out` artifact](https://artifacts.r-hub.io/eidith_0.1.0.tar.gz-0a125192db974bba811fbe6ef0c00e7e/eidith.Rcheck/00install.out):

```
...
*** arch - i386
Warning in dir.create(dirname(current_path), recursive = TRUE) :
  cannot create dir 'C:\Users\Default\AppData\Local\eidith', reason 'Permission denied'
Error : .onLoad failed in loadNamespace() for 'eidith', details:
  call: rsqlite_connect(dbname, loadable.extensions, flags, vfs)
  error: Could not connect to database:
unable to open database file
Error: loading failed
Execution halted
*** arch - x64
...
```

The package does fine on Appveyor and R-hub/Travis Linux builds.

**Comment by gaborcsardi** [comment]
THanks! 

Yes, you cannot just write to that directory on R-hub, the user is restricted. 

I'll need to set up a user-specific `AppData` directory, will do that.

**Comment by gaborcsardi** [comment]
I just deployed this, and it should work. Let me know if you still have problems.
