### ISSUE TITLE
windows-x86_64-oldrel: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by knausb** [r-hub/rhub#62]
I have a package that is currently errored on CRAN r-oldrel-windows:

https://cran.r-project.org/web/checks/check_results_vcfR.html

This appears to be due to a subscript out of bounds error. I do not feel this error is directly relevant to this issue. This error has caused me to be interested in:

    rhub::check( platform = "windows-x86_64-oldrel" )

Which currently fails to build:

https://builder.r-hub.io/status/vcfR_1.3.0.9000.tar.gz-c95e9fa9e1e041e4bc8a7a8d3cf9fa86

This appears to be because it can not find zlib, which my package uses to read gzipped files. The release and devel versions:

    rhub::check( platform = "windows-x86_64-release" )
    rhub::check( platform = "windows-x86_64-devel" )

appear fine.

https://builder.r-hub.io/status/vcfR_1.3.0.9000.tar.gz-1af6d4caa08548249584a9944f5db1e6
https://builder.r-hub.io/status/vcfR_1.3.0.9000.tar.gz-47d2ab211eb24b67a16c697b75738dce

Is this something that should be addressed in `rhub::check( platform = "windows-x86_64-oldrel" )`?

Thank you!

**Comment by gaborcsardi** [comment]
All windows builds run on machines with the same setup, so I am not sure why this happens, but will investigate.

**Comment by gaborcsardi** [comment]
Probably a temporary issue, it does not happen any more.
