### ISSUE TITLE
LaTeX error

### ISSUE THREAD

**Issue by graemeleehickey** [r-hub/rhub#63]
When using `rhub::check()` on my package [`joineRML`](https://cran.r-project.org/web/packages/joineRML/index.html), I get a warning message that the vignette could not be built. Here is a reproducible example using the CRAN package source for `joineRML` (version 0.1.1). Running

```r
library(rhub)

tmpdir <- tempdir()
url <- 'https://cran.r-project.org/src/contrib/joineRML_0.1.1.tar.gz'
file <- basename(url)
download.file(url, file)
setwd(tmpdir)

rhub::check(path = "joineRML_0.1.1.tar.gz", 
            platform = "fedora-gcc-devel")
```

generates the following WARNING

```
* checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
    nobs

The following object is masked from 'package:utils':

    object.size

The following object is masked from 'package:base':

    startsWith

Error: processing vignette 'technical.ltx' failed with diagnostics:
Running 'texi2dvi' on 'technical.ltx' failed.
LaTeX errors:
! LaTeX Error: File `biblatex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.22 ^^M
        
!  ==> Fatal error occurred, no output PDF file produced!
Execution halted
```

However, this warning is not present on the [CRAN checks](https://cran.r-project.org/web/checks/check_results_joineRML.html). BibLaTeX is a standard package, so I am not sure why it cannot be found. I should mention that I am using the `R.rsp` package as my vignette engine to generate my LaTeX vignette, which might be the cause for this.

**Comment by gaborcsardi** [comment]
Will be fixed in #116.
