### ISSUE TITLE
Workflow does not have 'workflow_dispatch' trigger.

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#630]
I keep trying to run rhub::rhub_check(platforms="windows") and it keeps finding new ways to frustrate me.  The output I get is as follows.
```
 library(rhub)
 rhub_check(platforms="windows")
✔ Found git repository at /home/rolf/Rpackages/Kanova/kanova.
✔ Found GitHub PAT.
Error in `rhub_check(platforms = "windows")`:
! :( Failed to start check: Workflow does not have 'workflow_dispatch' trigger.
ℹ If you think this is a bug in the rhub package, please open an issues at
  <https://github.com/r-hub/rhub/issues>.
Type .Last.error to see the more details.
```
How can I arrange for my "workflow" to have  "workflow_dispatch trigger"???
(I must confess that I have no idea what a "workflow" actually is.)

This problem seemed to come out of the blue. In all my previous attempts at using rhub_check() no such error was thrown. Then suddenly ....

**Comment by gaborcsardi** [comment]
You deleted the `rhub.yaml` workflow file: https://github.com/rolfTurner/kanova/commit/0831a8f47415049da0d1fb2d4c1b11825009608a#diff-66448eff86c4360e3d463a58ea3f83d0902a32e4f61a0007e212f91e5fffdd32
`rhub_check()` does not work without this. 
You can run `rhub_setup()` to crete it again.
