### ISSUE TITLE
NOTE from "R check" about hidden file ".github".

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#631]
I'm nearly there, thanks (hugely!) to wise counsel from Gábor Csárdi.

There's just one thing that bothers me slightly:  when I run rhub::rhub_check(...)
I get a NOTE from "R check" to the effect that it
```
Found the following hidden files and directories:
  .github
These were most likely included in error. See section 'Package
structure' in the 'Writing R Extensions' manual.
```
If I remove the .github directory, the procedure crashes at square zero with the problem described in the issue (630) that I previously raised: "Workflow does not have 'workflow_dispatch' trigger.  Gábor explained to me that the file "rhub.yaml" is needed for rhub_check() to work, and that file lives in ".github".

So should I just ignore the aforementioned NOTE?

**Comment by gaborcsardi** [comment]
Add 
```
^[.]github$
```
to your `.Rbuildignore` file.
