### ISSUE TITLE
Missing dependency on Fedora 38 jobs

### ISSUE THREAD

**Issue by albersonmiranda** [r-hub/rhub#633]
Hello there! 👋🏽

[CRAN requests](https://cran.r-project.org/web/packages/using_rust.html) that Rust dependencies are vendored instead of downloaded at compilation time:

>In most cases all the Rust software can be bundled into the package via cargo vendor. (Thanks to Hiroaki Yutani for providing an example of doing that in his string2path package, version 0.1.5 at the time of writing.) Please tar the included Rust sources using xz compression. If the bundle is too large to be included in the package sources, it could be hosted at a long-term secure site under the maintainer’s control.

But `xz` package is missing on Fedora 38 jobs (gcc13, intel, mkl, nosuggests, and valgrind) which is required in order to extract .tar.xz.

**Comment by gaborcsardi** [comment]
You need to include `xz` in `SystemRequirements` if you need it.

**Comment by albersonmiranda** [comment]
Thanks @gaborcsardi , that fixed it. Now I'm having

>Error in `dyn.load(file, DLLpath = DLLpath, ...)`: unable to load shared object '/github/home/R/x86_64-pc-linux-gnu-library/4.5/writexl/libs/writexl.so':
    libsvml.so: cannot open shared object file: No such file or directory

due to `writexl` dependency. Should I also add system libs required for my dependencies? Or maybe it's related to #616 ?

**Comment by gaborcsardi** [comment]
I don't know, can you link to a failing build?

**Comment by albersonmiranda** [comment]
Here it is: https://github.com/albersonmiranda/fio/actions/runs/10340447092

**Comment by gaborcsardi** [comment]
writexl is built in the container, so this is possibly because the cache has a version that does not work any more. Try deleting the cache.

**Comment by albersonmiranda** [comment]
> writexl is built in the container, so this is possibly because the cache has a version that does not work any more. Try deleting the cache.

🎯! Thank you very much!

For others that may find this issue, a quick way to delete all repository cache is through Github CLI: `gh cache delete --all`.
