### ISSUE TITLE
Check on GH (action/workflow) fails at setup stage

### ISSUE THREAD

**Issue by DISOhda** [r-hub/rhub#641]
Hello,

I setup my project with the newest version of the rhub package, as I did with other packages before, but the workflow now fails at the setup stage. A test with my other packages, for which the rhub checks did definitely work before,  yield the same results.

![grafik](https://github.com/user-attachments/assets/1977482b-bac5-4609-b037-32fa83932ad3)

It seems that the container, in which the checks are run, does not know the `R` command. (Have there been any changes to it? Maybe it does no longer have R installed or there is no symlink to the R executable?)

Is it something you can fix at all or is it GHs fault?

**Comment by gaborcsardi** [comment]
This is the same as https://github.com/r-hub/actions/issues/27

**Comment by gaborcsardi** [comment]
Should be fixed now in `r-hub/actions@v1` via https://github.com/r-hub/actions/commit/5f4956cc52ff95ec99a0444a3b9bfd621bcd60f4
