### ISSUE TITLE
Missed dependencies on GCC13 and GCC14 images

### ISSUE THREAD

**Issue by gowerc** [r-hub/rhub#642]
Hey,

Currently trying to run our tests using Rhub but we appear to be getting issues due to missed dependencies on the GCC13 and GCC14 images (other images such as Clang19 and Atlas run fine)

https://github.com/insightsengineering/rbmi/actions/runs/11362703172/job/31605118630#step:5:1762

In particular it seems to be missing the `BH` dependency from the lock file despite it being in the `LinkingTo:` section of [`rstan`](https://cran.r-project.org/web/packages/rstan/index.html) which our package has in it's suggests.

I suspect this is more a `pak` issue but I struggled to work out if the issue was in `pak` or the pipeline code itself sorry.

**Comment by gaborcsardi** [comment]
LinkingTo dependencies are only needed when a package is compiled from source. They are not needed when installing binary packages. If rstan needs BH at runtime, i could add it as an `Imports` or `Suggests` dependency.

See e.g. on macOS, where all packages have binaries available:
```
❯ pak::pkg_deps_explain("rstan", "BH", dependencies = TRUE)
x BH
```

Turning off the binaries:
```
❯ options(pkg.platforms = "source")
❯ pak::pkg_deps_explain("rstan", "BH", dependencies = TRUE)
rstan -> BH
```

**Comment by gaborcsardi** [comment]
Yes, sorry, typo.

**Comment by gaborcsardi** [comment]
> I must say I am slightly conflicted though, whilst I agree and understand the logic that LinkingTo isn't needed for binary packages as it lists stuff required at install time I feel this is likely to crop up in the future as it semi-conflicts with base `install.packages()` which appears to by default install `c("Depends", "Imports", "LinkingTo")` thus masking / side stepping the issue.

Only if it is not installing binaries:
>           In all of these, ‘"LinkingTo"’ is omitted for binary
          packages.
`?install.packages`

> That being said I am confused as to why this issue came up on the 2 GCC images but not the Clang or Atlas one 😕

It depends on which packages we are installing from binaries.

**Comment by gaborcsardi** [comment]
> Interesting... When I just tested this using the Posit Package Manager on a Fedora container it still installed BH,

`install.packages()` in this case does not know that it is installing binary Linux packages, that's why. R does not support Linux binary packages natively, so PPM sends them looking like source packages. Try on Windows or macOS or with pak, which (usually) does.
