### ISSUE TITLE
Check as CRAN?

### ISSUE THREAD

**Issue by jonocarroll** [r-hub/rhub#644]
Apologies if this is handled in rhubv2, but if it is, I could not find it.

Is it possible to set `NOT_CRAN=FALSE` with the rhubv2? I am preparing a package for submission that requires a lot of network tests, and I've used `skip_on_cran()` for these to sidestep the potential failures. I have tested locally, but I would also like to use the automated runners if possible.

rhubv1 set `check_args = "--as-cran"` but I don't see an equivalent for v2.

**Comment by jonocarroll** [comment]
Ah, I do see the `--as-cran` now. I am confused as to why all of these tests failed - they should have been skipped via `skip_on_cran()` and are, locally

https://github.com/jonocarroll/ntfy/actions/runs/11583975213

I ran this with `rhub::rhub_check(branch = "cran_release")` but looking once more at the docs; does this _require_ a non-NULL `gh_url`?

**Comment by gaborcsardi** [comment]
Yes, the non-container workflows do set `NOT_CRAN=true`, through `r-lib/actions/setup-r`, we should probably change that. Otoh, if you are using a GHA CI, then there isn't really a point in running those, they are the same.

**Comment by jonocarroll** [comment]
I don't have my own GHA CI set up yet, but I will probably do so - I find the rhub offering to be very convenient and I don't usually have to worry about skipped tests. I would certainly benefit from some runners which are specific to CRAN submissions.

Are any of the container workflows suitable for this?

**Comment by gaborcsardi** [comment]
I changed the `r-hub/actions/setup-r` action, so it should not set `NOT_CRAN` to anything now.

**Comment by jonocarroll** [comment]
Thank you - I have all green lights now in https://github.com/jonocarroll/ntfy/actions/runs/11592208228 -- I hope this makes sense as a default; it does for me - this service is most helpful to me when releasing a package to CRAN, so mimicking that environment as much as possible is extremely valuable.
