### ISSUE TITLE
Report mail signals "PREP-ERROR" although the checks were successfull

### ISSUE THREAD

**Issue by lbusett** [r-hub/rhub#65]
Hi, 
  just to signal that while checking my package, although the build seems successful (No notes, warning, errors) I receive a "PREP-ERROR" report.

Log: 
[https://builder.r-hub.io/status/MODIStsp_1.3.1.tar.gz-054d8e70e3bf401bb39b654071da338e]()

Message: 
![image](https://cloud.githubusercontent.com/assets/4480397/23128545/9c336ebc-f77f-11e6-92ef-08c2e4f7f915.png)

**Comment by gaborcsardi** [comment]
This is way too late now, but this means that there was a problem before the check even started. Could have been an R-hub problem or a system dependency might be missing.

There is a new error now, however, will be fixed by this: #118.
