### ISSUE TITLE
cannot find cmake on fedora

### ISSUE THREAD

**Issue by sn248** [r-hub/rhub#651]
Hi

I am running package build on `fedora` systems (`gcc14`, `intel`, `mkl` and `valgrind`) and see the error:

`checking for cmake... no`

See - https://github.com/sn248/sundialr/actions/runs/12339396049

The build works fine on `debian` systems. I am using the following code for checking installation of `cmake`

https://github.com/sn248/sundialr/blob/master/src/scripts/cmake_config.sh

Could this be looked at? 

Thanks!
Satya

**Comment by gaborcsardi** [comment]
If your package needs cmake, you need to add it to `SystemRequirements` in `DESCRIPTION`.

**Comment by sn248** [comment]
That seems to have done the trick. Thank you!
