### ISSUE TITLE
Problem with the Rd cross-references check

### ISSUE THREAD

**Issue by aravind-j** [r-hub/rhub#68]
[Getting the following note as particular package is referenced in a function documentation but not mentioned in dependencies.](https://builder.r-hub.io/status/PGRdup_0.2.3.1.tar.gz-b4c1c787947e498e98d231fa7423d55d)

`N  checking Rd cross-references
   Package unavailable to check Rd xrefs: ‘RecordLinkage’`

**Comment by gaborcsardi** [comment]
This is not an R-hub issue, it is an issue with your package. You need to declare that package as a dependency, or just ignore the NOTE, if CRAN and you are fine with that.
