### ISSUE TITLE
error in prep

### ISSUE THREAD

**Issue by sckott** [r-hub/rhub#69]
https://builder.r-hub.io/status/phylocomr_0.1.0.tar.gz-d6f248d984f54acf973cafd1b7fc253b#L58

relevant bit seems to be

```
Rscript -e library(sysreqs); cat(sysreq_commands("phylocomr/DESCRIPTION"))
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  :
  cannot download all files
Calls: cat ... get_cran_deps -> download_json -> download -> <Anonymous>
In addition: Warning message:
In utils::download.file(url, path, method = download_method(), quiet = quiet,  :
  URL 'http://crandeps.r-pkg.org/deps/phylocomr,tibble,sys,ape,testthat,roxygen2,knitr,rmarkdown': status was '502 Bad Gateway'
```

not sure but possible that it's just that crandeps.r-pkg.org is down, it's giving 502 right now

**Comment by gaborcsardi** [comment]
Yeah, it was just down, has a bug it seems. :( Nevertheless, it is up now.

**Comment by sckott** [comment]
thx

**Comment by juniperlsimonis** [comment]
seems like this might be happening again? 
![image](https://user-images.githubusercontent.com/23511502/68075474-7819ed00-fd65-11e9-9217-93f0278a6518.png)

**Comment by gaborcsardi** [comment]
Thanks, fixed!

**Comment by juniperlsimonis** [comment]
your expedience is remarkable! thank you!
