### ISSUE TITLE
WINDOWS: Env variable APPDATA (missing?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/rhub#70]
With
```sh
$ git clone git@github.com:hadley/rappdirs.git
$ cd rappdirs
```
and
```r
> rhub::check_on_windows(email = my_email)
```
you [get](https://builder.r-hub.io/status/rappdirs_0.3.1.9000.tar.gz-73b2b0b28fe94a6692693af80ce00637#L242):
```r
> user_data_dir("rappdirs")
 240#> [1] "C:\\Users\\USERLL~2\\AppData\\Local\\rappdirs\\rappdirs"
 241#> > user_config_dir("rappdirs", version="%p-platform/%v")
 242#> Error in Sys.getenv_force("APPDATA") :
 243#> Could not find Windows environmental variables
 244#> Calls: user_config_dir ... win_path -> %||% -> win_path_env -> Sys.getenv_force
 245#> Execution halted
```

This error shows up neither on AppVeyor CI nor with win-builder.

Not sure whether the above is a bug in [rappdirs](https://github.com/hadley/rappdirs) making too liberal assumptions about the Windows environment or rhub's check environment not providing environment variables that we expect to be there.  cc/ @hadley

PS. I discovered this error when rhub checking my [future.batchtools](https://github.com/HenrikBengtsson/future.batchtools) and then also checking [batchtools](https://cran.r-project.org/web/packages/batchtools/), which relies on rappdirs internally.

**Comment by gaborcsardi** [comment]
Yes, I need to set `APPDATA`. It seems that it is not set by default for the restricted user I have on R-hub.

**Comment by HenrikBengtsson** [comment]
Just a kind reminder that `APPDATA` is still missing on Windows as of 2017-09-10.

**Comment by gaborcsardi** [comment]
Not deployed yet, trying now, will comment here when done.

**Comment by gaborcsardi** [comment]
OK, it is deployed and working. The rappdirs test cases still fail, I think they are simply broken, and the directory you get is slightly different.
