### ISSUE TITLE
docker / libxml2

### ISSUE THREAD

**Issue by kasperdanielhansen** [r-hub/rhub#72]
I am trying to check `minfi` from Bioconductor. In the dependency graph of minfi I have XML (the R package) which requires libxml2 which apparently is missing from the platform used as default in `check_with_devel()`, at least it seems so from the build log.

I cannot (easily) find anything in the documentation about adding system libraries to the containers used.

Otherwise this looks incredible useful.

**Comment by gaborcsardi** [comment]
This was fixed, probably a long time, just forgot to close this, sorry:
https://sysreqs.r-hub.io/pkg/XML
See https://sysreqs.r-hub.io
