### ISSUE TITLE
Failing to Find Suggested Packages

### ISSUE THREAD

**Issue by brodieG** [r-hub/rhub#73]
Running `rhub` builds used to work fine, though for the last two days I've been getting:
```
E  checking package dependencies
   Package required but not available: 'diffobj'
   
   Packages suggested but not available for checking:
     'covr' 'knitr' 'rmarkdown' 'testthat' 'devtools'
   
   VignetteBuilder package required for checking but not installed: 'knitr'
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.

── 1 error ✖ | 0 warnings ✔ | 0 notes ✔
```
Looks like for whatever reason `rhub` can't get the packages from CRAN, or whatever repositories it uses.

This is using:
```
11: Windows Server 2008 R2 SP1, R-devel, 32/64 bit (windows-x86_64-devel)
```
launched via the R command line with `check()`.  Not a big deal as I can use winbuilder, but just an FYI.
```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhub_1.0.1

loaded via a namespace (and not attached):
 [1] whoami_1.1.1      prettyunits_1.0.2 clisymbols_1.1.0  digest_0.6.12    
 [5] crayon_1.3.2      withr_1.0.2       rprojroot_1.1     assertthat_0.1   
 [9] rappdirs_0.3.1    R6_2.2.0          jsonlite_1.3      backports_1.0.4  
[13] magrittr_1.5      httr_1.2.1        curl_2.3          rematch_1.0.1    
[17] callr_1.0.0       parsedate_1.1.3   devtools_1.12.0   desc_1.1.0       
[21] rcmdcheck_1.2.1   tools_3.3.3       memoise_1.0.0    
```

**Comment by gaborcsardi** [comment]
Thanks! Should be OK now.

**Comment by brodieG** [comment]
Yes, works now, great.

**Comment by stephlocke** [comment]
Hey @gaborcsardi - I'm getting this on a build for the same platform - need me to raise a new issue?


Build ID: | distcrete_0.1.0.tar.gz-26df7a73eeb5464eb7da612c81180f5a
Platform: | Windows Server 2008 R2 SP1,   R-devel, 32/64 bit

**Comment by tsibley** [comment]
I'm also seeing this issue on `Windows Server 2008 R2 SP1, R-devel, 32/64 bit`.

```
* checking package dependencies ... ERROR
Package suggested but not available: 'devtools'
```

**Comment by rsetienne** [comment]
I am also seeing something similar for various dependencies: magick, animation.
Installation of package 'packagename' had non-zero exit status.

**Comment by gaborcsardi** [comment]
@rsetienne 
1. this is a closed issue, please open another one if you have problems.
2. you'll need to tell use some details, i.e. which platform, and link to the  package you are trying to build.
