### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by SteffenMoritz** [r-hub/rhub#74]
I uploaded my package and then I have to authorize the application

"r-hub builder by @r-hub would like permission to access your account"

After clicking on "authorize" there is an error message
"Unexpected token u in JSON at position 0"

Can you tell me what the problem might be?

**Comment by SteffenMoritz** [comment]
ok....the problem is bigger than I thought...


Now I can not open the https://builder.r-hub.io/ page again.
I just get a nearly blank page saying:

"Unexpected token u in JSON at position 0"

**Comment by gaborcsardi** [comment]
Your github email is probably different from the package maintainer email. Or your github email is not public.

**Comment by SteffenMoritz** [comment]
Can I somehow fix this problem...?

-----

I tried now with the package version and I got this:

> validate_email()

── Choose email address to (re)validate (or 0 to exit) 

1:    steffen.moritz10@gmail.com
2:    New email address

Auswahl: 1
Fehler in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name

**Comment by gaborcsardi** [comment]
This was probably temporary and it does not happen any more. Please reopen if it does.
