### ISSUE TITLE
Allow package co-authors to submit?

### ISSUE THREAD

**Issue by wdwatkins** [r-hub/rhub#79]
Could package co-authors be allowed to submit to `rhub`, rather than only the single CRAN maintainer?  My team has packages that are maintained by multiple people, and we would like to still be able to test them with `rhub` when the listed maintainer is out of the office, if there are fixes that need to go to CRAN.

**Comment by gaborcsardi** [comment]
Anyone can submit a package, you don't need to be even a co-author. 

Just give your email address in `rhub::check()` or use the 'Advanced' tab on the web page.

**Comment by wdwatkins** [comment]
Ah, I didn't realize using the package maintainer's email was just a default.  Should have read the manual... thank you!
