### ISSUE TITLE
rchk support?

### ISSUE THREAD

**Issue by wrathematics** [r-hub/rhub#80]
Any chance of supporting [rchk](https://github.com/kalibera/rchk) ?

**Comment by jimhester** [comment]
cran is now checking with rchk as well as valgrind and the sanitizers (https://cran.r-project.org/web/checks/check_issue_kinds.html), so it would be nice to be able to do the same on r-hub.

**Comment by jimhester** [comment]
https://github.com/joshuaulrich/rchk-docker would probably be useful for this.

**Comment by gaborcsardi** [comment]
https://github.com/r-hub/rhub-linux-builders/blob/master/ubuntu-rchk/Dockerfile
