### ISSUE TITLE
Make it easier to check packages if you are not the official maintainer

### ISSUE THREAD

**Issue by richierocks** [r-hub/rhub#81]
I was just trying to check a package for which I'm not the maintainer listed in the DESCRIPTION file.

r-hub gives me the option to verify the maintainer email or send a code to that email address. At the moment it isn't obvious how to check the package and send results to my email address.

![screenshot 2017-06-13 14 49 02](https://user-images.githubusercontent.com/197589/27099012-7d67dff6-5047-11e7-9dc4-723e3a2462ff.png)

I guess I can change the email in the DESCRIPTION file, but this seems like hassle. It would be nice if there was an option to simply send the results to the email account associated with the github account.

**Comment by gaborcsardi** [comment]
Click on "Advanced" on the main page.

**Comment by richierocks** [comment]
Aha! Thanks.

Possibly worth adding something to the UI clarify how to do this.

**Comment by gaborcsardi** [comment]
There are some tooltips now on the main page.
