### ISSUE TITLE
check_on_solaris

### ISSUE THREAD

**Issue by tdhock** [r-hub/rhub#83]
that seems to be the only missing platform, and it is also the only platform with an ERROR for some  CRAN packages, e.g. https://cran.r-project.org/web/checks/check_results_PeakSegOptimal.html

**Comment by brodieG** [comment]
@tdhock fwiw `check(platform='solaris-x86-patched')` is [available now](https://twitter.com/BrodieGaslam/status/911390931852627968).

**Comment by tdhock** [comment]
thanks! I tried it on my penaltyLearning package to see if it got the same WARNING as on CRAN https://cran.r-project.org/web/checks/check_results_penaltyLearning.html

However I got an ERROR instead
```
> result <- check("penaltyLearning_2017.06.14.tar.gz", platform="solaris-x86-patched")
─  Uploading package
─  Preparing build, see status at
   http://builder.r-hub.io/status/penaltyLearning_2017.06.14.tar.gz-d31a58eb7d9e4070a4b86498269ff484
─  Build started
─  Downloading package
─  Setting up home directory
─  Running check
─  Installing package dependencies
─  Running R CMD check
─  using log directory ‘/export/home/XPkNVRL/penaltyLearning.Rcheck’
─  using R version 3.4.1 Patched (2017-07-15 r72924)
─  using platform: i386-pc-solaris2.10 (32-bit)
─  using session charset: UTF-8
✔  checking for file ‘penaltyLearning/DESCRIPTION’
─  this is package ‘penaltyLearning’ version ‘2017.06.14’
✔  checking package namespace information
E  checking package dependencies
   Package required but not available: ‘ggplot2’
   
   Package suggested but not available: ‘microbenchmark’
   
   The suggested packages are required for a complete check.
   Checking can be attempted without them by setting the environment
   variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
   
   See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
   manual.

   
── 1 error ✖ | 0 warnings ✔ | 0 notes ✔
    
> 
```
I don't think this is your fault -- I think the problem is that ggplot2 is no longer available for solaris. I will file an issue with ggplot2 devs.

**Comment by krlmlr** [comment]
I think a high-level `check_on_solaris()` entry point would be helpful. Would you mind reopening?
