### ISSUE TITLE
MPI packages?

### ISSUE THREAD

**Issue by wrathematics** [r-hub/rhub#84]
In anticipation of one day having rchk (which I still can't get to run myself...) available from rhub, is there any chance of supporting MPI packages? On Debian/Ubuntu, you should only need `libopenmpi-dev` and pbdMPI should build without any headaches. In my experience, Rmpi is much more annoying, but there's `r-cran-rmpi` in Debian. I think Fedora has something similar. Windows has MS-MPI if you wanted to go that far.

R + HPC is a relatively small group of people, so this obviously isn't a top priority. But it would be much appreciated.

**Comment by gaborcsardi** [comment]
There is openmpi on r-hub (on linux), you just need to put it in `SystemRequirements`: https://github.com/r-hub/sysreqsdb/blob/master/sysreqs/openmpi.json

Let me know if you have problems.

**Comment by wrathematics** [comment]
Well, pbdMPI is missing:

```
Package required but not available: ‘pbdMPI’
```

I suspect that Rmpi is as well.

Using `SystemRequirements` is not necessarily ideal. [pbdMPI's](https://cran.r-project.org/web/packages/pbdMPI/index.html) is very thorough. [Rmpi](https://cran.r-project.org/web/packages/Rmpi/index.html) doesn't even bother with one.  As far as I know, every MPI-using package on CRAN either uses (no linking) or links with one of those two packages, except for [bigGP](https://cran.r-project.org/web/packages/bigGP/index.html).

**Comment by gaborcsardi** [comment]
r-hub works off `SystemRequirements`. Your package declares openMPI, so that is installed just fine, before the package is checked:
https://builder.r-hub.io/status/pbdMPI_0.3-3.tar.gz-e4ca944c246145ca95ff4954d794e984

The install still fails, though, because it seems that you also need `ssh` or `rsh`? Please look at `00install.out` at https://artifacts.r-hub.io/pbdMPI_0.3-3.tar.gz-e4ca944c246145ca95ff4954d794e984/

**Comment by gaborcsardi** [comment]
If a package needs openMPI, but does not declare this, then we need to add an entry here: https://github.com/r-hub/sysreqsdb/tree/master/cran
PRs are welcome.

**Comment by gaborcsardi** [comment]
Closing this, as it is not clear what is needed.

**Comment by krivit** [comment]
The `SystemRequirements: OpenMPI` directive seems to work for Ubuntu but not for Fedora: https://builder.r-hub.io/status/ergm_3.10.4.tar.gz-5706b68f312d499ab984aba56ff4dee6 .

The key line appears to be https://builder.r-hub.io/status/ergm_3.10.4.tar.gz-5706b68f312d499ab984aba56ff4dee6#L1412 .

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
