### ISSUE TITLE
What is PREPERROR

### ISSUE THREAD

**Issue by dmenne** [r-hub/rhub#86]
I have trouble understanding the email I received when building a test package. It says "PREPERROR", but in the logs, everything seems to be ok. Did I miss something?

```
teststan 1.1.3: PREPERROR

Build ID:   teststan_1.1.3.tar.gz-bf078dbe9c5b426a8bdaa25d553423d9
Platform:   Ubuntu Linux 16.04 LTS, R-release, GCC
Submitted:  13 minutes 23.3 seconds ago
Build time: 13 minutes 22.9 seconds


See the full build log:
HTML: https://builder.r-hub.io/status/teststan_1.1.3.tar.gz-bf078dbe9c5b426a8bdaa25d553423d9
```

**Comment by gaborcsardi** [comment]
`PREPERROR` means that the check has not even started, because some error happened before.

In this case it not detected properly, so just ignore it.
