### ISSUE TITLE
.configure file problems

### ISSUE THREAD

**Issue by dmenne** [r-hub/rhub#87]
I need to use a configure file as suggested by Dirk Eddelbuettel to build a package on travis. See

http://discourse.mc-stan.org/t/new-cppobject-xp-constructor-in-2-16-and-how-to-configure-travisci/1192

When I started to use it, I get an error in line 3469  `sh: 1: ./configure: not found`

https://builder.r-hub.io/status/gastempt_0.4.03.9001.tar.gz-81db1bb9fec446248b4cab7f5b69a566

The file is on github, but I assume that it has something to do with executable permissions.

**Comment by gaborcsardi** [comment]
Your configure file has DOS line endings and this probably trips up the Linux. Change the line ending to Unix.

**Comment by dmenne** [comment]
I always thought autocrlf in git would take care of this. Thanks. Works. Possibly better error message? "Not found" is confusing.

**Comment by gaborcsardi** [comment]
Linux gives the error message. Ie the operating system.

**Comment by dmenne** [comment]
I know, but when I git-push from Windows, I usuall get the conversion done for me during the push. There is a message, for example for Makevars which is also CRLF sensitive.

**Comment by gaborcsardi** [comment]
I am just saying that for a better error we would need to patch linux.
