### ISSUE TITLE
Question about SystemRequirements

### ISSUE THREAD

**Issue by muschellij2** [r-hub/rhub#88]
I wanted to check a package that needed `git` and `cmake` (non-CRAN packages, so may be outside purview), which had:
```
SystemRequirements: cmake, git, clang (recommended)
```

I can remove the (recommended) or remove the compiler, but would rhub be able to install `git` `cmake` and put in PATH?  Tried out on https://builder.r-hub.io/status/ANTsRCore_0.3.8.2.tar.gz-b53aaffec08e4a058eebeb199489cb04 and got on 
line 213:
```
line 24: git: command not found
```

Do you have an example which uses SystemRequirements to have pre-requisites installed?  I tried on OSX, but will also try on Linux

**Comment by gaborcsardi** [comment]
Note that sysreqs do not work for macos yet: https://github.com/r-hub/macoscheck/issues/6

**Comment by muschellij2** [comment]
After the PR was merged, this issue is resolved.
