### ISSUE TITLE
Artifacts not being Copied for aborted checks

### ISSUE THREAD

**Issue by muschellij2** [r-hub/rhub#89]
I tried a build today:
https://builder.r-hub.io/status/gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118
and the build went fine and got an email.

Clicked the `artifacts` link: https://artifacts.r-hub.io/gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118 and got a "Not Found" response.  Looking at the log from the build, I see on [line 1918](https://builder.r-hub.io/status/gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118#L1918):
```
docker cp gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118-2:/home/docker/.Rcheck gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118/
Error response from daemon: lstat /var/lib/docker/aufs/mnt/6e4ad8abdebd2a54c4f576f3b7983894748fa6b1574686752a09d457bf4b607c/home/docker/.Rcheck: no such file or directory
```

and subsequently
```
mv gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118/.Rcheck/*.tar.gz gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118/
mv: cannot stat 'gifti_0.7.4.1.tar.gz-949c65935879424e96f264c3596f8118/.Rcheck/*.tar.gz': No such file or directory
```

I wanted to see if `R CMD check --install-args=--build` will give me the binary out, so I think there may be something off in the copying script for artifacts.

**Comment by HenrikBengtsson** [comment]
It works for me on several runs that return OK or NOTEs (don't know about ERROR), but for checks that are ABORTED (due to 10-min timeout during a test), it appears that artifacts are not available.

**Comment by gaborcsardi** [comment]
I'll take a look if this is possible. It might not be, because aborting the check abort the whole process,  which includes copying the artifacts.

**Comment by gaborcsardi** [comment]
It is not possible to copy artifacts if the build is aborted, unfortunately.

**Comment by gaborcsardi** [comment]
Actually, I just improved this a bit. Now a timeout will not abort the build, just fail it, so the artifacts are still copied.
