### ISSUE TITLE
Definition of "Success"

### ISSUE THREAD

**Issue by muschellij2** [r-hub/rhub#90]
Build has a clear ERROR (not warning/note), but the overall status is still "Success" - what does this mean exactly?

https://builder.r-hub.io/status/ANTsRCore_0.3.7.4.tar.gz-005c295f8b9e4aa0b421b731808ad6be

**Comment by tbates** [comment]
The key steps of package compilation and checking can error, but the last report is simply whether the SSH file transfer completed.

Probably would be more useful to report the first error, not the last state?

    12831#> Build step 'Send files or execute commands over SSH' changed build result to SUCCESS
    12833#> {"status":"ok"}
    12834#> Finished: SUCCESS

**Comment by gaborcsardi** [comment]
Finished: SUCCESS is from the build supervisor, stating that the package was checked. THe result of the check was an ERROR.

Ideally these lines should not be in the output, but they are now.
