### ISSUE TITLE
unable to start device PNG check_with_fedora

### ISSUE THREAD

**Issue by markvanderloo** [r-hub/rhub#92]
All tested platforms run w/o errors when testing a pkg (`validate`). However using `check_on_fedora` I get the following:

```
W  checking re-building of vignette outputs
   Error in re-building vignettes:
     ...
   Warning in (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
     unable to open connection to X11 display ''
   Quitting from lines 74-76 (indicators.Rmd) 
   Error: processing vignette 'indicators.Rmd' failed with diagnostics:
   unable to start device PNG
   Execution halted
```

Thing is, the `indicators.Rmd` vignette doesn't produce any plots (there's another vignette called `introduction.Rmd` that does).

not sure if I should be worried now for CRAN submission or not..

Cheers,
-M

**Comment by gaborcsardi** [comment]
Where is the package you are referring to?

**Comment by markvanderloo** [comment]
[github](https://github.com/data-cleaning/validate)

```
git clone https://github.com/data-cleaning/validate
R - e "rhub::check_on_fedora('pkg')"
```

**Comment by gaborcsardi** [comment]
Can you provide a link to an rhub build log?

**Comment by markvanderloo** [comment]
sure: [here it is](https://builder.r-hub.io/status/validate_0.2.0.tar.gz-24e8d32f0f7c4421bddd995664161cb3)

**Comment by gaborcsardi** [comment]
I think `knitr` is trying to open a png() device, I am not sure why. I am also not sure why it does not work.

**Comment by markvanderloo** [comment]
yeah, I guessed something like that. I'll play around with some vignette settings and maybe ping Yihui about this thread. Thanks!

**Comment by markvanderloo** [comment]
Gabor, just FYI.

I now get the same issue with the lumberjack pkg (not even a single figure in the vignette). See [log](https://builder.r-hub.io/status/lumberjack_0.2.0.tar.gz-1a7cf5625a8741bc90325653fb73d58c). 

possibly related: I recently had an issue with the stringdist pkg on CRAN/fedora and CRAN/windows which I could not reproduce on rhub/fedora (rhub/fedora did not fail a test caused by an uninitialized value in compiled code).

These things are hard to reproduce. I built a minimal pkg and got no error on the vignettes, regardless of whether there are figures. I'll update this thread if I find anything new.

**Comment by markvanderloo** [comment]
Update: the validate pkg [checks fine](https://cran.r-project.org/web/checks/check_results_validate.html) on CRAN/fedora (clang and gcc).

There must be some differences between the rhub and cran fedora configuration causing this.

**Comment by bbolker** [comment]
I would have guessed that CRAN had a virtual frame buffer (Xvfb) set up. On the other hand, I would have thought this would come up very frequently ...

**Comment by gaborcsardi** [comment]
I think the problem is that R-hub runs the check using `xvfb-run` and `knitr` runs in a child process, so that does not have access to the device. You can try to download the Docker image if you want to play with it locally. 

As a fix, I could try running Xvfb for the whole session. That's what I tried first, but it did not work well, I forgot why.

**Comment by gaborcsardi** [comment]
Also, the best solution would be if `knitr` could run without X11...

**Comment by bbolker** [comment]
I don't think that's going to work generally; for example, `knitr` might call `rgl` <https://yihui.name/knitr/hooks/>

**Comment by markvanderloo** [comment]
Weird thing is: on most other pkgs (including some minimal examples with vignettes including or not including figures) it _does_ work. Perhaps something triggers knitr to process vignettes differently in the two pkgs that produce an error.

Also @gaborcsardi : could you point me to the docker img? Would speed up my testing.

**Comment by RemkoDuursma** [comment]
I also run into this issue with my package, which can be found [here](https://github.com/remkoduursma/plantecophys).  Link to build status is [here](https://builder.r-hub.io/status/plantecophys_1.3.tar.gz-04809046a4eb417780baeda0ff410ead).

**Comment by adimajo** [comment]
Same for me ; [package](https://github.com/adimajo/glmdisc/tree/master/glmdisc), [log](https://builder.r-hub.io/status/scoring_0.1.tar.gz-ed14aca9c5f64456a534e87afbe9d16a).

**Comment by rikardn** [comment]
Same for me. I tested (almost) the same version of my package yesterday and then it worked fine.

Fail today
https://builder.r-hub.io/status/libsoc_0.6.2.tar.gz-de4f67acf7444277a45934b5a6279abd
No fail yesterday
https://builder.r-hub.io/status/libsoc_0.6.2.tar.gz-3590db78db1b4339b007dde573c453db

**Comment by jdblischak** [comment]
Another data point: [package](https://github.com/jdblischak/workflowr/tree/v1.0.0), [log](https://builder.r-hub.io/status/workflowr_1.0.0.tar.gz-ce4a6d07d011487d8e81b974a627755f#L2259)

**Comment by jdblischak** [comment]
> could you point me to the docker img? Would speed up my testing.

@markvanderloo The docker images are listed in https://github.com/r-hub/rhub-linux-builders

For example, to use the image running R-devel with clang on Fedora: 

```
sudo docker run --rm -ti rhub/fedora-clang-devel bash
```

**Comment by kgoldfeld** [comment]
I just want to chime in to say that I am getting this same type of warning when checking package simstudy using devtools::check_rhub(). The section of the vignette has no plot. This is a warning from the Fedora Linux check. Let me know if you need more information. If anyone has found a resolution, let me know.

checking re-building of vignette outputs ... WARNING

Error in re-building vignettes:
  ...
Loading required package: data.table
Warning in (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
  unable to open connection to X11 display ''
Quitting from lines 313-323 (simstudy.Rmd) 
Error: processing vignette 'simstudy.Rmd' failed with diagnostics:
unable to start device PNG
Execution halted

**Comment by gchung05** [comment]
Also having this issue with `mds` package.

**Comment by AnotherSamWilson** [comment]
Any solution to this? Running into this error with ParBayesianOptimization.

**Comment by gaborcsardi** [comment]
Since this does not ever happen on Debian or Ubuntu, I am starting to think that Fedora `xvfb-run` is buggy....

**Comment by gaborcsardi** [comment]
Updating `xvfb-run` does not seem to help.

**Comment by AnotherSamWilson** [comment]
The package checks fine when run by CRAN on fedora as mentioned by markvanderloo:
https://cran.r-project.org/web/checks/check_results_ParBayesianOptimization.html

**Comment by gaborcsardi** [comment]
OK, I think I (more or less) know why this happens!!! Fix is coming soon.
