### ISSUE TITLE
OS/X el capitan fortran is not working

### ISSUE THREAD

**Issue by jpritikin** [r-hub/rhub#93]
Log [here](https://builder.r-hub.io/status/OpenMx_2.7.16.tar.gz-5d85f540d0e24d0eb88faad54afc74e4). The same code builds fine on [gcc](https://travis-ci.org/OpenMx/OpenMx/jobs/263520351).

**Comment by tbates** [comment]
So  on line 3275 we see the gfortran call, accompanied by several thousand unsupported directive errors referring to '.stabs'

    3275#> gfortran -fPIC -g -O2 -c sadmvn.f -o sadmvn.o
    3276#> /Users/user21kQ1GCE/Rtemp/cczQPTZ1.s:1:9: error: unsupported directive '.stabs'
    3277#> .stabs     "/Users/user21kQ1GCE/Rtemp/RtmpMBgUls/remotes147f03dc376f9/OpenMx/src/",100,0,7,Ltext0
    3278#> ^
    3279#> /Users/user21kQ1GCE/Rtemp/cczQPTZ1.s:2:9: error: unsupported directive '.stabs'
    3280#> .stabs "sadmvn.f",100,0,7,Ltext0

**Comment by mcneale** [comment]
Is this perhaps related to the increased number (>200) of ERROR statuses for R package tests, OS X El Capitan **586** vs OS X Mavericks **351**, [as seen here](https://cran.r-project.org/web/checks./check_summary_by_package.html#summary_by_package):  I don't know which of these now-failing-and-weren't-under-Mavericks packages use FORTRAN.

**Comment by coatless** [comment]
The appropriate `gfortran` routines are MIA on the images. Specifically:

macOS 10.11 El Capitan, R-release (experimental) (macos-elcapitan-release) is missing the official gfortran binary (6.1) that _R_ is compiled against.

macOS 10.9 Mavericks, R-oldrel (experimental) (macos-mavericks-oldrel) is missing the _R_ specific gfortran binary of 4.8.2.

**Comment by gaborcsardi** [comment]
Sorry this has taken so long. It should be fixed now.

**Comment by tbates** [comment]
Let us know when/if you update your wonderful MacOS installer dmg, @coatless 

it's a life saver while CRAN is yet to create one
