### ISSUE TITLE
gateway error

### ISSUE THREAD

**Issue by jwijffels** [r-hub/rhub#95]
I'm trying out r-hub to test an R package (udpipe) on Solaris but I'm getting a gateway error https://builder.r-hub.io/status/udpipe_0.1.1.tar.gz-ac2ba4361d0a4502b70a4b7ba1927adf

**Comment by gaborcsardi** [comment]
Thanks for reporting! I am seeing this as well....

**Comment by gaborcsardi** [comment]
OK, running now. There is quite some backlog, but it will get there, slowly...

**Comment by jwijffels** [comment]
Many thanks!
