### ISSUE TITLE
Build error with package nlme (works on CRAN)

### ISSUE THREAD

**Issue by dmenne** [r-hub/rhub#96]
I have a package which builds ok on Windows and on Travis/Ubuntu (https://travis-ci.org/dmenne/breathtestcore/builds/273222941)

On r-hub, I get an error 

https://builder.r-hub.io/status/breathtestcore_0.3.0.9100.tar.gz-88bf85313f1f424dabe60a4321788e66

```
 +   cleanup_data()
 fit = nls_fit(data)
 coef_by_group(fit)
 Error in array(c(rep(1, p), .C(inner_perc_table, as.double(X), as.integer(unlist(grps)),  : 
   object 'inner_perc_table' not found
 Calls: coef_by_group ... .Call -> <Anonymous> -> lme.formula -> getFixDF -> array
 Execution halted

```

As Dirk Eddelbüttel mentions in:

http://r.789695.n4.nabble.com/bug-report-nlme-model-fitting-crashes-with-R-3-4-0-tp4733653p4733667.html
 
this is some problem with 3.30 and 3.4.0 inconsistency. Can I do something to get it to work again on r-hub?

**Comment by dmenne** [comment]
The package is now on CRAN (breathtestcore, 0.4.0), but still gives the same errror on r-hub.

**Comment by gaborcsardi** [comment]
Seems like this was a temporary R issue and it is fixed already.
