### ISSUE TITLE
RcppArmadillo on Solaris

### ISSUE THREAD

**Issue by kbose28** [r-hub/rhub#97]
My package that uses RcppArmadillo fails on Solaris with the the following error. The package passes on ubuntu, mac and win_build(release and devel). Thank you for your time. 

* checking package dependencies ... ERROR
Package required but not available: ‘RcppArmadillo’

Packages suggested but not available: ‘knitr’ ‘rmarkdown’

VignetteBuilder package required for checking but not installed: ‘knitr’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.

----------------------------------------------
https://builder.r-hub.io/status/farmtest_0.1.0.tar.gz-26c78a177c844c74894d1c06d7684166

**Comment by rstub** [comment]
I have a very similar error but the `Rcpp`, c.f. https://builder.r-hub.io/status/swephR_0.1.0.tar.gz-3b64c66e872c7b3e44153cc6148320eb and https://github.com/rstub/swephR/issues/34.

**Comment by gaborcsardi** [comment]
Works fine now. For the record, it is not essential to check your vignettes on Solaris. LaTeX vignettes will probably work, but the ones that need pandoc will not, because there is no pandoc for Solaris.
